select * from PISARREARTRANSACTION
WHERE TOKENNO='C1011'

select * from PISARREARTRANSACTION
WHERE TOKENNO='00210'


SELECT * FROM PISMONTHATTENDANCE
WHERE TOKENNO='C1011'

SELECT * FROM PISPAYTRANSACTION
WHERE TOKENNO='C1011'

PROC_COMPONENTASSINREPORT