

DELETE GTT_LOANMAXDATE

DROP TABLE GTT_LOANMAXDATE

SELECT * FROM GTT_LOANMAXDATE



--CREATE GLOBAL TEMPORARY TABLE GTT_LOANMAXDATE AS
INSERT INTO GTT_LOANMAXDATE
SELECT DISTINCT COMPANYCODE,DIVISIONCODE,PFNO, WORKERSERIAL,LOANCODE, 
MAX(LOANDATE) LOANDATE,NVL(MAX(DEDUCTIONSTARTDATE),MAX(LOANDATE)) DEDUCTIONSTARTDATE 
FROM PFLOANTRANSACTION  
WHERE COMPANYCODE = 'JT0069' AND DIVISIONCODE = '0002' 
AND LOANDATE <=  TO_DATE('21/10/2020','DD/MM/YYYY')
AND LOANTYPE ='REFUNDABLE'
GROUP BY COMPANYCODE,DIVISIONCODE, LOANCODE,WORKERSERIAL,PFNO  



SELECT B.WORKERSERIAL, B.TOKENNO, A.PFNO, A.LOANCODE, A.LOANDATE, SUM(A.AMOUNT) PFLOAN_BAL, 
CASE WHEN SUM(INTERESTAMOUNT) > 0 THEN SUM(INTERESTAMOUNT) ELSE 0 END PFLOAN_INT_BAL, 
SUM(LN_CAP_DEDUCT) PFLN_CAP_DEDUCT, SUM(LN_INT_DEDUCT) PFLN_INT_DEDUCT,  
/*NVL(X.CAP_EMI,0) CAP_EMI, NVL(X.INT_EMI,0) INT_EMI, */
CASE WHEN X.DEDUCTIONSTARTDATE > TO_DATE('21/10/2020','DD/MM/YYYY') THEN 0 ELSE 
CASE WHEN M.DEDUCTIONTYPE = 'DEDUCT INTEREST FULL THEN CAPITAL' AND SUM(INTERESTAMOUNT) > 0 THEN 0 ELSE DECODE(DEDUCTIONTYPE,'DEDUCT CAPITAL AND INTEREST SAMETIME',NVL(X.CAP_EMI,0),NVL(X.TOT_EMI,0)) END END CAP_EMI, 
CASE WHEN X.DEDUCTIONSTARTDATE > TO_DATE('21/10/2020','DD/MM/YYYY') THEN 0 ELSE 
CASE WHEN M.DEDUCTIONTYPE = 'DEDUCT INTEREST FULL THEN CAPITAL' AND SUM(INTERESTAMOUNT) > 0 THEN NVL(X.INT_EMI,0) 
ELSE CASE WHEN SUM(A.AMOUNT) <=0 AND SUM(INTERESTAMOUNT) > 0 THEN NVL(X.INT_EMI,0) ELSE 0 END END END INT_EMI, 
NVL(X.TOT_EMI,0) TOT_EMI, 
NVL(Y.CAP_STOP,'N') CAP_STOP,
NVL(Y.INT_STOP,'N') INT_STOP,
B.MODULE, 'FULL' CAP_EMI_DEDUCT_TYPE, 'FULL' INT_EMI_DEDUCT_TYPE  
FROM 
(  
    SELECT DISTINCT A.COMPANYCODE,A.DIVISIONCODE,A.PFNO, A.LOANCODE, A.LOANDATE, AMOUNT, 0 INTERESTAMOUNT , 0 LN_CAP_DEDUCT, 0 LN_INT_DEDUCT 
    FROM PFLOANTRANSACTION A,GTT_LOANMAXDATE B  
    WHERE A.COMPANYCODE=B.COMPANYCODE AND A.DIVISIONCODE=B.DIVISIONCODE 
    AND A.PFNO = B.PFNO AND A.LOANCODE = B.LOANCODE AND A.LOANDATE = B.LOANDATE  AND AMOUNT > 0 
    UNION ALL     
    SELECT A.COMPANYCODE,A.DIVISIONCODE,A.PFNO, A.LOANCODE, A.LOANDATE,   
    (
        CASE WHEN TRANSACTIONTYPE ='CAPITAL' THEN CASE WHEN EFFECTFORTNIGHT < TO_DATE('21/10/2020','DD/MM/YYYY') THEN AMOUNT ELSE 0 END  
            WHEN TRANSACTIONTYPE ='REPAY' THEN REPAYCAPITAL  
            WHEN TRANSACTIONTYPE ='REPAYCAP' THEN AMOUNT  
            ELSE 0  
        END
    )*(-1) AMOUNT, 0 INTERESTAMOUNT 
    , 0 LN_CAP_DEDUCT, 0 LN_INT_DEDUCT     
    FROM PFLOANBREAKUP A, GTT_LOANMAXDATE B  
    WHERE A.COMPANYCODE=B.COMPANYCODE AND A.DIVISIONCODE=B.DIVISIONCODE 
    AND A.PFNO = B.PFNO  AND A.LOANCODE = B.LOANCODE AND A.LOANDATE = B.LOANDATE  
    AND A.EFFECTFORTNIGHT <=  TO_DATE('21/10/2020','DD/MM/YYYY')  
    AND TRANSACTIONTYPE <> 'INTEREST'  
    UNION ALL  
    SELECT DISTINCT A.COMPANYCODE,A.DIVISIONCODE,A.PFNO, A.LOANCODE, A.LOANDATE, 0 AMOUNT, SUM(NVL(C.INTERESTAMOUNT,0)) INTERESTAMOUNT 
    , 0 LN_CAP_DEDUCT, 0 LN_INT_DEDUCT  
    FROM 
    ( 
        SELECT DISTINCT COMPANYCODE,DIVISIONCODE,PFNO, LOANCODE, LOANDATE 
        FROM PFLOANTRANSACTION 
        WHERE COMPANYCODE ='JT0069' AND DIVISIONCODE = '0002'
    ) A,GTT_LOANMAXDATE B, PFLOANINTEREST C  
    WHERE A.COMPANYCODE = 'JT0069' AND A.DIVISIONCODE = '0002' AND A.COMPANYCODE=B.COMPANYCODE 
    AND A.DIVISIONCODE=B.DIVISIONCODE  AND A.LOANCODE = B.LOANCODE AND A.PFNO = B.PFNO AND A.LOANDATE = B.LOANDATE  
    AND A.PFNO = C.PFNO AND A.LOANDATE = C.LOANDATE AND A.LOANCODE = C.LOANCODE  
    AND C.FORTNIGHTENDDATE <= TO_DATE('21/10/2020','DD/MM/YYYY') 
    AND C.TRANSACTIONTYPE = 'ADD'  
    GROUP BY A.COMPANYCODE,A.DIVISIONCODE,A.PFNO, A.LOANCODE, A.LOANDATE  
    UNION ALL  
    SELECT A.COMPANYCODE,A.DIVISIONCODE,A.PFNO, A.LOANCODE, A.LOANDATE, 0 AMOUNT,   
    (
        CASE WHEN TRANSACTIONTYPE ='INTEREST' THEN CASE WHEN EFFECTFORTNIGHT < TO_DATE('21/10/2020','DD/MM/YYYY') THEN AMOUNT ELSE 0 END  
        WHEN TRANSACTIONTYPE ='REPAY' THEN REPAYINTEREST  
        WHEN TRANSACTIONTYPE ='REPAYINT' THEN AMOUNT  
        ELSE 0  
        END
    )*(-1) INTERESTAMOUNT 
    , 0 LN_CAP_DEDUCT, 0 LN_INT_DEDUCT      
    FROM PFLOANBREAKUP A,GTT_LOANMAXDATE B  
    WHERE A.COMPANYCODE=B.COMPANYCODE AND A.DIVISIONCODE=B.DIVISIONCODE AND A.PFNO = B.PFNO AND A.LOANDATE = B.LOANDATE  
    AND A.EFFECTFORTNIGHT <= TO_DATE('21/10/2020','DD/MM/YYYY') 
    AND TRANSACTIONTYPE <> 'CAPITAL' 
    UNION ALL 
    SELECT A.COMPANYCODE,A.DIVISIONCODE,A.PFNO, A.LOANCODE, A.LOANDATE, 0 AMOUNT,  0 INTERESTAMOUNT,  
    DECODE(TRANSACTIONTYPE,'CAPITAL',AMOUNT,0) LN_CAP_DEDUCT, DECODE(TRANSACTIONTYPE,'INTEREST',AMOUNT,0) LN_INT_DEDUCT 
    FROM PFLOANBREAKUP A,GTT_LOANMAXDATE B  
    WHERE A.COMPANYCODE=B.COMPANYCODE AND A.DIVISIONCODE=B.DIVISIONCODE AND A.PFNO = B.PFNO AND A.LOANDATE = B.LOANDATE  
    AND A.EFFECTFORTNIGHT <= TO_DATE('21/10/2020','DD/MM/YYYY')
    AND TRANSACTIONTYPE IN ('CAPITAL','INTEREST')  
) A, PFEMPLOYEEMASTER B, 
(  
    SELECT M.COMPANYCODE,M.DIVISIONCODE,M.PFNO, M.LOANDATE, NVL(m.DEDUCTIONSTARTDATE,m.LOANDATE) DEDUCTIONSTARTDATE , 
    NVL(M.CAPITALINSTALLMENTAMT,0) CAP_EMI,  
    NVL(M.INTERESTINSTALLMENTAMT,0) INT_EMI, NVL(M.TOTALEMIAMOUNT,0) TOT_EMI  
    FROM PFLOANTRANSACTION M,GTT_LOANMAXDATE N   
    WHERE M.COMPANYCODE=N.COMPANYCODE AND M.DIVISIONCODE=N.DIVISIONCODE 
    AND M.PFNO = N.PFNO  AND M.LOANCODE = N.LOANCODE AND M.LOANDATE = N.LOANDATE  
)  X,   
( 
    SELECT DISTINCT COMPANYCODE,DIVISIONCODE,LOANCODE, DEDUCTIONTYPE FROM PFLOANMASTER 
) M, 
( 
    SELECT COMPANYCODE,DIVISIONCODE,PFNO, WORKERSERIAL, TOKENNO, LOANCODE, LOANDATE, 
    LOANSTOPFROMDATE, LOANSTOPTODATE, CAPITAL CAP_STOP, INTEREST INT_STOP, FULLMILL 
    FROM PFLOANDEDUCTIONSTOP 
    WHERE COMPANYCODE = 'JT0069' AND DIVISIONCODE = '0002' 
    AND LOANSTOPFROMDATE <= TO_DATE('21/10/2020','DD/MM/YYYY') 
    AND LOANSTOPTODATE >= TO_DATE('21/10/2020','DD/MM/YYYY') 
    AND NVL(FULLMILL,'N') <> 'Y' 
    AND PFNO IS NOT NULL 
) Y 
WHERE A.COMPANYCODE=B.COMPANYCODE  
AND A.COMPANYCODE=M.COMPANYCODE    
AND A.COMPANYCODE=X.COMPANYCODE    
AND A.COMPANYCODE=Y.COMPANYCODE (+)  
--AND A.COMPANYCODE=Z.COMPANYCODE  
AND A.DIVISIONCODE=B.DIVISIONCODE  
AND A.DIVISIONCODE=M.DIVISIONCODE  
AND A.DIVISIONCODE=X.DIVISIONCODE  
AND A.DIVISIONCODE=Y.DIVISIONCODE (+)  
--AND A.DIVISIONCODE=Z.DIVISIONCODE  
AND A.PFNO = B.PFNO  
AND A.PFNO = X.PFNO AND A.LOANDATE = X.LOANDATE 
AND A.LOANCODE = M.LOANCODE
--AND A.PFNO = Z.PFNO AND  A.LOANCODE = Z.LOANCODE AND A.LOANDATE = Z.LOANDATE 
AND A.PFNO = Y.PFNO (+)  
GROUP BY B.WORKERSERIAL, B.TOKENNO, A.PFNO, A.LOANCODE, A.LOANDATE, X.DEDUCTIONSTARTDATE, 
NVL(X.CAP_EMI,0), NVL(X.INT_EMI,0), NVL(X.TOT_EMI,0), B.MODULE, M.DEDUCTIONTYPE, Y.CAP_STOP, Y.INT_STOP