exec PROC_PISSALARY_DATA_IMPORT1('NJ0002','0010','202011')


PROC_PISSALARY_DATA_IMPORT1
(
    P_COMPANYCODE VARCHAR2,
    P_DIVISIONCODE VARCHAR2,
    P_YEARMONTH VARCHAR2
)

 SELECT 'A' OPERATIONMODE, SYS_guid() SYSROWID,0 VPF,'INSERT DATA FROM PROCEDURE' REMARKS,'Y' UPDATESTATUS,
    'PIS' MODULE, LOAN_CAP, PF_E, PF_C, LOAN_INT, 
    'MIGR' USERNAME, B.COMPANYCODE, B.DIVISIONCODE, A.YEARCODE, A.YEARMONTH, B.WORKERSERIAL, B.TOKENNO 
    FROM (
        SELECT 0 VPF, LOAN_MPL  LOAN_CAP,  PF_E,  PF_C, LINT_MPL LOAN_INT, 
        COMPANYCODE,  DIVISIONCODE, YEARCODE,  YEARMONTH,
        LPAD(EMPLOYEECODE,5,'7') TOKENNO
        FROM PISSALARYUPLOADRAWDATA 
        WHERE YEARMONTH='202011'
    ) A  , PFEMPLOYEEMASTER B
    WHERE A.TOKENNO=B.TOKENNO;
    
    
     SELECT * FROM PFTRANSACTIONDETAILS
        WHERE 1=1 /*EMPLOYEECOMPANYCODE=lv_CompCode
        AND EMPLOYEEDIVISIONCODE=lv_DivCode
        AND YEARCODE=lv_YearCode
        AND YEARMONTH=lv_YYYYMM
        AND MODULE =lv_Module */
        AND YEARMONTH='202011'
        AND WORKERSERIAL IN (
                SELECT DISTINCT WORKERSERIAL FROM 
                (
                    SELECT 'A' OPERATIONMODE, SYS_guid() SYSROWID,0 VPF,'INSERT DATA FROM PROCEDURE' REMARKS,'Y' UPDATESTATUS,
                    'PIS' MODULE, LOAN_CAP, PF_E, PF_C, LOAN_INT, 
                    'MIGR' USERNAME, B.COMPANYCODE, B.DIVISIONCODE, A.YEARCODE, A.YEARMONTH, B.WORKERSERIAL, B.TOKENNO 
                    FROM (
                        SELECT 0 VPF, LOAN_MPL  LOAN_CAP,  PF_E,  PF_C, LINT_MPL LOAN_INT, 
                        COMPANYCODE,  DIVISIONCODE, YEARCODE,  YEARMONTH,
                        LPAD(EMPLOYEECODE,5,'7') TOKENNO
                        FROM PISSALARYUPLOADRAWDATA 
                        WHERE YEARMONTH='202011'
                    ) A  , PFEMPLOYEEMASTER B
                    WHERE A.TOKENNO=B.TOKENNO 
                )
            ) ;


SELECT * FROM PISPAYTRANSACTION
WHERE YEARMONTH='202011'