SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%CHALLAN IN%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0103020608'

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

SELECT * FROM STORESCHALLANOUTTYPE

SET DEFINE OFF;
Insert into STORESCHALLANOUTTYPE
   (OUTTYPE, RETURNTYPE)
 Values
   ('STORE', 'NON RETURNABLE');
COMMIT;


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='4351'

 SELECT * FROM (  SELECT DISTINCT TRANSACTIONNO,TO_CHAR(A.TRANSACTIONDATE,'DD/MM/YYYY') TRANSACTIONDATE,A.OUTTYPE DOCTYPE,B.PARTYNAME,A.REPRESENTATIVE 
 FROM STORESCHALLANINDETAILS A ,PARTYMASTER B
  WHERE A.COMPANYCODE = B.COMPANYCODE
  AND A.PARTYCODE = B.PARTYCODE
  AND A.COMPANYCODE = 'CJ0101' 
   AND A.DIVISIONCODE ='0002'
   AND A.YEARCODE='2020-2021'
   AND B.PARTYTYPE ='SUPPLIER' 
   AND B.MODULE = 'STORES'    
    AND (TRANSACTIONNO LIKE '%MI%' OR OUTTYPE LIKE '%MI%' OR PARTYNAME LIKE '%MI%' OR REPRESENTATIVE LIKE '%MI%') ORDER BY  A.TRANSACTIONNO ) 
    
    SELECT * FROM STORESCHALLANINDETAILS
    
    UPDATE STORESCHALLANINDETAILS SET OUTTYPE= 'STORE'
    WHERE  OUTTYPE= 'MISC'
    
    
    PRCSTORES_CHALLANINB4MAIN
    
     select fn_autogen_params
     (lv_Master.CompanyCode,lv_Master.DivisionCode,lv_Master.YearCode,'STORES_CHALLANIN_NO',to_char(lv_Master.TRANSACTIONDATE,'dd/mm/yyyy')) 
           
     select fn_autogen_params
     ('CJ0101','0002','2020-2021','STORES_CHALLANIN_NO', '05/02/2021') XX FROM DUAL 
           
     
     SELECT * FROM SYS_AUTOGEN_PARAMS
     WHERE PARAM_NAME ='STORES_CHALLANIN_NO'
     
     SELECT * FROM SYS_AUTOGEN_PARAMS
     WHERE PARAM_NAME ='STORES_CHALLANIN_NO_GENERAL'
     
     SET DEFINE OFF;
Insert into SYS_AUTOGEN_PARAMS
   (COMPANYCODE, DIVISIONCODE, YEARCODE, PARAM_NAME, TOT_LENGTH, PREFIX, SUFFIX, ACT_TABLENAME, ACT_COL_NAME, PADDING_LENGTH, SEQUENCER_NAME, PURPOSE)
 Values
   ('CJ0101', '0002', '2020-2021', 'STORES_CHALLANIN_NO_WITHOUT_STORE', 13, 
    'C/GI/<<Y1>>/', NULL, 'STORESCHALLANINDETAILS', 'TRANSACTIONNO', 5, 
    NULL, NULL);
COMMIT;
