SELECT * FROM LOGIN


SELECT * FROM MENUMASTER_RND
WHERE MENUDESC LIKE 'User%Rol%'

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE LIKE '01993%'


SELECT * FROM roledetails
WHERE MENUCODE LIKE '019908'



SET DEFINE OFF;
Insert into BIRLANEW.MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, 
    MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, 
    REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, 
    EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, 
    FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, 
    DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('019919', NULL, 'File Upload into Location', 'UTILITIES', 'FILE UPLOAD INTO LOCATION', 
    NULL, NULL, 'Y', 'Y', 'N', 
    'N', 'N', 'Y', 'GENERAL', NULL, 
    NULL, '''0001''', NULL, 'GENERAL/Pages/Common/pgUploadFileIntoLocation.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into JOONK.MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, 
    MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, 
    REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, 
    EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, 
    FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, 
    DOCDATEVALIDATEFIELD, AUDITRAIL, KEY_COLUMN)
 Values
   ('019923', NULL, 'File Upload into Location', 'UTILITIES', 'FILE UPLOAD INTO LOCATION', 
    NULL, NULL, 'Y', 'Y', 'N', 
    'N', 'N', 'Y', 'GENERAL', NULL, 
    '''0001'',''0003'',''0002'',''0004'',''0005'',''0006'',''0007'',''0008'',''0009'',''0010'',''0011''', '''0001'',''0003'',''0002'',''0004'',''0005'',''0006'',''0007'',''0008'',''0009'',''0010'',''0011''', NULL, 'GENERAL/Pages/Common/pgUploadFileIntoLocation.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL, NULL);
COMMIT;



SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, 
    ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, 
    SYSROWID)
 Values
   ('54', '019923', 'Y', 'Y', 'X', 
    'X', 'X', 'X', 'X', 'GENERAL', 
    '202008031748500010870039');
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, 
    ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, 
    SYSROWID)
 Values
   ('1', '019923', 'Y', 'Y', 'X', 
    'X', 'X', 'X', 'X', 'GENERAL', 
    '202005081119430010404748');
COMMIT;
