SELECT * FROM COMPANYMAST

0004

SELECT * FROM LOGIN


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID LIKE '112_'


VW_RUKA_STOCK_DETAILS_DUMMY

---------------------------------------------------------



SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (1120, '""', 'COMPANYCODE~DIVISIONCODE~ARRIVALDATE~PATTERN', 'P.O. INFORMATION FOR JUTE ARRIVAL', NULL, 
    'SELECT ORDERNO, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') ORDERDATE, SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND A.TRANSACTIONDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO, A.ORDERDATE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND B.ARRIVALDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO,A.ORDERDATE
) 
WHERE 1=1
GROUP BY ORDERNO, ORDERDATE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO
', 'ORDERNO~', 'JUTE');
COMMIT;


SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (1121, '""', 'COMPANYCODE~DIVISIONCODE~ARRIVALDATE~REGIONCODE~PATTERN', 'P.O. INFORMATION FOR JUTE ARRIVAL', NULL, 
    'SELECT ORDERNO,REGIONCODE, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, B.REGIONCODE, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') ORDERDATE, 
        SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, 
        SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND A.TRANSACTIONDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO, A.ORDERDATE,B.REGIONCODE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,B.REGIONCODE, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE =  <<DIVISIONCODE>>
          AND B.ARRIVALDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO,A.ORDERDATE,B.REGIONCODE
) 
WHERE 1=1
 AND REGIONCODE =NVL(<<REGIONCODE>>,REGIONCODE)
GROUP BY ORDERNO, ORDERDATE,REGIONCODE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO
', 'ORDERNO~REGIONCODE~', 'JUTE');
COMMIT;


SELECT * FROM COMPANYMAST

0004

SELECT * FROM   DIVISIONMASTER

0042

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL DETAILS COLUMN TO BE CHANGE', 'ARRIVAL DETAILS COLUMN TO BE CHANGE', 
   'ORDERNO,ORDERDATE,PRIVATEMARKPO,MILLGRDCODEPO,MKTGRDCODEPO,CROPYEARASPERPO,BALETYPE,ORDERSERIALNO', 'JUTE', '0004', 
    TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0042', 'SWT', 'SWT TO SET');

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL MASTER COLUMN TO BE CHANGE', 'ARRIVAL MASTER COLUMN TO BE CHANGE', 
   'ORDERNO,ORDERDATE,BROKERCODE,REGIONCODE,BOOKINGSTATION,CONTRACTNO,CONTRACTDATE ', 'JUTE', '0004', 
    TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0042', 'SWT', 'SWT TO SET');
COMMIT;

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL DUMMY PO PREFIX', 'ARRIVAL DUMMY PO PREFIX', 'DUMMY', 'JUTE', '0004', 
   TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0042', 'SWT', 
    'SWT TO SET');
COMMIT;





select * from menumaster_rnd
where upper(menudesc) like upper('Purchase Order%')
and menutype like 'TRANS%'

select * from menumaster_rnd
where menucode like '01020221'


select * from menumaster_rnd
where menucode like '010202010_'

select * from roledetails
where menucode like '0102020101'


SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01020221', NULL, 'Arrival Details without PO', 'TRANSACTIONS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'JUTE', NULL, 
    NULL, '''0042''', NULL, 'JUTE/Pages/Transaction/pgRawJuteArrival_without_PO.aspx', NULL, 
    NULL, 'prcJuteArr_Before_MainSave', NULL, 'Y', 'N', 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '01020221', 'Y', 'Y', 'Y', 
    'X', 'X', 'Y', 'X', 'JUTE', 
    '201905201317530010060679');
COMMIT;




select * from menumaster_rnd
where menucode like '0102020105'

select * from roledetails
where menucode like '0102020101'


SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0102020105', NULL, 'Purchase Order (Dummy)', 'TRANSACTIONS', 'PURCHASE ORDER DUMMY', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'JUTE', NULL, 
    NULL, '''0042''', NULL, 'JUTE/Pages/Transaction/pgJUTEPURCHASEORDER_BS.aspx', NULL, 
    NULL, 'prcJutePODummy_Before_MainSave', NULL, 'Y', 'N', 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '0102020105', 'Y', 'Y', 'Y', 
    'X', 'X', 'Y', 'X', 'JUTE', 
    '201905201317530010060679');
COMMIT;




ALTER TABLE GBL_JUTEPURCHASEORDERMASTER ADD ISDUMMY VARCHAR2(1)


select * from SYS_TFMAP
where SYS_TABLENAME_ACTUAL='JUTEPURCHASEORDERMASTER'

SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (1023, 'NONE', 'GBL_JUTEPURCHASEORDERMASTER', 'ISDUMMY', 
    8, 'VARCHAR2', 1, 0, 'N', 
    'txtISDUMMY', TO_TIMESTAMP('08/11/2014 11:20:59.000000 AM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;



--------------------------------------------------------------------------------

SELECT * FROM SYS_PARAMETER 
WHERE PARAMETER_NAME IN 
(
    'ARRIVAL DETAILS COLUMN TO BE CHANGE',
    'ARRIVAL MASTER COLUMN TO BE CHANGE',
    'ARRIVAL DUMMY PO PREFIX'
)

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL DETAILS COLUMN TO BE CHANGE', 'ARRIVAL DETAILS COLUMN TO BE CHANGE', 'ORDERNO,ORDERDATE,PRIVATEMARKPO,MILLGRDCODEPO,MKTGRDCODEPO,CROPYEARASPERPO,BALETYPE,ORDERSERIALNO', 
   'JUTE', '0004', 
    TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0042', 'SWT', 'SWT TO SET');

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL MASTER COLUMN TO BE CHANGE', 'ARRIVAL MASTER COLUMN TO BE CHANGE', 'ORDERNO,ORDERDATE,BROKERCODE,REGIONCODE,BOOKINGSTATION,CONTRACTNO,CONTRACTDATE ', 
   'JUTE', '0004', 
    TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0042', 'SWT', 'SWT TO SET');
COMMIT;

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL DUMMY PO PREFIX', 'ARRIVAL DUMMY PO PREFIX', 'DUMMY', 'JUTE', 
    '0004', TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0042', 'SWT', 
    'SWT TO SET');
COMMIT;


---------------------------------------------------------------------------------


  select * from SYS_TFMAP --set SYS_KEYCOLUMN='N'
  WHERE SYS_TABLENAME_ACTUAL = 'JUTEARRIVALDETAILS'
--  AND SYS_TABLE_SEQUENCIER='1026'
  AND SYS_COLUMNNAME='SYSROWID'
  

  update SYS_TFMAP set SYS_KEYCOLUMN='N'
  WHERE SYS_TABLENAME_ACTUAL = 'JUTEARRIVALDETAILS'
  AND SYS_TABLE_SEQUENCIER='1026'
  AND SYS_COLUMNNAME='SYSROWID'
  
  
  EXEC PROC_CREATE_GBL_TMP_TABLES(1026,0)


---------------------------------------------------------------------------------
