SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='1026'


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='72'

SELECT PAYMENTTYPE 
FROM JUTEPAYTYPEMAST 
WHERE COMPANYCODE = <<COMPANYCODE>> 
AND DIVISIONCODE = <<DIVISIONCODE>>

JUTEPAYTYPEMAST


SELECT DISTINCT PAYMENTTYPE, CRDLMTDAYS, DEFAULTPYMENTTYPE
FROM JUTEPAYTYPEMAST
WHERE COMPANYCODE =<<COMPANYCODE>>
  AND DIVISIONCODE =<<DIVISIONCODE>>
  AND WITHEFFECTFROM=TO_DATE(<<WITHEFFECTFROM>>,'DD/MM/YYYY')
 ORDER BY PAYMENTTYPE
 
 

GBL_JUTEPAYTYPEMAST


SELECT * FROM SYS_TFMAP
WHERE 1=1
AND SYS_TABLE_SEQUENCIER='1003'
--AND SYS_TABLENAME_ACTUAL='JUTEPAYTYPEMAST'
AND SYS_COLUMNNAME='GRACEDAYS'


1003


EXEC PROC_CREATE_GBL_TMP_TABLES(1003,0).



SELECT * FROM MENUMASTER_RND
WHERE MENUDESC LIKE 'Payment%'

JUTE/Pages/Master/pgJutePaymentType.aspx


