

SELECT * FROM SYS_TFMAP
WHERE 1=1
AND SYS_TABLE_SEQUENCIER='1003'
--AND SYS_TABLENAME_ACTUAL='JUTEPAYTYPEMAST'
AND SYS_COLUMNNAME='GRACEDAYS'



SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (1003, 'JUTEPAYTYPEMAST', 'GBL_JUTEPAYTYPEMAST', 'GRACEDAYS', 8, 
    'NUMBER', 18, 2, 'N', 'txtGRACEDAYS', 
    TO_TIMESTAMP('16/11/2020 2:26:38.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;



EXEC PROC_CREATE_GBL_TMP_TABLES(1003,0).