
SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%pf loan%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE = '01110201'

prcWPS_PFLOAN_b4Save	prcWPS_PFLOAN_AfterSave

select * from pfloantransaction
where tokenno='63755'

PROC_PFLOANSANCTION