

INSERT INTO ACACLEDGER(COMPANYCODE,DIVISIONCODE,ACCODE,ACHEAD,ACSHORTDESCRIPTION, ACTYPE,MAINGROUPCODE,GROUPTYPE,ADDRESS1, COUNTRY,PIN,  STATE,
SHOWINTRANSACTIONS , LASTMODIFIED, SYNCHRONIZED, SYSROWID, SUPERKEYCODE,SUPERKEYNAME, USERNAME,GSTN)
SELECT  COMPANYCODE,'''0002''' DIVISIONCODE,PARTYCODE,PARTYNAME ACHEAD,PARTYNAME ACSHORTDESCRIPTION,  
'ASSETS' ACTYPE,'S000006' MAINGROUPCODE,'DEBTORS' GROUPTYPE,PARTYADDRESS ADDRESS1, PARTYCOUNTRY COUNTRY,REPLACE(TRIM(PARTYPIN),' ','') PIN,  PARTYSTATE STATE,
'Y' SHOWINTRANSACTIONS , SYSDATE LASTMODIFIED, 'N' SYNCHRONIZED, FN_GENERATE_SYSROWID SYSROWID, 'N000001' SUPERKEYCODE,'NONE' SUPERKEYNAME,'MIG' USERNAME,GSTNNO GSTN
FROM PARTYMASTER WHERE COMPANYCODE='DJ0107'

AND LENGTH(REPLACE(TRIM(PARTYPIN),' ','')) > 6

(DALHOUSIE_WEB.ACACLEDGER_PK) 

SELECT PARTYPIN FROM PARTYMASTER WHERE COMPANYCODE='DJ0107'


ACACLEDGER_PK

SELECT PARTYCODE,COUNT(PARTYCODE) FROM PARTYMASTER WHERE COMPANYCODE='DJ0107' GROUP BY PARTYCODE HAVING COUNT(PARTYCODE)>1


122.163.121.140


-----------------------------------------------------------------------------------------------

INSERT INTO ACACLEDGER(COMPANYCODE,DIVISIONCODE,ACCODE,ACHEAD,ACSHORTDESCRIPTION, ACTYPE,MAINGROUPCODE,GROUPTYPE,ADDRESS1, COUNTRY,  STATE,PIN,
SHOWINTRANSACTIONS , LASTMODIFIED, SYNCHRONIZED, SYSROWID, SUPERKEYCODE,SUPERKEYNAME, USERNAME,GSTN)

SELECT REPLACE(NVL(PARTYPIN,'000000'),' ','') ZZ FROM  (
SELECT  COMPANYCODE,'''0002''' DIVISIONCODE,PARTYCODE,PARTYNAME ACHEAD,PARTYNAME ACSHORTDESCRIPTION,  'ASSETS' ACTYPE,'S000006' MAINGROUPCODE,'DEBTORS' GROUPTYPE,PARTYADDRESS ADDRESS1, 
PARTYCOUNTRY COUNTRY, PARTYSTATE STATE, PARTYPIN,
'Y' SHOWINTRANSACTIONS , SYSDATE LASTMODIFIED, 'N' SYNCHRONIZED, FN_GENERATE_SYSROWID SYSROWID, 'N000001' SUPERKEYCODE,'NONE' SUPERKEYNAME,'MIG' USERNAME,GSTNNO GSTN
FROM PARTYMASTER WHERE COMPANYCODE='DJ0107'
)
WHERE INSTR(PARTYPIN,'1',1)<0

SELECT REPLACE(PARTYPIN,' ','') PARTYPIN FROM PARTYMASTER WHERE COMPANYCODE='DJ0107'

SELECT * FROM SALESQUALITYMASTER

SELECT PARTYPIN FROM PARTYMASTER WHERE COMPANYCODE='DJ0107'
AND PARTYPIN NOT LIKE '7%' AND PARTYPIN NOT LIKE '1%' AND PARTYPIN NOT LIKE '4%' AND PARTYPIN NOT LIKE '3%' AND PARTYPIN NOT LIKE '6%' AND PARTYPIN NOT LIKE '2%'
AND PARTYPIN NOT LIKE '5%' AND PARTYPIN NOT LIKE '8%'

SELECT SUBSTR(TRIM(' 711114'),1,6) FROM DUAL

DELETE FROM ACACLEDGER WHERE COMPANYCODE ='DJ0107'

