DROP TABLE SYS_SWT_PARAMDETAILS CASCADE CONSTRAINTS;

CREATE TABLE SYS_SWT_PARAMDETAILS
(
  COMPANYCODE        VARCHAR2(10 BYTE),
  DIVISIONCODE       VARCHAR2(10 BYTE),
  MODULE             VARCHAR2(30 BYTE),
  REF_TABLE_NAME     VARCHAR2(30 BYTE),
  PARAM_ID           VARCHAR2(10 BYTE),
  PARAM_NAME         VARCHAR2(50 BYTE),
  PARAM_VALUE        VARCHAR2(100 BYTE),
  USERNAME           VARCHAR2(100 BYTE),
  LASTMODIFIED       DATE                       DEFAULT SYSDATE,
  SYSROWID           VARCHAR2(50 BYTE),
  EFFECTIVEDATE      DATE,
  PARAMVALUE_STRING  VARCHAR2(250 BYTE),
  OBJECT_TYPE        VARCHAR2(50 BYTE)
)
TABLESPACE CJIL_WEB
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IDX_SYS_SWT_PAR_06022020122418 ON SYS_SWT_PARAMDETAILS
(COMPANYCODE, DIVISIONCODE, PARAM_ID)
LOGGING
TABLESPACE CJIL_WEB
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_SYS_SWT_PAR_18062018034121 ON SYS_SWT_PARAMDETAILS
(PARAM_ID)
LOGGING
TABLESPACE CJIL_WEB
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_SYS_SWT_PAR_19062018111411 ON SYS_SWT_PARAMDETAILS
(DIVISIONCODE, PARAM_ID, COMPANYCODE)
LOGGING
TABLESPACE CJIL_WEB
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

