SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='6001'


SELECT DEPARTMENTCODE, DEPARTMENTNAME
  FROM WPSDEPARTMENTMASTER 
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
 ORDER BY DEPARTMENTCODE
 
 
 SELECT * FROM WPSDEPARTMENTMASTER
 
 SELECT * FROM COMPANYMAST
 
 
 
UPDATE WPSDEPARTMENTMASTER
SET DEPARTMENTCODE = SUBSTR(DEPARTMENTCODE,1,2)
 