DECLARE 

BEGIN

SELECT DISTINCT TABLE_NAME FROM COLS
WHERE COLUMN_NAME='COMPANYCODE'
AND TABLE_NAME LIKE '%WPS%'
AND TABLE_NAME NOT LIKE 'GBL%'
AND TABLE_NAME NOT LIKE 'GTT%'

SELECT COMPANYCODE FROM 


WPSATTENDANCEDAYWISE

END;

SELECT * FROM COMPANYMAST

SELECT * FROM WPSDEPARTMENTMASTER

UPDATE WPSDEPARTMENTMASTER
SET COMPANYCODE='CJ0101'
WHERE COMPANYCODE='CJ0001'

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = 'WPSDEPARTMENTMASTER'


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_WPSDEPARTMENTMASTER'


--------------------------------------------------------------------------------


SELECT 'CJ0101' COMPANYCODE, '0002' DIVISIONCODE, '' MODULE, 
       A.PARAM_CAPTION, A.REF_TABLE_NAME, '04' PARAM_ID, A.PARAM_NAME, B.PARAM_VALUE,  'SWT' USERNAME, 
       'A' OPERATIONMODE, B.SYSROWID, NULL EFFECTIVEDATE 
  FROM SYS_SWT_TABLE_PARAMMAST A, 
       ( 
         SELECT * FROM SYS_SWT_PARAMDETAILS 
          WHERE COMPANYCODE='CJ0101' 
          AND DIVISIONCODE='0002' 
          AND PARAM_ID='04' 
          AND REF_TABLE_NAME='WPSSECTIONMAST' 
          AND PARAM_ID||EFFECTIVEDATE IN ( SELECT PARAM_ID||MAX(EFFECTIVEDATE) FROM SYS_SWT_PARAMDETAILS 
                                            WHERE COMPANYCODE='CJ0101' 
                                              AND DIVISIONCODE='0002' 
                                            GROUP BY PARAM_ID 
                                         ) 
       ) B 
 WHERE A.COMPANYCODE='CJ0101' 
   AND A.DIVISIONCODE='0002' 
   AND A.REF_TABLE_NAME='WPSSECTIONMAST' 
   AND A.COMPANYCODE=B.COMPANYCODE(+) 
   AND A.DIVISIONCODE=B.DIVISIONCODE(+) 
   AND A.PARAM_NAME = B.PARAM_NAME(+) 
   AND B.PARAM_ID (+) ='04' 
 ORDER BY A.PARAM_NAME 
 
 
 SELECT * FROM DIVISIONMASTER
 
 CJ0101
 
 0002
 
 
select * from  wpssectionmast