SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'MODETYPE', 15, 
    'VARCHAR2', 10, 0, 'N', 'MODETYPE', 
    TO_TIMESTAMP('20/02/2019 2:26:46.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'CLUSTERCODE', 4, 
    'VARCHAR2', 10, 0, 'N', 'CLUSTERCODE', 
    TO_TIMESTAMP('19/02/2019 3:56:46.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'LEAVECODE', 7, 
    'VARCHAR2', 10, 0, 'N', 'LEAVECODE', 
    TO_TIMESTAMP('19/02/2019 3:50:52.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'WORKERSERIAL', 9, 
    'VARCHAR2', 10, 0, 'N', 'WORKERSERIAL', 
    TO_TIMESTAMP('19/02/2019 3:50:52.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'ATTNBOOKCODE', 6, 
    'VARCHAR2', 10, 0, 'N', 'ATTNBOOKCODE', 
    TO_TIMESTAMP('19/02/2019 3:57:03.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'YEARCODE', 3, 
    'VARCHAR2', 10, 0, 'N', 'YEARCODE', 
    TO_TIMESTAMP('19/02/2019 3:50:52.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'TODATE', 12, 
    'DATE', 10, 0, 'N', 'TODATE', 
    TO_TIMESTAMP('19/02/2019 3:58:41.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'FROMDATE', 11, 
    'DATE', 10, 0, 'N', 'FROMDATE', 
    TO_TIMESTAMP('19/02/2019 3:50:52.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'BALANCENO', 10, 
    'NUMBER', 11, 2, 'N', 'BALANCENO', 
    TO_TIMESTAMP('19/02/2019 4:00:14.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'DAYOFFDAYS', 10, 
    'VARCHAR2', 50, 0, 'N', 'DAYOFFDAYS', 
    TO_TIMESTAMP('19/02/2019 3:50:52.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'COMPANYCODE', 1, 
    'VARCHAR2', 10, 0, 'Y', 'COMPANYCODE', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'USERNAME', 13, 
    'VARCHAR2', 100, 0, 'N', 'USERNAME', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'SYSROWID', 14, 
    'VARCHAR2', 50, 0, 'Y', 'SYSROWID', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'CATEGORYCODE', 5, 
    'VARCHAR2', 10, 0, 'N', 'CATEGORYCODE', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'DIVISIONCODE', 2, 
    'VARCHAR2', 10, 0, 'Y', 'DIVISIONCODE', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'GPSLEAVEAPPLICATION', 'GBL_GPSLVAPPLICATION', 'TOKENNO', 8, 
    'VARCHAR2', 10, 0, 'Y', 'TOKENNO', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20303, 'NONE', 'GBL_GPSLVAPPLICATION', 'OPERATIONMODE', 0, 
    'VARCHAR2', 1, 0, 'N', 'OPERATIONMODE', 
    TO_TIMESTAMP('19/02/2019 3:50:53.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;


EXEC PROC_CREATE_GBL_TMP_TABLES(20303,0)

SELECT * FROM GBL_LEAVEBAL

SELECT * FROM GPSATTNBOOKMAST

EXEC PRC_GPSLEAVEBALANCE ('DT0091','0001','2020-2021','19/11/2020',1,'','')


SELECT * FROM GPSLEAVEAPPLICATION
WHERE LEAVEDATE='19-NOV-2020'
AND LEAVECODE='ANL'

DELETE FROM GPSATTENDANCEDETAILS_STAGE
WHERE ATTENDANCEDATE='19-NOV-2020'
AND OCCUPATIONCODE='ANL'


GPSATTENDANCEDETAILS_STAGE