SELECT * FROM SYS_HELP_QRY

MENUMASTER_RND 

SELECT * FROM SYS_HELP_QRY
WHERE MODULENAME='PRODUCTION_TEA'

SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID LIKE '21075%'

SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, 
    WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (21034, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'SORTING INFORMATION', NULL, 
    'SELECT DISTINCT SORTINGNO, TO_CHAR(SORTINGDATE,''DD/MM/YYYY'') SORTINGDATE'||CHR(10)||'FROM PRODDAILYSORTINGDETAILS'||CHR(10)||'WHERE COMPANYCODE = <<COMPANYCODE>>'||CHR(10)||'AND DIVISIONCODE = <<DIVISIONCODE>>'||CHR(10)||'ORDER BY SORTINGNO DESC,SORTINGDATE'||CHR(10)||CHR(10)||CHR(10)||CHR(10)||'', 'SORTINGNO~SORTINGDATE~', 'PRODUCTION_TEA');
COMMIT;

SELECT * FROM PRODCATEGORYTRANSFERDETAILS
WHERE DOCUMENTNO=''
AND COMPANYCODE=''
AND DIVISIONCODE=''


DELETE FROM PRODCATEGORYTRANSFERDETAILS WHERE DOCUMENTNO = '1'


prcProd_CatgoryTransfer_B4Save

SELECT
COMPANYCODE, DIVISIONCODE, YEARCODE, SEASON, DRYERNO, TEACATEGORYCODE, PRODUCTIONDATE, 
DRYERMACHINENO, DRYERSTARTDATE, DRYERSTARTTIME, DRYERENDDATE, DRYERENDTIME, BDREASONCODE, 
BDTIME, BATCHNO, DRYERQTY, INTIME, OUTTIME, RUNNINGTIME, TEAMADEQTY, T1, T2, T3, T5, 
USERNAME, SYSROWID, TRANDATE, OWNBOUGHT, LASTMODIFIED
FROM PRODDAILYDRYERDETAILS
WHERE DRYERNO LIKE '%TRA%'

PRODUCTIONDATE ='10-SEP-2020'

WHERE BATCHNO='1/AM0082/A13/3/2020/04/28/OWN/001'

SELECT
COMPANYCODE, DIVISIONCODE, YEARCODE,TO_CHAR(TRANSFERDATE,'YYYY') SEASON,DOCUMENTNO DRYERNO,
CATEGORYCODETO TEACATEGORYCODE,TRANSFERDATE PRODUCTIONDATE,NULL DRYERMACHINENO,TRANSFERDATE DRYERSTARTDATE,
NULL DRYERSTARTTIME,TRANSFERDATE DRYERENDDATE,NULL DRYERENDTIME,NULL BDREASONCODE, NULL BDTIME,
'******************' BATCHNO,0 DRYERQTY,NULL INTIME,NULL OUTTIME,NULL RUNNINGTIME,
TRANSFERQTY TEAMADEQTY,NULL T1,NULL T2,NULL T3,NULL T5, 
USERNAME,SYS_GUID() SYSROWID,TRANSFERDATE TRANDATE,'OWN' OWNBOUGHT,SYSDATE LASTMODIFIED
FROM PRODCATEGORYTRANSFERDETAILS

WHERE BATCHNO='1/AM0082/A13/3/2020/04/28/OWN/001'

SELECT *
FROM PRODCATEGORYTRANSFERDETAILS


COMPANYCODE, DIVISIONCODE, YEARCODE, CATEGORYCODEFROM, CATEGORYCODETO, DOCUMENTNO, 
TRANSFERDATE, AVAILABLEQTY, TRANSFERQTY, BALANCEQTY, REMARKS, USERNAME, SYSROWID, LASTMODIFIED

SELECT FN_GETBATCH('AM0082','A16','A16','TRANSFER','01/09/2020','OWN','TRANSFER','TRANSFER') FROM DUAL


                        lv_Master.COMPANYCODE,
                        lv_Master.DIVISIONCODE,
                        lv_Master.DIVISIONCODE,
                        null,
                        lv_Master.TRANSFERDATE,
                        'OWN',
                        NULL,
                        NULL
                    );
                    
-----------------------------------------------------------------------                    

select * from PRODDAILYDRYERDETAILS
where divisioncode='A16'



select SUM(NVL(SORTINGQTY,0)) from proddailysortingdetails
where DIVISIONCODE='A16'
AND TEACATEGORYCODE='CTC'
 
SELECT SUM(NVL(TEAMADEQTY,0)) FROM PRODDAILYDRYERDETAILS
where DIVISIONCODE='A16'
AND TEACATEGORYCODE='CTC'
  AND COMPANYCODE =  'AM0082'
AND PRODUCTIONDATE < TO_DATE('09/09/2020','DD/MM/YYYY') 

SELECT SUM(NVL(TEAMADEQTY,0)) BALANCEQTY FROM PRODDAILYDRYERDETAILS 
    WHERE PRODUCTIONDATE < TO_DATE('09/09/2020','DD/MM/YYYY') 
    AND COMPANYCODE =  'AM0082'
    AND DIVISIONCODE = 'A16'
    AND TEACATEGORYCODE = 'CTC'



 SELECT NVL(SUM(BALANCEQTY),0) OPENINGBALANCEQTY 
FROM 
( 
    SELECT SUM(NVL(TEAMADEQTY,0)) BALANCEQTY FROM PRODDAILYDRYERDETAILS 
    WHERE PRODUCTIONDATE < TO_DATE('09/09/2020','DD/MM/YYYY') 
    AND COMPANYCODE =  'AM0082'
    AND DIVISIONCODE = 'A16'
    AND TEACATEGORYCODE = 'CTC'
    UNION ALL 
    SELECT -SUM(NVL(SORTINGQTY,0)) BALANCEQTY FROM PRODDAILYSORTINGDETAILS 
    WHERE SORTINGDATE < TO_DATE('09/09/2020','DD/MM/YYYY') 
    AND COMPANYCODE =  'AM0082'
    AND DIVISIONCODE = 'A16'
    AND TEACATEGORYCODE = 'CTC'
) 


PRODCATEGORYTRANSFERDETAILS



SELECT FN_GETBATCH('AM0082','A16','A16','','01/09/2020','OWN','','TRANSFER') FROM DUAL

AM0082/A16//2020/09/01/OWN/001


         
--FN_GETBATCH (
--   P_COMPANYCODE      VARCHAR2,
--   P_DIVOWN           VARCHAR2,
--   P_DIVISIONCODE     VARCHAR2,
--   P_AREACODE         VARCHAR2,
--   P_WITHERINGDATE    VARCHAR2,
--   P_RECEIPTTYPE      VARCHAR2,
--   P_TROUGHNO         VARCHAR2,
--   P_FLAG             VARCHAR2) 