SELECT * FROM WPSWAGESDETAILS
WHERE FORTNIGHTSTARTDATE='01-JAN-2021'
AND CASH_REALIZE > 0


 SELECT * FROM WPSUNREALIZEDDATA
 WHERE FORTNIGHTENDDATE < TO_DATE('15/01/2021','DD/MM/YYYY') 
 AND MODULE = 'WPS' 
 AND COMPONENTCODE = 'CASHOT_AMT'
-- AND TRANTYPE = 'REALIZED' 
 AND COMPANYCODE = '0003' 
 AND DIVISIONCODE = '0032' 
 
 
prcWPS_Wages_Process

truncate table wps_error_log


select * from wps_error_log

 WHERE 1=1 --COMPANYCODE =P_COMPCODE AND DIVISIONCODE=P_DIVCODE
          AND ORA_ERROR_MESSG IS NOT NULL;


PROC_WPSVIEWCREATION

PROC_WPSWAGESPROCESS_INSERT

PRC_REALIZEDUNREALDATA_INSERT





SELECT A.COMPONENTCODE, A.COMPONENTSHORTNAME, A.COMPONENTNAME, A.COMPONENTTYPE, 
A.COMPONENTGROUP, A.PHASE, A.COMPONENTTAG, A.FORMULA, A.CALCULATIONINDEX 
        FROM WPSCOMPONENTMASTER A 
        WHERE A.COMPANYCODE = '0003' AND A.DIVISIONCODE = '0032'
          AND TAKEPARTINWAGES = 'Y'
          --AND A.COMPONENTGROUP NOT IN ('LOAN')  
          
        ORDER BY CALCULATIONINDEX      
        
        
    

 CREATE TABLE SWT_PHASE_DEDN AS 
 SELECT WPSTEMPATTN.WORKERSERIAL,  WPSTEMPMAST.WORKERCATEGORYCODE, 
 SUM(NVL(WPSTEMPCOMPONENT.GROSS_WAGES,0)) AS GROSS_WAGES 
 , SUM(ROUND(WPSTEMPCOMPONENT.PF_GROSS * (10/100))) AS PF_CONT, SUM(CASE WHEN WPSTEMPMAST.ESIAPPLICABLE = 'Y' THEN  CEIL(TRUNC(WPSTEMPCOMPONENT.ESI_GROSS *0.0075,2)) ELSE 0 END

                                           
) AS ESI_CONT, SUM(GROSS_PTAX) AS P_TAX, SUM(NVL(WPSTEMPATTN.CASH_REALIZE,0)) AS CASH_REALIZE, SUM(CASE WHEN TO_CHAR( WPSTEMPATTN.FORTNIGHTSTARTDATE ,'DDMM') IN ( '1606','1612') THEN   3    ELSE 0 END ) AS WF_DEDN, SUM(NVL(WPSTEMPATTN.OTHR_DEDN,0)) AS OTHR_DEDN, SUM(NVL(WPSTEMPATTN.LOAN_PFLN,0)) AS LOAN_PFLN, SUM(NVL(WPSTEMPATTN.LINT_PFLN,0)) AS LINT_PFLN, 0 AS LOAN_PJADV, SUM(NVL(WPSTEMPATTN.SHIBCO_DEDN,0)) AS SHIBCO_DEDN, 0 AS LINT_PJADV
 FROM WPSTEMPMAST, WPSTEMPATTN, WPSTEMPCOMPONENT 
 WHERE WPSTEMPATTN.WORKERSERIAL = WPSTEMPMAST.WORKERSERIAL 
   AND WPSTEMPATTN.WORKERSERIAL = WPSTEMPCOMPONENT.WORKERSERIAL  
 GROUP BY WPSTEMPATTN.WORKERSERIAL, WPSTEMPMAST.WORKERCATEGORYCODE 
 
 
 wpscomponentmaster
 
 select * from WPSWORKERCATEGORYVSCOMPONENT
 where componentcode like 'CASH_R%'
 
 
 
 
 INSERT INTO GBL_CASHOTUNREALIZED 
 ( 
      WORKERSERIAL, TOKENNO, MODULE, CASHOT_EMI, CASHOT_UNREALIZED 
 ) 
 
 SELECT WORKERSERIAL,TOKENNO,MODULE, SUM(COMPONENTAMOUNT) CASHOT_EMI, SUM(COMPONENTAMOUNT) UNREALIZEDAMOUNT 
 FROM WPSUNREALIZEDDATA 
 WHERE COMPANYCODE = '0003' 
 AND DIVISIONCODE = '0032' 
-- AND COMPONENTCODE = 'CASHOT_AMT' 
 AND TRANTYPE IN('REALIZED','UNREALIZED') 
 AND YEARCODE = '2020-2021' 
-- AND FORTNIGHTENDDATE < TO_DATE('15/01/2021','DD/MM/YYYY') 
 GROUP BY WORKERSERIAL,TOKENNO,MODULE 
 
 
 SELECT * FROM WPSWAGESDETAILS_MV_SWT
WHERE FORTNIGHTSTARTDATE='01-JAN-2021'
AND CASH_REALIZE > 0


INSERT INTO WPSUNREALIZEDDATA
( 
    COMPANYCODE, DIVISIONCODE, YEARCODE, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, WORKERSERIAL, TOKENNO,  
    COMPONENTCODE, COMPONENTAMOUNT, ACTUALAMOUNT, REFERENCE_FNEDATE, PAIDON, TRANTYPE, MODULE, REMARKS,  
    USERNAME, SYSROSWID, LASTMODIFIED
) 


 SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, WORKERSERIAL, TOKENNO,  
'CASHOT_AMT' COMPONENTCODE,-1*CASH_REALIZE COMPONENTAMOUNT,-1*CASH_REALIZE ACTUALAMOUNT,FORTNIGHTENDDATE REFERENCE_FNEDATE, 
FORTNIGHTENDDATE PAIDON,'REALIZED' TRANTYPE,'WPS' MODULE,'REALIZED AMOUNT THROUGH WAGES PROCESS' REMARKS,  
'SWT' USERNAME,FN_GENERATE_SYSROWID SYSROSWID,SYSDATE LASTMODIFIED
FROM WPSWAGESDETAILS_MV_SWT
WHERE COMPANYCODE='0003' 
AND DIVISIONCODE='0032' 
AND FORTNIGHTSTARTDATE = TO_DATE('01/01/2021','DD/MM/YYYY') 
AND FORTNIGHTENDDATE = TO_DATE('15/01/2021','DD/MM/YYYY') 
AND NVL(CASH_REALIZE,0) > 0 


PROC_CASHOT_IMPORTFROMKIOSK



SELECT * FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
WHERE ISTRANSFER= 'Y'

UPDATE WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK SET ISTRANSFER= 'N'



SELECT * FROM WPSUNREALIZEDDATA
WHERE TRANTYPE='REALIZED'









EXEC PROC_CASHOT_IMPORTFROMKIOSK('0003','0032','16/12/2020','31/12/2020')

SELECT * FROM SYS_GBL_PROCOUTPUT_INFO
      


 DELETE FROM WPSUNREALIZEDDATA
 WHERE COMPANYCODE='0003'
 AND DIVISIONCODE='0032'
 AND FORTNIGHTSTARTDATE >= TO_DATE('16/12/2020','DD/MM/YYYY')
 AND FORTNIGHTENDDATE <= TO_DATE('31/12/2020','DD/MM/YYYY')
 AND COMPONENTCODE='CASH_REALIZE'
 AND TRANTYPE= 'UNREALIZED'

 INSERT INTO WPSUNREALIZEDDATA
 (
     COMPANYCODE,DIVISIONCODE,YEARCODE,FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,WORKERSERIAL,TOKENNO,
     COMPONENTCODE,COMPONENTAMOUNT,ACTUALAMOUNT,REFERENCE_FNEDATE,PAIDON,TRANTYPE,MODULE,REMARKS,
     USERNAME,SYSROSWID,LASTMODIFIED,DOCNO,DOCDATE,TRAN_SOURCE
 )    
 
 
 SELECT
 COMPANYCODE,DIVISIONCODE,'2020-2021' YEARCODE,PAYMENTFROMDATE FORTNIGHTSTARTDATE,PAYMENTTODATE FORTNIGHTENDDATE,WORKERSERIAL,TOKENNO,
 'CASH_REALIZE' COMPONENTCODE,SUM(NETPAY) COMPONENTAMOUNT,SUM(NETPAY) ACTUALAMOUNT,NULL REFERENCE_FNEDATE,PAYMENTDATE PAIDON,'UNREALIZED' TRANTYPE, 
 'WPS' MODULE,'DATA IMPORT FROM CASH OT PAYMENT' REMARKS,'SWT' USERNAME,FN_GENERATE_SYSROWID SYSROSWID,SYSDATE LASTMODIFIED,
 NULL DOCNO, NULL DOCDATE, NULL TRAN_SOURCE
 FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
 WHERE COMPANYCODE='0003'
 AND DIVISIONCODE='0032'
 AND PAYMENTFROMDATE >= TO_DATE('16/12/2020','DD/MM/YYYY')
 AND PAYMENTTODATE <= TO_DATE('31/12/2020','DD/MM/YYYY')
 AND PAYMENTLOCK='Y'
 AND ISTRANSFER='N'

 UPDATE WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
 SET ISTRANSFER='Y'
 WHERE COMPANYCODE='0003'
 AND DIVISIONCODE='0032'
 AND PAYMENTFROMDATE >= TO_DATE('16/12/2020','DD/MM/YYYY')
 AND PAYMENTTODATE <= TO_DATE('31/12/2020','DD/MM/YYYY')
 AND PAYMENTLOCK='Y'
 AND ISTRANSFER='N'