
SELECT --COMPONENTCODE, USERENTRYAPPLICABLE, ATTENDANCEENTRYAPPLICABLE, ROLLOVERAPPLICABLE
WM_CONCAT(CASE WHEN  ROLLOVERAPPLICABLE='Y' THEN 'PISASSIGN.'||COMPONENTCODE WHEN ATTENDANCEENTRYAPPLICABLE='Y' THEN 'PISATTN.'||COMPONENTCODE ELSE 'PISCOMP.'||COMPONENTCODE END) X,
WM_CONCAT('NVL('||COMPONENTCODE||',0)'||COMPONENTCODE) Y,
WM_CONCAT('SUM(NVL('||COMPONENTCODE||',0))'||COMPONENTCODE) z,
WM_CONCAT(COMPONENTCODE) W
FROM PISCOMPONENTMASTER
WHERE ISUNREALIZED='Y'


SELECT WORKRESERIAL, SUM(


SELECT WORKERSERIAL,TOKENNO,
SUM(NVL(ELECTRIC,0))ELECTRIC,SUM(NVL(CAR,0))CAR,SUM(NVL(CHOWKIDARI,0))CHOWKIDARI,SUM(NVL(FURNITURE,0))FURNITURE,SUM(NVL(CLUB,0))CLUB,SUM(NVL(RECREATION,0))RECREATION,SUM(NVL(SCHOOL_BUS,0))SCHOOL_BUS,SUM(NVL(DAIRY,0))DAIRY,SUM(NVL(SUBSCRIPTION,0))SUBSCRIPTION
FROM
(
SELECT A.WORKERSERIAL,A.TOKENNO,PISATTN.ELECTRIC,PISATTN.CAR,PISASSIGN.CHOWKIDARI,P ISASSIGN.FURNITURE,PISCOMP.CLUB,PISATTN.RECREATION,PISASSIGN.SCHOOL_BUS,PISATTN.DAIRY,PISATTN.SUBSCRIPTION
FROM PISEMPLOYEEMASTER A, PISASSIGN, PISATTN, PISCOMP 
WHERE A.COMPANYCODE ='BJ0056' AND A.DIVISIONCODE ='0001'
  AND A.WORKERSERIAL =PISASSIGN.WORKERSERIAL
  AND A.WORKERSERIAL =  PISATTN.WORKERSERIAL (+)
  AND A.WORKERSERIAL =  PISCOMP.WORKERSERIAL (+)
UNION ALL
SELECT WORKERSERIAL,TOKENNO, -NVL(ELECTRIC,0)ELECTRIC,-NVL(CAR,0)CAR,-NVL(CHOWKIDARI,0)CHOWKIDARI,-NVL(FURNITURE,0)FURNITURE,-NVL(CLUB,0)CLUB,-NVL(RECREATION,0)RECREATION,-NVL(SCHOOL_BUS,0)SCHOOL_BUS,-NVL(DAIRY,0)DAIRY,-NVL(SUBSCRIPTION,0)SUBSCRIPTION
FROM PISPAYTRANSACTION WHERE COMPANYCODE ='BJ0056' AND DIVISIONCODE ='0001'
AND YEARMONTH='202009'
)
GROUP BY WORKERSERIAL,TOKENNO

delete from pis_error_log


select * from pis_error_log
where proc_name='PRC_INSERT_UNREALIZEDDATA'


SELECT * FROM PISEMPLOYEEMASTER
WHERE TOKENNO='01230'

SELECT * FROM PISCOMPONENTMASTER
WHERE COMPONENTCODE='CLUB'

CASE WHEN PISMAST.UNITCODE='01' AND   PISMAST.TOKENNO<>'01207' 
AND  (PISMAST.CATEGORYCODE='10' OR PISMAST.CATEGORYCODE='11') THEN 
CASE WHEN PISASSIGN.BASIC < 2000 THEN 5 WHEN PISASSIGN.BASIC BETWEEN 2000 AND 2999 
THEN 8 WHEN PISASSIGN.BASIC BETWEEN 3000 AND 7499 THEN 10 ELSE 15 END 
END


SELECT LENGTH(SUBSTR('1234',1,6)) FROM DUAL