EXEC PRC_INSERT_UNREALIZEDDATA
(
    'BJ0056', 
    '0001', 
    '2020-2021', 
    '202010',
    '01/09/2020', 
    '30/09/2020', 
    '000001', 
    '00499', 
    'ELECTRIC', 
    200, 
    500, 
    '30/09/2020', 
    NULL, 
    'UNRELIZED', 
    'PIS', 
    'UNREALIZED AMOUNT INSERT', 
    'SWT'
)



IS
    lv_SqlStr VARCHAR2(1000);
    LV_CNT NUMBER(10);
BEGIN


SELECT COUNT(COMPONENTCODE) INTO LV_CNT 
FROM PISCOMPONENTMASTER 
WHERE COMPONENTCODE=P_COMPONENTCODE
AND ISUNREALIZED= 'Y';

IF LV_CNT > 0 THEN 

SELECT * FROM PISWPSUNREALIZEDDATA

INSERT INTO PISWPSUNREALIZEDDATA 
(
    COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
    WORKERSERIAL, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, ACTUALAMOUNT, REFERENCE_FNEDATE, 
    PAIDON, TRANTYPE, MODULE, REMARKS, USERNAME, SYSROSWID, LASTMODIFIED, DOCNO, DOCDATE, TRAN_SOURCE
)

SELECT 
'BJ0056' COMPANYCODE,'0001'  DIVISIONCODE,'2020-2021'  YEARCODE,'202010'  YEARMONTH, 
to_date('01/09/2020','DD/MM/YYYY') FORTNIGHTSTARTDATE,to_date('30/09/2020','DD/MM/YYYY')  FORTNIGHTENDDATE, 
'000001' WORKERSERIAL,'00499'  TOKENNO,'ELECTRIC'  COMPONENTCODE,'200'  COMPONENTAMOUNT,
'500'  ACTUALAMOUNT,to_date('30/09/2020','DD/MM/YYYY')  REFERENCE_FNEDATE, 
NULL PAIDON,'UNREALIZED'  TRANTYPE,'PIS'  MODULE,'UNREALIZED AMOUNT INSERT'  REMARKS,'SWT'  USERNAME,
fn_Generate_SysRowID SYSROSWID,SYSDATE LASTMODIFIED,
NULL DOCNO,NULL DOCDATE,NULL TRAN_SOURCE
FROM DUAL;

SELECT * FROM PIS_ERROR_LOG

INSERT INTO PISWPSUNREALIZEDDATA 
(
    COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
    WORKERSERIAL, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, ACTUALAMOUNT, REFERENCE_FNEDATE, 
    PAIDON, TRANTYPE, MODULE, REMARKS, USERNAME, SYSROSWID, LASTMODIFIED, DOCNO, DOCDATE, TRAN_SOURCE
)


SELECT * FROM PISWPSUNREALIZEDDATA


SELECT 
'BJ0056' COMPANYCODE,'0001'  DIVISIONCODE,'2020-2021'  YEARCODE,'202010'  YEARMONTH, 
to_date('01/09/2020','DD/MM/YYYY') FORTNIGHTSTARTDATE,to_date('30/09/2020','DD/MM/YYYY')  FORTNIGHTENDDATE, 
'000001' WORKERSERIAL,'00499'  TOKENNO,'ELECTRIC'  COMPONENTCODE,'200'  COMPONENTAMOUNT,
'500'  ACTUALAMOUNT,to_date('30/09/2020','DD/MM/YYYY')  REFERENCE_FNEDATE, 
NULL PAIDON,'UNREALIZED'  TRANTYPE,'PIS'  MODULE,'UNREALIZED AMOUNT INSERT'  REMARKS,'SWT'  USERNAME,
fn_Generate_SysRowID SYSROSWID,SYSDATE LASTMODIFIED,
NULL DOCNO,NULL DOCDATE,NULL TRAN_SOURCE
FROM DUAL;