EXEC PROC_GRATUITY_ENTITLEMENT_ADD('NJ0001','0002','30302','','A')

 SELECT 
    --TO_CHAR(DATEOFJOINING,'DD/MM/YYYY'),  
    CASE WHEN GRATUITYJOINDATE IS NULL THEN TO_CHAR(PFMEMBERSHIPDATE,'YYYY')
    ELSE  
     CASE WHEN  PFMEMBERSHIPDATE<=GRATUITYJOINDATE THEN TO_CHAR(GRATUITYJOINDATE,'YYYY') END 
     END ,
    TO_CHAR(nvl(DATEOFTERMINATION,sysdate),'YYYY') 
--    INTO LV_DATEOFJOINING,LV_YEAROFTERMINATION
    FROM WORKERVIEWGRATUITY 
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE='0002'
    AND TOKENNO='30302';
    
    SELECT * FROM WORKERVIEWGRATUITY
    WHERE TOKENNO='30302'
    
SELECT * FROM USER_SOURCE WHERE TEXT LIKE '%WORKERVIEWGRATUITY%'
    

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''