
SELECT FN_ROUNDOFFRS(P_AMOUNT NUMBER, P_ROUNDOFTO NUMBER, P_ROUNDOFTYPE VARCHAR2 DEFAULT 'S')
FROM DUAL


SELECT FN_ROUNDOFFRS(310, 5, CASE WHEN MOD(310,10) >= 5 THEN 'H' ELSE 'L' END)
FROM DUAL

SELECT MOD(315,10) FROM DUAL

WPSWAGESPROCESSTYPE_PHASE

PROC_WPSDAILYPROCESS_TRANSFER


SELECT TOKENNO,ACTUALPAYBLEAMOUNT,FN_ROUNDOFFRS(ACTUALPAYBLEAMOUNT, 5, CASE WHEN MOD(ACTUALPAYBLEAMOUNT,10) >= 5 THEN 'H' ELSE 'L' END)  FROM WPSDAILYWAGESDETAILS


CREATE TABLE WPSDAILYWAGESDETAILS_BK AS

SELECT * FROM WPSDAILYWAGESDETAILS

UPDATE WPSDAILYWAGESDETAILS
SET ACTUALPAYBLEAMOUNT = FN_ROUNDOFFRS(ACTUALPAYBLEAMOUNT, 5, CASE WHEN MOD(ACTUALPAYBLEAMOUNT,10) >= 5 THEN 'H' ELSE 'L' END)
WHERE 1=1;

