EXEC PROC_REIMBURSEMENT('0001','001','2020-2021','202008','001','02','','','LTA','','','')



(
    P_COMPANYCODE           VARCHAR2,
    P_DIVISIONCODE          VARCHAR2,
    P_YEARCODE              VARCHAR2,
    P_YEARMONTH             VARCHAR2,
    P_UNITCODE              VARCHAR2 DEFAULT NULL,
    P_CATEGORYCODE          VARCHAR2 DEFAULT NULL,
    P_GRADECODE             VARCHAR2 DEFAULT NULL,
    P_DEPARTMENTCODE        VARCHAR2 DEFAULT NULL,
    P_COMPONENTCODE        VARCHAR2 DEFAULT NULL,
    P_TOKENNO               VARCHAR2 DEFAULT NULL,
    P_MAXPREVYEAR         VARCHAR2 DEFAULT '1',
    P_OPERATIONMODE         VARCHAR2 DEFAULT 'A',
    P_WITHPREVIOUS         VARCHAR2 DEFAULT 'Y'
)