SELECT * FROM PISREIMBURSEMENTDETAILS

SELECT * FROM PISREIMBURSEMENT_ENTITLE



SELECT * FROM PIS_ERROR_LOG


SELECT * FROM PISCOMPONENTMASTER WHERE COMPONENTCODE LIKE 'LTA' AND DIVISIONCODE='001'

ACCCODE, SUBCODE


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%PAYROLL POST%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='010403020210'

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG LIKE '%TAG%'

SELECT * FROM SYS_TFMAP


ACCOUNTS/Pages/Transaction/AcPISPayrollPosting.aspx


prcpis_post_to_acc