SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='3093'

SELECT SALESBILLNO,TO_CHAR(SALESBILLDATE,'DD/MM/YYYY')SALESBILLDATE 
FROM SALESOTHERBILLMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>> 
AND CHANNELCODE=<<CHANNELCODE>> 
AND BILLTYPE=<<BILLTYPE>>
AND 1=1
ORDER BY SALESBILLNO


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = 'SALESOTHERBILLREFDETAILS'


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_SALESOTHERBILLREFDETAILS'


EXEC PROC_CREATE_SYSTFMAP('SALESOTHERBILLREFDETAILS','COMPANYCODE,DIVISIONCODE,SCRAPSALEBILLNO')

SELECT * FROM SYS_TFMAP WHERE  SYS_TABLE_SEQUENCIER = 15027

EXEC PROC_CREATE_GBL_TMP_TABLES(15027,0)


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%OTHER%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0105020905'

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

prcOth_Bill_Before_MainSave