
-- BIRLA DATA UPDATE ON 15/09/2020


fn_get_column_names_FORNULL_I



SELECT STATUSDATE,SUPERANUATIONDATE,PFSETTELMENTDATE,EXTENDEDRETIREDATE,DATEOFTERMINATIONADVICE FROM PISEMPLOYEEMASTER
WHERE TOKENNO=01069


SELECT STATUSDATE,SUPERANUATIONDATE,PFSETTELMENTDATE,EXTENDEDRETIREDATE,DATEOFTERMINATIONADVICE FROM PISEMPLOYEEMASTER
WHERE STATUSDATE IS NOT NULL

UPDATE PISEMPLOYEEMASTER SET (STATUSDATE,SUPERANUATIONDATE,PFSETTELMENTDATE,EXTENDEDRETIREDATE,DATEOFTERMINATIONADVICE) = 
(
    SELECT NULL,NULL,NULL,NULL,NULL FROM DUAL
)
WHERE STATUSDATE IS NOT NULL

--------------------------------------------------------------------------------------------------


SELECT E.TOKENNO, E.EMPLOYEENAME, E.DEPARTMENTCODE, D.DEPARTMENTDESC, L.ENTITLEMENTS, L.CARRYFORWARD, E.COMPANYCODE, E.DIVISIONCODE, '2020-2021' YEARCODE, E.UNITCODE, E.CATEGORYCODE, E.GRADECODE, E.WORKERSERIAL,  
       L.LEAVECODE,  CASE WHEN C.LEAVECALENDARORFINYRWISE='C' THEN TO_CHAR(TRUNC(SYSDATE),'YYYY') ELSE NULL END CALENDARYEAR, 
       L.SYSROWID, 'A' OPERATIONMODE, 'SWT' USERNAME 
  FROM PISEMPLOYEEMASTER E,  
       ( 
        SELECT T.* 
          FROM PISLEAVEENTITLEMENT T, PISLEAVEMASTER M  
         WHERE T.COMPANYCODE=M.COMPANYCODE 
           AND T.DIVISIONCODE=M.DIVISIONCODE 
           AND T.LEAVECODE=M.LEAVECODE 
           AND NVL(M.WITHOUTPAYLEAVE,'N')='N' 
           AND T.COMPANYCODE='BJ0056' 
           AND T.DIVISIONCODE='0001' 
           AND T.UNITCODE='01' 
           AND T.CATEGORYCODE='10' 
           AND T.GRADECODE='A' 
       ) L, PISDEPARTMENTMASTER D, PISCATEGORYMASTER C 
 WHERE E.COMPANYCODE=L.COMPANYCODE(+) 
   AND E.DIVISIONCODE=L.DIVISIONCODE(+) 
   AND E.WORKERSERIAL=L.WORKERSERIAL(+) 
   AND E.TOKENNO=L.TOKENNO(+) 
   AND L.LEAVECODE(+)='PL' 
   AND NVL(L.CALENDARYEAR,'NA') = DECODE(C.LEAVECALENDARORFINYRWISE,'C','2020', NVL(L.CALENDARYEAR,'NA'))
   AND E.COMPANYCODE=D.COMPANYCODE 
   AND E.DIVISIONCODE=D.DIVISIONCODE 
   AND E.DEPARTMENTCODE=D.DEPARTMENTCODE 
   AND E.COMPANYCODE=C.COMPANYCODE 
   AND E.DIVISIONCODE=C.DIVISIONCODE 
   AND E.CATEGORYCODE=C.CATEGORYCODE 
   AND E.COMPANYCODE='BJ0056' 
   AND E.DIVISIONCODE='0001' 
   AND E.UNITCODE='01' 
   AND E.CATEGORYCODE='10' 
   AND E.GRADECODE='A' 
 ORDER BY E.TOKENNO 
 
 SELECT * FROM PISLEAVEENTITLEMENT WHERE TOKENNO='00794'
 
 
SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL='PISLEAVEENTITLEMENT'

EXEC PROC_CREATE_GBL_TMP_TABLES(10010,0)

AND SYS_MAPFIELD LIKE 'msk%'

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP=''



CREATE TABLE PISLEAVEENTITLEMENT_BK AS
SELECT * FROM PISLEAVEENTITLEMENT


DELETE FROM PISLEAVEENTITLEMENT
WHERE ( YEARCODE, UNITCODE, CATEGORYCODE, GRADECODE,TOKENNO,LASTMODIFIED,SYSROWID) IN (
SELECT B.YEARCODE, B.UNITCODE, B.CATEGORYCODE, B.GRADECODE,A.TOKENNO,A.LASTMODIFIED,A.SYSROWID FROM PISLEAVEENTITLEMENT A,
(
SELECT DISTINCT YEARCODE, UNITCODE, CATEGORYCODE, GRADECODE,TOKENNO,COUNT(TOKENNO) CNT, MAX(LASTMODIFIED) LASTMODIFIED, MAX(SYSROWID) SYSROWID FROM PISLEAVEENTITLEMENT
GROUP BY YEARCODE, UNITCODE, CATEGORYCODE, GRADECODE,TOKENNO
HAVING COUNT(TOKENNO) > 1
) B
WHERE 
A.YEARCODE=B.YEARCODE AND 
A.UNITCODE=B.UNITCODE AND 
A.CATEGORYCODE=B.CATEGORYCODE AND  
A.GRADECODE=B.GRADECODE AND 
A.TOKENNO=B.TOKENNO AND 
--A.LASTMODIFIED<B.LASTMODIFIED  AND
A.SYSROWID<>B.SYSROWID 
)

SELECT DISTINCT YEARCODE, UNITCODE, CATEGORYCODE, GRADECODE,TOKENNO,COUNT(TOKENNO) CNT, MAX(LASTMODIFIED) LASTMODIFIED, MAX(SYSROWID) SYSROWID11 FROM PISLEAVEENTITLEMENT
WHERE TOKENNO='00794'
GROUP BY YEARCODE, UNITCODE, CATEGORYCODE, GRADECODE,TOKENNO

HAVING COUNT(TOKENNO) > 1