DROP TABLE GLOSTER_WEB.NOMINEMAST CASCADE CONSTRAINTS;

CREATE TABLE NOMINEMAST
(
  COMPANYCODE     VARCHAR2(10 BYTE),
  DIVISIONCODE    VARCHAR2(10 BYTE),
  WORKERSERIAL    VARCHAR2(20 BYTE),
  NOMINENAME      VARCHAR2(100 BYTE),
  NOMINEDOB       DATE,
  NOMINESEX       VARCHAR2(10 BYTE),
  NOMINERELATION  VARCHAR2(10 BYTE),
  NOMINESHARE     NUMBER(10,2),
  NOMINEFLAG      VARCHAR2(10 BYTE),
  LASTMODIFIED    DATE                          DEFAULT SYSDATE,
  SYSROWID        VARCHAR2(50 BYTE),
  USERNAME        VARCHAR2(50 BYTE)
) 

