SELECT * FROM PISEMPLOYEEMASTER
WHERE TOKENNO=01069


SELECT  * FROM MENUMASTER_RND
WHERE MENUCODE = ''

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%%')

SELECT  * FROM ROLEDETAILS
WHERE MENUCODE = ''

SELECT  * FROM REPORTPARAMETERMASTER
WHERE REPORTAG = ''


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER=''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL='PISEMPLOYEEMASTER'
AND SYS_MAPFIELD LIKE 'msk%'

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP=''

 

INSERT INTO GBL_PISEMPLOYEEMASTER
select AADHARNO, ACADEMICQUALIFICATION, ADDRESS_PERMANENT, ADDRESS_PRESENT, ATTNIDENTIFICATION, 
BANKACCHOLDINGNAME, BANKACCNUMBER, BANKCODE, BONUSAPPLICABLE, BOSSCODE, CATEGORYCODE, CITY_PERMANENT, 
CITY_PRESENT, COMPANYCODE, COSTCENTRECODE, DATEOFBIRTH, DATEOFCONFIRMATION, DATEOFJOIN, DATEOFRETIRE, 
NULL DATEOFTERMINATIONADVICE, DEPARTMENTCODE, DESIGNATIONCODE, DIVISIONCODE, EMAILID, EMPLOYEENAME, 
EMPLOYEESTATUS, EPFAPPLICABLE, ESINO,NULL EXTENDEDRETIREDATE, FATHERNAME, GRADECODE, GRATUITYAPPLICABLE, 
GRATUITYOPENINGYEARS, GRATUITYSETTELMENTDATE, GUARDIANNAME, IFSCCODE, LEAVINGSERVICE, MARITIALSTATUS, 
MOBILENO, MODULE,'M' OPERATIONMODE, PANCARDNO, PAYMENTSTATUS, PAYMODE, PENSIONNO, PFACCODE, 
PFAPPLICABLE, PFCODE, PFENTITLEDATE, PFNO,NULL PFSETTELMENTDATE, PHONE, PIN_PERMANENT, 
PIN_PRESENT, PROFESSIONQUALIFICATION, PTAXAPPLICABLE, QUARTERALLOTED, QUARTERNO, REMARKS, 
SEX, SNFACCODE, SPOUSENAME, STATE_PERMANENT, STATE_PRESENT,NULL STATUSDATE, SYSROWID, TOKENNO, 
UANNO, UNITCODE, VOTERID, WORKERSERIAL, USERNAME, PTAXSTATE, GRATUITYNUMBER, PRANNUMBER, 
RELIGION,NULL SUPERANUATIONDATE, SUPERANUATIONNUMBER from PISEMPLOYEEMASTER
WHERE TOKENNO=01069

SELECT STATUSDATE,SUPERANUATIONDATE,PFSETTELMENTDATE,EXTENDEDRETIREDATE,DATEOFTERMINATIONADVICE FROM PISEMPLOYEEMASTER
WHERE TOKENNO=01069

DELETE FROM GBL_PISEMPLOYEEMASTER 

SELECT * FROM GBL_PISEMPLOYEEMASTER 

SELECT STATUSDATE,SUPERANUATIONDATE,PFSETTELMENTDATE,EXTENDEDRETIREDATE,DATEOFTERMINATIONADVICE FROM GBL_PISEMPLOYEEMASTER 

WHERE TOKENNO=01069

EXEC proc_sd_GTTVSACTUAL_sync('GBL_PISEMPLOYEEMASTER', 'M')