COMP VAL 3 A
COMP VAL 3 610
COMP VAL 3 A1
COMP VAL 3
COMP VAL 3
COMP VAL 3 13698
COMP VAL 3 8290
COMP VAL 3 M
COMP VAL 3 M
COMP VAL 3 ACTIVE
COMP VAL 3 16-OCT-67
COMP VAL 3 04-APR-05
COMP VAL 3 04-APR-05
COMP VAL 3 04-APR-05
COMP VAL 3
COMP VAL 3 16-OCT-25
COMP VAL 3
COMP VAL 3
COMP VAL 3 16-SEP-20
COMP VAL 3
COMP VAL 3 BANK
COMP VAL 3
COMP VAL 3 UCBA0000306
COMP VAL 3 03060110167946
COMP VAL 3 GHISA RAM VERMA
COMP VAL 3 AAPPV8374F
COMP VAL 3 100153157591
COMP VAL 3
COMP VAL 3
COMP VAL 3 9339734696
COMP VAL 3 JAGDISH PRASAD VERMA
COMP VAL 3 JAGDISH PRASAD VERMA
COMP VAL 3 GRVERMA@BIRLACORP.COM
COMP VAL 3
COMP VAL 3 N
COMP VAL 3
COMP VAL 3 B.COM(H)
COMP VAL 3 CA
COMP VAL 3
COMP VAL 3
COMP VAL 3
COMP VAL 3 Y
COMP VAL 3 Y
COMP VAL 3 Y
COMP VAL 3 N
COMP VAL 3 Y
COMP VAL 3 0
COMP VAL 3
COMP VAL 3
COMP VAL 3
COMP VAL 3 PIS
COMP VAL 3 SWT
COMP VAL 3
COMP VAL 3
COMP VAL 3
COMP VAL 3
COMP VAL 3
COMP VAL 3 404, SURYA APARTMENTS,14/1/7 MACKENZIE LANE
COMP VAL 3 HOWRAH
COMP VAL 3 711101
COMP VAL 3 WEST BENGAL
COMP VAL 3
COMP VAL 3 WEST BENGAL
COMP VAL 3
COMP VAL 3
COMP VAL 3 HINDUISM
COMP VAL 3
COMP VAL 3 112698
COMP VAL 3  000221
COMP VAL 3 GHISA RAM VERMA
COMP VAL 3
COMP VAL 3
COMP VAL 3 02
COMP VAL 3 10
UPDATE STATEMENT  UPDATE PISEMPLOYEEMASTER
 SET 
   GRADECODE = 'A',
   DEPARTMENTCODE = '610',
   DESIGNATIONCODE = 'A1',
   ESINO = '',
   PFCODE = '',
   PFNO = '13698',
   PENSIONNO = '8290',
   SEX = 'M',
   MARITIALSTATUS = 'M',
   EMPLOYEESTATUS = 'ACTIVE',
   DATEOFBIRTH = '16-OCT-67',
   DATEOFJOIN = '04-APR-05',
   DATEOFCONFIRMATION = '04-APR-05',
   PFENTITLEDATE = '04-APR-05',
   STATUSDATE = NULL ,
   DATEOFRETIRE = '16-OCT-25',
   EXTENDEDRETIREDATE = NULL ,
   PFSETTELMENTDATE = NULL ,
   GRATUITYSETTELMENTDATE = '16-SEP-20',
   DATEOFTERMINATIONADVICE = NULL ,
   PAYMODE = 'BANK',
   BANKCODE = '',
   IFSCCODE = 'UCBA0000306',
   BANKACCNUMBER = '03060110167946',
   BANKACCHOLDINGNAME = 'GHISA RAM VERMA',
   PANCARDNO = 'AAPPV8374F',
   UANNO = '100153157591',
   AADHARNO = '',
   PHONE = '',
   MOBILENO = '9339734696',
   FATHERNAME = 'JAGDISH PRASAD VERMA',
   GUARDIANNAME = 'JAGDISH PRASAD VERMA',
   EMAILID = 'GRVERMA@BIRLACORP.COM',
   SPOUSENAME = '',
   QUARTERALLOTED = 'N',
   QUARTERNO = '',
   ACADEMICQUALIFICATION = 'B.COM(H)',
   PROFESSIONQUALIFICATION = 'CA',
   PAYMENTSTATUS = '',
   PFACCODE = '',
   SNFACCODE = '',
   PFAPPLICABLE = 'Y',
   EPFAPPLICABLE = 'Y',
   PTAXAPPLICABLE = 'Y',
   BONUSAPPLICABLE = 'N',
   GRATUITYAPPLICABLE = 'Y',
   GRATUITYOPENINGYEARS = '0',
   LEAVINGSERVICE = '',
   REMARKS = '',
   COSTCENTRECODE = '',
   MODULE = 'PIS',
   USERNAME = 'SWT',
   SYSROWID = '',
   ADDRESS_PRESENT = '',
   CITY_PRESENT = '',
   PIN_PRESENT = '',
   STATE_PRESENT = '',
   ADDRESS_PERMANENT = '404, SURYA APARTMENTS,14/1/7 MACKENZIE LANE',
   CITY_PERMANENT = 'HOWRAH',
   PIN_PERMANENT = '711101',
   STATE_PERMANENT = 'WEST BENGAL',
   VOTERID = '',
   PTAXSTATE = 'WEST BENGAL',
   SUPERANUATIONNUMBER = '',
   SUPERANUATIONDATE = NULL ,
   RELIGION = 'HINDUISM',
   PRANNUMBER = '',
   GRATUITYNUMBER = '112698',
   WORKERSERIAL = ' 000221',
   EMPLOYEENAME = 'GHISA RAM VERMA',
   ATTNIDENTIFICATION = '',
   BOSSCODE = '',
   UNITCODE = '02',
   CATEGORYCODE = '10'
   where (COMPANYCODE,DIVISIONCODE,TOKENNO,SYSROWID) 
 = ( select COMPANYCODE,DIVISIONCODE,TOKENNO,SYSROWID from GBL_PISEMPLOYEEMASTER where rowid = 'AADVesAAXAAAAPhAAA')
select FN_GET_COLUMN_NAMES_FORNULL('GBL_PISEMPLOYEEMASTER'),fn_get_mapped_column_names('GBL_PISEMPLOYEEMASTER') from dual
DELETE CHK :  


select COUNT(*) from ( 
 select nvl(AADHARNO,'~QQ~'),nvl(ACADEMICQUALIFICATION,'~QQ~'),nvl(ADDRESS_PERMANENT,'~QQ~'),nvl(ADDRESS_PRESENT,'~QQ~'),nvl(ATTNIDENTIFICATION,'~QQ~'),nvl(BANKACCHOLDINGNAME,'~QQ~'),nvl(BANKACCNUMBER,'~QQ~'),nvl(BANKCODE,'~QQ~'),nvl(BONUSAPPLICABLE,'~QQ~'),nvl(BOSSCODE,'~QQ~'),nvl(CATEGORYCODE,'~QQ~'),nvl(CITY_PERMANENT,'~QQ~'),nvl(CITY_PRESENT,'~QQ~'),nvl(COMPANYCODE,'~QQ~'),nvl(COSTCENTRECODE,'~QQ~'),nvl(DATEOFBIRTH,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFCONFIRMATION,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFJOIN,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFRETIRE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFTERMINATIONADVICE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DEPARTMENTCODE,'~QQ~'),nvl(DESIGNATIONCODE,'~QQ~'),nvl(DIVISIONCODE,'~QQ~'),nvl(EMAILID,'~QQ~'),nvl(EMPLOYEENAME,'~QQ~'),nvl(EMPLOYEESTATUS,'~QQ~'),nvl(EPFAPPLICABLE,'~QQ~'),nvl(ESINO,'~QQ~'),nvl(EXTENDEDRETIREDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(FATHERNAME,'~QQ~'),nvl(GRADECODE,'~QQ~'),nvl(GRATUITYAPPLICABLE,'~QQ~'),nvl(GRATUITYOPENINGYEARS,0),nvl(GRATUITYSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(GUARDIANNAME,'~QQ~'),nvl(IFSCCODE,'~QQ~'),nvl(LEAVINGSERVICE,'~QQ~'),nvl(MARITIALSTATUS,'~QQ~'),nvl(MOBILENO,'~QQ~'),nvl(MODULE,'~QQ~'),nvl(PANCARDNO,'~QQ~'),nvl(PAYMENTSTATUS,'~QQ~'),nvl(PAYMODE,'~QQ~'),nvl(PENSIONNO,'~QQ~'),nvl(PFACCODE,'~QQ~'),nvl(PFAPPLICABLE,'~QQ~'),nvl(PFCODE,'~QQ~'),nvl(PFENTITLEDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PFNO,'~QQ~'),nvl(PFSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PHONE,'~QQ~'),nvl(PIN_PERMANENT,'~QQ~'),nvl(PIN_PRESENT,'~QQ~'),nvl(PROFESSIONQUALIFICATION,'~QQ~'),nvl(PTAXAPPLICABLE,'~QQ~'),nvl(QUARTERALLOTED,'~QQ~'),nvl(QUARTERNO,'~QQ~'),nvl(REMARKS,'~QQ~'),nvl(SEX,'~QQ~'),nvl(SNFACCODE,'~QQ~'),nvl(SPOUSENAME,'~QQ~'),nvl(STATE_PERMANENT,'~QQ~'),nvl(STATE_PRESENT,'~QQ~'),nvl(STATUSDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SYSROWID,'~QQ~'),nvl(TOKENNO,'~QQ~'),nvl(UANNO,'~QQ~'),nvl(UNITCODE,'~QQ~'),nvl(VOTERID,'~QQ~'),nvl(WORKERSERIAL,'~QQ~'),nvl(USERNAME,'~QQ~'),nvl(PTAXSTATE,'~QQ~'),nvl(GRATUITYNUMBER,'~QQ~'),nvl(PRANNUMBER,'~QQ~'),nvl(RELIGION,'~QQ~'),nvl(SUPERANUATIONDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SUPERANUATIONNUMBER,'~QQ~'),SYSROWID from PISEMPLOYEEMASTER 
 where (COMPANYCODE,DIVISIONCODE,TOKENNO) in 
 ( select COMPANYCODE,DIVISIONCODE,TOKENNO from GBL_PISEMPLOYEEMASTER ) 
 minus 
 select nvl(AADHARNO,'~QQ~'),nvl(ACADEMICQUALIFICATION,'~QQ~'),nvl(ADDRESS_PERMANENT,'~QQ~'),nvl(ADDRESS_PRESENT,'~QQ~'),nvl(ATTNIDENTIFICATION,'~QQ~'),nvl(BANKACCHOLDINGNAME,'~QQ~'),nvl(BANKACCNUMBER,'~QQ~'),nvl(BANKCODE,'~QQ~'),nvl(BONUSAPPLICABLE,'~QQ~'),nvl(BOSSCODE,'~QQ~'),nvl(CATEGORYCODE,'~QQ~'),nvl(CITY_PERMANENT,'~QQ~'),nvl(CITY_PRESENT,'~QQ~'),nvl(COMPANYCODE,'~QQ~'),nvl(COSTCENTRECODE,'~QQ~'),nvl(DATEOFBIRTH,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFCONFIRMATION,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFJOIN,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFRETIRE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFTERMINATIONADVICE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DEPARTMENTCODE,'~QQ~'),nvl(DESIGNATIONCODE,'~QQ~'),nvl(DIVISIONCODE,'~QQ~'),nvl(EMAILID,'~QQ~'),nvl(EMPLOYEENAME,'~QQ~'),nvl(EMPLOYEESTATUS,'~QQ~'),nvl(EPFAPPLICABLE,'~QQ~'),nvl(ESINO,'~QQ~'),nvl(EXTENDEDRETIREDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(FATHERNAME,'~QQ~'),nvl(GRADECODE,'~QQ~'),nvl(GRATUITYAPPLICABLE,'~QQ~'),nvl(GRATUITYOPENINGYEARS,0),nvl(GRATUITYSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(GUARDIANNAME,'~QQ~'),nvl(IFSCCODE,'~QQ~'),nvl(LEAVINGSERVICE,'~QQ~'),nvl(MARITIALSTATUS,'~QQ~'),nvl(MOBILENO,'~QQ~'),nvl(MODULE,'~QQ~'),nvl(PANCARDNO,'~QQ~'),nvl(PAYMENTSTATUS,'~QQ~'),nvl(PAYMODE,'~QQ~'),nvl(PENSIONNO,'~QQ~'),nvl(PFACCODE,'~QQ~'),nvl(PFAPPLICABLE,'~QQ~'),nvl(PFCODE,'~QQ~'),nvl(PFENTITLEDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PFNO,'~QQ~'),nvl(PFSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PHONE,'~QQ~'),nvl(PIN_PERMANENT,'~QQ~'),nvl(PIN_PRESENT,'~QQ~'),nvl(PROFESSIONQUALIFICATION,'~QQ~'),nvl(PTAXAPPLICABLE,'~QQ~'),nvl(QUARTERALLOTED,'~QQ~'),nvl(QUARTERNO,'~QQ~'),nvl(REMARKS,'~QQ~'),nvl(SEX,'~QQ~'),nvl(SNFACCODE,'~QQ~'),nvl(SPOUSENAME,'~QQ~'),nvl(STATE_PERMANENT,'~QQ~'),nvl(STATE_PRESENT,'~QQ~'),nvl(STATUSDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SYSROWID,'~QQ~'),nvl(TOKENNO,'~QQ~'),nvl(UANNO,'~QQ~'),nvl(UNITCODE,'~QQ~'),nvl(VOTERID,'~QQ~'),nvl(WORKERSERIAL,'~QQ~'),nvl(USERNAME,'~QQ~'),nvl(PTAXSTATE,'~QQ~'),nvl(GRATUITYNUMBER,'~QQ~'),nvl(PRANNUMBER,'~QQ~'),nvl(RELIGION,'~QQ~'),nvl(SUPERANUATIONDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SUPERANUATIONNUMBER,'~QQ~'),SYSROWID from GBL_PISEMPLOYEEMASTER 
 )
 
 
INSERT CHK :  

select COUNT(*) from ( 
 select nvl(AADHARNO,'~QQ~'),nvl(ACADEMICQUALIFICATION,'~QQ~'),nvl(ADDRESS_PERMANENT,'~QQ~'),nvl(ADDRESS_PRESENT,'~QQ~'),nvl(ATTNIDENTIFICATION,'~QQ~'),nvl(BANKACCHOLDINGNAME,'~QQ~'),nvl(BANKACCNUMBER,'~QQ~'),nvl(BANKCODE,'~QQ~'),nvl(BONUSAPPLICABLE,'~QQ~'),nvl(BOSSCODE,'~QQ~'),nvl(CATEGORYCODE,'~QQ~'),nvl(CITY_PERMANENT,'~QQ~'),nvl(CITY_PRESENT,'~QQ~'),nvl(COMPANYCODE,'~QQ~'),nvl(COSTCENTRECODE,'~QQ~'),nvl(DATEOFBIRTH,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFCONFIRMATION,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFJOIN,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFRETIRE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFTERMINATIONADVICE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DEPARTMENTCODE,'~QQ~'),nvl(DESIGNATIONCODE,'~QQ~'),nvl(DIVISIONCODE,'~QQ~'),nvl(EMAILID,'~QQ~'),nvl(EMPLOYEENAME,'~QQ~'),nvl(EMPLOYEESTATUS,'~QQ~'),nvl(EPFAPPLICABLE,'~QQ~'),nvl(ESINO,'~QQ~'),nvl(EXTENDEDRETIREDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(FATHERNAME,'~QQ~'),nvl(GRADECODE,'~QQ~'),nvl(GRATUITYAPPLICABLE,'~QQ~'),nvl(GRATUITYOPENINGYEARS,0),nvl(GRATUITYSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(GUARDIANNAME,'~QQ~'),nvl(IFSCCODE,'~QQ~'),nvl(LEAVINGSERVICE,'~QQ~'),nvl(MARITIALSTATUS,'~QQ~'),nvl(MOBILENO,'~QQ~'),nvl(MODULE,'~QQ~'),nvl(PANCARDNO,'~QQ~'),nvl(PAYMENTSTATUS,'~QQ~'),nvl(PAYMODE,'~QQ~'),nvl(PENSIONNO,'~QQ~'),nvl(PFACCODE,'~QQ~'),nvl(PFAPPLICABLE,'~QQ~'),nvl(PFCODE,'~QQ~'),nvl(PFENTITLEDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PFNO,'~QQ~'),nvl(PFSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PHONE,'~QQ~'),nvl(PIN_PERMANENT,'~QQ~'),nvl(PIN_PRESENT,'~QQ~'),nvl(PROFESSIONQUALIFICATION,'~QQ~'),nvl(PTAXAPPLICABLE,'~QQ~'),nvl(QUARTERALLOTED,'~QQ~'),nvl(QUARTERNO,'~QQ~'),nvl(REMARKS,'~QQ~'),nvl(SEX,'~QQ~'),nvl(SNFACCODE,'~QQ~'),nvl(SPOUSENAME,'~QQ~'),nvl(STATE_PERMANENT,'~QQ~'),nvl(STATE_PRESENT,'~QQ~'),nvl(STATUSDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SYSROWID,'~QQ~'),nvl(TOKENNO,'~QQ~'),nvl(UANNO,'~QQ~'),nvl(UNITCODE,'~QQ~'),nvl(VOTERID,'~QQ~'),nvl(WORKERSERIAL,'~QQ~'),nvl(USERNAME,'~QQ~'),nvl(PTAXSTATE,'~QQ~'),nvl(GRATUITYNUMBER,'~QQ~'),nvl(PRANNUMBER,'~QQ~'),nvl(RELIGION,'~QQ~'),nvl(SUPERANUATIONDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SUPERANUATIONNUMBER,'~QQ~'),SYSROWID from GBL_PISEMPLOYEEMASTER 
 minus 
 select nvl(AADHARNO,'~QQ~'),nvl(ACADEMICQUALIFICATION,'~QQ~'),nvl(ADDRESS_PERMANENT,'~QQ~'),nvl(ADDRESS_PRESENT,'~QQ~'),nvl(ATTNIDENTIFICATION,'~QQ~'),nvl(BANKACCHOLDINGNAME,'~QQ~'),nvl(BANKACCNUMBER,'~QQ~'),nvl(BANKCODE,'~QQ~'),nvl(BONUSAPPLICABLE,'~QQ~'),nvl(BOSSCODE,'~QQ~'),nvl(CATEGORYCODE,'~QQ~'),nvl(CITY_PERMANENT,'~QQ~'),nvl(CITY_PRESENT,'~QQ~'),nvl(COMPANYCODE,'~QQ~'),nvl(COSTCENTRECODE,'~QQ~'),nvl(DATEOFBIRTH,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFCONFIRMATION,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFJOIN,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFRETIRE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DATEOFTERMINATIONADVICE,to_date('31/01/1000','dd/mm/yyyy')),nvl(DEPARTMENTCODE,'~QQ~'),nvl(DESIGNATIONCODE,'~QQ~'),nvl(DIVISIONCODE,'~QQ~'),nvl(EMAILID,'~QQ~'),nvl(EMPLOYEENAME,'~QQ~'),nvl(EMPLOYEESTATUS,'~QQ~'),nvl(EPFAPPLICABLE,'~QQ~'),nvl(ESINO,'~QQ~'),nvl(EXTENDEDRETIREDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(FATHERNAME,'~QQ~'),nvl(GRADECODE,'~QQ~'),nvl(GRATUITYAPPLICABLE,'~QQ~'),nvl(GRATUITYOPENINGYEARS,0),nvl(GRATUITYSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(GUARDIANNAME,'~QQ~'),nvl(IFSCCODE,'~QQ~'),nvl(LEAVINGSERVICE,'~QQ~'),nvl(MARITIALSTATUS,'~QQ~'),nvl(MOBILENO,'~QQ~'),nvl(MODULE,'~QQ~'),nvl(PANCARDNO,'~QQ~'),nvl(PAYMENTSTATUS,'~QQ~'),nvl(PAYMODE,'~QQ~'),nvl(PENSIONNO,'~QQ~'),nvl(PFACCODE,'~QQ~'),nvl(PFAPPLICABLE,'~QQ~'),nvl(PFCODE,'~QQ~'),nvl(PFENTITLEDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PFNO,'~QQ~'),nvl(PFSETTELMENTDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(PHONE,'~QQ~'),nvl(PIN_PERMANENT,'~QQ~'),nvl(PIN_PRESENT,'~QQ~'),nvl(PROFESSIONQUALIFICATION,'~QQ~'),nvl(PTAXAPPLICABLE,'~QQ~'),nvl(QUARTERALLOTED,'~QQ~'),nvl(QUARTERNO,'~QQ~'),nvl(REMARKS,'~QQ~'),nvl(SEX,'~QQ~'),nvl(SNFACCODE,'~QQ~'),nvl(SPOUSENAME,'~QQ~'),nvl(STATE_PERMANENT,'~QQ~'),nvl(STATE_PRESENT,'~QQ~'),nvl(STATUSDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SYSROWID,'~QQ~'),nvl(TOKENNO,'~QQ~'),nvl(UANNO,'~QQ~'),nvl(UNITCODE,'~QQ~'),nvl(VOTERID,'~QQ~'),nvl(WORKERSERIAL,'~QQ~'),nvl(USERNAME,'~QQ~'),nvl(PTAXSTATE,'~QQ~'),nvl(GRATUITYNUMBER,'~QQ~'),nvl(PRANNUMBER,'~QQ~'),nvl(RELIGION,'~QQ~'),nvl(SUPERANUATIONDATE,to_date('31/01/1000','dd/mm/yyyy')),nvl(SUPERANUATIONNUMBER,'~QQ~'),SYSROWID from PISEMPLOYEEMASTER 
 where (COMPANYCODE,DIVISIONCODE,TOKENNO) in 
 ( select COMPANYCODE,DIVISIONCODE,TOKENNO from GBL_PISEMPLOYEEMASTER ) 
 )
 
 
INSERT :  

insert into PISEMPLOYEEMASTER (AADHARNO,ACADEMICQUALIFICATION,ADDRESS_PERMANENT,ADDRESS_PRESENT,ATTNIDENTIFICATION,BANKACCHOLDINGNAME,BANKACCNUMBER,BANKCODE,BONUSAPPLICABLE,BOSSCODE,CATEGORYCODE,CITY_PERMANENT,CITY_PRESENT,COMPANYCODE,COSTCENTRECODE,DATEOFBIRTH,DATEOFCONFIRMATION,DATEOFJOIN,DATEOFRETIRE,DATEOFTERMINATIONADVICE,DEPARTMENTCODE,DESIGNATIONCODE,DIVISIONCODE,EMAILID,EMPLOYEENAME,EMPLOYEESTATUS,EPFAPPLICABLE,ESINO,EXTENDEDRETIREDATE,FATHERNAME,GRADECODE,GRATUITYAPPLICABLE,GRATUITYOPENINGYEARS,GRATUITYSETTELMENTDATE,GUARDIANNAME,IFSCCODE,LEAVINGSERVICE,MARITIALSTATUS,MOBILENO,MODULE,PANCARDNO,PAYMENTSTATUS,PAYMODE,PENSIONNO,PFACCODE,PFAPPLICABLE,PFCODE,PFENTITLEDATE,PFNO,PFSETTELMENTDATE,PHONE,PIN_PERMANENT,PIN_PRESENT,PROFESSIONQUALIFICATION,PTAXAPPLICABLE,QUARTERALLOTED,QUARTERNO,REMARKS,SEX,SNFACCODE,SPOUSENAME,STATE_PERMANENT,STATE_PRESENT,STATUSDATE,SYSROWID,TOKENNO,UANNO,UNITCODE,VOTERID,WORKERSERIAL,USERNAME,PTAXSTATE,GRATUITYNUMBER,PRANNUMBER,RELIGION,SUPERANUATIONDATE,SUPERANUATIONNUMBER)
 
 
 
 select replace(AADHARNO,'~QQ~','')  ,replace(ACADEMICQUALIFICATION,'~QQ~','')  ,replace(ADDRESS_PERMANENT,'~QQ~','')  ,
 replace(ADDRESS_PRESENT,'~QQ~','')  ,replace(ATTNIDENTIFICATION,'~QQ~','')  ,replace(BANKACCHOLDINGNAME,'~QQ~','')  ,
 replace(BANKACCNUMBER,'~QQ~','')  ,replace(BANKCODE,'~QQ~','')  ,replace(BONUSAPPLICABLE,'~QQ~','')  ,
 replace(BOSSCODE,'~QQ~','')  ,replace(CATEGORYCODE,'~QQ~','')  ,replace(CITY_PERMANENT,'~QQ~','')  ,
 replace(CITY_PRESENT,'~QQ~','')  ,replace(COMPANYCODE,'~QQ~','')  ,replace(COSTCENTRECODE,'~QQ~','')  ,
 DATEOFBIRTH,DATEOFCONFIRMATION,DATEOFJOIN,DATEOFRETIRE,DATEOFTERMINATIONADVICE,replace(DEPARTMENTCODE,'~QQ~','')  ,
 replace(DESIGNATIONCODE,'~QQ~','')  ,replace(DIVISIONCODE,'~QQ~','')  ,replace(EMAILID,'~QQ~','')  ,
 replace(EMPLOYEENAME,'~QQ~','')  ,replace(EMPLOYEESTATUS,'~QQ~','')  ,replace(EPFAPPLICABLE,'~QQ~','')  ,
 replace(ESINO,'~QQ~','')  ,EXTENDEDRETIREDATE,replace(FATHERNAME,'~QQ~','')  ,replace(GRADECODE,'~QQ~','')  ,
 replace(GRATUITYAPPLICABLE,'~QQ~','')  ,GRATUITYOPENINGYEARS,GRATUITYSETTELMENTDATE,replace(GUARDIANNAME,'~QQ~','')  ,
 replace(IFSCCODE,'~QQ~','')  ,replace(LEAVINGSERVICE,'~QQ~','')  ,replace(MARITIALSTATUS,'~QQ~','')  ,
 replace(MOBILENO,'~QQ~','')  ,replace(MODULE,'~QQ~','')  ,replace(PANCARDNO,'~QQ~','')  ,replace(PAYMENTSTATUS,'~QQ~','')  ,
 replace(PAYMODE,'~QQ~','')  ,replace(PENSIONNO,'~QQ~','')  ,replace(PFACCODE,'~QQ~','')  ,replace(PFAPPLICABLE,'~QQ~','')  ,
 replace(PFCODE,'~QQ~','')  ,PFENTITLEDATE,replace(PFNO,'~QQ~','')  ,PFSETTELMENTDATE,replace(PHONE,'~QQ~','')  ,
 replace(PIN_PERMANENT,'~QQ~','')  ,replace(PIN_PRESENT,'~QQ~','')  ,replace(PROFESSIONQUALIFICATION,'~QQ~','')  ,
 replace(PTAXAPPLICABLE,'~QQ~','')  ,replace(QUARTERALLOTED,'~QQ~','')  ,replace(QUARTERNO,'~QQ~','')  ,
 replace(REMARKS,'~QQ~','')  ,replace(SEX,'~QQ~','')  ,replace(SNFACCODE,'~QQ~','')  ,replace(SPOUSENAME,'~QQ~','')  ,
 replace(STATE_PERMANENT,'~QQ~','')  ,replace(STATE_PRESENT,'~QQ~','')  ,STATUSDATE,replace(SYSROWID,'~QQ~','')  ,
 replace(TOKENNO,'~QQ~','')  ,replace(UANNO,'~QQ~','')  ,replace(UNITCODE,'~QQ~','')  ,replace(VOTERID,'~QQ~','')  ,
 replace(WORKERSERIAL,'~QQ~','')  ,replace(USERNAME,'~QQ~','')  ,replace(PTAXSTATE,'~QQ~','')  ,
 replace(GRATUITYNUMBER,'~QQ~','')  ,replace(PRANNUMBER,'~QQ~','')  ,replace(RELIGION,'~QQ~','')  ,SUPERANUATIONDATE,
 replace(SUPERANUATIONNUMBER,'~QQ~','')   
 from ( 
 select nvl(AADHARNO,'~QQ~') AADHARNO  ,nvl(ACADEMICQUALIFICATION,'~QQ~') ACADEMICQUALIFICATION ,
 nvl(ADDRESS_PERMANENT,'~QQ~') ADDRESS_PERMANENT ,nvl(ADDRESS_PRESENT,'~QQ~') ADDRESS_PRESENT ,
 nvl(ATTNIDENTIFICATION,'~QQ~') ATTNIDENTIFICATION ,nvl(BANKACCHOLDINGNAME,'~QQ~') BANKACCHOLDINGNAME ,
 nvl(BANKACCNUMBER,'~QQ~') BANKACCNUMBER ,nvl(BANKCODE,'~QQ~') BANKCODE ,nvl(BONUSAPPLICABLE,'~QQ~') BONUSAPPLICABLE ,
 nvl(BOSSCODE,'~QQ~') BOSSCODE ,nvl(CATEGORYCODE,'~QQ~') CATEGORYCODE ,nvl(CITY_PERMANENT,'~QQ~') CITY_PERMANENT ,
 nvl(CITY_PRESENT,'~QQ~') CITY_PRESENT ,nvl(COMPANYCODE,'~QQ~') COMPANYCODE ,nvl(COSTCENTRECODE,'~QQ~') COSTCENTRECODE ,
 nvl(DATEOFBIRTH,sysdate) DATEOFBIRTH ,nvl(DATEOFCONFIRMATION,sysdate) DATEOFCONFIRMATION ,nvl(DATEOFJOIN,sysdate) DATEOFJOIN ,
 nvl(DATEOFRETIRE,sysdate) DATEOFRETIRE ,nvl(DATEOFTERMINATIONADVICE,sysdate) DATEOFTERMINATIONADVICE ,nvl(DEPARTMENTCODE,'~QQ~') DEPARTMENTCODE ,nvl(DESIGNATIONCODE,'~QQ~') DESIGNATIONCODE ,nvl(DIVISIONCODE,'~QQ~') DIVISIONCODE ,nvl(EMAILID,'~QQ~') EMAILID ,nvl(EMPLOYEENAME,'~QQ~') EMPLOYEENAME ,nvl(EMPLOYEESTATUS,'~QQ~') EMPLOYEESTATUS ,nvl(EPFAPPLICABLE,'~QQ~') EPFAPPLICABLE ,nvl(ESINO,'~QQ~') ESINO ,nvl(EXTENDEDRETIREDATE,sysdate) EXTENDEDRETIREDATE ,nvl(FATHERNAME,'~QQ~') FATHERNAME ,nvl(GRADECODE,'~QQ~') GRADECODE ,nvl(GRATUITYAPPLICABLE,'~QQ~') GRATUITYAPPLICABLE ,nvl(GRATUITYOPENINGYEARS,0) GRATUITYOPENINGYEARS ,nvl(GRATUITYSETTELMENTDATE,sysdate) GRATUITYSETTELMENTDATE ,nvl(GUARDIANNAME,'~QQ~') GUARDIANNAME ,nvl(IFSCCODE,'~QQ~') IFSCCODE ,nvl(LEAVINGSERVICE,'~QQ~') LEAVINGSERVICE ,nvl(MARITIALSTATUS,'~QQ~') MARITIALSTATUS ,nvl(MOBILENO,'~QQ~') MOBILENO ,nvl(MODULE,'~QQ~') MODULE ,nvl(PANCARDNO,'~QQ~') PANCARDNO ,nvl(PAYMENTSTATUS,'~QQ~') PAYMENTSTATUS ,nvl(PAYMODE,'~QQ~') PAYMODE ,nvl(PENSIONNO,'~QQ~') PENSIONNO ,nvl(PFACCODE,'~QQ~') PFACCODE ,nvl(PFAPPLICABLE,'~QQ~') PFAPPLICABLE ,nvl(PFCODE,'~QQ~') PFCODE ,nvl(PFENTITLEDATE,sysdate) PFENTITLEDATE ,nvl(PFNO,'~QQ~') PFNO ,nvl(PFSETTELMENTDATE,sysdate) PFSETTELMENTDATE ,nvl(PHONE,'~QQ~') PHONE ,nvl(PIN_PERMANENT,'~QQ~') PIN_PERMANENT ,nvl(PIN_PRESENT,'~QQ~') PIN_PRESENT ,nvl(PROFESSIONQUALIFICATION,'~QQ~') PROFESSIONQUALIFICATION ,nvl(PTAXAPPLICABLE,'~QQ~') PTAXAPPLICABLE ,nvl(QUARTERALLOTED,'~QQ~') QUARTERALLOTED ,nvl(QUARTERNO,'~QQ~') QUARTERNO ,nvl(REMARKS,'~QQ~') REMARKS ,nvl(SEX,'~QQ~') SEX ,nvl(SNFACCODE,'~QQ~') SNFACCODE ,nvl(SPOUSENAME,'~QQ~') SPOUSENAME ,nvl(STATE_PERMANENT,'~QQ~') STATE_PERMANENT ,nvl(STATE_PRESENT,'~QQ~') STATE_PRESENT ,nvl(STATUSDATE,sysdate) STATUSDATE ,nvl(SYSROWID,'~QQ~') SYSROWID ,nvl(TOKENNO,'~QQ~') TOKENNO ,nvl(UANNO,'~QQ~') UANNO ,nvl(UNITCODE,'~QQ~') UNITCODE ,nvl(VOTERID,'~QQ~') VOTERID ,nvl(WORKERSERIAL,'~QQ~') WORKERSERIAL ,nvl(USERNAME,'~QQ~') USERNAME ,nvl(PTAXSTATE,'~QQ~') PTAXSTATE ,nvl(GRATUITYNUMBER,'~QQ~') GRATUITYNUMBER ,nvl(PRANNUMBER,'~QQ~') PRANNUMBER ,nvl(RELIGION,'~QQ~') RELIGION ,nvl(SUPERANUATIONDATE,sysdate) SUPERANUATIONDATE ,nvl(SUPERANUATIONNUMBER,'~QQ~') SUPERANUATIONNUMBER  from GBL_PISEMPLOYEEMASTER 
 
 minus 
 select nvl(AADHARNO,'~QQ~') AADHARNO  ,nvl(ACADEMICQUALIFICATION,'~QQ~') ACADEMICQUALIFICATION ,nvl(ADDRESS_PERMANENT,'~QQ~') ADDRESS_PERMANENT ,nvl(ADDRESS_PRESENT,'~QQ~') ADDRESS_PRESENT ,nvl(ATTNIDENTIFICATION,'~QQ~') ATTNIDENTIFICATION ,nvl(BANKACCHOLDINGNAME,'~QQ~') BANKACCHOLDINGNAME ,nvl(BANKACCNUMBER,'~QQ~') BANKACCNUMBER ,nvl(BANKCODE,'~QQ~') BANKCODE ,nvl(BONUSAPPLICABLE,'~QQ~') BONUSAPPLICABLE ,nvl(BOSSCODE,'~QQ~') BOSSCODE ,nvl(CATEGORYCODE,'~QQ~') CATEGORYCODE ,nvl(CITY_PERMANENT,'~QQ~') CITY_PERMANENT ,nvl(CITY_PRESENT,'~QQ~') CITY_PRESENT ,nvl(COMPANYCODE,'~QQ~') COMPANYCODE ,nvl(COSTCENTRECODE,'~QQ~') COSTCENTRECODE ,nvl(DATEOFBIRTH,sysdate) DATEOFBIRTH ,nvl(DATEOFCONFIRMATION,sysdate) DATEOFCONFIRMATION ,nvl(DATEOFJOIN,sysdate) DATEOFJOIN ,nvl(DATEOFRETIRE,sysdate) DATEOFRETIRE ,nvl(DATEOFTERMINATIONADVICE,sysdate) DATEOFTERMINATIONADVICE ,nvl(DEPARTMENTCODE,'~QQ~') DEPARTMENTCODE ,nvl(DESIGNATIONCODE,'~QQ~') DESIGNATIONCODE ,nvl(DIVISIONCODE,'~QQ~') DIVISIONCODE ,nvl(EMAILID,'~QQ~') EMAILID ,nvl(EMPLOYEENAME,'~QQ~') EMPLOYEENAME ,nvl(EMPLOYEESTATUS,'~QQ~') EMPLOYEESTATUS ,nvl(EPFAPPLICABLE,'~QQ~') EPFAPPLICABLE ,nvl(ESINO,'~QQ~') ESINO ,nvl(EXTENDEDRETIREDATE,sysdate) EXTENDEDRETIREDATE ,nvl(FATHERNAME,'~QQ~') FATHERNAME ,nvl(GRADECODE,'~QQ~') GRADECODE ,nvl(GRATUITYAPPLICABLE,'~QQ~') GRATUITYAPPLICABLE ,nvl(GRATUITYOPENINGYEARS,0) GRATUITYOPENINGYEARS ,nvl(GRATUITYSETTELMENTDATE,sysdate) GRATUITYSETTELMENTDATE ,nvl(GUARDIANNAME,'~QQ~') GUARDIANNAME ,nvl(IFSCCODE,'~QQ~') IFSCCODE ,nvl(LEAVINGSERVICE,'~QQ~') LEAVINGSERVICE ,nvl(MARITIALSTATUS,'~QQ~') MARITIALSTATUS ,nvl(MOBILENO,'~QQ~') MOBILENO ,nvl(MODULE,'~QQ~') MODULE ,nvl(PANCARDNO,'~QQ~') PANCARDNO ,nvl(PAYMENTSTATUS,'~QQ~') PAYMENTSTATUS ,nvl(PAYMODE,'~QQ~') PAYMODE ,nvl(PENSIONNO,'~QQ~') PENSIONNO ,nvl(PFACCODE,'~QQ~') PFACCODE ,nvl(PFAPPLICABLE,'~QQ~') PFAPPLICABLE ,nvl(PFCODE,'~QQ~') PFCODE ,nvl(PFENTITLEDATE,sysdate) PFENTITLEDATE ,nvl(PFNO,'~QQ~') PFNO ,nvl(PFSETTELMENTDATE,sysdate) PFSETTELMENTDATE ,nvl(PHONE,'~QQ~') PHONE ,nvl(PIN_PERMANENT,'~QQ~') PIN_PERMANENT ,nvl(PIN_PRESENT,'~QQ~') PIN_PRESENT ,nvl(PROFESSIONQUALIFICATION,'~QQ~') PROFESSIONQUALIFICATION ,nvl(PTAXAPPLICABLE,'~QQ~') PTAXAPPLICABLE ,nvl(QUARTERALLOTED,'~QQ~') QUARTERALLOTED ,nvl(QUARTERNO,'~QQ~') QUARTERNO ,nvl(REMARKS,'~QQ~') REMARKS ,nvl(SEX,'~QQ~') SEX ,nvl(SNFACCODE,'~QQ~') SNFACCODE ,nvl(SPOUSENAME,'~QQ~') SPOUSENAME ,nvl(STATE_PERMANENT,'~QQ~') STATE_PERMANENT ,nvl(STATE_PRESENT,'~QQ~') STATE_PRESENT ,nvl(STATUSDATE,sysdate) STATUSDATE ,nvl(SYSROWID,'~QQ~') SYSROWID ,nvl(TOKENNO,'~QQ~') TOKENNO ,nvl(UANNO,'~QQ~') UANNO ,nvl(UNITCODE,'~QQ~') UNITCODE ,nvl(VOTERID,'~QQ~') VOTERID ,nvl(WORKERSERIAL,'~QQ~') WORKERSERIAL ,nvl(USERNAME,'~QQ~') USERNAME ,nvl(PTAXSTATE,'~QQ~') PTAXSTATE ,nvl(GRATUITYNUMBER,'~QQ~') GRATUITYNUMBER ,nvl(PRANNUMBER,'~QQ~') PRANNUMBER ,nvl(RELIGION,'~QQ~') RELIGION ,nvl(SUPERANUATIONDATE,sysdate) SUPERANUATIONDATE ,nvl(SUPERANUATIONNUMBER,'~QQ~') SUPERANUATIONNUMBER  from PISEMPLOYEEMASTER 
 where (COMPANYCODE,DIVISIONCODE,TOKENNO) in 
 ( select COMPANYCODE,DIVISIONCODE,TOKENNO from GBL_PISEMPLOYEEMASTER ) 
 )
