select * from loantransaction where tokenno='04053' 
 
 EXEC PROC_LOANBLNC('NJ0001','0002','18/10/2020','18/10/2020','','001544','WPS','','')
 
 DELETE FROM GBL_LOANBLNC
 
 SELECT SUM(LOAN_BAL) LOAN_BAL, SUM(LOAN_INT_BAL) LOAN_INT_BAL FROM GBL_LOANBLNC
         
 SELECT * FROM GBL_LOANBLNC
 
 SELECT A.WORKERSERIAL, NAME, MODULE, A.LOAN_BAL, A.LOAN_INT_BAL FROM
 (
    SELECT WORKERSERIAL, SUM(LOAN_BAL) LOAN_BAL, SUM(LOAN_INT_BAL) LOAN_INT_BAL 
    FROM GBL_LOANBLNC
    GROUP BY WORKERSERIAL
) A,
(
    SELECT NAME,WORKERSERIAL,MODULE 
    FROM 
    (
        SELECT 'WPS' MODULE, WORKERNAME AS  NAME ,WORKERSERIAL, COMPANYCODE,DIVISIONCODE,TOKENNO 
        FROM WPSWORKERMAST 
        UNION ALL 
        SELECT 'PIS' MODULE, EMPLOYEENAME AS NAME ,WORKERSERIAL,COMPANYCODE,DIVISIONCODE,TOKENNO 
        FROM PISEMPLOYEEMASTER
    ) 
    WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002' AND TOKENNO = '04053'
) B
WHERE A.WORKERSERIAL=B.WORKERSERIAL



SELECT * FROM WPSWORKERMAST
WHERE TOKENNO='04053'

SELECT * FROM QUERYMASTER
WHERE QRY_ID='38'


SELECT COUNT(GRATURITYENTILE) TOTAL_ENTILE_YEARS
FROM GRATUITYENTITLEMENTYEAR
WHERE TOKENNO=<<TOKENNO>>
AND COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY CALENDARYEAR

SELECT WORKERSERIAL,WORKERNAME,WORKERCATEGORYCODE 
CATEGORYCODE,GRADECODE, DATEOFJOINING,DATEOFRETIREMENT 
FROM WPSWORKERMAST 
WHERE COMPANYCODE=''
AND DIVISIONCODE=''
AND TOKENNO=''
UNION


SELECT WORKERSERIAL,CATEGORYCODE, GRADECODE, DATEOFJOINING,GRATUITYENTILEMENTDATE,TOTAL_ENTILE_YEARS
FROM 
( 
    SELECT WORKERSERIAL, WORKERCATEGORYCODE CATEGORYCODE,
    GRADECODE, DATEOFJOINING,DATEOFRETIREMENT  GRATUITYENTILEMENTDATE
    FROM WPSWORKERMAST 
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE='0002'
    AND TOKENNO='04053'
    UNION
    SELECT WORKERSERIAL,CATEGORYCODE,GRADECODE,
    DATEOFJOIN DATEOFJOINING,STATUSDATE GRATUITYENTILEMENTDATE 
    FROM PISEMPLOYEEMASTER 
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE='0002'
    AND TOKENNO='04053'
) A,
(
    SELECT COUNT(GRATURITYENTILE) TOTAL_ENTILE_YEARS
    FROM GRATUITYENTITLEMENTYEAR
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE='0002'
    AND TOKENNO='04053'
    AND GRATURITYENTILE='Y'
)



SELECT * FROM PISEMPLOYEEMASTER


FN_GRATUITY_ENTITLE

FN_GRATUITY_AMOUNT

GBL_GRATUITYSETTLEMENT


SELECT SUM(VBASIC) FROM WPSWAGESDETAILS
WHERE FORTNIGHTENDDATE IN
(
    SELECT FORTNIGHTENDDATE FROM 
    (
        SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO
        FROM WPSWAGESDETAILS 
        WHERE COMPANYCODE='NJ0001'
        AND DIVISIONCODE='0002'
        AND TOKENNO='04053'
        GROUP BY FORTNIGHTENDDATE
    )
    WHERE RNO <= 6
)
AND COMPANYCODE='NJ0001'
AND DIVISIONCODE='0002'
AND TOKENNO='04053'




SELECT * FROM WPSWAGESDETAILS
WHERE FORTNIGHTENDDATE IN
(
    SELECT FORTNIGHTENDDATE FROM 
    (
        SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO, FORTNIGHTENDDATE
        FROM WPSWAGESDETAILS 
        WHERE COMPANYCODE='NJ0001'
        AND DIVISIONCODE='0002'
        AND TOKENNO='04053'
--        GROUP BY FORTNIGHTENDDATE
    )
    WHERE RNO <= 
    (
        SELECT CASE WHEN VBASIC > 0 THEN 3 ELSE 1 END FROM
        (
            SELECT SUM(VBASIC)  VBASIC FROM WPSWAGESDETAILS
            WHERE FORTNIGHTENDDATE IN
            (
                SELECT FORTNIGHTENDDATE FROM 
                (
                    SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO
                    FROM WPSWAGESDETAILS 
                    WHERE COMPANYCODE='NJ0001'
                    AND DIVISIONCODE='0002'
                    AND TOKENNO='04053'
                    GROUP BY FORTNIGHTENDDATE
                )
                WHERE RNO <= 6
            )
            AND COMPANYCODE='NJ0001'
            AND DIVISIONCODE='0002'
            AND TOKENNO='04053'
        )
    )
)
AND COMPANYCODE='NJ0001'
AND DIVISIONCODE='0002'
AND TOKENNO='04053'



SELECT FN_GET_FORM_QRY_WEB (38, 'COMPANYCODE:NJ0001~DIVISIONCODE:0002~TOKENNO:04053' ) FROM DUAL 