PRC_GRATUITY_ENTITLE_YEAR_CALC

SELECT * FROM GRATUITYENTITLEMENTYEAR
where TOKENNO='04053'


SELECT CALENDARYEAR YEAR,TOTAL TOTALDAYS,GRATURITYENTILE 
FROM GRATUITYENTITLEMENTYEAR
WHERE TOKENNO=<<TOKENNO>>
AND COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY CALENDARYEAR



SELECT * FROM GRATUITYENTITLEMENTYEAR
where TOKENNO='04053'
and GRATURITYENTILE='Y'

GRATURITYENTILE

select * from wpscomponentmaster


------------------
SELECT * FROM sale_stats
UNPIVOT(
    quantity  -- unpivot_clause
    FOR product_code --  unpivot_for_clause
    IN ( -- unpivot_in_clause
        product_a AS 'A', 
        product_b AS 'B', 
        product_c AS 'C'
    )
);


SELECT TOKENNO, SUM(FBASIC_PEICERT) FBASIC_PEICERT, SUM(FBASIC) FBASIC
, SUM(VBASIC) VBASIC, SUM(DA) DA, SUM(TSA) TSA, SUM(ADHOC) ADHOC, SUM(ADHOC) NS_ALLOW
FROM 
(
    SELECT COMPONENT.TOKENNO, FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,
    COMPONENT.FBASIC_PEICERT, COMPONENT.FBASIC,COMPONENT.VBASIC ,COMPONENT.DA,
    COMPONENT.TSA,COMPONENT.ADHOC , (CASE WHEN SECMST.PFLINKHOURS >0 THEN COMPONENT.NS_ALLOW ELSE 0 END) NS_ALLOW ,
    --
    COMPONENT.FBASIC_PEICERT+ COMPONENT.FBASIC +COMPONENT.VBASIC +COMPONENT.DA+
    COMPONENT.TSA+COMPONENT.ADHOC + (CASE WHEN SECMST.PFLINKHOURS >0 THEN COMPONENT.NS_ALLOW ELSE 0 END) TOTAL_SUM
    FROM WPSWAGESDETAILS COMPONENT, VW_WPSSECTIONMAST  SECMST,
    (
        SELECT (MAX(FORTNIGHTENDDATE)-33) STARTDATE,MAX(FORTNIGHTENDDATE) ENDDATE  FROM WPSWAGESDETAILS WHERE TOKENNO='00046'
    ) MAXDATE
    WHERE TOKENNO='00046' --'04053'
    AND COMPONENT.SECTIONCODE=SECMST.SECTIONCODE
    AND COMPONENT.COMPANYCODE=SECMST.COMPANYCODE
    AND COMPONENT.DIVISIONCODE=SECMST.DIVISIONCODE
    AND COMPONENT.DEPARTMENTCODE=SECMST.DEPARTMENTCODE
    -- AND FORTNIGHTENDDATE BETWEEN (TO_DATE('31/03/2020','DD/MM/YYYY') - 20) AND TO_DATE('31/03/2020','DD/MM/YYYY')
    -- AND FORTNIGHTENDDATE BETWEEN MAXDATE.STARTDATE AND MAXDATE.ENDDATE
    AND FORTNIGHTENDDATE IN 
    (
        SELECT FORTNIGHTENDDATE FROM 
        (
            SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO, 
            FORTNIGHTENDDATE  FROM WPSWAGESDETAILS WHERE TOKENNO='00046'
            GROUP BY FORTNIGHTENDDATE
        )
        WHERE RNO <= 8
        --     ORDER BY FORTNIGHTENDDATE DESC
    )
)
GROUP BY TOKENNO



 SELECT * FROM VW_WPSSECTIONMAST
 
 SELECT * FROM WPSWAGESDETAILS  WHERE TOKENNO='00046'
 
 SELECT * 
 FROM WPSWAGESDETAILS A, VW_WPSSECTIONMAST B 
 WHERE TOKENNO='00046'
 AND A.SECTIONCODE=B.SECTIONCODE
 AND A.COMPANYCODE=B.COMPANYCODE
 AND A.DIVISIONCODE=B.DIVISIONCODE
 AND A.DEPARTMENTCODE=B.DEPARTMENTCODE
 
 VW_WPSSECTIONMAST
 
 SELECT * FROM USER_SOURCE
 WHERE TEXT LIKE '%SECMST%'
 
 
 SELECT FORTNIGHTENDDATE FROM 
 (
     SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO, 
     FORTNIGHTENDDATE  FROM WPSWAGESDETAILS WHERE TOKENNO='00046'
     GROUP BY FORTNIGHTENDDATE
 )
 WHERE RNO <= 6
 ORDER BY FORTNIGHTENDDATE DESC
 
 
     SELECT TOKENNO, ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE) RNO, 
     FORTNIGHTENDDATE  FROM WPSWAGESDETAILS --WHERE TOKENNO='04053'
     ORDER BY TOKENNO
     
     
     GROUP BY FORTNIGHTENDDATE