SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%PIS%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''




SELECT LISTAGG(COLUMNNAME,'~') WITHIN GROUP (ORDER BY COLUMNNAME) AS XX FROM (
SELECT C.COLUMNNAME FROM
(
    SELECT A.SYS_TABLENAME_ACTUAL TABLENAME,A.SYS_COLUMNNAME COLUMNNAME FROM SYS_TFMAP A
    WHERE A.SYS_TABLENAME_TEMP='GBL_SALESGARDENINVOICEMASTER'
) B,
(
    SELECT * FROM CHECKLOCKDATEINFO
  --  WHERE PROJECTNAME='SALES'
) C
WHERE 1 = 1
AND     B.COLUMNNAME=C.COLUMNNAME
AND     B.TABLENAME=C.TABLENAME )


SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYSTAF
WHERE SYS_TABLENAME_ACTUAL=''






SELECT LISTAGG(COLUMNNAME,'~') WITHIN GROUP (ORDER BY COLUMNNAME) AS XX FROM (
SELECT C.COLUMNNAME FROM
(
    SELECT A.SYS_TABLENAME_ACTUAL TABLENAME,A.SYS_COLUMNNAME COLUMNNAME FROM SYS_TFMAP A
    WHERE A.SYS_TABLENAME_TEMP='GBL_SALESGARDENINVOICEMASTER'
) B,
(
    SELECT * FROM CHECKLOCKDATEINFO
  --  WHERE PROJECTNAME='SALES'
) C
WHERE 1 = 1
AND     B.COLUMNNAME=C.COLUMNNAME
AND     B.TABLENAME=C.TABLENAME )



SELECT LISTAGG(COLUMNNAME,'~') WITHIN GROUP (ORDER BY COLUMNNAME) AS XX FROM (
SELECT C.COLUMNNAME FROM
(
    SELECT A.SYS_TABLENAME_ACTUAL TABLENAME,A.SYS_COLUMNNAME COLUMNNAME FROM SYS_TFMAP A
    WHERE A.SYS_TABLENAME_TEMP='GBL_SALESGARDENINVOICEDETAIL'
) B,
(
    SELECT * FROM CHECKLOCKDATEINFO
  --  WHERE PROJECTNAME='SALES'
) C
WHERE 1 = 1
AND     B.COLUMNNAME=C.COLUMNNAME
AND     B.TABLENAME=C.TABLENAME )



SELECT LISTAGG(COLUMNNAME,'~') WITHIN GROUP (ORDER BY COLUMNNAME) AS XX FROM (
SELECT C.COLUMNNAME FROM
(
    SELECT A.SYS_TABLENAME_ACTUAL TABLENAME,A.SYS_COLUMNNAME COLUMNNAME FROM SYS_TFMAP A
    WHERE A.SYS_TABLENAME_TEMP='GBL_SALESCHARGEDETAILS'
) B,
(
    SELECT * FROM CHECKLOCKDATEINFO
  --  WHERE PROJECTNAME='SALES'
) C
WHERE 1 = 1
AND     B.COLUMNNAME=C.COLUMNNAME
AND     B.TABLENAME=C.TABLENAME )


SELECT FN_CHECKLOCKINFO('GBL_SALESCHARGEDETAILS','28/09/2020','0105010201010103','null','0002') XX FROM DUAL

INTO LV_RETSTR

    SELECT COUNT(*) XX  FROM LOCKDATE A,
    (
        SELECT A.SYS_TABLENAME_ACTUAL TABLENAME,A.SYS_COLUMNNAME COLUMNNAME FROM SYS_TFMAP A
        WHERE A.SYS_TABLENAME_TEMP='GBL_SALESCHARGEDETAILS'
    --    AND A.SYS_COLUMNNAME='SUSPENDDATE'
    ) B,
    (
        SELECT * FROM CHECKLOCKDATEINFO
    --    WHERE COLUMNNAME='SUSPENDDATE'
    ) C
    WHERE  A.PROJECTNAME=C.PROJECTNAME
    AND B.COLUMNNAME=C.COLUMNNAME
    AND  B.TABLENAME=C.TABLENAME
    AND TO_DATE('28/09/2020','DD/MM/YYYY') BETWEEN LOCKSTARTDATE AND LOCKENDDATE
    AND A.COMPANYCODE=NVL('NULL',A.COMPANYCODE)
    AND A.DIVISIONCODE=NVL('0002',A.DIVISIONCODE);
    
    SELECT * FROM MENUMASTER_RND
    WHERE UPPER(MENUDESC) LIKE UPPER('%garden invoi%')
    
    SELECT * FROM MENUMASTER_RND
    WHERE MENUCODE='0105010201010103'
    
    prcSales_GIDispatch_b4_Save
    
    
    SELECT * FROM ROLEDETAILS
    WHERE MENUCODE=''
    
    
    SELECT * FROM REPORTPARAMETERMASTER
    WHERE REPORTTAG = ''
    
    SELECT * FROM SYSTAF
    WHERE SYS_TABLENAME_ACTUAL=''