'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pgSalesOtherBillWOChallan_GST

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCOMPCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOMPCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIVCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIVCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYRCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYRCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUSRNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUSRNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOPTMODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPTMODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPROJNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPROJNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSYSROWID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSYSROWID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGRIDDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGRIDDATA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCHANNELTAG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHANNELTAG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBILLTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBILLTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDOCUMENTTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOCUMENTTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCHARGEGRIDDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHARGEGRIDDATA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSCRAPSALESBILLNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSCRAPSALESBILLNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''mskSCRAPSALESBILLDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskSCRAPSALESBILLDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCHANNELCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCHANNELCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHANNELCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHANNELCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMAND1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMAND1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSALESBILLNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSALESBILLNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSALESBILLNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSALESBILLNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSALESBILLDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSALESBILLDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskSALESBILLDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskSALESBILLDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPARTYCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPARTYCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPARTYCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPARTYNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGridCurRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGridCurRow As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGridHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGridHelp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblADDRESSCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblADDRESSCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtADDRESSCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtADDRESSDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSDESC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblADDRESSCODEBILL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblADDRESSCODEBILL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtADDRESSCODEBILL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSCODEBILL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtADDRESSDESCBILL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSDESCBILL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBILLSTATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBILLSTATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBILLSTATECODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBILLSTATECODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBILLSTATEDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBILLSTATEDESC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGATEPASSNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGATEPASSNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGATEPASSNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGATEPASSNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblGATEPASSDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGATEPASSDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskGATEPASSDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskGATEPASSDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLORRYNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLORRYNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLORRYNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLORRYNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWEIGHTSLIPNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWEIGHTSLIPNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWEIGHTSLIPNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWEIGHTSLIPNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLETTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLETTERNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLETTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLETTERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLETTERDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLETTERDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskLETTERDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskLETTERDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPONO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPONO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPONO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPONO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPODATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPODATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPODATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPODATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMRNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMRNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMRNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMRDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMRDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMRDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAMENDMENT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAMENDMENT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAMENDMENT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAMENDMENT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDESTINATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDESTINATION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDESTINATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDESTINATION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gridPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TabsView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabsView1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''TabPanelDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelDetails As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''UpdatePanelBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelBill As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PanelDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TabPanelChargeDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelChargeDetails As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''UpdatePanelChrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelChrg As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PanelChrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelChrg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTOTALQTY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTOTALQTY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTOTALQTY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTOTALQTY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTOTALNETAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTOTALNETAMOUNT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNETAMT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNETAMT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTOTALGROSSAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTOTALGROSSAMOUNT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGROSSAMT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGROSSAMT As Global.System.Web.UI.WebControls.TextBox
End Class
