'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pgSalesDebitCreditNote_GST

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCOMPCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOMPCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIVCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIVCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYRCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYRCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUSRNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUSRNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOPTMODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPTMODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPROJNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPROJNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSYSROWID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSYSROWID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDETAILSGRIDDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDETAILSGRIDDATA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCHANNELTAG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHANNELTAG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEXCHANGERATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEXCHANGERATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTOTALNETWEIGHT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTOTALNETWEIGHT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTOTALNOOFPACKING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTOTALNOOFPACKING As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDOCUMENTTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOCUMENTTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCHARGEGRIDDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHARGEGRIDDATA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RbtDebitNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbtDebitNote As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RbtCreditNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbtCreditNote As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtREFERENCETYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtREFERENCETYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSALESTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSALESTYPE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHANNELCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHANNELCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPROFORMAINVNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPROFORMAINVNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSALEBILLNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSALEBILLNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblM4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblM4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPROFORMAINVDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPROFORMAINVDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskSALEBILLDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskSALEBILLDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtREFEXCISEINVNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtREFEXCISEINVNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''mskREFEXCISEINVDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskREFEXCISEINVDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDEBITCREDITNOTENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEBITCREDITNOTENO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDEBITCREDITNOTENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEBITCREDITNOTENO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEBITCREDITNOTEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEBITCREDITNOTEDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskDEBITCREDITNOTEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskDEBITCREDITNOTEDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChallanNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChallanNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHALLANNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHALLANNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBROKERCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBROKERCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBROKERCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBROKERCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBROKERNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBROKERNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBUYERCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBUYERCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBUYERCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBUYERCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBUYERNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBUYERNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblADDRESSCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblADDRESSCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtADDRESSCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtADDRESSDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSDESC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblADDRESSCODEBILL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblADDRESSCODEBILL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtADDRESSCODEBILL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSCODEBILL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtADDRESSDESCBILL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADDRESSDESCBILL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBILLSTATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBILLSTATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBILLSTATECODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBILLSTATECODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBILLSTATEDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBILLSTATEDESC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEXCHRATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEXCHRATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEXCHRATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEXCHRATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gridPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TabsView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabsView1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''TabPanelDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelDetails As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''UpdatePanelLedger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelLedger As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PanelDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TabPanelChargeDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelChargeDetails As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''PanelChargeDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelChargeDetails As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtTOTALNETQUANTITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTOTALNETQUANTITY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNETINDIANAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNETINDIANAMOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTOTALNETAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTOTALNETAMOUNT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNETAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNETAMOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTOTALGROSSAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTOTALGROSSAMOUNT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGROSSAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGROSSAMOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblREMARKS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblREMARKS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtREMARKS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtREMARKS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVEHICLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVEHICLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVEHICLENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVEHICLENO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTRANSPORTERCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTRANSPORTERCODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTRANSPORTERCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRANSPORTERCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTRANSPORTERDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRANSPORTERDESC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDESTINATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDESTINATION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDESTINATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDESTINATION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCNOTENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCNOTENO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCNOTENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNOTENO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCNOTEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCNOTEDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskCNOTEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskCNOTEDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBOOKING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBOOKING As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBOOKING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBOOKING As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblREMOVALDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblREMOVALDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskREMOVALDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskREMOVALDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTIMEOFPREPARATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIMEOFPREPARATION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTIMEOFPREPARATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTIMEOFPREPARATION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSEALNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSEALNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSEALNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSEALNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblISSUEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISSUEDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskISSUEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskISSUEDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTIMEOFISSUE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIMEOFISSUE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTIMEOFISSUE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTIMEOFISSUE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVESSELFLIGHTNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVESSELFLIGHTNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVESSELFLIGHTNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVESSELFLIGHTNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVESSELFLIGHTDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVESSELFLIGHTDESC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCONTAINERTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCONTAINERTYPE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCONTAINERTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCONTAINERTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCONTAINERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCONTAINERNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCONTAINERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCONTAINERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPADLOCKKEYNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPADLOCKKEYNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPADLOCKKEYNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPADLOCKKEYNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEX As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEXFROM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEXFROM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEXTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEXTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRENO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRENO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFORM1NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFORM1NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFORM1NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFORM1NO As Global.System.Web.UI.WebControls.TextBox
End Class
