CREATE  TABLE UNREALIZED_15032021
(
    TOKENNO VARCHAR2(30),
    EMP_NAME VARCHAR2(120),
    UNREALIZED_AMT NUMBER(10,2)
)



SELECT * FROM UNREALIZED_15032021 A, PISEMPLOYEEMASTER B
WHERE A.TOKENNO=B.TOKENNO



SELECT * FROM UNREALIZED_15032021 
WHERE TOKENNO NOT IN 
(
    SELECT DISTINCT TOKENNO FROM PISEMPLOYEEMASTER 
)

SELECT * FROM PISEMPLOYEEMASTER
WHERE TOKENNO LIKE '00407'



INSERT INTO PISWPSUNREALIZEDDATA


SELECT * FROM PISWPSUNREALIZEDDATA

SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH,'01-FEB-2021' FORTNIGHTSTARTDATE,'28-FEB-2021' FORTNIGHTENDDATE, C.WORKERSERIAL, B.TOKENNO, 
COMPONENTCODE,B.UNREALIZED_AMT COMPONENTAMOUNT,B.UNREALIZED_AMT ACTUALAMOUNT,'28-FEB-2021' REFERENCE_FNEDATE, PAIDON, TRANTYPE, MODULE, REMARKS, USERNAME, 
FN_GENERATE_SYSROWID SYSROSWID,SYSDATE LASTMODIFIED, DOCNO, DOCDATE, TRAN_SOURCE FROM 
(
SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, WORKERSERIAL, TOKENNO, 
COMPONENTCODE,COMPONENTAMOUNT, ACTUALAMOUNT, REFERENCE_FNEDATE, PAIDON, TRANTYPE, MODULE, REMARKS, USERNAME, 
SYSROSWID, LASTMODIFIED, DOCNO, DOCDATE, TRAN_SOURCE FROM PISWPSUNREALIZEDDATA
WHERE WORKERSERIAL='000001'
) A,UNREALIZED_15032021 B, 
(
    SELECT TOKENNO, WORKERSERIAL FROM PISEMPLOYEEMASTER
) C
WHERE  B.TOKENNO = C.TOKENNO




'BJ0056' COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, WORKERSERIAL, TOKENNO, 
COMPONENTCODE, COMPONENTAMOUNT, ACTUALAMOUNT, REFERENCE_FNEDATE, PAIDON, TRANTYPE, MODULE, REMARKS, USERNAME, 
SYSROSWID, LASTMODIFIED, DOCNO, DOCDATE, TRAN_SOURCE
FROM UNREALIZED_15032021