GBL_STAFFPFDATAUPLOAD

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%staff%upload%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''


SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''

prcPIS_STF_DTULD_b4Save


STAFFPFDATAUPLOAD

select * from STAFFPFDATAUPLOAD


alter table STAFFPFDATAUPLOAD add GROSSEARN number(15,2)

alter table STAFFPFDATAUPLOAD add PF_GROSS number(15,2)

alter table STAFFPFDATAUPLOAD add PEN_GROSS number(15,2)

alter table STAFFPFDATAUPLOAD add ESI_E number(15,2)

alter table STAFFPFDATAUPLOAD add ATTN_SALD number(15,2)

alter table STAFFPFDATAUPLOAD add ATTN_WPAY number(15,2)


add columns(GROSSEARN, PF_GROSS, PEN_GROSS, ESI_E, PTAX, ATTN_SALD,  ATTN_WPAY




select * from pispaytransaction


----------------------------------------------------------------


SELECT FN_ELIGIBLEFORPFL('NJ0002','0010','WS1119','MPL','12/10/2020') FROM DUAL


select decode(rtrim(xmlagg(xmlelement(e,x.componentcode||' = '||x.COMPONENTAMOUNT||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.componentcode||' = '||x.COMPONENTAMOUNT||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Actual Balance'' ')
FROM 
(
    SELECT COMPONENTCODE, SUM(COMPONENTAMOUNT) COMPONENTAMOUNT 
    FROM
    (
        SELECT COMPONENTCODE, COMPONENTAMOUNT FROM PFTRANSACTIONDETAILS
         WHERE COMPANYCODE='NJ0002'
           --AND DIVISIONCODE='0010' 
           AND YEARCODE='2020-2021'
          -- AND YEARMONTH <= TO_CHAR(TO_NUMBER(TO_char(to_date('12/10/2020','DD/MM/YYYY'),'YYYY'))) ||CASE WHEN TO_NUMBER(TO_char(to_date('12/10/2020','DD/MM/YYYY'),'MM'))>=4 AND TO_char(to_date('12/10/2020','DD/MM/YYYY'),'MM')<=9 THEN '09' ELSE '03' END
          AND YEARMONTH <= TO_CHAR(TO_NUMBER(TO_char(to_date('12/10/2020','DD/MM/YYYY'),'YYYYMM'))) --||CASE WHEN TO_NUMBER(TO_char(to_date('12/10/2020','DD/MM/YYYY'),'MM'))>=4 AND TO_char(to_date('12/10/2020','DD/MM/YYYY'),'MM')<=9 THEN '09' ELSE '03' END
           AND PFNO='WS1119'
           AND COMPONENTCODE<>'EPF'
         UNION ALL
        SELECT 'PF_E' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
         UNION ALL
        SELECT 'PF_C' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
         UNION ALL
        SELECT 'VPF' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
    )
    GROUP BY COMPONENTCODE 
) X

select decode(rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Ratio'' ')
FROM 
(  
    SELECT PARAMVALUE PERCENTAGE, 'PF_C' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_C_PERCENTAGE' AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
    union
    SELECT PARAMVALUE PERCENTAGE, 'PF_E' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_E_PERCENTAGE' AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
    union
    SELECT PARAMVALUE PERCENTAGE, 'VPF'  COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='VPF_PERCENTAGE'  AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
) X



SELECT COMPONENTCODE, COMPONENTAMOUNT FROM PFTRANSACTIONDETAILS
WHERE COMPANYCODE='NJ0002'
--AND DIVISIONCODE='0010' 
AND YEARCODE='2020-2021'
AND YEARMONTH <= TO_CHAR(TO_NUMBER(TO_char(to_date('12/10/2020','DD/MM/YYYY'),'YYYYMM'))) --||CASE WHEN TO_NUMBER(TO_char(to_date('12/10/2020','DD/MM/YYYY'),'MM'))>=4 AND TO_char(to_date('12/10/2020','DD/MM/YYYY'),'MM')<=9 THEN '09' ELSE '03' END
AND PFNO='WS1119'
AND COMPONENTCODE<>'EPF'


--------------------------------------------------------

select * from pfloantransaction


exec PRC_PF_COMPONENT_SHARE('NJ0002','0010' ,'2020-2021','005585','MPL','12/10/2020','A')


select * from GTT_LOANSANCTION_PRAM

SELECT * FROM (
SELECT 'NJ0002' COMPANYCODE,'0010' DIVISIONCODE,'2020-2021' YEARCODE,
NVL(D.PFNO,P.PFNO) PFNO,NVL(D.TOKENNO,P.TOKENNO) TOKENNO,NVL(D.WORKERSERIAL,P.WORKERSERIAL) WORKERSERIAL,TO_CHAR(NVL(D.LOANDATE,P.LOANDATE),'DD/MM/YYYY') LOANDATE,NVL(D.LOANCODE,P.LOANCODE) LOANCODE,
NVL(D.PARAM_NAME,P.PARAM_NAME) PARAM_NAME,NVL(D.PF_E,P.PF_E) PF_E,NVL(D.PF_C,P.PF_C) PF_C,NVL( D.VPF,P.VPF) VPF, NVL(D.OTHER,P.OTHER) OTHER,'A' OPERATIONMODE,P.ISELLIGIBLE,P.REMARKS
FROM GTT_LOANSANCTION_PRAM P,LOANSANCTION_DETAILS D
WHERE P.PFNO=D.PFNO(+)
AND P.COMPANYCODE=D.COMPANYCODE(+)
AND P.DIVISIONCODE=D.DIVISIONCODE(+)
AND P.LOANCODE=D.LOANCODE(+)
AND P.LOANDATE=D.LOANDATE(+)
AND P.PARAM_NAME=D.PARAM_NAME(+)
ORDER BY TABINDEX
)
WHERE PF_E IS NOT NULL OR PF_C IS NOT NULL OR VPF IS NOT NULL OR OTHER IS NOT NULL OR ISELLIGIBLE IS NOT NULL OR REMARKS IS NOT NULL


PROC_PFLOANSANCTION
