insert into gtt_salesbillprintgst


SELECT S.SALEBILLNO, S.SALEBILLDATE, S.EXCISEINVNO, S.EXCISEINVDATE, S.PROFORMAINVNO, S.PROFORMAINVDATE, S.SAUDANO, S.SAUDADATE, 
       /*S.BUYERORDERNO*/S.CONTRACTNO BUYERORDERNO, /*S.BUYERORDERDATE*/CONTRACTDATE BUYERORDERDATE, S.BROKERCODE,'['|| S.BROKERCODE ||'] '|| S.BROKERNAME, S.BUYERCODE, S.BUYERNAME, S.TRANSPORTERCODE, P.PARTYNAME, 
       '['|| P1.PARTYCODE ||'] '||  P1.ADDRESSNAME  ADDRESSNAMEBILL, P1.ADDRESS ||' Pin : '||P1.PIN ADDRESSBILL, P1.PIN PINBILL, P1.GSTSTATECODE||' '||P1.STATE STATEBILL, P1.GSTNNO GSTNNOBILL, 
       '['|| P2.PARTYCODE ||'] '|| P2.ADDRESSNAME  ADDRESSNAMESHIP, P2.ADDRESS ||' Pin : '||P2.PIN ADDRESSSHIP, P2.PIN PINSHIP, P2.GSTSTATECODE||' '||P2.STATE STATESHIP, P2.GSTNNO GSTNNOSHIP, 
       S.DESTINATION, S.VEHICLENO, S.VESSELORFLIGHT, S.VESSELFLIGHTNO, S.CNOTENO, S.CNOTEDATE, S.CHALLANNO, S.CHANNELCODE, 
       S.BILLSERIALNO, S.QUALITYCODE, H.HSNCODE,'['|| S.QUALITYCODE ||']  '|| S.QUALITYMANUALDESC||CHR(10)||S.MARKS QUALITYMANUALDESC, S.PACKINGCODE, S.PACKINGNAME, S.NOOFPACKINGUNIT, S.UORCODE,  
       S.UORNAME, S.MEASURECODE, S.TOTALQUANTITY, DECODE(S.MEASUREUNIT,'KGS',S.TOTALWEIGHT,S.TOTALWEIGHT*1) TOTALWEIGHT, DECODE(S.MEASUREUNIT,'KGS',S.PACKSHEETWEIGHT,S.PACKSHEETWEIGHT*1) PACKSHEETWEIGHT, DECODE(S.MEASUREUNIT,'KGS',S.GROSSWEIGHT,S.GROSSWEIGHT*1) GROSSWEIGHT, /*S.RATE*/ S.INDIANRATE, /*S.TOTALAMOUNT*/ S.TOTALINDIANAMOUNT, 
       /*S.GROSSAMOUNT*/ S.GROSSAMOUNTINR, fn_num_to_words(ROUND(S.GROSSAMOUNTINR,2),'RS') AMTINWORDS, CH.CHARGEDATA, T.SRL, T.TEXT, 
       C.BANKCODE, B.BANKNAME, B.BANKADDRESS, B.ACNO, C.IFSCCODE IFCSCODE, 
       replace(C.COMPANYNAME,'Unit : ', chr(10)||'Unit : ') COMPANYNAME,'Registered office : '|| C.COMPANYADDRESS, C.COMPANYADDRESS1, C.COMPANYADDRESS2,'PAN : '||  C.PANNO, C.COMPANYEMAIL, 
       D.DIVISIONNAME, D.GSTNNO, D.GSTSTATECODE, 'D:\SWT_ERP_ONLINE\SWT_Jute\swterp\swterp\\LOGO\LOGO_DJC.JPG' LOGOPATH, C.CINNO EX1,  
       CASE WHEN CHANNELTAG='EXPORT' AND CH.CHARGEDATA LIKE '%GST%' THEN 'SUPPLY MEANT FOR EXPORT ON PAYMENT OF INTEGRATED TAX' WHEN CHANNELTAG='EXPORT' AND CH.CHARGEDATA NOT LIKE '%GST%' THEN 'SUPPLY MEANT FOR EXPORT UNDER BOND OR LETTER OF UNDERTAKING WITHOUT PAYMENT OF INTERGREATED TAX' ELSE '' END EX2, S.CURRENCYCODE EX3, S.PACKSTYLECODE EX4, 'D:\SWT_ERP_ONLINE\SWT_Jute\swterp\swterp\\LOGO\LOGO.JPG' EX5, 
       S.EWAYBILLNO, S.EWAYBILLDATE, S.TIME_STAMP, TO_CHAR(S.SALEBILLDATE,'DD/MM/YYYY')||'  '||S.TIMEOFPREPARATION EX6,S.PCONUMBER EX7, TO_CHAR(S.PCODATE,'DD/MM/YYYY') EX8, REMARKSPRO EX9, S.CHANNELTAG EX10, 
        'D:\SWT_ERP_ONLINE\SWT_Jute\swterp\swterp\\LOGO\DRAFT_WTR2.png' EX11, NULL EX12, NULL EX13, NULL EX14, NULL EZ15 ,   
        'FAX : '||COMPANYFAX EX16, 'COUNTRY : '|| C.COMPANYCOUNTRY EX17,'STATE : '||C.COMPANYSTATE ||'   STATE CODE : '||D.GSTSTATECODE EX18,'Registered office : '|| C.COMPANYADDRESS1/*USED FOR FOOTER PART NOTE*/ EX19,C.COMPANYHOPHONE1 EX20,/*CASE WHEN S.DOCUMENTTYPE='SALE MEMO' AND CHANNELTAG='EXPORT'  THEN 'DELIVERY CHALLAN' ELSE 'TAX INVOICE' END*/'TAX INVOICE'  EX21,NULL /*AmendmentNo. 1*/ EX22,NULL /*AmendmentNo. Date*/ EX23,NULL /*AmendmentNo. 2*/ EX24,NULL /*AmendmentNo. Date*/  EX25,S.SHIPPINGINSNO EX26,TO_CHAR(S.SHIPPINGINSDATE,'DD/MM/YYYY') EX27,CASE WHEN CHANNELTAG='EXPORT' THEN S.PROFORMAINVNO ELSE NULL END EX28,CASE WHEN CHANNELTAG='EXPORT' THEN TO_CHAR(S.PROFORMAINVDATE,'DD/MM/YYYY') ELSE NULL END EX29, 
        RTRIM(LTRIM(P.PARTYADDRESS)) ||' City : '||P.PARTYCITY ||' Pin : '||P.PARTYPIN ||' GSTIN : '||P.GSTNNO EX30,S.CONTAINERNO EX31,S.SEALNO EX32,NULL /*E SEAL NO*/ EX33,S.BOOKING EX34,F.LUTNO /*LUT NO*/ EX35,TO_CHAR(F.LUTDATE,'DD/MM/YYYY')/*LUT DATE*/ EX36,NULL EX37,'Registered office : '|| C.COMPANYADDRESS1 ||' '||C.COMPANYADDRESS2 EX38,NULL EX39,NULL EX40,NULL EX41,NULL EX42,NULL EX43, 
        NULL EX44,NULL EX45,NULL EX46,NULL EX47,NULL EX48,NULL EX49,NULL EX50,NULL EX51,NULL EX52,NULL EX53,NULL EX54,NULL EX55,NULL EX56, 
        NULL EX57,NULL EX58,NULL EX59,NULL EX60
FROM SALESBILLVIEW_CAN S, COMPANYMAST C, DIVISIONMASTER D, PARTYADDRESS P1, PARTYADDRESS P2, PARTYMASTER P, GSTITEMVSHSNMAPPING H, SALESBANKMASTER B,FINANCIALYEAR F, 
     ( 
      SELECT DOCUMENTNO, rtrim(xmlagg(xmlelement(e, X.CHARGESHORTNAME || '             '|| X.CHARGEAMOUNT || '~')order by X.SERIALNO).extract ('//text()'),'~') CHARGEDATA 
        FROM ( 
        SELECT D.DOCUMENTNO, M.CHARGESHORTNAME, TO_CHAR(CHARGEAMOUNT,'9999999990.99') CHARGEAMOUNT, TO_NUMBER(SERIALNO) SERIALNO 
        FROM SALESCHARGEDETAILS_CAN D, CHARGEMASTER M 
        WHERE D.COMPANYCODE=M.COMPANYCODE 
        AND D.DIVISIONCODE=M.DIVISIONCODE 
        AND D.CHARGECODE=M.CHARGECODE 
        AND D.CHANNELCODE=M.CHANNELCODE 
        AND M.MODULE='SALES' 
        AND M.CHARGETYPE NOT LIKE 'GST_%' 
        AND D.COMPANYCODE='DJ0107' 
        AND D.DIVISIONCODE='0002' 
        AND D.DOCUMENTTYPE='SALE BILL' 
        UNION ALL 
        SELECT D.DOCUMENTNO, 'TAXABLE VALUE' CHARGESHORTNAME, TO_CHAR(MAX(NVL(ASSESSABLEAMOUNT,0)),'9999999990.99') CHARGEAMOUNT, MIN(TO_NUMBER(SERIALNO))-0.1 SERIALNO 
        FROM SALESCHARGEDETAILS_CAN D, CHARGEMASTER M 
        WHERE D.COMPANYCODE=M.COMPANYCODE 
        AND D.DIVISIONCODE=M.DIVISIONCODE 
        AND D.CHARGECODE=M.CHARGECODE 
        AND D.CHANNELCODE=M.CHANNELCODE 
        AND M.MODULE='SALES' 
        AND M.CHARGETYPE LIKE 'GST_%' 
        AND D.COMPANYCODE='DJ0107' 
        AND D.DIVISIONCODE='0002' 
        AND D.DOCUMENTTYPE='SALE BILL' 
        GROUP BY D.DOCUMENTNO 
        UNION ALL 
        SELECT D.DOCUMENTNO, M.CHARGESHORTNAME, TO_CHAR(CHARGEAMOUNT,'9999999990.99') CHARGEAMOUNT, TO_NUMBER(SERIALNO) SERIALNO 
        FROM SALESCHARGEDETAILS_CAN D, CHARGEMASTER M 
        WHERE D.COMPANYCODE=M.COMPANYCODE 
        AND D.DIVISIONCODE=M.DIVISIONCODE 
        AND D.CHARGECODE=M.CHARGECODE 
        AND D.CHANNELCODE=M.CHANNELCODE 
        AND M.MODULE='SALES' 
        AND M.CHARGETYPE LIKE 'GST_%' 
        AND D.COMPANYCODE='DJ0107' 
        AND D.DIVISIONCODE='0002' 
        AND D.DOCUMENTTYPE='SALE BILL' 
        ORDER BY SERIALNO 
        ) X 
        GROUP BY DOCUMENTNO 
     ) CH, 
     ( 
        SELECT 1 SRL, 'Original for Recipient' TEXT FROM DUAL 
        UNION ALL 
        SELECT 2 SRL, 'Duplicate For Transporter' TEXT FROM DUAL 
        UNION ALL 
        SELECT 3 SRL, 'Triplicate for Supplier' TEXT FROM DUAL 
        UNION ALL 
        SELECT 4 SRL, 'Extra Copy' TEXT FROM DUAL 
     ) T 
WHERE S.COMPANYCODE=C.COMPANYCODE 
AND S.COMPANYCODE=D.COMPANYCODE 
AND S.DIVISIONCODE=D.DIVISIONCODE 
AND S.COMPANYCODE=H.COMPANYCODE 
AND S.QUALITYCODE=H.ITEMCODE 
AND H.MODULE='SALES' 
AND C.COMPANYCODE=B.COMPANYCODE(+) 
AND B.DIVISIONCODE(+)='0002' 
AND C.BANKCODE=B.BANKCODE(+) 
AND C.IFSCCODE=B.IFSCCODE(+) 
AND S.SALEBILLNO=CH.DOCUMENTNO(+) 
AND S.COMPANYCODE=P1.COMPANYCODE(+) 
AND S.BUYERCODE=P1.PARTYCODE(+) 
AND S.ADDRESSCODEBILL=P1.ADDRESSCODE(+) 
AND P1.MODULE(+)='SALES' 
AND S.COMPANYCODE=P2.COMPANYCODE(+) 
AND S.BUYERCODE=P2.PARTYCODE(+) 
AND S.ADDRESSCODE=P2.ADDRESSCODE(+) 
AND P2.MODULE(+)='SALES' 
AND S.COMPANYCODE=P.COMPANYCODE(+) 
AND S.TRANSPORTERCODE=P.PARTYCODE(+) 
AND P.MODULE(+)='SALES' 
AND P.PARTYTYPE(+)='TRANSPORTER' 
AND S.COMPANYCODE='DJ0107' 
AND S.DIVISIONCODE='0002' 
AND S.COMPANYCODE=F.COMPANYCODE
AND S.DIVISIONCODE=F.DIVISIONCODE
AND S.YEARCODE=F.YEARCODE
AND S.SALEBILLDATE>=TO_DATE('01/04/2020','DD/MM/YYYY') 
AND S.SALEBILLDATE<=TO_DATE('31/03/2021','DD/MM/YYYY') 
 AND S.SALEBILLNO IN ('DJC/2021/G1859') 
ORDER BY S.SALEBILLNO, T.SRL, S.BILLSERIALNO