SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%pf loa%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='01110212'

update MENUMASTER_RND set VIEWPOSSIBLE='Y' WHERE MENUCODE='01110212' 

update ROLEDETAILS set ACCESSVIEW='Y' WHERE MENUCODE='01110212' 

SELECT * FROM ROLEDETAILS
WHERE MENUCODE='01110212'

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

select * from pfloantransaction
where systemvoucherno is not null
and yearmonth = '202006'
and systemvoucherno ='SYS/PF/JVM/2021/03455'


SELECT A.ACCODE,ACHEAD 
FROM ACVOUCHERDETAILS_ENTRY A, ACACLEDGER B
WHERE SYSTEMVOUCHERNO=
(
    SELECT MAX(SYSTEMVOUCHERNO) FROM PFLOANTRANSACTION
    WHERE SYSTEMVOUCHERNO IS NOT NULL
    AND loandate between '01-jun-2020' and '30-jun-2020'
)
AND A.DRCR='C'
AND A.ACCODE=B.ACCODE

SELECT ACSHORTDESCRIPTION FROM ACACLEDGER
WHERE ACCODE='P000014'





prcPF_LOANLIABILITY_b4Save

SELECT * FROM GBL_PFLEDGERMAPPING

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = ''


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_PFLEDGERMAPPING'

 

SELECT A.COMPANYCODE, A.DIVISIONCODE,A.LOANCODE, A.LOANDATE, A.YEARMONTH,
A.WORKERSERIAL, A.TOKENNO, A.SYSTEMVOUCHERNO, A.SYSTEMVOUCHERDATE 
FROM PFLOANTRANSACTION A, GBL_PFLEDGERMAPPING B
WHERE A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.WORKERSERIAL=B.WORKERSERIAL
AND A.LOANDATE=B.PFLOANDATE
AND A.LOANCODE=B.LOANCODE
AND A.YEARMONTH=B.YEARMONTH



 


 
SELECT  * FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'



UPDATE PFLOANTRANSACTION
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
AND WORKERSERIAL='1232656'
AND LOANCODE='MPL'
AND LOANDATE='12/12/12'

SELECT * FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
AND TRANSACTIONTYPE='LOAN'

AND YEARMONTH='202006'

AND WORKERSERIAL='1232656'


UPDATE PFTRANSACTIONDETAILS
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
AND TRANSACTIONTYPE='LOAN'
AND YEARMONTH='202006'
AND WORKERSERIAL='1232656'


UPDATE PFLOANAPPLICATION
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'


select * from pfloantransaction
where yearmonth='202006'
and SYSTEMVOUCHERNO IS NOT NULL
--577



 SELECT ROW_NUMBER() OVER(ORDER BY NVL(ACTUALLOANDATE, LOANDATE), A.PFNO) SLNO, A.PFNO, LOANCODE,A.TOKENNO, A.WORKERSERIAL, WORKERNAME,AMOUNT,SANCTIONEDAMOUNT, PF_E, PF_C, VPF, 
 TO_CHAR(NVL(ACTUALLOANDATE, LOANDATE),'DD/MM/YYYY') PFLOANDATE , 
 TO_CHAR(NVL(ACTUALLOANDATE, LOANDATE),'DD/MM/YYYY') VOUCHERDATE, YEARMONTH,MODULE, TO_CHAR(TO_DATE('01/06/2020','DD/MM/YYYY'),'DD/MM/YYYY') FROMDATE,TO_CHAR(TO_DATE('30/06/2020','DD/MM/YYYY'),'DD/MM/YYYY') TODATE   
 FROM PFLOANTRANSACTION A, VW_WPSPISMASTER B  
 WHERE
 A.EMPLOYEECOMPANYCODE=B.COMPANYCODE(+) 
 AND A.EMPLOYEEDIVISIONCODE=B.DIVISIONCODE(+) 
 AND A.PFNO=B.PFNO(+)
 AND A.COMPANYCODE='NJ0002' 
 AND A.DIVISIONCODE='0010' 
 AND NVL(ACTUALLOANDATE, LOANDATE) >= TO_DATE('01/06/2020','DD/MM/YYYY')
 AND NVL(ACTUALLOANDATE, LOANDATE) <= TO_DATE('30/06/2020','DD/MM/YYYY')
 
 
 SELECT * FROM PFLOANTRANSACTION A, VW_WPSPISMASTER B  
 WHERE 1=1
 and A.EMPLOYEECOMPANYCODE=B.COMPANYCODE(+) 
 AND A.EMPLOYEEDIVISIONCODE=B.DIVISIONCODE(+) 
 AND A.PFNO=B.PFNO(+)
-- AND A.COMPANYCODE='NJ0002' 
-- AND A.DIVISIONCODE='0010' 
and yearmonth='202006'

 AND NVL(ACTUALLOANDATE, LOANDATE) >= TO_DATE('01/06/2020','DD/MM/YYYY')
 AND NVL(ACTUALLOANDATE, LOANDATE) <= TO_DATE('30/06/2020','DD/MM/YYYY')
 
 
 SELECT a.systemvoucherno,ROW_NUMBER() OVER(ORDER BY NVL(ACTUALLOANDATE, LOANDATE), A.PFNO) SLNO, A.PFNO, LOANCODE,A.TOKENNO, A.WORKERSERIAL, WORKERNAME,AMOUNT,SANCTIONEDAMOUNT, PF_E, PF_C, VPF, 
 TO_CHAR(NVL(ACTUALLOANDATE, LOANDATE),'DD/MM/YYYY') PFLOANDATE , 
 TO_CHAR(NVL(ACTUALLOANDATE, LOANDATE),'DD/MM/YYYY') VOUCHERDATE, YEARMONTH,MODULE, TO_CHAR(TO_DATE('01/06/2020','DD/MM/YYYY'),'DD/MM/YYYY') FROMDATE,TO_CHAR(TO_DATE('30/06/2020','DD/MM/YYYY'),'DD/MM/YYYY') TODATE   
 FROM PFLOANTRANSACTION A, VW_WPSPISMASTER B  
 WHERE
 A.EMPLOYEECOMPANYCODE=B.COMPANYCODE(+) AND A.EMPLOYEEDIVISIONCODE=B.DIVISIONCODE(+) AND A.PFNO=B.PFNO(+)
 AND A.COMPANYCODE='NJ0002' 
 AND A.DIVISIONCODE='0010' 
 AND NVL(ACTUALLOANDATE, LOANDATE) >= TO_DATE('01/06/2020','DD/MM/YYYY')
 AND NVL(ACTUALLOANDATE, LOANDATE) <= TO_DATE('30/06/2020','DD/MM/YYYY')
 AND SYSTEMVOUCHERNO IS NOT NULL
 AND MODULE IN ('WPS', 'PIS') 
 ORDER BY NVL(ACTUALLOANDATE, LOANDATE), A.PFNO 
 
 
 select * from PFLOANTRANSACTION
  where NVL(ACTUALLOANDATE, LOANDATE) >= TO_DATE('01/06/2020','DD/MM/YYYY')
 AND NVL(ACTUALLOANDATE, LOANDATE) <= TO_DATE('30/06/2020','DD/MM/YYYY')
 AND SYSTEMVOUCHERNO IS NOT NULL
 
 
 insert into PFLEDGERMAPPING
 (
 WORKERNAME, PFLOANDATE, TODATE, FROMDATE, PF_C, SYSROWID, TOKENNO, ACCODE, PF_E,  USERNAME, 
 SANCTIONEDAMOUNT, PAYABLEDATE, LOANCODE, VPF, COMPANYCODE, DIVISIONCODE, PFNO, WORKERSERIAL, YEARCODE, YEARMONTH, MODULE
 )
 select 
 WORKERNAME, PFLOANDATE, TODATE, FROMDATE, PF_C, SYSROWID, TOKENNO, ACCODE, PF_E, USERNAME, 
 SANCTIONEDAMOUNT, PAYABLEDATE, LOANCODE, VPF, COMPANYCODE, DIVISIONCODE, PFNO, WORKERSERIAL, YEARCODE, YEARMONTH, MODULE
 from GBL_PFLEDGERMAPPING
 
 
 insert into PFLEDGERMAPPING_tmp
 
 select * from PFLEDGERMAPPING
 
  select * from 
 PFLEDGERMAPPING_tmp
 
delete from 
 PFLEDGERMAPPING_tmp
 
  SELECT A.COMPANYCODE, A.DIVISIONCODE,A.LOANCODE, A.LOANDATE, A.YEARCODE,
                A.WORKERSERIAL, A.TOKENNO, A.SYSTEMVOUCHERNO, A.SYSTEMVOUCHERDATE 
                FROM PFLOANTRANSACTION A --, PFLEDGERMAPPING_tmp B
                WHERE A.SYSTEMVOUCHERNO IS NOT NULL
                and A.COMPANYCODE=B.COMPANYCODE
                AND A.DIVISIONCODE=B.DIVISIONCODE
                AND A.WORKERSERIAL=B.WORKERSERIAL
                AND NVL(a.ACTUALLOANDATE, a.LOANDATE)=B.PFLOANDATE
                AND A.LOANCODE=B.LOANCODE
                AND A.YEARMONTH=B.YEARMONTH
                
select * from PFLOANTRANSACTION
where systemvoucherno LIKE 'SYS/PF/JVM/2021/%'                

select * from acvoucherdetails_entry
where systemvoucherno='SYS/PF/JVM/2021/03717'