SELECT A.ACCODE,ACSHORTDESCRIPTION 
FROM ACVOUCHERDETAILS_ENTRY A, ACACLEDGER B
WHERE SYSTEMVOUCHERNO=
(
    SELECT MAX(SYSTEMVOUCHERNO) FROM PFLOANTRANSACTION A
    WHERE SYSTEMVOUCHERNO IS NOT NULL
    and NVL(a.ACTUALLOANDATE, a.LOANDATE) between '01-JUN-2020' AND '30-JUN-2020'
)
AND A.DRCR='C'
AND A.ACCODE=B.ACCODE

SELECT COUNT(A.ACCODE) 
FROM ACVOUCHERDETAILS_ENTRY A, ACACLEDGER B
WHERE SYSTEMVOUCHERNO=
(
    SELECT MAX(SYSTEMVOUCHERNO) FROM PFLOANTRANSACTION A
    WHERE SYSTEMVOUCHERNO IS NOT NULL
    and NVL(a.ACTUALLOANDATE, a.LOANDATE) > '01-MAY-2020'
)
AND A.DRCR='C'
AND A.ACCODE=B.ACCODE



 SELECT A.ACCODE,ACHEAD  FROM ACVOUCHERDETAILS_ENTRY A, ACACLEDGER B 
 WHERE SYSTEMVOUCHERNO= (     SELECT MAX(SYSTEMVOUCHERNO) 
 FROM PFLOANTRANSACTION    A  
 WHERE SYSTEMVOUCHERNO IS NOT NULL    
 AND NVL(A.ACTUALLOANDATE, A.LOANDATE) BETWEEN TO_DATE('01/05/2020','DD/MM/YYYY') AND TO_DATE('31/05/2020','DD/MM/YYYY') ) 
 AND A.DRCR='C' AND A.ACCODE=B.ACCODE 