SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%atten%othe%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''


SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

GPS/Pages/Transaction/pgGPSComponentAssignment.aspx


GPS/Pages/Transaction/pgGPSSectionWiseAreaCover.aspx

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''


SELECT * FROM (SELECT COMPMAST.EXTRA_ALLOW,COMPMAST.NONPF_ALLOW,COMPMAST.MED_ALLOW,COMPMAST.DED_WELFARE,COMPMAST.DED_UNION,COMPMAST.DED_ELEC,COMPMAST.OTHER_DED,COMPMAST.DED_LPG,COMPMAST.TEMP_DED, 'Y' STATUS 
  FROM GPSEMPLOYEEMAST EMPMAST,  
       ( 
        SELECT A.* 
          FROM GPSCOMPONENTASSIGNMENT A
         WHERE COMPANYCODE='DT0091' 
           AND DIVISIONCODE='0001' 
           AND A.TRANSACTIONTYPE = 'ATTENDANCE'
           AND EFFECTIVEDATE = TO_DATE('17/11/2020','DD/MM/YYYY') 
       ) COMPMAST 
 WHERE EMPMAST.COMPANYCODE='DT0091' 
   AND EMPMAST.DIVISIONCODE='0001' 
   AND EMPMAST.COMPANYCODE=COMPMAST.COMPANYCODE(+) 
   AND EMPMAST.DIVISIONCODE=COMPMAST.DIVISIONCODE(+) 
   AND EMPMAST.WORKERSERIAL=COMPMAST.WORKERSERIAL(+) 
   AND EMPMAST.CATEGORYCODE='PAR' 
   AND EMPMAST.DATEOFJOINING <=TO_DATE('17/11/2020', 'DD/MM/YYYY') 
   AND (EMPMAST.DATEOFRETIREMENT IS NULL OR EMPMAST.DATEOFRETIREMENT >= TO_DATE('17/11/2020', 'DD/MM/YYYY')) 
   AND (EMPMAST.DATEOFTERMINATION IS NULL OR EMPMAST.DATEOFTERMINATION >= TO_DATE('17/11/2020', 'DD/MM/YYYY')) 
   AND NVL(EMPMAST.ACTIVE,'N') ='Y' ) ORDER BY TOKENNO 
   
   
   ORA-20100: ~RAISE ERROR START~ORA-00904: "TOKENNO": invalid identifier~RAISE ERROR END~ ORA-06512: at "DHAMAI.PRC_CREATE_DYN_VIEW_CMP_ASSIGN", line 106 ORA-06512: at line 1