WPSUNREALIZEDDATA

SELECT WM_CONCAT(COLUMN_NAME) FROM COLS
WHERE TABLE_NAME = 'WPSUNREALIZEDDATA'


SELECT  COLUMN_NAME  FROM COLS
WHERE TABLE_NAME = 'WPSCASHOTPAYMENTDETAILS'


SELECT FN_GENERATE_SYSROWID
FROM DUAL

WPSCOMPONENTMASTER

INSERT INTO  WPSUNREALIZEDDATA
(
    COMPANYCODE,DIVISIONCODE,YEARCODE,FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,WORKERSERIAL,TOKENNO,
    COMPONENTCODE,COMPONENTAMOUNT,ACTUALAMOUNT,REFERENCE_FNEDATE,PAIDON,TRANTYPE,MODULE,REMARKS,
    USERNAME,SYSROSWID,LASTMODIFIED,DOCNO,DOCDATE,TRAN_SOURCE
)    


SELECT
COMPANYCODE,DIVISIONCODE,'2020-2021' YEARCODE,PAYMENTFROMDATE FORTNIGHTSTARTDATE,PAYMENTTODATE FORTNIGHTENDDATE,WORKERSERIAL,TOKENNO,
'CASHOT_AMT' COMPONENTCODE,NETPAY COMPONENTAMOUNT,NETPAY ACTUALAMOUNT,NULL REFERENCE_FNEDATE,PAYMENTDATE PAIDON,'UNREALIZED' TRANTYPE, 
'WPS' MODULE,'DATA IMPORT FROM CASH OT PAYMENT' REMARKS,'SWT' USERNAME,FN_GENERATE_SYSROWID SYSROSWID,SYSDATE LASTMODIFIED,
NULL DOCNO, NULL DOCDATE, NULL TRAN_SOURCE
FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND PAYMENTFROMDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTTODATE <= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTLOCK='Y'
AND ISTRANSFER='N'



DELETE
SELECT * 
FROM WPSUNREALIZEDDATA
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND FORTNIGHTSTARTDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND FORTNIGHTENDDATE <= TO_DATE('25/12/2020','DD/MM/YYYY')
AND COMPONENTCODE='CASHOT_AMT'
AND TRANTYPE= 'UNREALIZED'


UPDATE WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
SET ISTRANSFER='Y'
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND PAYMENTFROMDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTTODATE <= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTLOCK='Y'
AND ISTRANSFER='N'






COMPANYCODE,DIVISIONCODE,PAYMENTFROMDATE,PAYMENTTODATE,DEPARTMENTCODE,DEPARTMENTNAME,SHIFTCODE,TOKENNO,
WORKERNAME,WORKERSERIAL,OTHOURS,OTAMOUNT,ESI_OT,NETPAY,PAYMENTLOCK,ISTRANSFER