SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID LIKE '6030'

SELECT PFNO,WORKERSERIAL,TOKENNO,EMPLOYEENAME,MODULE  
 FROM PFEMPLOYEEMASTER  
 WHERE COMPANYCODE ='NJ0002'
   --AND DIVISIONCODE=<<DIVISIONCODE>>
   AND EMPLOYEESTATUS = 'ACTIVE'
   AND WORKERSERIAL IN (SELECT DISTINCT WORKERSERIAL FROM PFLOANINTEREST)
ORDER BY 1 DESC 

SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID LIKE '6093'
 
SELECT * FROM PFLOANINTERESTADJUSMENT
WHERE TOKENNO='85808'

GBL_PFLOANINTERESTADJUSMENT

SELECT * FROM QUERYMASTER


select * from PFLOANINTEREST
WHERE TOKENNO='85808'


SELECT A.COMPANYCODE, A.DIVISIONCODE, C.YEARCODE, C.YEARMONTH, C.FORTNIGHTSTARTDATE, 
C.FORTNIGHTENDDATE, B.PFNO, A.LOANCODE, A.LOANDATE,C.LOANAMOUNT LOANAMOUNT, C.INTERESTAPPLICABLEON, 
C.INTERESTPERCENTAGE,A.ADJUSTEDAMOUNT INTERESTAMOUNT, C.EMPLOYEECOMPANYCODE, C.EMPLOYEEDIVISIONCODE, 
C.MODULE,'ADJUSTMENT' TRANSACTIONTYPE, NVL(A.REMARKS,'INSERT DATA FROM PF LOAN INTEREST ADJUSTMENT ON '||TO_CHAR(SYSDATE,'DD/MM/YYYY')) REMARKS, A.USERNAME,SYS_GUID() SYSROWID, A.WORKERSERIAL, A.TOKENNO
FROM GBL_PFLOANINTERESTADJUSMENT A, PFEMPLOYEEMASTER B, PFLOANINTEREST C
WHERE A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.WORKERSERIAL=B.WORKERSERIAL
AND A.COMPANYCODE=C.COMPANYCODE
AND A.DIVISIONCODE=C.DIVISIONCODE
AND A.WORKERSERIAL=C.WORKERSERIAL
AND A.LOANCODE=C.LOANCODE
AND A.LOANDATE=C.LOANDATE
AND A.TOKENNO='85808'


SELECT * FROM PFLOANINTERESTADJUSMENT A, GBL_PFLOANINTERESTADJUSMENT B
WHERE 1=1
AND A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.WORKERSERIAL=B.WORKERSERIAL
AND A.LOANCODE=B.LOANCODE
AND A.LOANDATE=B.LOANDATE


DELETE FROM PFLOANINTERESTADJUSMENT A
WHERE 1=1
AND A.COMPANYCODE=lvMaster.COMPANYCODE
AND A.DIVISIONCODE=lvMaster.DIVISIONCODE
AND A.WORKERSERIAL=lvMaster.WORKERSERIAL
AND A.LOANCODE=lvMaster.LOANCODE
AND A.LOANDATE=lvMaster.LOANDATE


DELETE FROM PFLOANINTEREST A
WHERE 1=1
AND A.COMPANYCODE=lvMaster.COMPANYCODE
AND A.DIVISIONCODE=lvMaster.DIVISIONCODE
AND A.WORKERSERIAL=lvMaster.WORKERSERIAL
AND A.LOANCODE=lvMaster.LOANCODE
AND A.LOANDATE=lvMaster.LOANDATE
AND A.TRANSACTIONTYPE='ADJUSTMENT';


SELECT  * FROM MENUMASTER_RND
WHERE MENUCODE = '01110211'


prcPFLOANINT_ADJ_b4Save


-----------------------------------------------------------

 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.PFNO,  A.TOKENNO, A.WORKERSERIAL,  A.LOANCODE,  
 TO_CHAR(A.LOANDATE,'DD/MM/YYYY') LOANDATE,  A.ASONCAPITALBAL,A.ASONINTERESTBAL,A.SANCTIONAMOUNT, 
 NVL(A.INTERESTAMOUNT,0) INTERESTAMOUNT,A.MERGELOANAMOUNT,A.ADJINTERESTAMOUNT,A.ADJUSTMENTAMOUNT ,
 A.ADJUSTEDAMOUNT 
 FROM PFLOANINTERESTADJUSMENT A, PFEMPLOYEEMASTER B 
 WHERE 1=1 AND A.COMPANYCODE=B.COMPANYCODE 
 AND A.DIVISIONCODE=B.DIVISIONCODE 
 AND A.TOKENNO=B.TOKENNO 
-- AND NVL(A.TRANSACTIONTYPE,'NA') <> 'ADJUSTMENT' 
 AND A.LOANDATE= (SELECT MAX(LOANDATE)  FROM PFLOANINTERESTADJUSMENT WHERE WORKERSERIAL=A.WORKERSERIAL AND LOANCODE='MPL')
AND B.TOKENNO = '85808'
ORDER BY B.TOKENNO 