SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%PF Loan%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''


SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''


prcWPS_PFLOAN_b4Save

prcWPS_PFLOAN_AfterSave


SELECT * from PFLOANTRANSACTION

SELECT * from PFTRANSACTIONDETAILS

SELECT * FROM PFLOANMASTER

SELECT DISTINCT LOANCODE from PFLOANTRANSACTION

SELECT * FROM PFLOANTRANSACTION
WHERE TOKENNO='10833'


SELECT * FROM PFLOANBREAKUP
WHERE TOKENNO='10833'


SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO='10833'
AND YEARCODE='2020-2021'