 
INSERT INTO GRATUITYCOMPONENTRATE
(
    COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
    TRANSTYPE, MODULE, 
    FBASIC_PEICERT, FBASIC, VBASIC, DA, TSA, ADHOC, NS_ALLOW, NS_HRS, ATTENDANCEHOURS
)   
 SELECT A.COMPANYCODE, A.DIVISIONCODE,A.TOKENNO,WORKERSERIAL, FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,
'FORTNIGHT DETAILS' TRANSTYPE, 'WPS' MODULE,
A.FBASIC_PEICERT, A.FBASIC,A.VBASIC ,A.DA,
A.TSA,A.ADHOC , (CASE WHEN B.PFLINKHOURS >0 THEN A.NS_ALLOW ELSE 0 END) NS_ALLOW 
,(CASE WHEN B.PFLINKHOURS >0 THEN A.NIGHTALLOWANCEHOURS ELSE 0 END) NS_HRS , A.ATTENDANCEHOURS
FROM WPSWAGESDETAILS A, VW_WPSSECTIONMAST  B
WHERE TOKENNO='04053' --'04053'
AND A.COMPANYCODE='NJ0001'
AND A.DIVISIONCODE='0002'
AND A.SECTIONCODE=B.SECTIONCODE
AND A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.DEPARTMENTCODE=B.DEPARTMENTCODE
AND FORTNIGHTENDDATE IN 
(
    SELECT FORTNIGHTENDDATE FROM 
    (
        SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO, FORTNIGHTENDDATE
        FROM WPSWAGESDETAILS 
        WHERE TOKENNO='04053' --'04053'
        AND COMPANYCODE='NJ0001'
        AND DIVISIONCODE='0002'
--        GROUP BY FORTNIGHTENDDATE
    )
    WHERE RNO <= 
    (
        SELECT CASE WHEN VBASIC > 0 THEN 6 ELSE 1 END FROM
        (
            SELECT SUM(VBASIC)  VBASIC FROM WPSWAGESDETAILS
            WHERE FORTNIGHTENDDATE IN
            (
                SELECT FORTNIGHTENDDATE FROM 
                (
                    SELECT ROW_NUMBER() OVER (ORDER BY FORTNIGHTENDDATE DESC) RNO
                    FROM WPSWAGESDETAILS 
                    WHERE TOKENNO='04053' --'04053'
                    AND COMPANYCODE='NJ0001'
                    AND DIVISIONCODE='0002'
                    GROUP BY FORTNIGHTENDDATE
                )
                WHERE RNO <= 6
            )
            AND TOKENNO='04053' --'04053'
            AND COMPANYCODE='NJ0001'
            AND DIVISIONCODE='0002'
        )
    )
)
        