SELECT * FROM JSWRAPPER


SELECT * FROM GRATUITYENTITLEMENTYEAR
WHERE TOKENNO='04053'


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = 'GRATUITYSETTLEMENT'


SELECT * FROM 


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = ''


SELECT SYS_COLUMNNAME FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_GRATUITYSETTLEMENT'
AND SYS_KEYCOLUMN='Y'


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = ''


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''



GRATUITYSETTLEMENT

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

EXEC PROC_CREATE_GBL_TMP_TABLES(10,0)





EXEC PROC_CREATE_SYSTFMAP('GRATUITYSETTLEMENT','COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO','',20112)

SELECT * FROM SYS_TFMAP WHERE  SYS_TABLE_SEQUENCIER = 20112

EXEC PROC_CREATE_GBL_TMP_TABLES(20112,0)


PRCWPS_GRATUITY_SETTLE_B4SAVE 


SELECT * FROM GRATUITYSETTLEMENT

delete FROM GRATUITYSETTLEMENT


select * from querymaster




SELECT * FROM SYS_PARAMETER
--
WHERE PARAMETER_NAME ='GRATUITY COMPONENTS'

FBASIC_PEICERT,FBASIC,VBASIC,DA,TSA,ADHOC,NS_ALLOW,NS_HRS,ATTENDANCEHOURS


SELECT SUM(FBASIC_PEICERT) FBASIC_PEICERT, SUM(FBASIC) FBASIC
, SUM(VBASIC) VBASIC, SUM(DA) DA, SUM(TSA) TSA, SUM(ADHOC) ADHOC, SUM(NS_ALLOW) NS_ALLOW,
(SUM(FBASIC_PEICERT) +SUM(FBASIC)+ SUM(VBASIC)+SUM(DA)+SUM(TSA)+SUM(ADHOC)+SUM(NS_ALLOW))/
(SUM(NS_HRS) +SUM(ATTENDANCEHOURS))


DROP TABLE GRATUITYCOMPONENTRATE

CREATE TABLE GRATUITYCOMPONENTRATE
(
    COMPANYCODE VARCHAR2(10),
    DIVISIONCODE VARCHAR2(10),
    TOKENNO VARCHAR2(10),
    WORKERSERIAL VARCHAR2(10),
    FORTNIGHTSTARTDATE DATE,
    FORTNIGHTENDDATE DATE,
    TRANSTYPE VARCHAR2(30),
    MODULE VARCHAR2(10),
    FBASIC_PEICERT NUMBER(20,6),
    FBASIC NUMBER(20,6),
    VBASIC NUMBER(20,6),
    DA NUMBER(20,6),
    TSA NUMBER(20,6),
    ADHOC NUMBER(20,6),
    NS_ALLOW NUMBER(20,6),
    NS_HRS NUMBER(20,6),
    ATTENDANCEHOURS NUMBER(20,6)
)


SELECT FN_GET_FORM_QRY_WEB (38, 'COMPANYCODE:NJ0001~DIVISIONCODE:0002~TOKENNO:04053' ) FROM DUAL


SELECT * FROM WPSWAGESDETAILS
WHERE TOKENNO='04053'

SELECT * FROM VW_WPSSECTIONMAST

DELETE FROM GRATUITYCOMPONENTRATE

SELECT * FROM GRATUITYCOMPONENTRATE

   
INSERT INTO GRATUITYCOMPONENTRATE
(
    COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
    TRANSTYPE, MODULE, 
    FBASIC_PEICERT, FBASIC, VBASIC, DA, TSA, ADHOC, NS_ALLOW, NS_HRS, ATTENDANCEHOURS
)

SELECT COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL, 
MIN(FORTNIGHTSTARTDATE) FORTNIGHTSTARTDATE ,MAX(FORTNIGHTENDDATE) FORTNIGHTENDDATE ,
'TOTAL RATE PER HOUR' TRANSTYPE,'WPS' MODULE,
ROUND(SUM(FBASIC_PEICERT)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)),5) FBASIC_PEICERT, 
SUM(FBASIC)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) FBASIC, 
SUM(VBASIC)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) VBASIC, 
SUM(DA)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) DA, 
SUM(TSA)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) TSA, 
SUM(ADHOC)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) ADHOC, 
SUM(NS_ALLOW)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) NS_ALLOW, 
SUM(NS_HRS)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) NS_HRS, 
SUM(ATTENDANCEHOURS)/(SUM(NS_HRS)+SUM(ATTENDANCEHOURS)) ATTENDANCEHOURS
FROM GRATUITYCOMPONENTRATE
GROUP BY COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL