
 SELECT DECODE(NVL(A.TDSCODE,'AA'), 'AA', 'NO','YES') SELECTED, A.ACCODE, B.TDSNATURE, B.PERCENTNEW AS TDSPERCENTAGE,B.PERCENTNEW AS NETPERCENTAGE, A.BILLNO, A.BILLDATE, 
     A.BILLAMOUNT, A.TDSDEDUCTEDON , A.DRCR,A.SREEDUCESSAMT, A.SERVICETAXAMOUNT, A.EDUCESSAMT, A.NETTDSAMT, A.NETAMT, A.TDSAMT,
    A.TRANSACTIONTYPE, A.MANUALAUTO, A.PARTYCODE,
   'GJ0108' as COMPANYCODE, 
   '0001' as DIVISIONCODE, 
   '2020-2021' as YEARCODE, 
   'SWT' as USERNAME, 'A' as OPERATIONMODE , '' as SYSTEMVOUCHERNO, 
    B.TDSCODE, B.ALWAYSDEDUCT, B.LOWERDEDUCTLIMIT, B.YEARLYLIMIT, B.SINGLETRANSACTIONLIMIT,A.CASHFLOWCODE,A.CASHFLOWDESC
 FROM 
 (
  SELECT 'YES' AS SELECTED, A.ACCODE, B.TDSNATURE, A.PERCENTAGE as TDSPERCENTAGE, A.BILLNO, TO_CHAR(A.BILLDATE,'DD/MM/YYYY') BILLDATE,A.BILLAMOUNT, A.TDSDEDUCTEDON ,A.DRCR, 
  A.HSEDUCATIONCESSAMOUNT AS SREEDUCESSAMT, A.SERVICETAXAMOUNT, A.EDUCATIONCESSAMOUNT AS EDUCESSAMT, A.NETTDSAMOUNT AS NETTDSAMT, NETAMOUNT AS NETAMT, TOTALTDSAMOUNT AS TDSAMT, 
  A.TRANSACTIONTYPE, A.MANUALAUTO, A.PARTYCODE, 
         B.TDSCODE, B.ALWAYSDEDUCT, B.LOWERDEDUCTLIMIT, C.YEARLYLIMIT, C.SINGLETRANSACTIONLIMIT,NVL(Z.CASHFLOWCODE,'') CASHFLOWCODE,NVL(Z.CASHFLOWDESC,'') CASHFLOWDESC
   FROM ACTDSDETAILS_ENTRY A, ACTDSLEDGERMASTER B,ACTDSMASTER C,ACCASHFLOWMAST Z 
         WHERE A.COMPANYCODE = B.COMPANYCODE
    AND A.TDSTYPE=B.TDSNATURE
    AND A.ACCODE=B.ACCODE
    AND A.COMPANYCODE=C.COMPANYCODE 
    AND A.TDSTYPE=C.TDSNATURE 
    AND A.COMPANYCODE = Z.COMPANYCODE (+) 
    AND A.CASHFLOWCODE = Z.CASHFLOWCODE (+) 
    AND A.COMPANYCODE ='GJ0108' 
    AND A.SYSTEMVOUCHERNO='' 
    AND B.WITHEFFECTFROM = (SELECT MAX(C.WITHEFFECTFROM) 
                           FROM ACTDSLEDGERMASTER C 
                           WHERE C.COMPANYCODE = 'GJ0108' 
                             AND C.ACCODE = A.ACCODE 
                             AND C.WITHEFFECTFROM <= TO_DATE('31/03/2021','DD/MM/YYYY') 
                          )
    AND C.WITHEFFECTFROM = (SELECT MAX(D.WITHEFFECTFROM)
                            FROM ACTDSMASTER D 
                            WHERE D.COMPANYCODE = 'GJ0108'
                              AND D.TDSNATURE = A.TDSTYPE 
                              AND D.WITHEFFECTFROM <= TO_DATE('31/03/2021','DD/MM/YYYY')
                          )
 ) A,
 (           
  SELECT 'NO' AS SELECTED, A.ACCODE, A.TDSNATURE,A.TDSCODE,A.ALWAYSDEDUCT,A.LOWERDEDUCTLIMIT,
   B.EDUCATIONCESS,B.SREDUCATIONCESS,B.SERVICETAXPERCENT,B.YEARLYLIMIT,B.SINGLETRANSACTIONLIMIT,'' AS TDSDEDUCTEDON, 
  A.PERCENT,A.PERCENTNEW 
   FROM ACTDSLEDGERMASTER A , ACTDSMASTER B
         WHERE A.COMPANYCODE = B.COMPANYCODE
    AND A.TDSNATURE=B.TDSNATURE
    AND A.COMPANYCODE ='GJ0108' 
    AND A.WITHEFFECTFROM = (SELECT MAX(B.WITHEFFECTFROM) 
                           FROM ACTDSLEDGERMASTER B 
                           WHERE B.COMPANYCODE = 'GJ0108' 
                             AND B.ACCODE = A.ACCODE 
                             AND B.WITHEFFECTFROM <= TO_DATE('31/03/2021','DD/MM/YYYY') 
                          )
    AND B.WITHEFFECTFROM = (SELECT MAX(C.WITHEFFECTFROM)
                            FROM ACTDSMASTER C 
                            WHERE C.COMPANYCODE = 'GJ0108'
                              AND C.TDSNATURE = A.TDSNATURE 
                              AND C.WITHEFFECTFROM <= TO_DATE('31/03/2021','DD/MM/YYYY')
                          )
  AND A.ACCODE='A000368'  
 ) B
 WHERE A.TDSCODE(+)=B.TDSCODE
 
 
 GBL_
 
 ACVOUCHERDETAILS_PYMT
 
 
 
 DELETE FROM SYS_TFMAP
 WHERE SYS_TABLE_SEQUENCIER = '9025'
 
 SELECT * FROM SYS_TFMAP
 WHERE SYS_TABLENAME_ACTUAL = 'ACVOUCHER_PYMT'
 
 
 SELECT * FROM SYS_TFMAP
 WHERE SYS_TABLENAME_TEMP = ''
 