
DROP TABLE GBL_UNREALIZEDCOMPAMT CASCADE CONSTRAINTS;

CREATE TABLE GBL_UNREALIZEDCOMPAMT
(
  WORKERSERIAL         VARCHAR2(10 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  INSURANCEAPPLICABLE  VARCHAR2(1 BYTE),
  COMPONENT_AMT             NUMBER(11,2),
  COMPONENT_UNREALIZED      NUMBER(11,2),
  TOTAL_COMPONENT_EMI       NUMBER(11,2),
  MODULE               VARCHAR2(10 BYTE)
)



SELECT * FROM PISUNREALIZEDDATA

CREATE TABLE PISWPSUNREALIZEDDATA AS SELECT * FROM PISUNREALIZEDDATA WHERE 1=2 

CREATE TABLE BIRLA_PIS_UNREALIZEDDATA (
EMP_CD    VARCHAR2(10),
EMP_NAME  VARCHAR2(100),  
UNREALSL_EARN_AMT NUMBER(11,2)
)

ALTER TABLE PISWPSUNREALIZEDDATA MODIFY COLUMN YEARMONTH TO

INSERT INTO PISWPSUNREALIZEDDATA (
COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
WORKERSERIAL, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, ACTUALAMOUNT, REFERENCE_FNEDATE, 
TRANTYPE, MODULE, REMARKS, USERNAME, SYSROSWID, LASTMODIFIED )

SELECT A.COMPANYCODE, A.DIVISIONCODE, '2020-2021' YEARCODE, '202010' YEARMONTH, '01-OCT-2020' FORTNIGHTSTARTDATE, '31-OCT-2020' FORTNIGHTENDDATE, 
A.WORKERSERIAL, A.TOKENNO, 'RECREATION' COMPONENTCODE, B.UNREALSL_EARN_AMT COMPONENTAMOUNT, B.UNREALSL_EARN_AMT ACTUALAMOUNT, '31-OCT-2020' REFERENCE_FNEDATE, 
'UNREALIZED' TRANTYPE, 'PIS' MODULE, 'DATA MIGRATE' REMARKS, 'SWT' USERNAME, FN_GENERATE_SYSROWID SYSROSWID, SYSDATE LASTMODIFIED 
FROM PISEMPLOYEEMASTER A, BIRLA_PIS_UNREALIZEDDATA B
WHERE A.TOKENNO=B.EMP_CD

SELECT EMP_CD FROM BIRLA_PIS_UNREALIZEDDATA
MINUS
SELECT TOKENNO FROM PISEMPLOYEEMASTER

SELECT * FROM PISEMPLOYEEMASTER WHERE EMPLOYEENAME LIKE '%PANDEY%';

SELECT * FROM PISEMPLOYEEMASTER WHERE TOKENNO LIKE '%952'


INSERT INTO GBL_UNREALIZEDCOMPAMT 
(
    WORKERSERIAL, TOKENNO, COMPONENT_AMT, COMPONENT_UNREALIZED, 
    TOTAL_COMPONENT_EMI, MODULE
)
SELECT A.WORKERSERIAL,B.TOKENNO, SUM(COMPONENTAMOUNT) COMPONENT_AMT, SUM(COMPONENTAMOUNT) UNREALIZEDAMOUNT,
SUM(COMPONENTAMOUNT) TOTAL_COMPONENT_EMI, 'PIS' MODULE 
FROM PISWPSUNREALIZEDDATA A, PISEMPLOYEEMASTER B
WHERE A.WORKERSERIAL=B.WORKERSERIAL 
  AND A.YEARMONTH < '202011'
GROUP BY A.WORKERSERIAL,B.TOKENNO 

SELECT * FROM GBL_UNREALIZEDCOMPAMT

SELECT * FROM PISWPSUNREALIZEDDATA

SELECT WORKERSERIAL, SUM(COMPONENTAMOUNT) UNREALIZEDAMOUNT 
FROM PISWPSUNREALIZEDDATA
WHERE YEARMONTH < '202011'
GROUP BY WORKERSERIAL


SELECT * FROM PISCOMPONENTMASTER


ALTER TABLE PISCOMPONENTMASTER ADD ISUNREALIZED VARCHAR2(1 BYTE) DEFAULT 'N'


UPDATE PISCOMPONENTMASTER SET ISUNREALIZED='Y'
WHERE COMPONENTCODE IN
(
    'CAR',
    'CHOWKIDARI',
    'CLUB',
    'DAIRY',
    'ELECTRIC',
    'FURNITURE',
    'RECREATION',
    'SCHOOL_BUS',
    'SUBSCRIPTION'
)

SELECT WM_CONCAT(COMPONENTCODE) FROM PISCOMPONENTMASTER
WHERE ISUNREALIZED = 'Y'

SELECT * FROM PISASSIGN

SELECT * FROM COLS
WHERE TABLE_NAME='PISASSIGN'
AND COLUMN_NAME IN 
(
    'CAR',
    'CHOWKIDARI',
    'CLUB',
    'DAIRY',
    'ELECTRIC',
    'FURNITURE',
    'RECREATION',
    'SCHOOL_BUS',
    'SUBSCRIPTION'
)


SELECT * FROM COLS
WHERE TABLE_NAME='PISATTN'
AND COLUMN_NAME IN 
(
    'CAR',
    'CHOWKIDARI',
    'CLUB',
    'DAIRY',
    'ELECTRIC',
    'FURNITURE',
    'RECREATION',
    'SCHOOL_BUS',
    'SUBSCRIPTION'
)

'CAR', --ATTN
--'CHOWKIDARI',
'CLUB',
'DAIRY', --ATTN
'ELECTRIC', --ATTN
--'FURNITURE',
'RECREATION', --ATTN
--'SCHOOL_BUS',
'SUBSCRIPTION' --ATTN




SELECT WM_CONCAT(COLUMN_NAME) FROM COLS
WHERE TABLE_NAME='PISATTN'
AND COLUMN_NAME IN 
(
    'CAR',
    'CHOWKIDARI',
    'CLUB',
    'DAIRY',
    'ELECTRIC',
    'FURNITURE',
    'RECREATION',
    'SCHOOL_BUS',
    'SUBSCRIPTION'
)



SELECT WM_CONCAT(COLUMN_NAME) FROM COLS
WHERE TABLE_NAME='PISASSIGN'
AND COLUMN_NAME IN 
(
    'CAR',
    'CHOWKIDARI',
    'CLUB',
    'DAIRY',
    'ELECTRIC',
    'FURNITURE',
    'RECREATION',
    'SCHOOL_BUS',
    'SUBSCRIPTION'
)


SELECT --COMPONENTCODE, USERENTRYAPPLICABLE, ATTENDANCEENTRYAPPLICABLE, ROLLOVERAPPLICABLE
WM_CONCAT(CASE WHEN  ROLLOVERAPPLICABLE='Y' THEN 'PISASSIGN.'||COMPONENTCODE WHEN ATTENDANCEENTRYAPPLICABLE='Y' THEN 'PISATTN.'||COMPONENTCODE ELSE 'PISCOMP.'||COMPONENTCODE END) X,
WM_CONCAT('NVL('||COMPONENTCODE||',0)'||COMPONENTCODE) Y 
FROM PISCOMPONENTMASTER
WHERE ISUNREALIZED='Y'


SELECT WORKRESERIAL, SUM(
SELECT A.WORKERSERIAL,PISATTN.ELECTRIC,PISATTN.CAR,PISASSIGN.CHOWKIDARI,PISASSIGN.FURNITURE,PISCOMP.CLUB,PISATTN.RECREATION,PISASSIGN.SCHOOL_BUS,PISATTN.DAIRY,PISATTN.SUBSCRIPTION
FROM PISEMPLOYEEMASTER A, PISASSIGN, PISATTN, PISCOMP 
WHERE A.COMPANYCODE ='BJ0056' AND A.DIVISIONCODE ='0001'
  AND A.WORKERSERIAL =PISASSIGN.WORKERSERIAL
  AND A.WORKERSERIAL =  PISATTN.WORKERSERIAL (+)
  AND A.WORKERSERIAL =  PISCOMP.WORKERSERIAL (+)
UNION ALL
SELECT WORKERSERIAL, -NVL(ELECTRIC,0)ELECTRIC,-NVL(CAR,0)CAR,-NVL(CHOWKIDARI,0)CHOWKIDARI,-NVL(FURNITURE,0)FURNITURE,-NVL(CLUB,0)CLUB,-NVL(RECREATION,0)RECREATION,-NVL(SCHOOL_BUS,0)SCHOOL_BUS,-NVL(DAIRY,0)DAIRY,-NVL(SUBSCRIPTION,0)SUBSCRIPTION
FROM PISPAYTRANSACTION WHERE COMPANYCODE ='BJ0056' AND DIVISIONCODE ='0001'
AND YEARMONTH='202009'

SELECT '0001' WORKERSERIAL, 100 ELEC, 50 CLUB FROM DUAL
MINUS
SELECT '0001' WORKERSERIAL, 100 ELEC, 25 CLUB FROM DUAL



SELECT A.WORKERSERIAL,ELECTRIC,CAR,CHOWKIDARI,FURNITURE,CLUB,RECREATION,SCHOOL_BUS,DAIRY,SUBSCRIPTION
FROM
(
SELECT WORKERSERIAL,CHOWKIDARI,FURNITURE,SCHOOL_BUS FROM PISASSIGN
) A,
(
SELECT WORKERSERIAL,RECREATION,SUBSCRIPTION,CAR,DAIRY,ELECTRIC FROM PISATTN
) B
WHERE A.WORKERSERIAL=B.WORKERSERIAL


SELECT A.WORKERSERIAL,ELECTRIC,CAR,CHOWKIDARI,FURNITURE,0 CLUB,RECREATION,SCHOOL_BUS,DAIRY,SUBSCRIPTION
FROM
(
    SELECT WORKERSERIAL,CHOWKIDARI,FURNITURE,SCHOOL_BUS FROM PISASSIGN
) A,
(
    SELECT WORKERSERIAL,RECREATION,SUBSCRIPTION,CAR,DAIRY,ELECTRIC FROM PISATTN
) B
WHERE A.WORKERSERIAL=B.WORKERSERIAL
AND A.WORKERSERIAL='000082'



SELECT * FROM PISPAYTRANSACTION
WHERE CLUB > 0







SELECT WORKERSERIAL, COMPONENTCODE, COMPONENTAMOUNT 
FROM (
    SELECT * FROM 
    (
        SELECT  WORKERSERIAL,SUM(ELECTRIC) ELECTRIC,SUM(CAR) CAR,SUM(CHOWKIDARI) CHOWKIDARI,
        SUM(FURNITURE) FURNITURE,SUM(CLUB)  CLUB,SUM(RECREATION) RECREATION,SUM(SCHOOL_BUS) SCHOOL_BUS,
        SUM(DAIRY) DAIRY,SUM(SUBSCRIPTION) SUBSCRIPTION
        FROM 
        (
            SELECT A.WORKERSERIAL,ELECTRIC,CAR,CHOWKIDARI,FURNITURE,0 CLUB,RECREATION,SCHOOL_BUS,DAIRY,SUBSCRIPTION
            FROM
            (
                SELECT WORKERSERIAL,CHOWKIDARI,FURNITURE,SCHOOL_BUS FROM PISASSIGN
            ) A,
            (
                SELECT WORKERSERIAL,RECREATION,SUBSCRIPTION,CAR,DAIRY,ELECTRIC FROM PISATTN
            ) B
            WHERE A.WORKERSERIAL=B.WORKERSERIAL
            AND A.WORKERSERIAL='000082'
            UNION ALL
            SELECT A.WORKERSERIAL,ELECTRIC*(-1),CAR,CHOWKIDARI*(-1),FURNITURE*(-1),0 CLUB,RECREATION*(-1),SCHOOL_BUS*(-1),DAIRY*(-1),SUBSCRIPTION*(-1)
            FROM
            (
                SELECT WORKERSERIAL,CHOWKIDARI,FURNITURE,SCHOOL_BUS FROM PISASSIGN
            ) A,
            (
                SELECT WORKERSERIAL,RECREATION,SUBSCRIPTION,CAR,DAIRY,ELECTRIC FROM PISATTN
            ) B
            WHERE A.WORKERSERIAL=B.WORKERSERIAL
            AND A.WORKERSERIAL='000082'
        )
        GROUP BY WORKERSERIAL
    ) A
    UNPIVOT(
        COMPONENTAMOUNT  -- unpivot_clause
        FOR COMPONENTCODE --  unpivot_for_clause
        IN ( -- unpivot_in_clause
            CAR AS 'CAR',
            CHOWKIDARI AS 'CHOWKIDARI',
            CLUB AS 'CLUB',
            DAIRY AS 'DAIRY',
            ELECTRIC AS 'ELECTRIC',
            FURNITURE AS 'FURNITURE',
            RECREATION AS 'RECREATION',
            SCHOOL_BUS AS 'SCHOOL_BUS',
            SUBSCRIPTION AS 'SUBSCRIPTION'
        )
    )
)
WHERE COMPONENTAMOUNT > 0;
