SELECT * FROM PISWPSUNREALIZEDDATA


SELECT A.COMPANYCODE, A.DIVISIONCODE, '2020-2021' YEARCODE, '202010' YEARMONTH, '01-OCT-2020' FORTNIGHTSTARTDATE, '31-OCT-2020' FORTNIGHTENDDATE, 
A.WORKERSERIAL, A.TOKENNO,COMPONENTCODE, B.COMPONENTAMOUNT COMPONENTAMOUNT, B.COMPONENTAMOUNT ACTUALAMOUNT, '31-OCT-2020' REFERENCE_FNEDATE, 
'UNREALIZED' TRANTYPE, 'PIS' MODULE, 'DATA MIGRATE' REMARKS, 'SWT' USERNAME, FN_GENERATE_SYSROWID SYSROSWID, SYSDATE LASTMODIFIED 
FROM PISEMPLOYEEMASTER A, 
(
    SELECT WORKERSERIAL, COMPONENTCODE, COMPONENTAMOUNT 
    FROM (
        SELECT * FROM 
        (
            SELECT  WORKERSERIAL,SUM(ELECTRIC) ELECTRIC,SUM(CAR) CAR,SUM(CHOWKIDARI) CHOWKIDARI,
            SUM(FURNITURE) FURNITURE,SUM(CLUB)  CLUB,SUM(RECREATION) RECREATION,SUM(SCHOOL_BUS) SCHOOL_BUS,
            SUM(DAIRY) DAIRY,SUM(SUBSCRIPTION) SUBSCRIPTION
            FROM 
            (
                SELECT A.WORKERSERIAL,ELECTRIC,CAR,CHOWKIDARI,FURNITURE,0 CLUB,RECREATION,SCHOOL_BUS,DAIRY,SUBSCRIPTION
                FROM
                (
                    SELECT WORKERSERIAL,CHOWKIDARI,FURNITURE,SCHOOL_BUS FROM PISASSIGN
                ) A,
                (
                    SELECT WORKERSERIAL,RECREATION,SUBSCRIPTION,CAR,DAIRY,ELECTRIC FROM PISATTN
                ) B
                WHERE A.WORKERSERIAL=B.WORKERSERIAL
--                AND A.WORKERSERIAL='000082'
                UNION ALL
                SELECT A.WORKERSERIAL,ELECTRIC*(-1),CAR,CHOWKIDARI*(-1),FURNITURE*(-1),0 CLUB,RECREATION*(-1),SCHOOL_BUS*(-1),DAIRY*(-1),SUBSCRIPTION*(-1)
                FROM PISPAYTRANSACTION A
                WHERE A.YEARMONTH='202009'
--                AND A.WORKERSERIAL='000082'
            )
            GROUP BY WORKERSERIAL
        ) A
        UNPIVOT(
            COMPONENTAMOUNT  -- unpivot_clause
            FOR COMPONENTCODE --  unpivot_for_clause
            IN ( -- unpivot_in_clause
                CAR AS 'CAR',
                CHOWKIDARI AS 'CHOWKIDARI',
                CLUB AS 'CLUB',
                DAIRY AS 'DAIRY',
                ELECTRIC AS 'ELECTRIC',
                FURNITURE AS 'FURNITURE',
                RECREATION AS 'RECREATION',
                SCHOOL_BUS AS 'SCHOOL_BUS',
                SUBSCRIPTION AS 'SUBSCRIPTION'
            )
        )
    )
    WHERE COMPONENTAMOUNT > 0
) B
WHERE A.WORKERSERIAL=B.WORKERSERIAL