PROC_RPT_REIMBURSEMENT_REG_EXL	


SELECT * FROM PISCOMPONENTMASTER
WHERE ALLOWREIMBURSEMENT='Y'


UPDATE PISCOMPONENTMASTER SET PRINTSERIAL = NULL WHERE ALLOWREIMBURSEMENT='Y'

SELECT * FROM PISPAYTRANSACTION WHERE TOKENNO='C7002'

SELECT * FROM PISREIMBURSEMENTDETAILS

SELECT * FROM PISREIMBURSEMENT_ENTITLE

----------------------------------------------------------------------


EXEC PROC_RPT_REIMBURSEMENT_REG_EXL('0001','001','2020-2021','APR-20','AUG-20','''001''','''02''','','','')


PROC_RPT_REIMBURSEMENT_REG_EXL('COMPANYCODE','DIVISIONCODE','YEARCODE','ddlYEARMONTHSHOW','ddlYEARMONTHSHOW2','btnUnit','btnCategory','btnGrade','btnEmployee','btnCOLUMNS')





SELECT * FROM VW_REIMBURSEMENT_REG

-----------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_REIMBURSEMENT_REG AS

SELECT TO_CHAR(TO_DATE(A.YEARMONTH,'YYYYMM'),'MON-YYYY')MON_YYYY, A.YEARMONTH,E.UNITCODE, E.TOKENNO, E.EMPLOYEENAME, E.GRADECODE, E.CATEGORYCODE,BASIC,SOFT_ALLW,SERV_ALLW,CONV_ALLW,CHILD_ALLW,PERS_ALLW,HRA,OTH_ALLW,INCENTIVE,FIX_ALW,OTH_ALLW2,SARR_ARRE,FSTL_EARN,LTA,MEDICAL,FIX_CONV,LOCAL_CONV,TELEPHONE,BONUS,OTHER_REIM,EXGRATIA,ESI_E,PF_E,PTAX,ITAX,CANTEEN,TOTLOANAMT,TOTLOANINT,SAL_SAVING,SARR_ARRD,FSTL_DED FROM 
(
    SELECT TOKENNO,YEARMONTH,SUM(BASIC) BASIC,SUM(SOFT_ALLW) SOFT_ALLW,SUM(SERV_ALLW) SERV_ALLW,SUM(CONV_ALLW) CONV_ALLW,SUM(CHILD_ALLW) CHILD_ALLW,SUM(PERS_ALLW) PERS_ALLW,SUM(HRA) HRA,SUM(OTH_ALLW) OTH_ALLW,SUM(INCENTIVE) INCENTIVE,SUM(FIX_ALW) FIX_ALW,SUM(OTH_ALLW2) OTH_ALLW2,SUM(SARR_ARRE) SARR_ARRE,SUM(FSTL_EARN) FSTL_EARN
    FROM PISPAYTRANSACTION
    WHERE COMPANYCODE='0001'
    AND DIVISIONCODE='001'
    AND TO_NUMBER(YEARMONTH) BETWEEN 202004 AND 202008
    GROUP BY TOKENNO,YEARMONTH
) A,
(
    SELECT * FROM 
    (
        ( 
            SELECT TOKENNO, COMPONENTCODE, PAIDAMOUNT, YEARMONTH
            FROM PISREIMBURSEMENTDETAILS
        )
        PIVOT(
            SUM(PAIDAMOUNT)
            FOR COMPONENTCODE
            IN ( 
                'LTA' AS LTA,'MEDICAL' AS MEDICAL,'FIX_CONV' AS FIX_CONV,'LOCAL_CONV' AS LOCAL_CONV,'TELEPHONE' AS TELEPHONE,'BONUS' AS BONUS,'OTHER_REIM' AS OTHER_REIM,'EXGRATIA' AS EXGRATIA
            )
        )
    )
) B,
(
    SELECT TOKENNO,YEARMONTH,SUM(ESI_E) ESI_E,SUM(PF_E) PF_E,SUM(PTAX) PTAX,SUM(ITAX) ITAX,SUM(CANTEEN) CANTEEN,SUM(TOTLOANAMT) TOTLOANAMT,SUM(TOTLOANINT) TOTLOANINT,SUM(SAL_SAVING) SAL_SAVING,SUM(SARR_ARRD) SARR_ARRD,SUM(FSTL_DED) FSTL_DED
    FROM PISPAYTRANSACTION
    WHERE COMPANYCODE='0001'
    AND DIVISIONCODE='001'
    AND TO_NUMBER(YEARMONTH) BETWEEN 202004 AND 202008
    GROUP BY TOKENNO,YEARMONTH
) C,
(
    SELECT * FROM PISEMPLOYEEMASTER
    WHERE COMPANYCODE='0001'
    AND DIVISIONCODE='001'
) E
WHERE A.TOKENNO=B.TOKENNO(+)
AND A.TOKENNO=C.TOKENNO(+)
AND A.YEARMONTH=B.YEARMONTH(+)
AND A.YEARMONTH=C.YEARMONTH(+)
AND A.TOKENNO=E.TOKENNO


-----------------------------------------------------------------------------