
SELECT COMPANYCODE,DIVISIONCODE,DATEOFJOINING, TOKENNO,EMPLOYEENAME, NVL(CARRYFORWARD,0) CARRYFORWARD , ENTITLEMENT PREVIOUSENTITLEMENT, (NVL(CARRYFORWARD,0) +  ENTITLEMENT) ENTITLEMENTS,LEAVECODE,WORKERSERIAL,CATEGORYCODE,CALENDARYEAR,YEARCODE 
FROM
(
    SELECT TO_CHAR(B.DATEOFJOINING,'DD/MM/YYYY') DATEOFJOINING, B.TOKENNO, B.EMPLOYEENAME, A.LEAVEBAL, B.COMPANYCODE, B.DIVISIONCODE, 
    C.MAXCARRYFORWARDLIMIT,C.CARRYFORWARDUPTO,C.ENTITLEMENT MAXENTITLEMENT,B.WORKERSERIAL,B.CATEGORYCODE,
    (SELECT 'ALS' FROM DUAL)  LEAVECODE, 
    (SELECT '2021' FROM DUAL) CALENDARYEAR,(SELECT '2020-2021' FROM DUAL) YEARCODE,
    CASE WHEN A.LEAVEBAL = C.MAXCARRYFORWARDLIMIT THEN C.MAXCARRYFORWARDLIMIT 
    ELSE 
        CASE WHEN A.LEAVEBAL <  C.MAXCARRYFORWARDLIMIT THEN
            CASE WHEN A.LEAVEBAL < C.CARRYFORWARDUPTO THEN A.LEAVEBAL 
                ELSE C.CARRYFORWARDUPTO 
            END
        END
    END
    CARRYFORWARD ,
     CASE WHEN C.CARRYFORWARDUPTO = 0 AND C.MAXCARRYFORWARDLIMIT = 0 THEN C.ENTITLEMENT 
    ELSE
        CASE WHEN A.LEAVEBAL = C.MAXCARRYFORWARDLIMIT AND C.MAXCARRYFORWARDLIMIT <> 0 THEN 0 ELSE C.ENTITLEMENT END
    END     ENTITLEMENT    
    FROM 
    (
        SELECT TOKENNO, SUM(BAL) LEAVEBAL 
        FROM 
        (
            SELECT TOKENNO, -SUM(HAZIRA) BAL  FROM GPSATTENDANCEDETAILS
            WHERE OCCUPATIONCODE='ALS'
            AND TO_CHAR(ATTENDANCEDATE,'YYYY') =  '2020'
            AND COMPANYCODE='JT0069'
            AND DIVISIONCODE='0006'
            AND CATEGORYCODE='SUP'
            GROUP BY TOKENNO
            UNION ALL
            SELECT TOKENNO, SUM(NVL(ENTITLEMENTS,0)+NVL(CARRYFORWARD,0)) BAL 
            FROM GPSLEAVEENTITLEMENT
            WHERE LEAVECODE='ALS'
            AND COMPANYCODE='JT0069'
            AND DIVISIONCODE='0006'
            AND CATEGORYCODE='SUP'
            AND CALENDARYEAR='2020'
            GROUP BY TOKENNO
        )
        GROUP BY TOKENNO
    ) A, GPSEMPLOYEEMAST B, GPSLEAVEPARAMS C
    WHERE B.TOKENNO=A.TOKENNO(+)
    AND B.CATEGORYCODE=C.CATEGORYCODE
    AND B.COMPANYCODE=C.COMPANYCODE
    AND B.DIVISIONCODE=C.DIVISIONCODE
    AND B.COMPANYCODE='JT0069'
    AND B.DIVISIONCODE='0006'
    AND C.LEAVECODE='ALS'
    AND C.CALENDARYEAR='2021'
    AND B.CATEGORYCODE='SUP'
)
ORDER BY TOKENNO;


SELECT * FROM GPSLEAVEPARAMS C
WHERE LEAVECODE='ALS'
AND CATEGORYCODE='SUP'