SELECT * FROM LOGIN


SELECT * FROM TAB
WHERE TNAME LIKE '%ITAX%'

SELECT * FROM PISITAXPARAM
WHERE COLUMNSUBHEADING1 LIKE '%MEDICAL%'
AND YEARCODE='2020-2021'

SELECT * FROM PISITAXPARAM
WHERE COLUMNSOURCE LIKE 'PISREIMBURSEMENTDETAILS'
AND YEARCODE='2020-2021'


SELECT * FROM PISITAXPARAM
WHERE COLUMNSUBHEADING1 LIKE '%LTA%'


SELECT * FROM PISREIMBURSEMENTDETAILS
WHERE TOKENNO='00090'