SELECT  * FROM  WPSWORKERMAST
WHERE COMPANYCODE IS NOT  NULL
AND WORKERCATEGORYCODE IS NULL



AND OCCUPATIONCODE IS NULL




SELECT * FROM WPSMACHINEMASTER



SELECT * FROM WPSMACHINEGROUPMASTER



WPSMACHINEGROUPMAST





insert into MACHINEMASTER (
COMPANYCODE, DIVISIONCODE, PRODUCTIONTYPE, DEPARTMENTCODE, MACHINECODE, MACHINENAME, LOOMYESNO, PARTNERLOOMCODE, PAIRLOOMCODE, 
MACHINETYPECODE, MACHINEGROUP, ACTUALRPM, MACHINEREEDSPACE, MAXWIDTH, DIVISIONFACTOR, MODULE, LASTMODIFIED, SYSROWID, USERNAME, 
PIC_A, PIC_B, PIC_C, ROLLYESNO)


COMPANYCODE, DIVISIONCODE, DEPARTMENTCODE, MACHINECODE, MACHINENAME, PARTNERLOOMCODE, LASTMODIFIEDDATE, LOOMYESNO, PAIRLOOM, MACHINEREEDSPACE, ISDEFAULTMACHINE

select COMPANYCODE, DIVISIONCODE, 'P0003' PRODUCTIONTYPE, DEPARTMENTCODE, MACHINECODE, MACHINENAME, LOOMYESNO, PARTNERLOOMCODE,NULL PAIRLOOMCODE, 
NULL MACHINETYPECODE, 'H' MACHINEGROUP, NULL ACTUALRPM, MACHINEREEDSPACE,NULL MAXWIDTH,NULL DIVISIONFACTOR, 'WPS' MODULE, 
SYSDATE LASTMODIFIED, SYS_GUID() SYSROWID, 'SWT' USERNAME, 
0 PIC_A, 0 PIC_B, 0 PIC_C, 'N' ROLLYESNO
from WPSMACHINEMASTER



INSERT INTO QUALITYMASTER (
COMPANYCODE, DIVISIONCODE, PRODUCTIONTYPE, QUALITYCODE, QUALITYNAME, QUALITYTYPECODE, QUALITYUOMCODE, QUALITYUOMCODE2, 
QUALITYUOMDESC, QUALITYUOMDESC2, CONVERSIONFACTOR, FINISHTYPE, PORTER, SHOTS, ACTUALSHOTS, SHORTNAME, 
OZ, BASEOZ, OZTYPE, WIDTH, FINISHEDLENGTH, LAIDLENGTH, SPEED, CHATTAK, YARDPRECUT, SELVEDGE, WARPMARK, 
WARPGRIST, WEFTMARK, WEFTGRIST, WEIGHTSPECIFICATION, TARGETPRODUCTION, TARGETEFFICIENCYPERCENT, ISTIMERATEQUALITY, GSM, 
MAXWIDTH, ACTPICMETER, LASTMODIFIED, USERNAME, SYSROWID, MODULE, RATE, DEPARTMENTCODE)

SELECT A.COMPANYCODE, A.DIVISIONCODE, A.PRODUCTIONTYPE, A.QUALITYCODE, A.QUALITYNAME, A.QUALITYTYPECODE, A.QUALITYUOMCODE, A.QUALITYUOMCODE2, 
A.QUALITYUOMDESC, QUALITYUOMDESC2, CONVERSIONFACTOR, FINISHTYPE, PORTER, SHOTS, ACTUALSHOTS, SHORTNAME, 
OZ,NULL BASEOZ,NULL OZTYPE, WIDTH,NULL FINISHEDLENGTH,NULL LAIDLENGTH,NULL SPEED,NULL CHATTAK,NULL YARDPRECUT,NULL SELVEDGE,NULL WARPMARK, NULL WARPGRIST,
NULL WEFTMARK,NULL WEFTGRIST, WEIGHTSPECIFICATION,NULL TARGETPRODUCTION,NULL TARGETEFFICIENCYPERCENT, ISTIMERATEQUALITY,NULL GSM, 
NULL MAXWIDTH,0 ACTPICMETER, SYSDATE LASTMODIFIED, 'SWT' USERNAME, SYS_GUID() SYSROWID, 'WPS' MODULE, 0 RATE, B.DEPARTMENTCODE
FROM WPSQUALITYMASTER A, WPSPRODUCTIONTYPEMAST B
WHERE A.PRODUCTIONTYPE = B.PRODUCTIONTYPECODE

SELECT * FROM WPSQUALITYMASTER

