DROP TABLE NJMCL_WEB.GRATUITYCOMPONENTRATE CASCADE CONSTRAINTS;

CREATE TABLE NJMCL_WEB.GRATUITYCOMPONENTRATE
(
  COMPANYCODE         VARCHAR2(10 BYTE),
  DIVISIONCODE        VARCHAR2(10 BYTE),
  TOKENNO             VARCHAR2(10 BYTE),
  WORKERSERIAL        VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE  DATE,
  FORTNIGHTENDDATE    DATE,
  TRANSTYPE           VARCHAR2(30 BYTE),
  MODULE              VARCHAR2(10 BYTE),
  FBASIC_PEICERT      NUMBER(20,6),
  FBASIC              NUMBER(20,6),
  VBASIC              NUMBER(20,6),
  DA                  NUMBER(20,6),
  TSA                 NUMBER(20,6),
  ADHOC               NUMBER(20,6),
  NS_ALLOW            NUMBER(20,6),
  NS_HRS              NUMBER(20,6),
  ATTENDANCEHOURS     NUMBER(20,6),
  TOTAL_AMT           NUMBER(20,6),
  TOTAL_HRS           NUMBER(20,6),
  USERNAME            VARCHAR2(30 BYTE),
  LASTMODIFIED        DATE DEFAULT SYSDATE,
  SYSROWID           VARCHAR2(50 BYTE)
)


EXEC PROC_CREATE_SYSTFMAP('GRATUITYCOMPONENTRATE','COMPANYCODE,DIVISIONCODE,TOKENNO,WORKERSERIAL,FORTNIGHTENDDATE,TRANSTYPE','','20126')

SELECT * FROM SYS_TFMAP WHERE  SYS_TABLE_SEQUENCIER = 20126

EXEC PROC_CREATE_GBL_TMP_TABLES(20126,0)


 P_TABLE_NAME VARCHAR2,
    P_SYS_COLUMNNAMES     VARCHAR2 DEFAULT NULL,
    P_GBL_TABLE_NAME VARCHAR2 DEFAULT NULL,
    P_SEQUENCE  NUMBER DEFAULT NULL
    
    
           
          
                