

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%GRATUITY%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0110023002'


SELECT * FROM ROLEDETAILS
WHERE MENUCODE='0110023002'


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL='GRATUITYSETTLEMENT'
and     SYS_KEYCOLUMN='Y'




Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, 
    SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, 
    SYS_TIMESTAMP, SYS_USEMAP, IS_EDITABLE, ISCONVERT_TOUPPER)
 Values
   (20112, 'GRATUITYSETTLEMENT', 'GBL_GRATUITYSETTLEMENT', 'ISFINALIZE', 4, 
    'VARCHAR2', 1, 0, 'N', 'txtISFINALIZE', 
    TO_TIMESTAMP('19/11/2020 1:20:16.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', 'Y', 'Y');
COMMIT;


EXEC PROC_CREATE_GBL_TMP_TABLES(20126,0)

SELECT * FROM GRATUITYSETTLEMENT



DELETE FROM GRATUITYSETTLEMENT


SELECT G.TOKENNO||'~'|| GRATUITYSETTLEMENTNO||'~'|| GRATUITYAMOUNT||'~'|| OTHEREARNING||'~'||LOANCAPITALBAL
||'~'|| LOANINTERESTBAL||'~'|| OTHERDEDUCTION||'~'|| NETPAYABLE||'~'||to_CHAR(SETTLEMENTDATE,'DD/MM/YYYY')||'~'||
to_CHAR(GRATUITYENTDATE,'DD/MM/YYYY')||'~'||TO_CHAR(DETACHMENTDATE,'DD/MM/YYYY')||'~'|| CHEQUENO||'~'||
TO_CHAR(CHEQUEDATE,'DD/MM/YYYY')||'~'|| G.BANKCODE||'~'|| G.REMARKS||'~'|| AUTHORISEDBY||'~'|| G.DESIGNATION||'~'|| 
GRATUITYYEAR||'~'||BANKNAME||'~'||WORKERNAME||'~'||SAL_15DAYS||'~'||ISFINALIZE 
FROM GRATUITYSETTLEMENT G,WPSWORKERMAST W ,(select distinct COMPANYCODE,DIVISIONCODE, BANKCODE, BANKNAME from SALESBANKMASTER) S
WHERE 1=1
AND G.COMPANYCODE=S.COMPANYCODE(+) 
AND G.DIVISIONCODE=S.DIVISIONCODE(+) 
AND G.BANKCODE=S.BANKCODE(+) 
AND  G.COMPANYCODE=W.COMPANYCODE 
AND G.DIVISIONCODE=W.DIVISIONCODE 
AND G.WORKERSERIAL=W.WORKERSERIAL 
AND G.COMPANYCODE = 'NJ0001' 
AND G.DIVISIONCODE = '0002' 
AND G.TOKENNO = '04053' 

select distinct BANKCODE, BANKNAME from SALESBANKMASTER


SELECT G.TOKENNO||'~'|| GRATUITYSETTLEMENTNO||'~'|| GRATUITYAMOUNT||'~'|| OTHEREARNING||'~'||LOANCAPITALBAL||'~'|| LOANINTERESTBAL||'~'|| OTHERDEDUCTION||'~'|| NETPAYABLE||'~'||to_CHAR(SETTLEMENTDATE,'DD/MM/YYYY')||'~'||to_CHAR(GRATUITYENTDATE,'DD/MM/YYYY')||'~'||TO_CHAR(DETACHMENTDATE,'DD/MM/YYYY')||'~'|| CHEQUENO||'~'||TO_CHAR(CHEQUEDATE,'DD/MM/YYYY')||'~'|| G.BANKCODE||'~'|| G.REMARKS||'~'|| AUTHORISEDBY||'~'|| G.DESIGNATION||'~'|| GRATUITYYEAR||'~'||BANKNAME||'~'||WORKERNAME||'~'||SAL_15DAYS||'~'||ISFINALIZE||'~'||G.WORKERSERIAL FROM GRATUITYSETTLEMENT G,(select distinct COMPANYCODE,DIVISIONCODE, BANKCODE, BANKNAME from SALESBANKMASTER) S,WPSWORKERMAST W WHERE G.COMPANYCODE=S.COMPANYCODE(+) AND G.DIVISIONCODE=S.DIVISIONCODE(+) AND G.BANKCODE=S.BANKCODE(+) AND  G.COMPANYCODE=W.COMPANYCODE AND G.DIVISIONCODE=W.DIVISIONCODE AND G.WORKERSERIAL=W.WORKERSERIAL AND G.COMPANYCODE = 'NJ0001' AND G.DIVISIONCODE = '0002' AND G.TOKENNO = '04053' 




SELECT COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL, 
TO_CHAR(FORTNIGHTSTARTDATE,'DD/MM/YYYY') FORTNIGHTSTARTDATE, TO_CHAR(FORTNIGHTENDDATE,'DD/MM/YYYY') FORTNIGHTENDDATE,
TRANSTYPE, MODULE, FBASIC_PEICERT, FBASIC, VBASIC, DA, TSA, ADHOC, NS_ALLOW, NS_HRS, ATTENDANCEHOURS, TOTAL_AMT, TOTAL_HRS
FROM GRATUITYCOMPONENTRATE
WHERE TOKENNO ='04053'
AND COMPANYCODE ='NJ0001'
AND DIVISIONCODE ='0002'
ORDER BY TRANSTYPE,TO_DATE(FORTNIGHTENDDATE,'DD/MM/YYYY')


PRCWPS_GRATUITY_SETTLE_B4SAVE