DROP TABLE  GTT_WPSSTLENTITLEMENT CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_WPSSTLENTITLEMENT
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(10 BYTE),
  WORKERNAME        VARCHAR2(50 BYTE),
  DEPARTMENTCODE    VARCHAR2(10 BYTE),
  SHIFTCODE         VARCHAR2(10 BYTE),
  ATTNHOURS         NUMBER(7,2),
  HOLIDAYHOURS      NUMBER(7,2),
  STANDARDSTLHOURS  NUMBER(7,2),
  ADJUSTEDHOURS     NUMBER(7,2),
  STLDAYS_BF        NUMBER(7,2),
  STLDAYS           NUMBER(7,2),
  STLHRSTAKEN       NUMBER(7,2),
  COMPANYNAME       VARCHAR2(200 BYTE),
  PRINTDATE         VARCHAR2(50 BYTE),
  IS_RET_LEFT       VARCHAR2(3 BYTE),
  CLOSING           NUMBER(18,2),
  WORKDAYS          NUMBER(18,2),
  ENTDAYS           NUMBER(18,2),
  PREVDUE           NUMBER(18,2),
  TOTALDUE          NUMBER(18,2),
  EX1               VARCHAR2(1000 BYTE),
  EX2               VARCHAR2(1000 BYTE),
  EX3               VARCHAR2(1000 BYTE),
  EX4               VARCHAR2(1000 BYTE),
  EX9               VARCHAR2(1000 BYTE),
  EX10              NUMBER(12,2),
  EX11              NUMBER(12,2),
  EX12              NUMBER(12,2),
  EX5               VARCHAR2(1000 BYTE),
  EX6               VARCHAR2(1000 BYTE),
  EX7               VARCHAR2(100 BYTE),
  EX8               VARCHAR2(100 BYTE),
  EX13              VARCHAR2(98 BYTE),
  EX14              VARCHAR2(100 BYTE),
  EX15              VARCHAR2(100 BYTE),
  EX16              VARCHAR2(100 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;

