  INSERT INTO GTT_PAYSLIP_NJMCL
            (SLIPNO, COMPANYCODE, DIVISIONCODE, FORTNIGHTENDDATE, DEPT, SRLNO, RECORDNO, WORKERNAME, EBDESIG, DSGCD, CT,ESINO,ATNHRS,
            STLDAYS,STLPERIOD,OTHR,DA,HRA, PBF,FPF,PF, ESI, P_TAX, PCO, GRERNG, GRDEDN, NETPAY,DEPARTMENTCODE,WORKERCATEGORYCODE,  WORKERCATEGORYNAME, SECTION, SHIFT) 
    
            SELECT ROW_NUMBER() OVER(ORDER BY DEPARTMENTCODE,SECTIONCODE, SHIFTCODE,TO_NUMBER(SRLNO), RECORDNO) SLIPNO,COMPANYCODE, DIVISIONCODE,
                TO_CHAR(PAYMENTDATE,'DD-MM-YY')PAYMENTDATE, DEPT, SRLNO, RECORDNO, WORKERNAME,EBDESIG, DSGCD, CT, ESINO, ATNHRS, 
                STLDAYS, STLPERIOD, OTHR, DA, HRA,  PBF, FPF, PF,ESI, P_TAX,PCO,GRERNG, GRDEDN,NETPAY,DEPARTMENTCODE, WORKERCATEGORYCODE,  
                WORKERCATEGORYNAME, SECTIONCODE, SHIFTCODE
            FROM VW_WPSPAYSLIP_STL 
            WHERE COMPANYCODE='NJ0001'
                AND DIVISIONCODE='0002'
                AND PAYMENTDATE>=TO_DATE('16/01/2021','DD/MM/YYYY')
                AND PAYMENTDATE<=TO_DATE('31/01/2021','DD/MM/YYYY')         
                
       --       AND RECORDNO IN ('04202','04189','00060','05101') 
       --       AND RECORDNO IN ('00053','95063','95013','95021')  
       --   AND RECORDNO IN ('61257','61294','61296')  
       --   AND RECORDNO IN ('64853','01507','01441')  
       --   and departmentcode in ('01','04')
       
       
select * from wpsstlentitlementcalcdetails
where tokenno='41608'       


       
select * from wpsstlentitlementcalcdetails
where tokenno='00046'       

