exec PROC_RPT_WPSSTLDETAILS('NJ0001','0002','01/01/2021','15/01/2021','','','','','')


SELECT * FROM WPSSTLTRANSACTION WHERE TOKENNO='50181'

FN_GENERATE_SYSROWID

SELECT DISTINCT FROMYEAR FROM WPSSTLTRANSACTION

     INSERT INTO GBL_STLBAL ( COMPANYCODE, DIVISIONCODE, LEAVECODE, YEAR, ASONDATE, WORKERSERIAL, TOKENNO, 
     ENTITLE_DAYS, PREV_STLDAYS, STLTAKEN_DAYS, STLBAL_DAYS) 
     SELECT A.COMPANYCODE, A.DIVISIONCODE, 'STL' LEAVECODE, B.YEARCODE,  
     TO_DATE('31/12/2020','DD/MM/YYYY') ASONDATE, B.WORKERSERIAL, A.TOKENNO, 
     SUM(STLDAYS) ENTITLE_DAYS, SUM(PREV_STLDAYS) PREV_STLDAYS, SUM(STLDAYS_TAKEN) STLTAKEN_DAYS,  
     (SUM(STLDAYS) + SUM(PREV_STLDAYS) - SUM(STLDAYS_TAKEN)) STLBAL_DAYS 
     FROM WPSWORKERMAST A, 
     (   
         SELECT WORKERSERIAL,FROMYEAR YEARCODE, STLDAYS,PREV_STLDAYS, 0 STLDAYS_TAKEN 
         FROM WPSSTLTRANSACTION  
         WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002'  
         AND FROMYEAR BETWEEN '2017' AND '2019'
         UNION ALL 
         SELECT WORKERSERIAL,/*'2020'*/YEAR YEARCODE, 0  STLDAYS,0 PREV_STLDAYS, SUM(LEAVEDAYS) STLDAYS_TAKEN 
         FROM WPSSTLENTRYDETAILS  
         WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002'  
         AND PAYMENTDATE<=TO_DATE('31/12/2020','DD/MM/YYYY')
         AND YEAR BETWEEN '2017' AND '2019'
         AND LEAVECODE='STL' AND LEAVEDAYS>0
         GROUP BY WORKERSERIAL,YEAR    
     ) B 
     WHERE A.COMPANYCODE = 'NJ0001' AND A.DIVISIONCODE = '0002'  
      AND A.WORKERSERIAL = B.WORKERSERIAL 
      GROUP BY A.COMPANYCODE, A.DIVISIONCODE, B.YEARCODE, B.WORKERSERIAL, A.TOKENNO  

     INSERT INTO GBL_STLBAL ( COMPANYCODE, DIVISIONCODE, LEAVECODE, YEAR, ASONDATE, WORKERSERIAL, TOKENNO, 
     ENTITLE_DAYS, PREV_STLDAYS, STLTAKEN_DAYS, STLBAL_DAYS) 
     SELECT A.COMPANYCODE, A.DIVISIONCODE, 'STL' LEAVECODE, B.YEARCODE,  
     TO_DATE('01/01/2021','DD/MM/YYYY') ASONDATE, B.WORKERSERIAL, A.TOKENNO, 
     SUM(STLDAYS) ENTITLE_DAYS, SUM(PREV_STLDAYS) PREV_STLDAYS, SUM(STLDAYS_TAKEN) STLTAKEN_DAYS,  
     (SUM(STLDAYS) + SUM(PREV_STLDAYS) - SUM(STLDAYS_TAKEN)) STLBAL_DAYS 
     FROM WPSWORKERMAST A, 
     (   
         SELECT WORKERSERIAL,FROMYEAR YEARCODE, STLDAYS,PREV_STLDAYS, 0 STLDAYS_TAKEN 
         FROM WPSSTLTRANSACTION  
         WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002'  
         AND FROMYEAR BETWEEN '2018' AND '2020'
         UNION ALL 
         SELECT WORKERSERIAL,/*'2021'*/YEAR YEARCODE, 0  STLDAYS,0 PREV_STLDAYS, SUM(LEAVEDAYS) STLDAYS_TAKEN 
         FROM WPSSTLENTRYDETAILS  
         WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002'  
         AND PAYMENTDATE<=TO_DATE('01/01/2021','DD/MM/YYYY')
         AND YEAR BETWEEN '2018' AND '2020'
         AND LEAVECODE='STL' AND LEAVEDAYS>0
         GROUP BY WORKERSERIAL,YEAR    
     ) B 
     WHERE A.COMPANYCODE = 'NJ0001' AND A.DIVISIONCODE = '0002'  
      AND A.WORKERSERIAL = B.WORKERSERIAL 
      GROUP BY A.COMPANYCODE, A.DIVISIONCODE, B.YEARCODE, B.WORKERSERIAL, A.TOKENNO  

LV_PVTSTR -------
'2018' AS YR_2018,'2019' AS YR_2019
LV_AVLSTR -------
NVL(A.YR_2018,0) AVL_YR_2018,NVL(A.YR_2019,0) AVL_YR_2019
LV_BALSTR -------
(NVL(A.YR_2018,0)  - NVL(B.YR_2018,0)) BAL_YR_2018,(NVL(A.YR_2019,0)  - NVL(B.YR_2019,0)) BAL_YR_2019
     INSERT INTO GBL_STLBAL ( COMPANYCODE, DIVISIONCODE, LEAVECODE, YEAR, ASONDATE, WORKERSERIAL, TOKENNO, 
     ENTITLE_DAYS, PREV_STLDAYS, STLTAKEN_DAYS, STLBAL_DAYS) 
     SELECT A.COMPANYCODE, A.DIVISIONCODE, 'STL' LEAVECODE, B.YEARCODE,  
     TO_DATE('15/01/2021','DD/MM/YYYY') ASONDATE, B.WORKERSERIAL, A.TOKENNO, 
     SUM(STLDAYS) ENTITLE_DAYS, SUM(PREV_STLDAYS) PREV_STLDAYS, SUM(STLDAYS_TAKEN) STLTAKEN_DAYS,  
     (SUM(STLDAYS) + SUM(PREV_STLDAYS) - SUM(STLDAYS_TAKEN)) STLBAL_DAYS 
     FROM WPSWORKERMAST A, 
     (   
         SELECT WORKERSERIAL,FROMYEAR YEARCODE, STLDAYS,PREV_STLDAYS, 0 STLDAYS_TAKEN 
         FROM WPSSTLTRANSACTION  
         WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002'  
         AND FROMYEAR BETWEEN '2018' AND '2020'
         UNION ALL 
         SELECT WORKERSERIAL,/*'2021'*/YEAR YEARCODE, 0  STLDAYS,0 PREV_STLDAYS, SUM(LEAVEDAYS) STLDAYS_TAKEN 
         FROM WPSSTLENTRYDETAILS  
         WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002'  
         AND PAYMENTDATE<=TO_DATE('15/01/2021','DD/MM/YYYY')
         AND YEAR BETWEEN '2018' AND '2020'
         AND LEAVECODE='STL' AND LEAVEDAYS>0
         GROUP BY WORKERSERIAL,YEAR    
     ) B 
     WHERE A.COMPANYCODE = 'NJ0001' AND A.DIVISIONCODE = '0002'  
      AND A.WORKERSERIAL = B.WORKERSERIAL 
      GROUP BY A.COMPANYCODE, A.DIVISIONCODE, B.YEARCODE, B.WORKERSERIAL, A.TOKENNO  

INSERT INTO GTT_STLDETAILS
(
   TOKENNO, PREV_YR_STLBAL_1, PREV_YR_STLBAL_2, CURR_YR_STLBAL1, STL_AVAILED_YR1, STL_AVAILED_YR2, STL_AVAILED_YR3
)
SELECT A.TOKENNO
,NVL(A.YR_2018,0) AVL_YR_2018,NVL(A.YR_2019,0) AVL_YR_2019
,(NVL(A.YR_2018,0)  - NVL(B.YR_2018,0)) BAL_YR_2018,(NVL(A.YR_2019,0)  - NVL(B.YR_2019,0)) BAL_YR_2019
FROM 
(
    SELECT * FROM 
    (
       SELECT TOKENNO,'STLBAL_DAYS' CAPTION, STLBAL_DAYS, YEAR
       FROM  STLBAL_TMP
    )
    PIVOT 
    (
       SUM(STLBAL_DAYS)
       FOR YEAR IN ('2018' AS YR_2018,'2019' AS YR_2019)
    )
) A,
(
SELECT * FROM 
    (
       SELECT TOKENNO,'STLBAL_DAYS' CAPTION, STLBAL_DAYS, YEAR
       FROM GBL_STLBAL
    )
    PIVOT 
    (
       SUM(STLBAL_DAYS)
       FOR YEAR IN ('2018' AS YR_2018,'2019' AS YR_2019)
    )
) B
WHERE A.TOKENNO=B.TOKENNO