exec PROC_RPT_ECR('NJ0001','0002','2020-2021','202101','ALL','')


select * from WPSWAGESDETAILS_MV
where tokenno='85130'
and FORTNIGHTSTARTDATE >= '01-jan-21'

select * from WPSworkermast b
where tokenno='85130'
and B.WORKERCATEGORYCODE NOT IN ('A','O','R') 
         AND B.DATEOFJOINING <= TO_DATE('31/01/2021','DD/MM/YYYY') 
         AND (B.DATEOFTERMINATION IS NULL OR B.DATEOFTERMINATION >= TO_DATE('01/01/2021','DD/MM/YYYY'))
     AND PFMEMBERSHIPDATE<=TO_DATE('31/01/2021','DD/MM/YYYY') 
     AND (PFSETTELMENTDATE IS NULL OR PFSETTELMENTDATE >TO_DATE('31/01/2021','DD/MM/YYYY')) 

and FORTNIGHTSTARTDATE >= '01-jan-21'

select 63+58 from dual



 INSERT INTO GTT_ECRREPORT (
SERIAL_NO, COMPANYCODE,COMPANYNAME,DIVISIONCODE,DIVISIONNAME,UANNO,TOKENNO, WORKERNAME, PENSIONNO, PFNO, GROSSWAGES,  PF_GROSS,  PENSION_GROSS, 
  DLI_GROSS,  PENSION_CONTRIBUTION,  EPF_EE, EE_REFUND,NCPDAYS , 
 DOL,REASON,  WAGE_ARR, EE_ARR,ER_ARR,EPS_ARR, PFCATEGORY,AADHARNO,MODULE, REPORTHEADER ,PRINDATE, EX1, EX2, EX3, EX4 ) 
 
 
 SELECT SERIAL_NO, X.COMPANYCODE,C.COMPANYNAME,X.DIVISIONCODE,D.DIVISIONNAME,UANNO,TOKENNO, WORKERNAME, PENSIONNO, PFNO,ROUND(GROSSWAGES,0) GROSSWAGES, 
 ROUND(PF_GROSS,0) PF_GROSS,ROUND(PENSION_GROSS,0) PENSION_GROSS,ROUND(DLI_GROSS,0) DLI_GROSS,ROUND(ROUND(PENSION_GROSS,0) * 8.33/100,0) PENSION_CONTRIBUTION,
 0 EPF_EE, 0 EE_REFUND,NCPDAYS , 
 TO_CHAR(DOL,'DD/MM/YYYY') DOL, CASE WHEN  DOL IS NOT NULL THEN REASON ELSE NULL END REASON,  WAGE_ARR, EE_ARR,ER_ARR,EPS_ARR, PFCATEGORY,AADHARNO,MODULE,  
 'ECR Report JANUARY  ,2021 (WPS AND PIS AND CON)' ,TO_CHAR(SYSDATE,'DD/MM/YYYY') PRONTDATE,0 EX1,'' EX2,'' EX3,'' EX4 
 FROM 
 ( 

     SELECT 0 SERIAL_NO,B.COMPANYCODE,B.DIVISIONCODE,B.UANNO, B.TOKENNO, WORKERNAME, PENSIONNO, PFNO, B.DATEOFBIRTH, SUM(NVL(GROSS_WAGES,0)) GROSSWAGES, SUM(NVL(PF_GROSS,0)) PF_GROSS, 
     CASE WHEN SUM(NVL(PENSION_GROSS,0)) >=15000 THEN 15000 ELSE SUM(NVL(PENSION_GROSS,0)) END PENSION_GROSS, CASE WHEN SUM(NVL(PF_GROSS,0)) >= 15000 THEN 15000 ELSE SUM(NVL(PF_GROSS,0)) END DLI_GROSS, SUM(NVL(FPF,0)) AS PENSION_CONTRIBUTION,0 EPF_EE,0 EE_REFUND, 
     CASE WHEN ROUND(((SUM(NVL(ATTENDANCEHOURS,0)+NVL(NS_HRS_PFLINK,0)+NVL(HOLIDAYHOURS,0)+NVL(STLHOURS,0))))/8,0) >= 31 THEN 0 
     ELSE 
       31 - ROUND(((SUM(NVL(ATTENDANCEHOURS,0)+NVL(NS_HRS_PFLINK,0)+NVL(HOLIDAYHOURS,0)+NVL(STLHOURS,0))))/8,0) 
     END NCPDAYS, 
     B.DATEOFTERMINATIONADVICE DOL, 
     CASE WHEN B.DATEOFTERMINATIONADVICE IS NULL OR B.DATEOFTERMINATIONADVICE > TO_DATE('31/01/2021','DD/MM/YYYY') THEN '' 
     ELSE   WORKERSTATUS  
     END REASON,  
     0 WAGE_ARR, 0 EE_ARR, 0 ER_ARR, 0 EPS_ARR,        
     CASE WHEN  B.PFAPPLICABLE='Y' AND B.EPFAPPLICABLE='Y' THEN '2'       
          WHEN  B.PFAPPLICABLE='Y' AND B.EPFAPPLICABLE='N' THEN '1'      
          ELSE '3'      
     END AS PFCATEGORY,               
     B.ADHARCARDNO AADHARNO,'WPS' MODULE 
     FROM (  
             SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL,NVL(GROSS_WAGES,0) GROSS_WAGES, NVL(PF_GROSS,0) PF_GROSS, NVL(PENSION_GROSS,0) PENSION_GROSS, NVL(FPF,0) FPF, NVL(PF_CONT,0) PF_CONT,  
             NVL(ATTENDANCEHOURS,0) ATTENDANCEHOURS, NVL(NS_HRS_PFLINK,0) NS_HRS_PFLINK, NVL(HOLIDAYHOURS,0) HOLIDAYHOURS, 0 STLHOURS  
             FROM WPSWAGESDETAILS_MV   
             WHERE COMPANYCODE= 'NJ0001' AND DIVISIONCODE='0002'  
               AND YEARCODE ='2020-2021'   
               AND FORTNIGHTSTARTDATE >= TO_DATE('01/01/2021','DD/MM/YYYY') AND FORTNIGHTENDDATE <=  TO_DATE('31/01/2021','DD/MM/YYYY')  
             UNION ALL  
             SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL,NVL(STLAMOUNT,0) GROSS_WAGES, NVL(PF_GROSS,0) PF_GROSS, NVL(STLAMOUNT,0) PENSION_GROSS, NVL(FPF,0) FPF, NVL(PF_E,0) PF_CONT,  
             0 ATTENDANCEHOURS, 0 NS_HRS_PFLINK, 0 HOLIDAYHOURS, NVL(STLHOURS,0) STLHOURS  
             FROM WPSSTLWAGESDETAILS  
             WHERE COMPANYCODE= 'NJ0001' AND DIVISIONCODE='0002' 
               AND YEARCODE ='2020-2021'  
               AND PAYMENTDATE >= TO_DATE('01/01/2021','DD/MM/YYYY') AND PAYMENTDATE <=  TO_DATE('31/01/2021','DD/MM/YYYY') 
          ) A, WPSWORKERMAST B  
     WHERE A.WORKERSERIAL (+)= B.WORKERSERIAL 
         AND B.WORKERCATEGORYCODE NOT IN ('A','O','R') 
         AND B.DATEOFJOINING <= TO_DATE('31/01/2021','DD/MM/YYYY') 
         AND (B.DATEOFTERMINATION IS NULL OR B.DATEOFTERMINATION >= TO_DATE('01/01/2021','DD/MM/YYYY'))
     AND PFMEMBERSHIPDATE<=TO_DATE('31/01/2021','DD/MM/YYYY') 
     AND (PFSETTELMENTDATE IS NULL OR PFSETTELMENTDATE >TO_DATE('31/01/2021','DD/MM/YYYY')) 
     GROUP BY B.COMPANYCODE,B.DIVISIONCODE,B.UANNO, B.TOKENNO, WORKERNAME, PENSIONNO, PFNO, B.DATEOFBIRTH,B.PFCATEGORY,B.ADHARCARDNO,B.DATEOFTERMINATIONADVICE,WORKERSTATUS,B.PFAPPLICABLE,B.EPFAPPLICABLE
       
     UNION ALL  
     SELECT 0 SERIAL_NO,B.COMPANYCODE,B.DIVISIONCODE, B.UANNO, B.TOKENNO, B.EMPLOYEENAME WORKERNAME, B.PENSIONNO, B.PFNO,  B.DATEOFBIRTH, NVL(A.GROSSEARN,0) GROSSWAGES, NVL(A.PF_GROSS,0) PF_GROSS, 
     CASE WHEN NVL(A.PEN_GROSS,0) >15000 THEN 15000 ELSE NVL(A.PEN_GROSS,0) END PENSION_GROSS, CASE WHEN PEN_GROSS >= 15000 THEN 15000 ELSE PEN_GROSS END DLI_GROSS, NVL(A.FPF,0) PENSION_CONTRIBUTION,0 EPF_EE,0 EE_REFUND, 
     /*CASE WHEN NVL(PF_GROSS,0)>=15000 THEN 0  ELSE CASE WHEN (ATTN_CALCF - ATTN_SALD)>0 THEN  (ATTN_CALCF - ATTN_SALD) ELSE 0 END END ELSE 0 END END*/ ATTN_WPAY   NCPDAYS,  
     CASE WHEN B.STATUSDATE >= TO_DATE('01/01/2021','DD/MM/YYYY') AND B.STATUSDATE <=  TO_DATE('31/01/2021','DD/MM/YYYY')  THEN B.STATUSDATE ELSE NULL END DOL, 
     CASE WHEN B.STATUSDATE IS NULL OR B.STATUSDATE > TO_DATE('31/01/2021','DD/MM/YYYY') THEN '' 
     ELSE   EMPLOYEESTATUS  
     END REASON, 
     0 WAGE_ARR, 0 EE_ARR, 0 ER_ARR, 0 EPS_ARR, 
     CASE WHEN  B.PFAPPLICABLE='Y' AND B.EPFAPPLICABLE='Y' THEN '2'       
          WHEN  B.PFAPPLICABLE='Y' AND B.EPFAPPLICABLE='N' THEN '1'      
     ELSE '3'      
     END AS PFCATEGORY,               
     B.AADHARNO,'PIS' MODULE 
     FROM PISPAYTRANSACTION A, PISEMPLOYEEMASTER B 
     WHERE A.WORKERSERIAL (+)= B.WORKERSERIAL 
       AND A.YEARCODE='2020-2021' 
       AND A.COMPANYCODE='NJ0001' 
       AND B.DATEOFCONFIRMATION <= TO_DATE('31/01/2021','DD/MM/YYYY') 
       AND (B.STATUSDATE IS NULL OR B.STATUSDATE >= TO_DATE('01/01/2021','DD/MM/YYYY')) 
       AND A.YEARMONTH>=  TO_NUMBER(TO_CHAR(TO_DATE('01/01/2021','DD/MM/YYYY'),'YYYYMM')) AND A.YEARMONTH<=TO_NUMBER(TO_CHAR(TO_DATE('31/01/2021','DD/MM/YYYY'),'YYYYMM')) 
     /*GROUP BY B.COMPANYCODE,B.DIVISIONCODE,B.UANNO, B.TOKENNO, B.EMPLOYEENAME, PENSIONNO, PFNO, 
              B.AADHARNO,B.STATUSDATE,B.EMPLOYEESTATUS,A.ATTN_WPAY, A.ATTN_SALD,B.PFAPPLICABLE,B.EPFAPPLICABLE,PF_GROSS */ 
     UNION ALL  
     SELECT  0 SERIAL_NO,B.COMPANYCODE,B.DIVISIONCODE, B.UANNO,TOKENNO, /*B.SUBCONTRACTORNO,*/ B.SUBCONTRACTORNAME WORKERNAME, B.PENSIONNO, B.PFNO,  B.DATEOFBIRTH, 
     SUM(NVL(A.GROSS_EARN,0)) GROSSWAGES, SUM(NVL(A.PFGROSS,0)) PF_GROSS,                          
     SUM(NVL(A.PENSIONGROSS,0)) PENSION_GROSS,  CASE WHEN PFGROSS >= 15000 THEN 15000 ELSE PFGROSS END DLI_GROSS, SUM(NVL(A.EPF,0)) PENSION_CONTRIBUTION,0 EPF_EE,0 EE_REFUND,  
     CASE WHEN SUM(PFGROSS)>=15000 THEN 0   
          WHEN A.SALARYDAYS >=26 THEN 0   
          ELSE (26 - A.SALARYDAYS)            
     END NCPDAYS,  
     B.STATUSDATE DOL,  
     CASE WHEN B.STATUSDATE IS NULL OR B.STATUSDATE > TO_DATE('31/01/2021','DD/MM/YYYY') THEN ''  
     ELSE   EMPLOYEESTATUS   
     END REASON,  
     0 WAGE_ARR, 0 EE_ARR, 0 ER_ARR, 0 EPS_ARR,  
     CASE WHEN  B.PFAPPLICABLE='Y' AND B.PENSIONAPPLICABLE='Y' THEN '2'        
          WHEN  B.PFAPPLICABLE='Y' AND B.PENSIONAPPLICABLE='N' THEN '1'       
     ELSE '3'       
     END AS PFCATEGORY,                
     B.ADHARCARDNO AADHARNO,'CON' MODULE  
     FROM CONWAGESDETAILS A, WPSSUBCONTRACTORMASTER B  
     WHERE A.WORKERSERIAL=B.WORKERSERIAL  
       AND A.COMPANYCODE='NJ0001' 
        AND A.DIVISIONCODE IN ('0002')   
       AND A.YEARCODE='2020-2021'  
       AND A.YEARMONTH=  TO_CHAR(TO_DATE('01/01/2021','DD/MM/YYYY'),'YYYYMM')
       AND A.YEARMONTH<=TO_NUMBER(TO_CHAR(TO_DATE('31/01/2021','DD/MM/YYYY'),'YYYYMM')) 
       AND PF_E>0 AND PFNO IS NOT NULL   
       AND PFJOINDATE<=TO_DATE('31/01/2021','DD/MM/YYYY')         
       AND (PFSETTLEMENTDATE IS NULL OR PFSETTLEMENTDATE >TO_DATE('31/01/2021','DD/MM/YYYY'))  
     GROUP BY YEARMONTH,B.COMPANYCODE,B.DIVISIONCODE,B.UANNO, B.SUBCONTRACTORNO, B.SUBCONTRACTORNAME, PENSIONNO, PFNO,TOKENNO, B.DATEOFBIRTH, 
          B.ADHARCARDNO,B.STATUSDATE,B.EMPLOYEESTATUS,A.SALARYDAYS ,B.PFAPPLICABLE,B.PENSIONAPPLICABLE,PFGROSS 
 ) X, COMPANYMAST C,DIVISIONMASTER D
 WHERE X.COMPANYCODE=C.COMPANYCODE
   AND X.COMPANYCODE=D.COMPANYCODE
   AND X.DIVISIONCODE=D.DIVISIONCODE
   AND ROUND(MONTHS_BETWEEN(TO_DATE('31/01/2021','DD/MM/YYYY'),DATEOFBIRTH)/12,6)<= 58