SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL, LOANCODE, MAX(LOANDATE) LOANDATE FROM PFLOANTRANSACTION PFL
            WHERE WORKERSERIAL IN (
                SELECT DISTINCT WORKERSERIAL FROM STAFFPFDATAUPLOAD
                WHERE TOKENNO='71468'
            ) 
            AND LOANDATE = 
            (
                SELECT MAX(LOANDATE) FROM PFLOANTRANSACTION  
                WHERE COMPANYCODE=PFL.COMPANYCODE
                AND DIVISIONCODE=PFL.DIVISIONCODE
                AND WORKERSERIAL=PFL.WORKERSERIAL
            )
            AND LOANTYPE ='REFUNDABLE'
            GROUP BY COMPANYCODE, DIVISIONCODE,WORKERSERIAL, LOANCODE
            
            SELECT MAX(LOANDATE) FROM PFLOANTRANSACTION WHERE TOKENNO='71468'
--                WHERE COMPANYCODE=PFL.LOANCODE
--                AND DIVISIONCODE=PFL.DIVISIONCODE
--                AND WORKERSERIAL=PFL.WORKERSERIAL