
GBL_GSTHSNMASTER

--------------------------------------------------------------------------------

ALTER TABLE GSTHSNMASTER ADD ISINPUTCREDIT VARCHAR2(3)

ALTER TABLE GSTHSNMASTER ADD ISREVERSECHARGE VARCHAR2(3)

ALTER TABLE GSTHSNMASTER ADD ISGSTAPPLICABLE VARCHAR2(3)


--------------------------------------------------------------------------------

ALTER TABLE GBL_GSTHSNMASTER ADD ISINPUTCREDIT VARCHAR2(3)

ALTER TABLE GBL_GSTHSNMASTER ADD ISREVERSECHARGE VARCHAR2(3)

ALTER TABLE GBL_GSTHSNMASTER ADD ISGSTAPPLICABLE VARCHAR2(3)


--------------------------------------------------------------------------------

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = '9101'

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = 'GSTHSNMASTER'


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_GSTHSNMASTER'



--------------------------------------------------------------------------------

SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (9101, 'GSTHSNMASTER', 'GBL_GSTHSNMASTER', 'ISINPUTCREDIT', 7, 
    'VARCHAR2', 1, 0, 'N', 'txtISINPUTCREDIT', 
    TO_TIMESTAMP('13/09/2019 1:50:03.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (9101, 'GSTHSNMASTER', 'GBL_GSTHSNMASTER', 'ISREVERSECHARGE', 7, 
    'VARCHAR2', 1, 0, 'N', 'txtISREVERSECHARGE', 
    TO_TIMESTAMP('13/09/2019 1:50:03.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (9101, 'GSTHSNMASTER', 'GBL_GSTHSNMASTER', 'ISGSTAPPLICABLE', 7, 
    'VARCHAR2', 1, 0, 'N', 'txtISGSTAPPLICABLE', 
    TO_TIMESTAMP('13/09/2019 1:50:03.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;


EXEC PROC_CREATE_GBL_TMP_TABLES(9101,0)


--------------------------------------------------------------------------------

SELECT DISTINCT DESCRIPTION||'~'||BOSSCODE||'~'||UOMCODE||'~'||GSTSLABCODE||'~'||TYPEOFITEM||'~'||NVL(ISCESSAPPLICABLE,'N')||'~'||SYSROWID||'~'||NVL(ISINPUTCREDIT,'N')||'~'||NVL(ISREVERSECHARGE,'N')||'~'||NVL(ISGSTAPPLICABLE,'N') XX FROM GSTHSNMASTER WHERE HSNCODE = '999111' AND ROWNUM=1 