
--------------------------------------------------------------------------------
-- APRIL
--------------------------------------------------------------------------------


SELECT YEARMONTH, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, transactiontype,
VOUCHERNO, SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'


--************* 572 RECORD FOUND

SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'

--************* NO RECORD FOUND
 
SELECT * FROM ACVOUCHER WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00001'

SELECT * FROM ACVOUCHERDETAILS_ENTRY  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00001'

SYS/PF/JVM/2021/00001

PF/JVA/20-05/00001
PF/JVA/20-05/00001



--------------------------------------------------------------------------------
-- MAY
--------------------------------------------------------------------------------


SELECT YEARMONTH, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, transactiontype,
VOUCHERNO, SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'

and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


--************* 1150 RECORD FOUND

SELECT YEARMONTH,TOKENNO,AMOUNT, SYSTEMVOUCHERNO 
FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

--************* 1150 RECORD FOUND
 
SELECT * FROM ACVOUCHER_04022021 WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

SELECT * FROM ACVOUCHERDETAILS_ENTRY_040221  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


SELECT * FROM ACVOUCHER WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

SELECT * FROM ACVOUCHERDETAILS_ENTRY  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/02901'

SELECT * FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)


DELETE FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)

SELECT * FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)



DELETE FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)
 


UPDATE PFTRANSACTIONDETAILS
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'


 
SELECT  * FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'



UPDATE PFLOANTRANSACTION
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'


--------------------------------------------------------------------------------
-- JUNE
--------------------------------------------------------------------------------


SELECT YEARMONTH, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, transactiontype,
VOUCHERNO, SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'

and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


--************* 1150 RECORD FOUND

SELECT YEARMONTH,TOKENNO,AMOUNT, SYSTEMVOUCHERNO 
FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

--************* 1150 RECORD FOUND
-- 
--SELECT * FROM ACVOUCHER_04022021 WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

--SELECT * FROM ACVOUCHERDETAILS_ENTRY_040221  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


SELECT * FROM ACVOUCHER WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

SELECT * FROM ACVOUCHERDETAILS_ENTRY  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/02901'

SELECT * FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT  SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)


DELETE FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)

SELECT * FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)



DELETE FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT  SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)
 


UPDATE PFTRANSACTIONDETAILS
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'
 


 
SELECT  * FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'



UPDATE PFLOANTRANSACTION
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'


--------------------------------------------------------------------------------
-- JULY
--------------------------------------------------------------------------------


SELECT YEARMONTH, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, transactiontype,
VOUCHERNO, SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'

and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


--************* 1150 RECORD FOUND

SELECT YEARMONTH,TOKENNO,AMOUNT, SYSTEMVOUCHERNO 
FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

--************* 1150 RECORD FOUND
-- 
--SELECT * FROM ACVOUCHER_04022021 WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

--SELECT * FROM ACVOUCHERDETAILS_ENTRY_040221  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


SELECT * FROM ACVOUCHER WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'

SELECT * FROM ACVOUCHERDETAILS_ENTRY  WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/02901'

SELECT * FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)


DELETE FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)

SELECT * FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)



DELETE FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)
 


UPDATE PFTRANSACTIONDETAILS
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'
 


 
SELECT  * FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'



UPDATE PFLOANTRANSACTION
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'



--------------------------------------------------------------------------------
-- AUGUST
--------------------------------------------------------------------------------


SELECT YEARMONTH, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, transactiontype,
VOUCHERNO, SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'

and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'


--************* 1150 RECORD FOUND

SELECT YEARMONTH,TOKENNO,AMOUNT, SYSTEMVOUCHERNO 
FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008' 


SELECT * FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)


DELETE FROM ACVOUCHER 
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)

SELECT * FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)



DELETE FROM ACVOUCHERDETAILS_ENTRY  
WHERE SYSTEMVOUCHERNO IN (
SELECT DISTINCT  SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE 1=1 -- SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008'
--and SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00719'
)
 

 
SELECT  * FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'

UPDATE PFTRANSACTIONDETAILS
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH>='202004'
 


 
SELECT  * FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008'



UPDATE PFLOANTRANSACTION
SET  VOUCHERNO = NULL,
VOUCHERDATE = NULL,
SYSTEMVOUCHERNO = NULL,
SYSTEMVOUCHERDATE = NULL
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH>='202004'