
SELECT * FROM ACVOUCHERDETAILS_ENTRY_040221
WHERE SYSTEMVOUCHERNO IN (
SELECT SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS_040221
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'
)

http://localhost:64972/PRODUCTION_COFFEE/Pages/Transaction/pgMillingProcess.aspx