
SELECT * FROM TAB WHERE TNAME LIKE '%PFTRANSACTIONDETAILS%'

--CREATE TABLE PISPAYTRANSACTION_040221 AS
SELECT DISTINCT YEARMONTH FROM PISPAYTRANSACTION


---------------------------------------------------------------------------------------------------
--------         APRIL
---------------------------------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO IN ('71561')
AND YEARMONTH='202004'
AND TRANSACTIONTYPE='SALARY'


SELECT DISTINCT YEARMONTH FROM PISPAYTRANSACTION

SELECT TOKENNO, YEARMONTH, PF_E, PF_C, FPF FROM PISPAYTRANSACTION WHERE TOKENNO IN ('70202','71561') AND YEARMONTH='202004' 

UPDATE PISPAYTRANSACTION SET PF_C = 1850, FPF=1250 WHERE TOKENNO='70202' AND YEARMONTH='202004'
UPDATE PISPAYTRANSACTION SET PF_C = 300, FPF=0 WHERE TOKENNO='71561' AND YEARMONTH='202004'

---------------------------------------------------------------------------------------------------
--------         MAY
---------------------------------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO IN ('71561')
AND YEARMONTH='202004'
AND TRANSACTIONTYPE='SALARY'

SELECT TOKENNO, YEARMONTH, PF_E, PF_C, FPF FROM PISPAYTRANSACTION WHERE TOKENNO IN ('70202','71561') AND YEARMONTH='202005'

UPDATE PISPAYTRANSACTION SET PF_C = 1850, FPF=1250 WHERE TOKENNO='70202' AND YEARMONTH='202005'

UPDATE PISPAYTRANSACTION SET PF_C = 813, FPF=0 WHERE TOKENNO='71561' AND YEARMONTH='202005'


---------------------------------------------------------------------------------------------------
--------         JUN
---------------------------------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO IN ('71561')
AND YEARMONTH='202004'
AND TRANSACTIONTYPE='SALARY'

SELECT TOKENNO, YEARMONTH, PF_E, PF_C, FPF FROM PISPAYTRANSACTION WHERE TOKENNO IN ('70202','71561','71570') AND YEARMONTH='202006'

UPDATE PISPAYTRANSACTION SET PF_C = 1850, FPF=1250 WHERE TOKENNO='70202' AND YEARMONTH='202006'

UPDATE PISPAYTRANSACTION SET PF_C = 1680, FPF=0 WHERE TOKENNO='71561' AND YEARMONTH='202006'

UPDATE PISPAYTRANSACTION SET PF_C = 6252, FPF=0 WHERE TOKENNO='71570' AND YEARMONTH='202006'


---------------------------------------------------------------------------------------------------
--------         JULY
---------------------------------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO IN ('71561')
AND YEARMONTH='202007'
AND TRANSACTIONTYPE='SALARY'

SELECT TOKENNO, YEARMONTH, PF_E, PF_C, FPF FROM PISPAYTRANSACTION WHERE TOKENNO IN ('70202','70216') AND YEARMONTH='202007'

UPDATE PISPAYTRANSACTION SET PF_C = 1850, FPF=1250 WHERE TOKENNO='70202' AND YEARMONTH='202007'

UPDATE PISPAYTRANSACTION SET PF_C = 5050, FPF=1250 WHERE TOKENNO='70216' AND YEARMONTH='202007'


---------------------------------------------------------------------------------------------------
--------         AUGUST
---------------------------------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO IN ('71561')
AND YEARMONTH='202008'
AND TRANSACTIONTYPE='SALARY'

SELECT TOKENNO, YEARMONTH, PF_E, PF_C, FPF FROM PISPAYTRANSACTION WHERE TOKENNO IN ('71561') AND YEARMONTH='202008'

UPDATE PISPAYTRANSACTION SET PF_C = 1800, FPF=0 WHERE TOKENNO='71561' AND YEARMONTH='202008'


---------------------------------------------------------------------------------------------------
--------         SEPTEMBER
---------------------------------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS
WHERE TOKENNO IN ('71446','70222')
AND YEARMONTH='202009'
AND TRANSACTIONTYPE='SALARY'
AND COMPONENTCODE='PF_C'


UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 151  WHERE TOKENNO='71446' AND YEARMONTH='202009' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C'



SELECT TOKENNO, YEARMONTH, PF_E, PF_C, FPF FROM PISPAYTRANSACTION WHERE TOKENNO IN ('71446','70222') AND YEARMONTH='202009'

UPDATE PISPAYTRANSACTION SET PF_C = 151, FPF=754 WHERE TOKENNO='71446' AND YEARMONTH='202009'

UPDATE PISPAYTRANSACTION SET PF_C = 5795, FPF=1250 WHERE TOKENNO='70222' AND YEARMONTH='202009'


-----------------------------------------------------------------------------

SELECT * FROM PFTRANSACTIONDETAILS WHERE TOKENNO='71561' AND YEARMONTH='202004' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C'

UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 1850  WHERE TOKENNO='70202' AND YEARMONTH='202004' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';

UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 300  WHERE TOKENNO='71561' AND YEARMONTH='202004' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';


UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 1850  WHERE TOKENNO='70202' AND YEARMONTH='202005' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';
UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 813  WHERE TOKENNO='71561' AND YEARMONTH='202005' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';


UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 1850  WHERE TOKENNO='70202' AND YEARMONTH='202006' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';
UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 1680  WHERE TOKENNO='71561' AND YEARMONTH='202006' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';
UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 6252  WHERE TOKENNO='71570' AND YEARMONTH='202006' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';


UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 1850  WHERE TOKENNO='70202' AND YEARMONTH='202007' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';
UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 5050  WHERE TOKENNO='70216' AND YEARMONTH='202007' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';


UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 1800  WHERE TOKENNO='71561' AND YEARMONTH='202008' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';

UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 151  WHERE TOKENNO='71446' AND YEARMONTH='202009' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C';
UPDATE PFTRANSACTIONDETAILS SET COMPONENTAMOUNT = 5795  WHERE TOKENNO='70222' AND YEARMONTH='202009' AND TRANSACTIONTYPE='SALARY' AND COMPONENTCODE='PF_C'


--------------------------------------------------------------------------------
-- VOUCHER UPDATE
--------------------------------------------------------------------------------



SELECT * FROM ACACLEDGER


SELECT * FROM ACVOUCHER

SELECT * FROM ACVOUCHERDETAILS_ENTRY

--------------------------------------------------------------------------------
-- APRIL
--------------------------------------------------------------------------------


SELECT YEARMONTH, TOKENNO, COMPONENTCODE, COMPONENTAMOUNT, 
VOUCHERNO, SYSTEMVOUCHERNO FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'


--************* 572 RECORD FOUND

SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'

--************* NO RECORD FOUND
 
SELECT * FROM ACVOUCHER WHERE SYSTEMVOUCHERNO='SYS/PF/JVM/2021/00001'

SELECT * FROM ACVOUCHERDETAILS_ENTRY

SYS/PF/JVM/2021/00001

PF/JVA/20-05/00001
PF/JVA/20-05/00001

--------------------------------------------------------------------------------
-- MAY
--------------------------------------------------------------------------------

SELECT DISTINCT SYSTEMVOUCHERNO 
FROM PFTRANSACTIONDETAILS
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'



SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202004'

SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202005'

--------------------------------------------------------------------------------
-- JUN
--------------------------------------------------------------------------------


SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202006'

--------------------------------------------------------------------------------
-- JULY
--------------------------------------------------------------------------------


SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202007'

--------------------------------------------------------------------------------
-- AUGUST
--------------------------------------------------------------------------------


SELECT YEARMONTH,TOKENNO,SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
WHERE SYSTEMVOUCHERNO IS NOT NULL
AND YEARMONTH='202008'


