
DECLARE
LV_YEARMONTH VARCHAR2(10);

BEGIN

    FOR C1 IN 
    (
    SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, SYSTEMVOUCHERNO FROM PFLOANTRANSACTION
    WHERE SYSTEMVOUCHERNO IS NOT NULL
    )
    LOOP
    --    prc_delete_systemvoucher('LJ0054', '0001', '2018-2019', 'L/SBE/18/06221', 'FORCED')
        prc_delete_systemvoucher(C1.COMPANYCODE,C1.DIVISIONCODE, C1.YEARCODE, C1.SYSTEMVOUCHERNO, 'FORCED');
    END LOOP;

END;   
 