DROP TABLE WPSOCCUPATIONMAST CASCADE CONSTRAINTS;

CREATE TABLE WPSOCCUPATIONMAST
(
  COMPANYCODE                VARCHAR2(10 BYTE)  NOT NULL,
  DIVISIONCODE               VARCHAR2(10 BYTE)  NOT NULL,
  DEPARTMENTCODE             VARCHAR2(10 BYTE)  NOT NULL,
  SECTIONCODE                VARCHAR2(10 BYTE)  NOT NULL,
  OCCUPATIONCODE             VARCHAR2(10 BYTE)  NOT NULL,
  OCCUPATIONNAME             VARCHAR2(80 BYTE),
  OCCUPATIONTYPE             VARCHAR2(50 BYTE),
  WORKERTYPECODE             VARCHAR2(10 BYTE),
  MACHINEMANDETORY           VARCHAR2(3 BYTE)   DEFAULT 'N',
  RATE                       NUMBER(18,4)       DEFAULT 0,
  MAINSARDER                 VARCHAR2(3 BYTE)   DEFAULT 'N',
  MAINSARDERVBRATE           NUMBER(18,4)       DEFAULT 0,
  PLWCALCULATIONBASEDON      VARCHAR2(50 BYTE)  DEFAULT 'NONE',
  ACTIVE                     VARCHAR2(1 BYTE)   DEFAULT 'Y',
  USERNAME                   VARCHAR2(100 BYTE) NOT NULL,
  LASTMODIFIED               DATE               DEFAULT SYSDATE,
  SYSROWID                   VARCHAR2(50 BYTE)  NOT NULL,
  DEPTOCCPCODE               VARCHAR2(20 BYTE),
  VB_PROCNAME                VARCHAR2(30 BYTE),
  IB_PROCNAME                VARCHAR2(50 BYTE),
  VB_PERCENTAGE              NUMBER(7,2),
  IB_PERCENTAGE              NUMBER(7,2),
  VB_DEPENDENT_DEPTOCCPCODE  VARCHAR2(100 BYTE),
  IB_DEPENDENT_DEPTOCCPCODE  VARCHAR2(100 BYTE),
  VBRATE                     NUMBER(11,6),
  IBCALCULATIONINDEX         NUMBER(6),
  STANDARDHANDSHIFT1         NUMBER(5),
  STANDARDHANDSHIFT2         NUMBER(5),
  STANDARDHANDSHIFT3         NUMBER(5),
  DEFAULTOCCUPATION          VARCHAR2(1 BYTE),
  FITMENTRATE                NUMBER(18,4),
  LINENOAPPLICABLE           VARCHAR2(1 BYTE)
)
TABLESPACE NJMCL_WEB
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IDX_WPSOCCUPATI_19112015040602 ON WPSOCCUPATIONMAST
(COMPANYCODE, DIVISIONCODE, DEPARTMENTCODE, SECTIONCODE, OCCUPATIONCODE)
LOGGING

TABLESPACE NJMCL_WEB
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE WPSOCCUPATIONMAST ADD (
  CONSTRAINT WPSOCCUPATIONMAST_U01
 UNIQUE (COMPANYCODE, DIVISIONCODE, DEPARTMENTCODE, SECTIONCODE, OCCUPATIONCODE));

ALTER TABLE WPSOCCUPATIONMAST ADD (
  CONSTRAINT WPSOCCUPATIONMAST_R01 
 FOREIGN KEY (COMPANYCODE, DIVISIONCODE, DEPARTMENTCODE, SECTIONCODE) 
 REFERENCES WPSSECTIONMAST (COMPANYCODE,DIVISIONCODE,DEPARTMENTCODE,SECTIONCODE) DISABLE);
