SELECT * FROM PISPAYTRANSACTION_SWT WHERE TOKENNO='0004'

DELETE FROM PISARREARTRANSACTION

SELECT * FROM PISARREARTRANSACTION WHERE TOKENNO='0004'

SELECT * FROM PISPAYTRANSACTION

DELETE FROM PIS_ERROR_LOG

SELECT * FROM PIS_ERROR_LOG


begin 
PRC_PISSALARYPROCESS_ARREAR ( 
      '0001',  
      '002',
      'ARREAR', 
      0, 
      '202004',
      '202004',
      '202007', 
      'PISARREARTRANSACTION',
      'PISARREARTRANSACTION',
      '002',
      '01',
      '01',
      '',
      ''
);
end;


