
Insert into WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2, PARAM_3, PARAM_4, 
    PARAM_5, MODULE)
 Values
   ('0001', '003', 'SALARY', 'PRC_PISSALARYPROCESS_UPDTARR', 0, 
    5, 'PISARREARTRANSACTION', 'PISPAYTRANSACTION_SWT', NULL, NULL, 
    NULL, 'PIS');
COMMIT;


DELETE FROM PISARREARTRANSACTION

SELECT * FROM PISPAYTRANSACTION
WHERE TOKENNO='0004'
AND YEARMONTH='202007'


SELECT * FROM PISARREARTRANSACTION
WHERE TOKENNO='0004'
AND YEARMONTH='202007'


SELECT * FROM PISPAYTRANSACTION
WHERE 1=1 --TOKENNO='0015'
AND YEARMONTH='202007'


SELECT * FROM PISARREARTRANSACTION
WHERE TOKENNO='0015'

AND YEARMONTH='202007'


DELETE PIS_ERROR_LOG

 UPDATE PISPAYTRANSACTION_SWT A 
    SET (SARR_ARRE, SARR_ARRD, SARR_PFARRE, SARR_NPFARRE) = 
        ( 
          SELECT GROSSEARN, GROSSDEDN, PF_GROSS, GROSSEARN - PF_GROSS 
            FROM PISARREARTRANSACTION 
           WHERE COMPANYCODE = A.COMPANYCODE 
             AND DIVISIONCODE = A.DIVISIONCODE 
             AND YEARMONTH = A.YEARMONTH 
             AND TRANSACTIONTYPE = 'ARREAR' 
             AND UNITCODE = A.UNITCODE 
             AND CATEGORYCODE = A.CATEGORYCODE 
             AND GRADECODE = A.GRADECODE 
             AND DEPARTMENTCODE = A.DEPARTMENTCODE 
             AND WORKERSERIAL = A.WORKERSERIAL 
        ) 
  WHERE COMPANYCODE = '0001' 
    AND DIVISIONCODE = '002' 
    AND YEARMONTH = '202007' 
    AND UNITCODE = '002' 
    AND CATEGORYCODE = NVL2('01' , '01' , CATEGORYCODE ) 
    AND GRADECODE = NVL2('01' , '01' , GRADECODE) 
    AND DEPARTMENTCODE = NVL2('','',DEPARTMENTCODE) 
    AND WORKERSERIAL = NVL2('000110','000110',WORKERSERIAL)
    
    
    
 SELECT * FROM PISPAYTRANSACTION_SWT A 
    WHERE 
        ( 
        
        
          SELECT B.GROSSEARN, B.GROSSDEDN, B.PF_GROSS, B.GROSSEARN - B.PF_GROSS 
            FROM PISARREARTRANSACTION B,PISPAYTRANSACTION_SWT A 
           WHERE B.COMPANYCODE = A.COMPANYCODE 
             AND B.DIVISIONCODE = A.DIVISIONCODE 
             AND B.YEARMONTH = A.YEARMONTH 
             AND B.TRANSACTIONTYPE = 'ARREAR' 
             AND B.UNITCODE = A.UNITCODE 
             AND B.CATEGORYCODE = A.CATEGORYCODE 
             AND B.GRADECODE = A.GRADECODE 
             AND B.DEPARTMENTCODE = A.DEPARTMENTCODE 
             AND B.WORKERSERIAL = A.WORKERSERIAL 
             
             
        ) 
  WHERE COMPANYCODE = '0001' 
    AND DIVISIONCODE = '002' 
    AND YEARMONTH = '202007' 
    AND UNITCODE = '002' 
    AND CATEGORYCODE = NVL2('01' , '01' , CATEGORYCODE ) 
    AND GRADECODE = NVL2('01' , '01' , GRADECODE) 
    AND DEPARTMENTCODE = NVL2('','',DEPARTMENTCODE) 
    AND WORKERSERIAL = NVL2('000110','000110',WORKERSERIAL)