PF ENTITLEMENT MUST BE GRATER THEN 5 YEAR.

PRC_PF_COMPONENT_SHARE


exec PRC_PF_COMPONENT_SHARE('NJ0002','0010' ,'2020-2021','008622','HBLDG','01/01/2020','A')

fn_ElegibleYearChecking
(
'<<COMPANYCODE>>',
'<<DIVISIONCODE>>',
'<<PFNO>>',
'<<LOANCODE>>',
'<<LOANDATE>>'
)

SELECT * FROM (
SELECT 'NJ0002' COMPANYCODE,'0010' DIVISIONCODE,'2020-2021' YEARCODE,
NVL(D.PFNO,P.PFNO) PFNO,NVL(D.TOKENNO,P.TOKENNO) TOKENNO,NVL(D.WORKERSERIAL,P.WORKERSERIAL) WORKERSERIAL,TO_CHAR(NVL(D.LOANDATE,P.LOANDATE),'DD/MM/YYYY') LOANDATE,NVL(D.LOANCODE,P.LOANCODE) LOANCODE,
NVL(D.PARAM_NAME,P.PARAM_NAME) PARAM_NAME,NVL(D.PF_E,P.PF_E) PF_E,NVL(D.PF_C,P.PF_C) PF_C,NVL( D.VPF,P.VPF) VPF, NVL(D.OTHER,P.OTHER) OTHER,'A' OPERATIONMODE,P.ISELLIGIBLE,P.REMARKS
FROM GTT_LOANSANCTION_PRAM P,LOANSANCTION_DETAILS D
WHERE P.PFNO=D.PFNO(+)
AND P.COMPANYCODE=D.COMPANYCODE(+)
AND P.DIVISIONCODE=D.DIVISIONCODE(+)
AND P.LOANCODE=D.LOANCODE(+)
AND P.LOANDATE=D.LOANDATE(+)
AND P.PARAM_NAME=D.PARAM_NAME(+)
ORDER BY TABINDEX
)
WHERE PF_E IS NOT NULL OR PF_C IS NOT NULL OR VPF IS NOT NULL OR OTHER IS NOT NULL OR ISELLIGIBLE IS NOT NULL OR REMARKS IS NOT NULL