
insert into gtt_salesbillregisterall 


SELECT A.CHANNELCODE,A.SALEBILLNO,A.SALEBILLDATE,A.BILLSERIALNO,A.BUYERCODE,A.ADDRESSCODE,A.ADDRESSCODEBILL,F.HSNCODE,A.QUALITYCODE,SUBSTR(REPLACE(REPLACE(A.QUALITYMANUALDESC,CHR(13),''),CHR(10),''),1,25) QUALITYMANUALDESC, 
       CASE WHEN MEASUREUNIT='KGS' THEN A.TOTALWEIGHT/1000 ELSE A.TOTALWEIGHT END WTINMT, 
       A.NOOFPACKINGUNIT, A.PACKSTYLENAME, A.TOTALINDIANAMOUNT, A.NETINDIANAMOUNT,0 ASSESSABLEAMOUNT, B.CHARGECODE, B.CHARGEAMOUNT,C.CHARGESHORTNAME,C.SERIALNO,C.CHARGETYPE , 
       D.ADDRESSNAME SHIPNAME,D.ADDRESS SHIPADDRESS,E.ADDRESSNAME BILLNAME,E.ADDRESS BILLADDRESS,A.SHIPSTATECODE, A.BILLSTATECODE, 
       G.COMPANYNAME, NULL EX1, NULL EX2, NULL EX3, NULL EX4, NULL EX5 
FROM SALESBILLVIEW A, SALESLINEWISECHARGEDETAILS B,CHARGEMASTER C,PARTYADDRESS D,PARTYADDRESS E, GSTITEMVSHSNMAPPING F, COMPANYMAST G 
WHERE A.COMPANYCODE='DJ0107' 
  AND A.DIVISIONCODE='0002' 
  AND A.SALEBILLDATE>=TO_DATE('01/04/2021','DD/MM/YYYY') 
  AND A.SALEBILLDATE<=TO_DATE('31/03/2022','DD/MM/YYYY') 
  AND A.SALEBILLNO NOT LIKE '%SEI%' 
  AND A.COMPANYCODE=B.COMPANYCODE(+) 
  AND A.DIVISIONCODE=B.DIVISIONCODE(+) 
  AND A.SALEBILLNO=B.DOCUMENTNO(+) 
  AND A.SALEBILLDATE=B.DOCUMENTDATE(+) 
  AND A.BILLSERIALNO=B.SERIALNO(+) 
  /*AND B.DOCUMENTTYPE(+) IN ('SALE BILL','SALE BILL RETURN','CREDIT NOTE','DEBIT NOTE')*/ 
  AND INSTR('SALE BILL~,SALE BILL RETURN~,CREDIT NOTE~,DEBIT NOTE~',  B.DOCUMENTTYPE(+) || '~')>0 
  AND B.COMPANYCODE=C.COMPANYCODE(+) 
  AND B.DIVISIONCODE=C.DIVISIONCODE(+) 
  AND B.CHARGECODE=C.CHARGECODE(+) 
  AND C.MODULE(+)='SALES' 
  AND A.CHANNELCODE=B.CHANNELCODE(+) 
  AND B.CHANNELCODE=C.CHANNELCODE(+) 
  AND A.COMPANYCODE=D.COMPANYCODE 
  AND A.COMPANYCODE=E.COMPANYCODE 
  AND A.BUYERCODE=D.PARTYCODE 
  AND A.BUYERCODE=E.PARTYCODE 
  AND D.PARTYTYPE='BUYER' 
  AND E.PARTYTYPE='BUYER'   
  AND A.ADDRESSCODE=D.ADDRESSCODE 
  AND A.ADDRESSCODEBILL=E.ADDRESSCODE 
  AND A.COMPANYCODE=F.COMPANYCODE 
  AND A.QUALITYCODE=F.ITEMCODE 
  AND F.MODULE='SALES' 
  AND A.COMPANYCODE=G.COMPANYCODE 
UNION ALL 
SELECT A1.CHANNELCODE,A1.SALESBILLNO,A1.SALESBILLDATE,A2.SERIALNO,A1.PARTYCODE BUYERCODE,A1.ADDRESSCODE,A1.ADDRESSCODEBILL,A2.HSNCODE,NULL QUALITYCODE,A2.ITEMDESC QUALITYMANUALDESC, 
       CASE WHEN A2.UOMCODE='KGS' THEN A2.QUANTITY/1000 ELSE A2.QUANTITY END WTINMT, 
       A2.QUANTITY NOOFPACKINGUNIT, NULL PACKSTYLENAME, A2.AMOUNT TOTALINDIANAMOUNT, A1.GROSSAMT, 0 ASSESSABLEAMOUNT, B.CHARGECODE, B.CHARGEAMOUNT,C.CHARGESHORTNAME,C.SERIALNO,C.CHARGETYPE , 
       D.ADDRESSNAME SHIPNAME,D.ADDRESS SHIPADDRESS,E.ADDRESSNAME BILLNAME,E.ADDRESS BILLADDRESS,NULL SHIPSTATECODE, A1.BILLSTATECODE, 
       G.COMPANYNAME, NULL EX1, NULL EX2, NULL EX3, NULL EX4, NULL EX5 
 FROM SALESOTHERBILLMASTER A1, SALESOTHERBILLDETAIL A2, SALESLINEWISECHARGEDETAILS B,CHARGEMASTER C,PARTYADDRESS D,PARTYADDRESS E, COMPANYMAST G 
WHERE A1.COMPANYCODE='DJ0107' 
  AND A1.DIVISIONCODE='0002' 
  AND A1.SALESBILLDATE>=TO_DATE('01/04/2021','DD/MM/YYYY') 
  AND A1.SALESBILLDATE<=TO_DATE('31/03/2022','DD/MM/YYYY') 
  AND A1.COMPANYCODE=A2.COMPANYCODE 
  AND A1.DIVISIONCODE=A2.DIVISIONCODE 
  AND A1.SALESBILLNO=A2.SALESBILLNO 
  AND A2.COMPANYCODE=B.COMPANYCODE(+) 
  AND A2.DIVISIONCODE=B.DIVISIONCODE(+) 
  AND A2.CHANNELCODE=B.CHANNELCODE(+) 
  AND A2.SALESBILLNO=B.DOCUMENTNO(+) 
  AND A2.SALESBILLDATE=B.DOCUMENTDATE(+) 
  AND A2.SERIALNO=B.SERIALNO(+) 
  /*AND B.DOCUMENTTYPE(+) IN('SALE BILL','SALE BILL RETURN','OTHERS BILL','SCRAP BILL')*/ 
  AND INSTR('SALE BILL~,SALE BILL RETURN~,OTHERS BILL~,SCRAP BILL~',  B.DOCUMENTTYPE(+) || '~')>0 
  AND B.COMPANYCODE=C.COMPANYCODE(+) 
  AND B.DIVISIONCODE=C.DIVISIONCODE(+) 
  AND B.CHARGECODE=C.CHARGECODE(+) 
  AND C.MODULE(+)='SALES' 
  AND B.CHANNELCODE=C.CHANNELCODE(+) 
  AND A1.COMPANYCODE=D.COMPANYCODE 
  AND A1.COMPANYCODE=E.COMPANYCODE 
  AND A1.PARTYCODE=D.PARTYCODE 
  AND A1.PARTYCODE=E.PARTYCODE 
  AND D.PARTYTYPE='BUYER' 
  AND E.PARTYTYPE='BUYER' 
  AND A1.ADDRESSCODE=D.ADDRESSCODE 
  AND A1.ADDRESSCODEBILL=E.ADDRESSCODE 
  AND A1.COMPANYCODE=G.COMPANYCODE