EXEC PROC_SALESBILLREGISTERALL('DJ0107','0002','01/04/2021','31/03/2022','','','GST BILL','ALL')

EXEC PROC_SALESBILLREGISTERALL('DJ0107','0002','01/04/2021','31/03/2022','','','GST BILL','ALL')


SELECT * FROM GTT_SALESBILLREGISTERALL WHERE SALEBILLNO='DJC/2122/G0001'



DELETE FROM GTT_SALESBILLREGISTERALL WHERE SALEBILLNO<>'DJC/2122/G0001';

SELECT * FROM GTT_SALESBILLREGISTERALL



select * from saleschargedetails
where chargecode='SSHCC'
AND YEARCODE='2021-2022'
AND DOCUMENTTYPE LIKE 'SALE%'

UPDATE GTT_SALESBILLREGISTERALL SET CHARGESHORTNAME = 'ABC'
WHERE CHARGESHORTNAME LIKE '2ND%';

TRUNCATE TABLE  GTT_SALESBILLSUMMARY_GRPWISE

DROP TABLE GTT_SALESBILLSUMMARY_GRPWISE

CREATE TABLE GTT_SALESBILLSUMMARY_GRPWISE
(
  COMPANYCODE      VARCHAR2(10 BYTE), 
  DIVISIONCODE     VARCHAR2(10 BYTE), 
  COMPANYNAME      VARCHAR2(100 BYTE), 
  DIVISIONNAME     VARCHAR2(250 BYTE), 
  COLUMNHEAD       VARCHAR2(10 BYTE),
  COLUMNDESC       VARCHAR2(500 BYTE),
  AMOUNTVALUE           NUMBER(18,4),
  CHARGEAMOUNT     NUMBER(18,4),
  SUMAMOUNT     NUMBER(18,4),
  CHARGESHORTNAME  VARCHAR2(100 BYTE),
  CHARGETYPE VARCHAR2(200 BYTE),
  REPORTHEADER       VARCHAR2(300 BYTE),
  FIN_STARTDATE       VARCHAR2(30 BYTE),
  MONTHSTARTDATE       VARCHAR2(30 BYTE),
  MONTHENDDATE       VARCHAR2(30 BYTE),
  PERIODFROMDATE       VARCHAR2(30 BYTE),
  PERIODTODATE       VARCHAR2(30 BYTE),
  TAG              VARCHAR2(10 BYTE),
  SLNO             NUMBER(18,2)
)


WHERE 

60616251.50

62724089.80


SELECT * FROM GTT_SALESBILLSUMMARY_GRPWISE


delete GTT_SALESBILLSUMMARY_GRPWISE


--------TAG A -----------GRAND TOTAL

INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT   'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'A' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
UNION ALL
SELECT   'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'A' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
UNION ALL
SELECT CHARGETYPE,CHARGESHORTNAME,'A' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY CHARGETYPE,CHARGESHORTNAME

SELECT * FROM SALESBILLVIEW 


SELECT * FROM GTT_SALESBILLSUMMARY_GRPWISE



SELECT   'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'A' TAG,
SUM(B.TOTALQUANTITY)  QUANTITY
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO


UPDATE GTT_SALESBILLSUMMARY_GRPWISE SET SLNO = 
CASE WHEN CHARGESHORTNAME LIKE '%QUANTITY%' THEN 1
    WHEN  CHARGESHORTNAME LIKE '%AMOUNT%' THEN 2
    WHEN  CHARGESHORTNAME LIKE 'PRINT%' THEN 3
    WHEN  CHARGESHORTNAME LIKE '%HANDLING%' THEN 4
    WHEN  CHARGESHORTNAME LIKE '%CGST%' THEN 5
    WHEN  CHARGETYPE LIKE '%SGST%' THEN 6
    WHEN  CHARGETYPE LIKE '%IGST%' THEN 7
    WHEN  CHARGETYPE LIKE '%TCS%' THEN 8
    ELSE 9
    END
    
    
    SELECT * FROM SYS_PARAMETER
WHERE PARAMETER_NAME ='REFERENCE INVOICE TAG IN OTHER SALE'


AND COMPANYCODE='CJ0101'
AND DIVISIONCODE='0002'



SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_SALESOTHERBILLREFDETAILS'



SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = '15027'

prcOth_Bill_Before_MainSave




INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    COLUMNHEAD,CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT  HSNCODE, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'C' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY HSNCODE
UNION ALL
SELECT   HSNCODE,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'C' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
GROUP BY HSNCODE
UNION ALL
SELECT HSNCODE,CHARGETYPE,CHARGESHORTNAME,'C' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY HSNCODE,CHARGETYPE,CHARGESHORTNAME


SELECT DESCRIPTION 
FROM GTT_SALESBILLSUMMARY_GRPWISE A, GSTHSNMASTER B
WHERE TAG='B'

UPDATE GTT_SALESBILLSUMMARY_GRPWISE A SET
COLUMNDESC = 
(
    SELECT DESCRIPTION FROM GSTHSNMASTER WHERE A.COLUMNHEAD = HSNCODE 
)
WHERE TAG='B'

AND A.COLUMNHEAD = B.HSNCODE




SELECT * FROM GSTHSNMASTER




--------TAG  B -----------GRAND TOTAL

INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)


SELECT  QUALITYGROUPCODE, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'B' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY QUALITYGROUPCODE
UNION ALL
SELECT   QUALITYGROUPCODE,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'B' TAG, SUM(A.TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY QUALITYGROUPCODE
UNION ALL
SELECT QUALITYGROUPCODE,CHARGETYPE,CHARGESHORTNAME,'B' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY QUALITYGROUPCODE,CHARGETYPE,CHARGESHORTNAME

SELECT * FROM SALESBILLVIEW 



UPDATE GTT_SALESBILLSUMMARY_GRPWISE A SET
COLUMNDESC = 
(
    SELECT QUALITYTYPENAME FROM SALESQUALITYTYPEMASTER WHERE A.COLUMNHEAD = QUALITYTYPECODE 
)
WHERE TAG='B'





SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='3027'



-----------------------------------------------------------------------

-----------------------------------------------------------------------


delete GTT_SALESBILLSUMMARY_GRPWISE


--------TAG A -----------GRAND TOTAL

INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT   'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'A' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
UNION ALL
SELECT   'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'A' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
UNION ALL
SELECT CHARGETYPE,CHARGESHORTNAME,'A' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY CHARGETYPE,CHARGESHORTNAME


-----------------------------------------------------------------------
--------TAG  B -----------SALE A/C GROUP WISE
-----------------------------------------------------------------------


INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    COLUMNHEAD,CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT  QUALITYGROUPCODE, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'B' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY QUALITYGROUPCODE
UNION ALL
SELECT   QUALITYGROUPCODE,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'B' TAG, SUM(A.TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY QUALITYGROUPCODE
UNION ALL
SELECT QUALITYGROUPCODE,CHARGETYPE,CHARGESHORTNAME,'B' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY QUALITYGROUPCODE,CHARGETYPE,CHARGESHORTNAME




UPDATE GTT_SALESBILLSUMMARY_GRPWISE A SET
COLUMNDESC = 
(
    SELECT QUALITYTYPENAME FROM SALESQUALITYTYPEMASTER WHERE A.COLUMNHEAD = QUALITYTYPECODE 
)
WHERE TAG='B'


-----------------------------------------------------------------------
--------TAG  C ----------- HSNCODE GROUP WISE
-----------------------------------------------------------------------



INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    COLUMNHEAD,CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT  HSNCODE, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'C' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY HSNCODE
UNION ALL
SELECT   HSNCODE,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'C' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
GROUP BY HSNCODE
UNION ALL
SELECT HSNCODE,CHARGETYPE,CHARGESHORTNAME,'C' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY HSNCODE,CHARGETYPE,CHARGESHORTNAME


SELECT DESCRIPTION 
FROM GTT_SALESBILLSUMMARY_GRPWISE A, GSTHSNMASTER B
WHERE TAG='C'

UPDATE GTT_SALESBILLSUMMARY_GRPWISE A SET
COLUMNDESC = 
(
    SELECT DESCRIPTION FROM GSTHSNMASTER WHERE A.COLUMNHEAD = HSNCODE 
)
WHERE TAG='C'



-----------------------------------------------------------------------
--------TAG  D ----------- ITEM WISE GROUP 
----------------------------------------------------------------------- 


INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    COLUMNHEAD,COLUMNDESC,CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT  A.QUALITYCODE, A.QUALITYMANUALDESC, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'D' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY A.QUALITYCODE,A.QUALITYMANUALDESC
UNION ALL
SELECT QUALITYCODE,QUALITYMANUALDESC,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'D' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
GROUP BY QUALITYCODE,QUALITYMANUALDESC
UNION ALL
SELECT QUALITYCODE,QUALITYMANUALDESC,CHARGETYPE,CHARGESHORTNAME,'D' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY QUALITYCODE,QUALITYMANUALDESC,CHARGETYPE,CHARGESHORTNAME

 
-----------------------------------------------------------------------
--------TAG  E ----------- ITEM WISE GROUP 
----------------------------------------------------------------------- 


INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    COLUMNHEAD,COLUMNDESC,CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)
SELECT  A.BUYERCODE, A.QUALITYMANUALDESC, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'E' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY A.BUYERCODE,A.QUALITYMANUALDESC
UNION ALL
SELECT BUYERCODE,QUALITYMANUALDESC,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'E' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
GROUP BY BUYERCODE,QUALITYMANUALDESC
UNION ALL
SELECT BUYERCODE,QUALITYMANUALDESC,CHARGETYPE,CHARGESHORTNAME,'E' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY BUYERCODE,QUALITYMANUALDESC,CHARGETYPE,CHARGESHORTNAME

 

SELECT * FROM PARTYMASTER
WHERE PARTYCODE='AG069' 


UPDATE GTT_SALESBILLSUMMARY_GRPWISE A SET
COLUMNDESC = 
(
    SELECT PARTYSHORTNAME FROM PARTYMASTER WHERE A.COLUMNHEAD = PARTYCODE 
)
WHERE TAG='E'


-----------------------------------------------------------------------
--------UPDATE CHARGE SHORTNAME 
-----------------------------------------------------------------------


UPDATE GTT_SALESBILLSUMMARY_GRPWISE SET SLNO = 
CASE WHEN CHARGESHORTNAME LIKE '%QUANTITY%' THEN 1
    WHEN  CHARGESHORTNAME LIKE '%AMOUNT%' THEN 2
    WHEN  CHARGESHORTNAME LIKE 'PRINT%' THEN 3
    WHEN  CHARGESHORTNAME LIKE '%HANDLING%' THEN 4
    WHEN  CHARGESHORTNAME LIKE '%CGST%' THEN 5
    WHEN  CHARGETYPE LIKE '%SGST%' THEN 6
    WHEN  CHARGETYPE LIKE '%IGST%' THEN 7
    WHEN  CHARGETYPE LIKE '%TCS%' THEN 8
    ELSE 9
    END
    

-----------------------------------------------------------------------

SELECT TAG,CHARGESHORTNAME, SUM(AMOUNTVALUE) FROM GTT_SALESBILLSUMMARY_GRPWISE
--WHERE TAG='B'
GROUP BY TAG,CHARGESHORTNAME

UPDATE GTT_SALESBILLSUMMARY_GRPWISE  A SET SUMAMOUNT=
(
    SELECT SUMAMOUNT FROM (
        SELECT TAG,CHARGESHORTNAME, SUM(AMOUNTVALUE) SUMAMOUNT FROM GTT_SALESBILLSUMMARY_GRPWISE
        GROUP BY TAG,CHARGESHORTNAME
    )
    WHERE A.TAG=TAG
    AND A.CHARGESHORTNAME = CHARGESHORTNAME
)


SELECT * FROM GTT_SALESBILLSUMMARY_GRPWISE
where tag='F'


SELECT TAG,columnhead,CHARGESHORTNAME, SUM(AMOUNTVALUE) SUMAMOUNT FROM GTT_SALESBILLSUMMARY_GRPWISE
where tag='F'
and CHARGESHORTNAME='QUANTITY'
GROUP BY TAG,columnhead,CHARGESHORTNAME

SELECT * FROM GTT_SALESBILLSUMMARY_GRPWISE
where tag='F'
and CHARGESHORTNAME='QUANTITY'
AND COLUMNHEAD='AY006'
        
        
-----------------------------------------------------------------------



EXEC PROC_SALESBILLSUMMARY_GRPWISE('DJ0107','0002','01/04/2021','02/04/2021','','','GST BILL','ALL')


SELECT STARTDATE FROM FINANCIALYEAR
WHERE TO_DATE('04/09/2021','DD/MM/YYYY') BETWEEN STARTDATE AND ENDDATE
AND ROWNUM=1


SELECT '01'||SUBSTR('18/05/2020',3), LAST_DAY(TO_DATE('18/05/2020','DD/MM/YYYY')) FROM DUAL



WHERE TO_DATE('04/09/2021','DD/MM/YYYY') BETWEEN STARTDATE AND ENDDATE
AND ROWNUM=1


SELECT * FROM SALESBILLVIEW
WHERE SALEBILLDATE > '01-APR-2021'


 


EXEC PROC_SALESBILLREGISTERALL('DJ0107','0002','01/04/2021','30/04/2021','','','GST BILL','ALL')
 
    PROC_SALESBILLREGISTERALL(p_companycode,p_divisioncode,lv_MonStartDate,lv_MonEndDate,p_channel,p_buyer,p_type,p_option);
    
 SELECT * FROM GTT_SALESBILLREGISTERALL   WHERE BUYERCODE='AY006'
    
INSERT INTO GTT_SALESBILLSUMMARY_GRPWISE
(
    COLUMNHEAD,COLUMNDESC,CHARGETYPE, CHARGESHORTNAME, TAG, AMOUNTVALUE
)


SELECT * FROM SALESBILLVIEW WHERE BUYERCODE='AY006'

SELECT  A.BUYERCODE, A.QUALITYMANUALDESC, 'QUANTITY' CHARGETYPE,'QUANTITY' CHARGESHORTNAME,'F' TAG,
SUM(B.TOTALQUANTITY) AMOUNTVALUE
FROM GTT_SALESBILLREGISTERALL A, SALESBILLVIEW B
WHERE A.SALEBILLNO=B.SALEBILLNO
GROUP BY A.BUYERCODE,A.QUALITYMANUALDESC
UNION ALL
SELECT BUYERCODE,QUALITYMANUALDESC,'BASIC VALUE' CHARGETYPE,'AMOUNT' CHARGESHORTNAME,'F' TAG, SUM(TOTALINDIANAMOUNT) 
FROM GTT_SALESBILLREGISTERALL 
GROUP BY BUYERCODE,QUALITYMANUALDESC
UNION ALL
SELECT BUYERCODE,QUALITYMANUALDESC,CHARGETYPE,CHARGESHORTNAME,'F' TAG,SUM(CHARGEAMOUNT) 
FROM GTT_SALESBILLREGISTERALL
GROUP BY BUYERCODE,QUALITYMANUALDESC,CHARGETYPE,CHARGESHORTNAME;