
SELECT * FROM JUTEPURCHASEORDERMASTER 


CREATE TABLE JUTEARRIVALMAST_TEST AS
SELECT * FROM JUTEARRIVALMAST
WHERE ARRIVALNO='L/JAR/21/00287'


CREATE TABLE JUTEARRIVALDETAILS_TEST AS
SELECT * FROM JUTEARRIVALDETAILS
WHERE ARRIVALNO='L/JAR/21/00287'

SELECT * FROM SYS_TFMAP WHERE SYS_TABLENAME_ACTUAL='JUTEARRIVALDETAILS'

SELECT * FROM JUTEARRIVALMAST_TEST


SELECT * FROM JUTEARRIVALDETAILS_TEST


SELECT * FROM JUTEPURCHASEORDERMASTER 
WHERE ORDERNO='G/JPO/21/00014'

SELECT * FROM JUTEPURCHASEORDERDETAILS
WHERE ORDERNO='G/JPO/21/00014'


PRCJUTEARR_BEFORE_MAINSAVE


---------------------------------------------------------------------------------
--add new menu
---------------------------------------------------------------------------------

select * from menumaster_rnd
where menucode='01020213'

SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01020213', NULL, 'Arrival Details without PO', 'TRANSACTIONS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'JUTE', NULL, 
    NULL, '''0001''', NULL, 'JUTE/Pages/Transaction/pgRawJuteArrival_without_PO.aspx', NULL, 
    NULL, 'prcJuteArr_Before_MainSave', NULL, 'Y', 'N', 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '01020213', 'Y', 'Y', 'Y', 
    'X', 'X', 'Y', 'X', 'JUTE', 
    '201904042021190011822202');
COMMIT;


SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0102020105', NULL, 'Purchase Order (Dummy)', 'TRANSACTIONS', 'PURCHASE ORDER DUMMY', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'JUTE', NULL, 
    NULL, '''0001''', NULL, 'JUTE/Pages/Transaction/pgJUTEPURCHASEORDER_BS.aspx', NULL, 
    NULL, 'prcJutePODummy_Before_MainSave', NULL, 'Y', 'N', 
    NULL, NULL);
COMMIT;

prcJutePO_Before_MainSave

SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '0102020105', 'Y', 'Y', 'Y', 
    'X', 'X', 'Y', 'X', 'JUTE', 
    '201904042021190011822202');
COMMIT;



---------------------------------------------------------------------------------
-- add sys parameter data
---------------------------------------------------------------------------------

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL DETAILS COLUMN TO BE CHANGE', 'ARRIVAL DETAILS COLUMN TO BE CHANGE', 'ORDERNO,ORDERDATE,PRIVATEMARKPO,MILLGRDCODEPO,MKTGRDCODEPO,CROPYEARASPERPO,BALETYPE,ORDERSERIALNO', 'JUTE', 'LJ0054', 
    TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0001', 'SWT', 'SWT TO SET');

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL MASTER COLUMN TO BE CHANGE', 'ARRIVAL MASTER COLUMN TO BE CHANGE', 'ORDERNO,ORDERDATE,BROKERCODE,REGIONCODE,BOOKINGSTATION,CONTRACTNO,CONTRACTDATE ', 'JUTE', 'LJ0054', 
    TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0001', 'SWT', 'SWT TO SET');
COMMIT;

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('ARRIVAL DUMMY PO PREFIX', 'ARRIVAL DUMMY PO PREFIX', 'DUMMY', 'JUTE', 
    'LJ0054', TO_DATE('02/28/2015 22:48:42', 'MM/DD/YYYY HH24:MI:SS'), '4', '0001', 'SWT', 
    'SWT TO SET');
COMMIT;



---------------------------------------------------------------------------------


  update SYS_TFMAP set SYS_KEYCOLUMN='N'
  WHERE SYS_TABLENAME_ACTUAL = 'JUTEARRIVALDETAILS'
  AND SYS_TABLE_SEQUENCIER='1026'
  AND SYS_COLUMNNAME='SYSROWID'
  
  
  EXEC PROC_CREATE_GBL_TMP_TABLES(1026,0)

---------------------------------------------------------------------------------


select * from sys_autogen_params
where param_name LIKE 'RAW_JUTE_PURCHASE_ORDER%'

SET DEFINE OFF;
Insert into SYS_AUTOGEN_PARAMS
   (COMPANYCODE, DIVISIONCODE, YEARCODE, PARAM_NAME, TOT_LENGTH, PREFIX, SUFFIX, ACT_TABLENAME, ACT_COL_NAME, PADDING_LENGTH, SEQUENCER_NAME, PURPOSE)
 Values
   ('LJ0054', '0001', '2020-2021', 'RAW_JUTE_PURCHASE_ORDER_DUMMY', 14, 
    'DUMMY/<<Y2>>/', NULL, 'JUTEPURCHASEORDERMASTER', 'ORDERNO', 5, 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (1023, 'NONE', 'GBL_JUTEPURCHASEORDERMASTER', 'ISDUMMY', 
    8, 'VARCHAR2', 1, 0, 'N', 
    'txtISDUMMY', TO_TIMESTAMP('08/11/2014 11:20:59.000000 AM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;


---------------------------------------------------------------------------------

SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (1020, '""', 'COMPANYCODE~DIVISIONCODE~ARRIVALDATE~PATTERN', 'P.O. INFORMATION FOR JUTE ARRIVAL', NULL, 
    'SELECT ORDERNO, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') ORDERDATE, SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND A.TRANSACTIONDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO, A.ORDERDATE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND B.ARRIVALDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO,A.ORDERDATE
) 
WHERE 1=1
GROUP BY ORDERNO, ORDERDATE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO
', 'ORDERNO~', 'JUTE');
COMMIT;


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='1121'

QRY_ID='1021'


SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (1120, '""', 'COMPANYCODE~DIVISIONCODE~ARRIVALDATE~PATTERN', 'P.O. INFORMATION FOR JUTE ARRIVAL', NULL, 
    'SELECT ORDERNO, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') ORDERDATE, SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND A.TRANSACTIONDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO, A.ORDERDATE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND B.ARRIVALDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO,A.ORDERDATE
) 
WHERE 1=1
GROUP BY ORDERNO, ORDERDATE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO
', 'ORDERNO~', 'JUTE');
COMMIT;


SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (1121, '""', 'COMPANYCODE~DIVISIONCODE~ARRIVALDATE~REGIONCODE~PATTERN', 'P.O. INFORMATION FOR JUTE ARRIVAL', NULL, 
    'SELECT ORDERNO,REGIONCODE, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, B.REGIONCODE, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') ORDERDATE, 
        SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, 
        SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND A.TRANSACTIONDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO, A.ORDERDATE,B.REGIONCODE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,B.REGIONCODE, TO_CHAR(A.ORDERDATE,''DD/MM/YYYY'') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE =  <<DIVISIONCODE>>
          AND B.ARRIVALDATE <= TO_DATE(<<ARRIVALDATE>>,''DD/MM/YYYY'')
        GROUP BY A.ORDERNO,A.ORDERDATE,B.REGIONCODE
) 
WHERE 1=1
 AND REGIONCODE =NVL(<<REGIONCODE>>,REGIONCODE)
GROUP BY ORDERNO, ORDERDATE,REGIONCODE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO
', 'ORDERNO~REGIONCODE~', 'JUTE');
COMMIT;



---------------------------------------------------------------------------------

ALTER TABLE gbl_JutePurchaseOrderMaster ADD ISDUMMY VARCHAR2(1)


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER = '1023'

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = ''


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_JUTEPURCHASEORDERMASTER'


---------------------------------------------------------------------------------

SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='1020'

---------------------------------------------------------------------------------

SELECT * FROM VW_RUKA_STOCK_DETAILS_DUMMY

SELECT ORDERNO,REGIONCODE, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, B.REGIONCODE, TO_CHAR(A.ORDERDATE,'DD/MM/YYYY') ORDERDATE, 
        SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, 
        SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = 'LJ0054'
          AND A.DIVISIONCODE = '0001'
          AND A.TRANSACTIONDATE <= TO_DATE('06/03/2021','DD/MM/YYYY')
        GROUP BY A.ORDERNO, A.ORDERDATE,B.REGIONCODE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,B.REGIONCODE, TO_CHAR(A.ORDERDATE,'DD/MM/YYYY') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = 'LJ0054'
          AND A.DIVISIONCODE =  '0001'
          AND B.ARRIVALDATE <= TO_DATE('06/03/2021','DD/MM/YYYY')
        GROUP BY A.ORDERNO,A.ORDERDATE,B.REGIONCODE
) 
WHERE 1=1
 AND REGIONCODE =<<REGIONCODE>>
GROUP BY ORDERNO, ORDERDATE,REGIONCODE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO


---------------------------------------------------------------------------------

SELECT ORDERNO,REGIONCODE, ORDERDATE, SUM(BALANCEUNIT) AS BALANCEUNIT, SUM(BALANCEQTY) AS BALANCEQTY
FROM ( 
        SELECT A.ORDERNO, B.REGIONCODE, TO_CHAR(A.ORDERDATE,'DD/MM/YYYY') ORDERDATE, 
        SUM(A.BALES_ORDERED - A.BALES_RECEIVED - A.BALES_CANC_ADJ) BALANCEUNIT, 
        SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) BALANCEQTY 
        FROM VW_RUKA_STOCK_DETAILS_DUMMY A, JUTEPURCHASEORDERMASTER B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ORDERNO = B.ORDERNO
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE = <<DIVISIONCODE>>
          AND A.TRANSACTIONDATE <= TO_DATE(<<ARRIVALDATE>>,'DD/MM/YYYY')
        GROUP BY A.ORDERNO, A.ORDERDATE,B.REGIONCODE
        HAVING SUM(A.QTY_ORDERED - A.QTY_RECEIVED - A.QTY_CANC_ADJ) >0
        UNION ALL
        SELECT A.ORDERNO,B.REGIONCODE, TO_CHAR(A.ORDERDATE,'DD/MM/YYYY') AS ORDERDATE,-SUM(NVL(A.NOOFBALES,0)) AS BALANCEUNIT,-SUM(NVL(A.CHALLANWTINQT,0)) AS BALANCEQTY  
        FROM JUTEARRIVALDETAILS A, JUTEARRIVALMAST B
        WHERE A.COMPANYCODE = B.COMPANYCODE
          AND A.DIVISIONCODE = B.DIVISIONCODE
          AND A.ARRIVALNO = B.ARRIVALNO
          AND A.ARRIVALNO NOT IN (SELECT ARRIVALNO FROM JUTEMILLRECEIPTMAST)
          AND A.COMPANYCODE = <<COMPANYCODE>>
          AND A.DIVISIONCODE =  <<DIVISIONCODE>>
          AND B.ARRIVALDATE <= TO_DATE(<<ARRIVALDATE>>,'DD/MM/YYYY')
        GROUP BY A.ORDERNO,A.ORDERDATE,B.REGIONCODE
) 
WHERE 1=1
 AND REGIONCODE =<<REGIONCODE>>
GROUP BY ORDERNO, ORDERDATE,REGIONCODE
HAVING SUM(BALANCEQTY) > 0
ORDER BY ORDERNO


---------------------------------------------------------------------------------