

CREATE TABLE GPSARREARDAILYPAYSHEETDETAILS
AS
SELECT * FROM GPSDAILYPAYSHEETDETAILS
WHERE 1=2

GPSARREARDAILYPAYSHEETDETAILS


INSERT INTO GPSARREARDAILYPAYSHEETDETAILS


SELECT * FROM GPSDAILYPAYSHEETDETAILS
WHERE PERIODFROM BETWEEN '01-OCT-2020' AND '31-OCT-2020'
AND CLUSTERCODE='ZB'
AND TOKENNO='K00641'


SELECT * FROM GPSARREARDAILYPAYSHEETDETAILS

UPDATE GPSARREARDAILYPAYSHEETDETAILS
SET PROCESSTYPE='NEW DAILY PROCESS'

UPDATE GPSARREARDAILYPAYSHEETDETAILS
SET DAILYWAGES = 120,
GROSSWAGES = 120,
PF_GROSS = 120








SELECT TOKENNO,PERIODFROM,'DAILY ARREAR PROCESS' PROCESSTYPE, 

SELECT TOKENNO,'DAILY ARREAR PROCESS' PROCESSTYPE, 
SUM(GROSSWAGES) GROSSWAGES, SUM(PF_GROSS) PF_GROSS, SUM(DAILYWAGES) DAILYWAGES
FROM
(
    SELECT TOKENNO,PERIODFROM, GROSSWAGES,PF_GROSS,DAILYWAGES 
    FROM GPSARREARDAILYPAYSHEETDETAILS
    WHERE PERIODFROM BETWEEN '01-OCT-2020' AND '31-OCT-2020'
    AND CLUSTERCODE='ZB'
    AND PROCESSTYPE='NEW DAILY PROCESS'
--    AND TOKENNO='K00641'
    UNION ALL
    SELECT TOKENNO,PERIODFROM, GROSSWAGES*-1,PF_GROSS*-1,DAILYWAGES*-1 
    FROM GPSDAILYPAYSHEETDETAILS
    WHERE PERIODFROM BETWEEN '01-OCT-2020' AND '31-OCT-2020'
    AND CLUSTERCODE='ZB'
     AND PROCESSTYPE='DAILY PROCESS'
--    AND TOKENNO='K00641'
)
GROUP BY TOKENNO  
ORDER BY TOKENNO

GROSSWAGES,PF_GROSS,DAILYWAGES

SELECT * FROM GPSCOMPONENTMAST
WHERE INCLUDEARREAR='Y'


SELECT WM_CONCAT(COMPONENTCODE) FROM GPSCOMPONENTMAST
WHERE INCLUDEARREAR='Y'
ORDER BY CALCULATIONINDEX

LALW_AL,LALW_SL,BASIC,DAILYWAGES,INCENTIVE

SELECT WM_CONCAT(COMPONENTCODE),
WM_CONCAT('SUM(NVL('||COMPONENTCODE||',0)) '||COMPONENTCODE),
WM_CONCAT('SUM(NVL('||COMPONENTCODE||',0))*-1 '||COMPONENTCODE) 
FROM GPSCOMPONENTMAST
WHERE INCLUDEARREAR='Y'
ORDER BY PHASE,CALCULATIONINDEX

LALW_AL,LALW_SL,BASIC,DAILYWAGES,INCENTIVE




SUM(NVL(LALW_AL,0)) LALW_AL,SUM(NVL(LALW_SL,0)) LALW_SL,SUM(NVL(BASIC,0)) BASIC,SUM(NVL(DAILYWAGES,0)) DAILYWAGES,SUM(NVL(INCENTIVE,0)) INCENTIVE



LALW_AL,LALW_SL,BASIC,DAILYWAGES,INCENTIVE	

SUM(NVL(LALW_AL,0)) LALW_AL,SUM(NVL(LALW_SL,0)) LALW_SL,SUM(NVL(BASIC,0)) BASIC,SUM(NVL(DAILYWAGES,0)) DAILYWAGES,SUM(NVL(INCENTIVE,0)) INCENTIVE	

SUM(NVL(LALW_AL,0))*-1 LALW_AL,SUM(NVL(LALW_SL,0))*-1 LALW_SL, SUM(NVL(BASIC,0))*-1 BASIC, SUM(NVL(DAILYWAGES,0))*-1 DAILYWAGES,SUM(NVL(INCENTIVE,0))*-1 INCENTIVE

