Insert into ASIANTEA.MENUMASTER_RND
   (MENUCODE, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, 
    ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, 
    ACTIVE, PROJECTNAME, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, URLSRC, 
    VIEWPOSSIBLE, PRINTPOSSIBLE)
 Values
   ('01100402030133', 'Ration Sheet', 'REPORTS', 'ASIANTEA LIGRIPOOKRIE REPORT', 'RATION SHEET', 
    'X', 'X', 'X', 'Y', 'X', 
    'Y', 'GPS', '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', 'GPS/Pages/Report/pgReportGPSTemplate.aspx', 
    'Y', 'X');
COMMIT;
