SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('wage%PRO%')
and MENUTYPE ='TRANSACTION'

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE LIKE '01100308'


SELECT * FROM ROLEDETAILS
WHERE MENUCODE='01100307'


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''


PRCGPSWAGESPROCESS_B4SAVE


PRCGPSWAGESPROCESS_B4SAVE



select COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, CALCULATIONINDEX, PARAM_1, PARAM_2, PARAM_3 
from WAGESPROCESSTYPE_PHASE  
where COMPANYCODE = 'BDBR01' and DIVISIONCODE = '0002'
and PROCESSTYPE = 'DAILY'
ORDER BY PHASE, CALCULATIONINDEX

SELECT DISTINCT PROCESSTYPE
from WAGESPROCESSTYPE_PHASE  


SELECT * FROM GPS


Insert into KARNAFULI.MENUMASTER_RND
   (MENUCODE, MENUDESC, MENUTYPE, MENUTAG, MENUTAG2, 
    ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, 
    ACTIVE, PROJECTNAME, EFFECTIVEINDIVISION, URLSRC, FUNCTIONCALL_BEFORE, 
    VIEWPOSSIBLE, PRINTPOSSIBLE)
 Values
   ('01100309', 'Daily Arrear Process', 'TRANSACTION', 'ARREAR', 'GPS', 
    'Y', 'X', 'X', 'X', 'X', 
    'N', 'GPS', '''0002''', 'GPS/Pages/Transaction/pgRATIONWAGESPROCESS.aspx', 'PRCGPSWAGESPROCESS_B4SAVE', 
    'X', 'X');
COMMIT;



Insert into KARNAFULI.ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, 
    ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, 
    SYSROWID)
 Values
   ('1', '01100309', 'Y', 'X', 'X', 
    'X', 'X', 'X', 'X', 'GPS', 
    '0110030720190213120344');
Insert into KARNAFULI.ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, 
    ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, 
    SYSROWID)
 Values
   ('4', '01100309', 'Y', 'N', 'N', 
    'N', 'N', 'N', 'N', 'GPS', 
    '201811081845210002396310');
COMMIT;



CREATE TABLE WAGESPROCESSTYPE_PHASE_BK
AS
SELECT * FROM WAGESPROCESSTYPE_PHASE

--------------------------------------------------------------------------------

Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSMATERNITY_RATE_UPDT', 0, 
    1, 'SWT_GPS_PHASE_0_1', 'GPSDAILYPAYSHEETDETAILS_SWT');
Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSWAGESPROCESS_INSERT', 0, 
    10, 'SWT_GPS_PHASE_0', 'GPSDAILYPAYSHEETDETAILS_SWT');
Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSINCENTIVE_CALC', 1, 
    15, 'GPSINCENTIVEDETAILS', 'GPSDAILYPAYSHEETDETAILS_SWT');
Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSWAGESPROCESS_UPDATE', 1, 
    30, 'SWT_GPS_PHASE_1', 'GPSDAILYPAYSHEETDETAILS_SWT');
Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSWAGESPROCESS_UPDATE', 2, 
    40, 'SWT_GPS_PHASE_2', 'GPSDAILYPAYSHEETDETAILS_SWT');
Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSWAGESPROCESS_UPDATE', 4, 
    60, 'SWT_GPS_PHASE_4', 'GPSDAILYPAYSHEETDETAILS_SWT');
Insert into KARNAFULI.WAGESPROCESSTYPE_PHASE
   (COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, 
    CALCULATIONINDEX, PARAM_1, PARAM_2)
 Values
   ('BDBR01', '0002', 'ARREAR', 'PROC_GPSWAGESPROCESS_TRANSFER', 100, 
    100, 'GPSDAILYPAYSHEETDETAILS_SWT', 'GPSARREARDAILYPAYSHEETDETAILS');
COMMIT;

SELECT * FROM GPSARREARDAILYPAYSHEETDETAILS




select COMPANYCODE, DIVISIONCODE, PROCESSTYPE, PROCEDURE_NAME, PHASE, CALCULATIONINDEX, PARAM_1, PARAM_2, PARAM_3 
from WAGESPROCESSTYPE_PHASE  
where COMPANYCODE = 'BDBR01' and DIVISIONCODE = '0002'
and PROCESSTYPE = 'ARREAR'
ORDER BY PHASE, CALCULATIONINDEX


--------------------------------------------------------------------------------
--ALL PROCEDURES
--------------------------------------------------------------------------------

PROC_GPSMATERNITY_RATE_UPDT
PROC_GPSWAGESPROCESS_INSERT
PROC_GPSINCENTIVE_CALC
PROC_GPSWAGESPROCESS_UPDATE
PROC_GPSWAGESPROCESS_UPDATE
PROC_GPSWAGESPROCESS_UPDATE
PROC_GPSWAGESPROCESS_TRANSFER


select count(*) from GPSWAGEDPERIODDECLARATION 
where FORTNIGHTSTARTDATE= TO_DATE('06/11/2020','DD/MM/YYYY') and FORTNIGHTENDDATE= TO_DATE('06/11/2020','DD/MM/YYYY')


SELECT * FROM GPSWAGEDPERIODDECLARATION





SELECT * FROM 
GPSDAILYPAYSHEETDETAILS_SWT

DELETE FROM GPS_ERROR_LOG


SELECT * FROM GPS_ERROR_LOG



CREATE TABLE GBL_GPSWAGEPROCESS_TMP
AS


SELECT * FROM GBL_GPSWAGEPROCESS;

INSERT INTO GBL_GPSWAGEPROCESS
SELECT * FROM GBL_GPSWAGEPROCESS_TMP;

EXEC prcGPSWAGESPROCESS_B4SAVE

EXEC PROC_GPSMATERNITY_RATE_UPDT('BDBR01','0002','ARREAR','2020-2021','28/10/2020','28/10/2020','28/10/2020','0','SWT_GPS_PHASE_0_1','GPSDAILYPAYSHEETDETAILS_SWT','','WORKER','','')

EXEC PROC_GPSWAGESPROCESS_INSERT('BDBR01','0002','ARREAR','2020-2021','28/10/2020','28/10/2020','28/10/2020','0','SWT_GPS_PHASE_0','GPSDAILYPAYSHEETDETAILS_SWT','','WORKER','','')

EXEC PROC_GPSWAGESPROCESS_UPDATE('BDBR01','0002','ARREAR','2020-2021','28/10/2020','28/10/2020','28/10/2020','1','SWT_GPS_PHASE_1','GPSDAILYPAYSHEETDETAILS_SWT','','WORKER','','')

EXEC PROC_GPSWAGESPROCESS_UPDATE('BDBR01','0002','ARREAR','2020-2021','28/10/2020','28/10/2020','28/10/2020','2','SWT_GPS_PHASE_2','GPSDAILYPAYSHEETDETAILS_SWT','','WORKER','','')

EXEC PROC_GPSWAGESPROCESS_UPDATE('BDBR01','0002','ARREAR','2020-2021','28/10/2020','28/10/2020','28/10/2020','4','SWT_GPS_PHASE_4','GPSDAILYPAYSHEETDETAILS_SWT','','WORKER','','')

EXEC PROC_GPSWAGESPROCESS_TRANSFER('BDBR01','0002','ARREAR','2020-2021','28/10/2020','28/10/2020','28/10/2020','100','GPSDAILYPAYSHEETDETAILS_SWT','GPSARREARDAILYPAYSHEETDETAILS','','WORKER','','')
  


DELETE FROM GPSDAILYPAYSHEETDETAILS_SWT

SELECT * FROM GPSDAILYPAYSHEETDETAILS_SWT




DELETE FROM GPS_ERROR_LOG


SELECT * FROM GPS_ERROR_LOG

PROC_GPSVIEWCREATION





INSERT INTO GPSARREARDAILYPAYSHEETDETAILS
(
    COMPANYCODE, DIVISIONCODE,YEARCODE,PERIODFROM,PERIODTO,ATTENDANCEDATE,
    WORKERSERIAL, TOKENNO,CATEGORYCODE,CATEGORYTYPE, OCCUPATIONCODE, CLUSTERCODE,  ATTNBOOKCODE,
    PROCESSTYPE, 
LALW_AL,LALW_SL,BASIC,DAILYWAGES,INCENTIVE
)
SELECT COMPANYCODE, DIVISIONCODE,'2020-2021' YEARCODE,TO_DATE('01/10/2020','DD/MM/YYYY') PERIODFROM,TO_DATE('30/10/2020','DD/MM/YYYY') PERIODTO,TO_DATE('30/10/2020','DD/MM/YYYY') ATTENDANCEDATE,
A.WORKERSERIAL, A.TOKENNO,B.CATEGORYCODE,A.CATEGORYTYPE, B.OCCUPATIONCODE, B.CLUSTERCODE,  B.ATTNBOOKCODE,
'DAILY ARREAR PROCESS' PROCESSTYPE, 
SUM(NVL(LALW_AL,0)) LALW_AL,SUM(NVL(LALW_SL,0)) LALW_SL,SUM(NVL(BASIC,0)) BASIC,SUM(NVL(DAILYWAGES,0)) DAILYWAGES,SUM(NVL(INCENTIVE,0)) INCENTIVEFROM
(
    SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, 
    ATTENDANCEDATE, WORKERSERIAL, TOKENNO, CATEGORYCODE, CATEGORYTYPE, 
    OCCUPATIONCODE, CLUSTERCODE, AREACLASSIFICATIONCODE, ATTNBOOKCODE, 
SUM(NVL(LALW_AL,0)) LALW_AL,SUM(NVL(LALW_SL,0)) LALW_SL,SUM(NVL(BASIC,0)) BASIC,SUM(NVL(DAILYWAGES,0)) DAILYWAGES,SUM(NVL(INCENTIVE,0)) INCENTIVE    FROM GPSARREARDAILYPAYSHEET_TEMP
    WHERE PERIODFROM BETWEEN TO_DATE('01/10/2020','DD/MM/YYYY') AND TO_DATE('30/10/2020','DD/MM/YYYY')
    AND PROCESSTYPE='NEW DAILY PROCESS'
    GROUP BY COMPANYCODE, DIVISIONCODE, YEARCODE, 
    ATTENDANCEDATE, WORKERSERIAL, TOKENNO, CATEGORYCODE, CATEGORYTYPE, 
    OCCUPATIONCODE, CLUSTERCODE, AREACLASSIFICATIONCODE, ATTNBOOKCODE
    UNION ALL
    SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, 
    ATTENDANCEDATE, WORKERSERIAL, TOKENNO, CATEGORYCODE, CATEGORYTYPE, 
    OCCUPATIONCODE, CLUSTERCODE, AREACLASSIFICATIONCODE, ATTNBOOKCODE, 
SUM(NVL(LALW_AL,0))*-1 LALW_AL,SUM(NVL(LALW_SL,0))*-1 LALW_SL,SUM(NVL(BASIC,0))*-1 BASIC,SUM(NVL(DAILYWAGES,0))*-1 DAILYWAGES,SUM(NVL(INCENTIVE,0))*-1 INCENTIVE    FROM GPSDAILYPAYSHEETDETAILS_PREV
    WHERE PERIODFROM BETWEEN TO_DATE('01/10/2020','DD/MM/YYYY') AND TO_DATE('30/10/2020','DD/MM/YYYY')
     AND PROCESSTYPE='DAILY PROCESS'
     GROUP BY COMPANYCODE, DIVISIONCODE, YEARCODE, 
    ATTENDANCEDATE, WORKERSERIAL, TOKENNO, CATEGORYCODE, CATEGORYTYPE, 
    OCCUPATIONCODE, CLUSTERCODE, AREACLASSIFICATIONCODE, ATTNBOOKCODE
) A, 
(
    SELECT WORKERSERIAL,TOKENNO, CATEGORYCODE, OCCUPATIONCODE, CLUSTERCODE,  ATTNBOOKCODE FROM GPSEMPLOYEEMAST
) B
WHERE A.WORKERSERIAL=B.WORKERSERIAL
GROUP BY COMPANYCODE, DIVISIONCODE, YEARCODE, B.CATEGORYCODE,A.CATEGORYTYPE, B.OCCUPATIONCODE, 
B.CLUSTERCODE, B.ATTNBOOKCODE, A.WORKERSERIAL, A.TOKENNO


PRCGPSWAGESPROCESS_B4SAVE