SELECT RAW_TABLE_NAME, KEYCOLUMN1 FROM EXPIMPINF_EXCEL WHERE COMPANYCODE = 'NJ0001'
 AND DIVISIONCODE = '0002'
 
 AND IMPORTTAG = 'STAFF PF DATA UPLOAD'
 
 SELECT RAW_TABLE_NAME, KEYCOLUMN1 FROM EXPIMPINF_EXCEL WHERE COMPANYCODE = 'NJ0002'
 AND DIVISIONCODE = '0010'
 AND IMPORTTAG = 'STAFF PF DATA UPLOAD'
 
 SELECT * from EXPIMPINF_EXCEL
 
 WPSELECTRICRAWDATA
 
 SELECT * FROM WPSWAGESPARAMETER
 
 
 SELECT * FROM STAFFPFUPLOADRAWDATA


SELECT * FROM PFEMPLOYEEMASTER

PROC_STAFFPFUPLOADDATA_TRNSFER


ACT_PF_GRS, ADHOC, ADHOC_NPF, ATN_INCAMT, ATN_INCNT, ATTN_ADJD, ATTN_CALCF, ATTN_HOLD, ATTN_LDAY, ATTN_OFFD, ATTN_SALD, ATTN_TOTD, ATTN_WPAY, ATTN_WRKD, 

BASIC, CATEGORYCODE, CLUB, COMPANYCODE, CONV_ALOW, CONV_PERC, CUM_PFGROS, CUMM_DAYS, CUMM_PF_C, CUMM_PF_E, CUMM_VPF, DA, DEPARTMENTCODE, 


LIBL_FEADV, 
LIBL_OLADV, LIBL_OTADV, 

ALTER TABLE PISPAYTRANSACTION ADD LIBL_MPL NUMBER(15,2)

ALTER TABLE PISPAYTRANSACTION ADD LINT_MPL NUMBER(15,2)

ALTER TABLE PISPAYTRANSACTION ADD LNBL_MPL NUMBER(15,2)

ALTER TABLE PISPAYTRANSACTION ADD LOAN_MPL NUMBER(15,2) 


LINT_MPL 
LNBL_MPL 
LOAN_MPL 
 
 
 

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%staff%pf%upload%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='01110210'

pgPFStaffDataUploadDynamicQry


SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''