DROP TABLE NJMCL_WEB.PISSALARYUPLOADRAWDATA CASCADE CONSTRAINTS;

CREATE TABLE PISSALARYUPLOADRAWDATA
(
  COMPANYCODE   VARCHAR2(10 BYTE),
  DIVISIONCODE  VARCHAR2(10 BYTE),
  YEARCODE      VARCHAR2(10 BYTE),
  YEARMONTH     VARCHAR2(10 BYTE),
  UNITCODE       VARCHAR2(10 BYTE),
  CATEGORYCODE       VARCHAR2(10 BYTE),
  GRADECODE       VARCHAR2(10 BYTE),
  TOKENNO       VARCHAR2(10 BYTE),
  PFNO       VARCHAR2(10 BYTE),
  ATTN_SALD     NUMBER(10,2),
  NCP_DAYS      NUMBER(10,2),
  GROSSWAGES    NUMBER(15,2),
  PF_GROSS      NUMBER(15,2),
  PEN_GROSS     NUMBER(15,2),
  ESI_GROSS     NUMBER(15,2),
  PTAX_GROSS    NUMBER(15,2),
  PF_E          NUMBER(15,2),
  EPF           NUMBER(15,2),
  PF_C          NUMBER(15,2),
  PTAX          NUMBER(15,2),
  ESI_E         NUMBER(15,2),
  ESI_C         NUMBER(15,2),
  LOAN_MPL      NUMBER(15,2),
  LINT_MPL      NUMBER(15,2)
)
TABLESPACE NJMCL_WEB
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;



SELECT * FROM PISEMPLOYEEMASTER


SELECT * FROM PISSALARYUPLOADRAWDATA


SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, UNITCODE, CATEGORYCODE, GRADECODE, TOKENNO, PFNO, 
ATTN_SALD, NCP_DAYS, GROSSWAGES, PF_GROSS, PEN_GROSS, ESI_GROSS, PTAX_GROSS, PF_E, EPF, PF_C, PTAX, ESI_E, ESI_C, 
LOAN_MPL, LINT_MPL FROM PISSALARYUPLOADRAWDATA

SELECT * FROM PISPAYTRANSACTION

DELETE FROM PISPAYTRANSACTION

INSERT INTO PISPAYTRANSACTION
(
    COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH,EFFECT_YEARMONTH, UNITCODE, CATEGORYCODE, GRADECODE, DEPARTMENTCODE, TOKENNO, WORKERSERIAL,
    ATTN_SALD, ATTN_WPAY,ATTN_WRKD, GROSSEARN, PF_GROSS, PEN_GROSS, ESI_GROSS, PTAX_GROSS, PF_E, EPF, PF_C, PTAX, ESI_E, ESI_C, 
    LOAN_MPL, LINT_MPL, TRANSACTIONTYPE
)
SELECT A.COMPANYCODE, A.DIVISIONCODE, B.YEARCODE, YEARMONTH,YEARMONTH EFFECT_YEARMONTH, 
'01' UNITCODE, A.CATEGORYCODE, A.GRADECODE, A.DEPARTMENTCODE, A.TOKENNO , A.WORKERSERIAL , 
B.ATTN_SALD, B.NCP_DAYS,B.ATTN_SALD ATTN_WRKD, B.GROSSWAGES, B.PF_GROSS, B.PEN_GROSS, B.ESI_GROSS, B.PTAX_GROSS, B.PF_E, B.EPF, B.PF_C, B.PTAX, B.ESI_E, B.ESI_C, 
B.LOAN_MPL, B.LINT_MPL, 'SALARY'  TRANSACTIONTYPE
FROM PFEMPLOYEEMASTER A,
(
    SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, UNITCODE, CATEGORYCODE, GRADECODE, LPAD(TOKENNO,5,'0') TOKENNO , 
    ATTN_SALD, NCP_DAYS, GROSSWAGES, PF_GROSS, PEN_GROSS, ESI_GROSS, PTAX_GROSS, PF_E, EPF, PF_C, PTAX, ESI_E, ESI_C, 
    LOAN_MPL, LINT_MPL FROM PISSALARYUPLOADRAWDATA
) B
WHERE A.TOKENNO=B.TOKENNO


SELECT LPAD('1342',5,'0') FROM DUAL

COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, EFFECT_YEARMONTH, UNITCODE, DEPARTMENTCODE, 
CATEGORYCODE, GRADECODE, WORKERSERIAL, TOKENNO, TRANSACTIONTYPE, PAYMODE, ATTN_SALD, ATTN_WPAY, 
ATTN_ADJD, ATTN_TOTD, ATTN_LDAY, ATTN_CALCF, ATTN_OFFD, ATTN_HOLD, ATTN_WRKD, LDAY_CL, LDAY_PL, 
LDAY_SL, LVBL_CL, LVBL_PL, LVBL_SL, LV_ENCASH_DAYS, LV_ENCASH, BASIC, DA, HRA_GROSS, HRA_PER, HRA, 
PF_GROSS, PEN_GROSS, ESI_GROSS, PTAX_GROSS, PF_E, PF_C, FPF, VPF_PERC, VPF, ESI_E, ESI_C, PTAX, LWF, 
ITAX, ESI_RT, SARR_ARRE, SARR_ARRD, SARR_PFARRE, SARR_NPFARRE, GROSSEARN, GROSSDEDN, MISC_BF, MISC_CF, TOTEARN, TOTDEDN, NETSALARY, SYSROWID, LASTMODIFIED, USERNAME, ADHOC, SPL_ALLOW, NS_HRS, OT_HRS, OT_DAYS, NS_ALLOW, OT_AMT, SERV_PERC, SERV_ALW, CONV_PERC, CONV_ALOW, OEPF, OE_NPF, ESI_ADJERN, HRA_PERC, ACT_PF_GRS, LIC, ELECTRIC, MESS, LTP, SUSP_DEDN, MISC_DEDN, HRA_AMT, ADHOC_NPF, OTHR_DEDN, PROF_BONUS, MEDICAL, LTA, LOAN_SPL, LINT_SPL, LNBL_SPL, LIBL_SPL, LOAN_STADV, LINT_STADV, LNBL_STADV, LIBL_STADV, LOAN_OTADV, LINT_OTADV, LNBL_OTADV, LIBL_OTADV, LOAN_PJADV, LINT_PJADV, LNBL_PJADV, LIBL_PJADV, LOAN_SA, LINT_SA, LNBL_SA, LIBL_SA, LOAN_FEADV, LINT_FEADV, LNBL_FEADV, LIBL_FEADV, LOAN_OLADV, LINT_OLADV, LNBL_OLADV, LIBL_OLADV, LVENCSH_DAYS, LEAVE_ENC, EPF, ATN_INCNT, ATN_INCAMT, CLUB, CUMM_DAYS, CUM_PFGROS, ESI_RATE, LOAN_PFL, LINT_PFL, LNBL_PFL, LIBL_PFL, LOAN_SPL1, LINT_SPL1, LNBL_SPL1, LIBL_SPL1, CUMM_PF_E, CUMM_PF_C, CUMM_VPF, RT_BASIC, LDAY_CS, LIBL_MPL, LINT_MPL, LNBL_MPL, LOAN_MPL