SELECT * FROM SALESGSTBILLDBCRDETAILS WHERE H/1718/GC/0024

SELECT * FROM SALESGSTBILLDBCRMASTER

H/2021/GC/0057

EXEC PROC_RPT_DEBITCREDITNOTE_IRN('0002','DOMESTIC-WITHIN-WESTBENGAL','H/2021/NGC/006') 

EXEC PROC_RPT_DEBITCREDITNOTE_IRN('0002','','H/2021/NGC/006') 

select fn_num_to_words (5225.65,'RS') FROM DUAL

exec PROC_RPT_DEBITCREDITNOTE_IRN('0002','0021','01/04/2020','31/03/2021','''H/2021/GC/0076''','DEBIT NOTE','','F:\SWTERP\SWT_JUTE\swterp\swterp\\LOGO\','F:\SWTERP\SWT_JUTE\swterp\swterp\\LOGO\','F:\SWTERP\SWT_JUTE\swterp\swterp\\LOGO\')

select * FROM GTT_REP_DEBITCREDITNOTE WHERE 1=1;

NOOFPACKINGUNIT,PACKSTYLECODE,
PACKINGQUANTITY  MEASURENAME


TOTALWEIGHT
PACKSHEETWEIGHT
GROSSWEIGHT0

TOTALQUANTITY

TOTALQUANTITY  MEASURENAME

UPDATE GTT_REP_DEBITCREDITNOTE SET  EX1 = 'CREDIT NOTE' 
WHERE DOCUMENTTYPE LIKE '%CRNOTE%';


UPDATE GTT_REP_DEBITCREDITNOTE SET  EX1 = 'DEBIT NOTE' 
WHERE DOCUMENTTYPE NOT LIKE '%CRNOTE%';



SALESGSTDBCRNOTEVIEW
CASE WHEN DOCUMENTTYPE LIKE '%CRNOTE%' THEN 'CREDIT NOTE' ELSE 'DEBIT NOTE' END


PROC_REP_OTHERINVOICEPRINTGST

SALESGSTDBCRNOTEVIEW

SALESGSTDBCRNOTEVIEW