SELECT COUNT(*) 
  FROM PISGRADECOMPONENTMAPPING 
  WHERE COMPANYCODE='0001' 
  AND DIVISIONCODE='001' 
  AND COMPONENTCODE='FIX_CONV' 

lv_SqlStr 
INSERT INTO PISREIMBURSEMENT_ENTITLE 
 ( COMPANYCODE, DIVISIONCODE, YEARCODE, WORKERSERIAL, TOKENNO, UNITCODE, CATEGORYCODE, GRADECODE, COMPONENTCODE, COMPONENTAMOUNT, TRANSACTIONTYPE, ADDLESS ,USERNAME)
   
   SELECT DISTINCT A.COMPANYCODE, A.DIVISIONCODE,'2020-2021' YEARCODE, A.WORKERSERIAL, A.TOKENNO,
  A.UNITCODE,A.CATEGORYCODE,A.GRADECODE,'FIX_CONV' COMPONENTCODE,PISASSIGN.BASIC*0.5 BASIC,'ENTITLEMEN' TRANSACTIONTYPE,'ADD' ADDLESS ,'' USERNAME 
  FROM PISEMPLOYEEMASTER A,PISASSIGN B 
  WHERE A.COMPANYCODE=B.COMPANYCODE 
  AND A.DIVISIONCODE=B.DIVISIONCODE 
  AND A.WORKERSERIAL=B.WORKERSERIAL 
  AND A.EMPLOYEESTATUS='ACTIVE' 
  AND A.COMPANYCODE='0001' 
  AND A.DIVISIONCODE='001' 
   AND A.UNITCODE = '001' 

