SELECT * FROM PISREIMBURSEMENTDETAILS



SELECT WM_CONCAT(COMPONENTCODE) FROM PISCOMPONENTMASTER WHERE DIVISIONCODE='001'

SELECT * FROM PISCOMPONENTMASTER WHERE COMPONENTCODE='LTA'

ATTN_CUMD,ATTN_FDAY,ATTN_HOLD,ATTN_WOFD,ATTN_WOHD,BASIC,BASIC_RT,CANTEEN,CHILD_ALLW,
CONV_ALLW,ESI_C,ESI_E,ESI_GROSS,FIX_ALW,FPF,FSTL_DED,FSTL_EARN,GELESI,GROSSDEDN,GROSSEARN,
GR_ESI_OTH,HRA,HRA_GROSS,HRA_PER,HRA_RT,INCENTIVE,ITAX,LCUM_CL,LCUM_PL,LIBL_EDLN,LIBL_HBLN,
LIBL_MDLN,LIBL_MGLN,LIBL_OTLN,LIBL_PF,LIBL_PRLN,LIBL_SADV,LIBL_VCLN,LINT_EDLN,LINT_HBLN,
LINT_MDLN,LINT_MGLN,LINT_OTLN,LINT_PF,LINT_PRLN,LINT_SADV,LINT_VCLN,LNBL_EDLN,LNBL_HBLN,
LNBL_MDLN,LNBL_MGLN,LNBL_OTLN,LNBL_PF,LNBL_PRLN,LNBL_SADV,LNBL_VCLN,LOAN_EDLN,LOAN_HBLN,
LOAN_MDLN,LOAN_MGLN,LOAN_OTLN,LOAN_PF,LOAN_PRLN,LOAN_SADV,LOAN_VCLN,LTA,LVBL_CL,LVBL_PL,
LVBL_SL,MEDICAL,MISC_BF,MISC_CF,NETSALARY,OTH_ALLW,OTH_ALLW2,PEN_GROSS,PERS_ALLW,PF_C,
PF_E,PF_GROSS,PTAX,PTAX_GROSS,SAL_SAVING,SARR_ARRD,SARR_ARRE,SERV_ALLW,SOFT_ALLW,
TOTALDED,TOTEARN,TOTINT,TOTLOANAMT,TOTLOANINT

LTA	FIX CONVEYANCE 	LOCAL CONVEYANCE	TELEPHONE	INCENTIVE	BONUS	EXGRACIA	OTHER BENEFIT


SELECT * FROM PISPAYTRANSACTION
WHERE INCENTIVE > 0



SELECT * FROM PISCOMPONENTMASTER WHERE 1=1--COMPONENTCODE='LTA' 
AND PHASE =99
ORDER BY
CALCULATIONINDEX



PROC_REIMBURSEMENT

SELECT * FROM JSWRAPPER

SELECT * FROM COLS
WHERE COLUMN_NAME = 'EXGRACIA'


GBL_PISCOMPONENTASSIGNMENT
PISARREARTRANSACTION
PISCOMPONENTASSIGNMENT
PISPAYTRANSACTION
PISPAYTRANSACTION_SWT



PRC_PIS_REIMBURSMENT_ENT (P_COMPCODE Varchar2, 
                                                  P_DIVCODE Varchar2,
                                                  P_YEARCODE varchar2,
                                                  P_YEARMONTH Varchar2,
                                                  P_COMPONENTCODE varchar2,
                                                  P_CATEGORYCODE varchar2 DEFAULT NULL,
                                                  P_GRADECODE varchar2 DEFAULT NULL,
                                                  P_USERNAME varchar2 DEFAULT NULL
                                                 )