
CREATE TABLE TEMP_LEAVE
AS

SELECT WORKERSERIAL,LEAVECODE,SUM(OPENING) OPENING,SUM(ENT) ENT,SUM(AVAIL) AVAIL
FROM
(
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, SUM(NOOFDAYS) OPENING, 0 ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,PISLEAVETRANSACTION B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='F'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.TRANSACTIONTYPE='BF'
         AND B.YEARCODE='2020-2021'
         AND B.YEARMONTH<=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM')
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, SUM(NOOFDAYS) OPENING, 0 ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,PISLEAVETRANSACTION B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='C'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.TRANSACTIONTYPE='BF'
         AND B.CALENDARYEAR=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
         AND B.YEARMONTH<=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM')
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     UNION ALL
     
     
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, SUM(ENTITLEMENTS) ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,PISLEAVEENTITLEMENT B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='F'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.YEARCODE='2020-2021'
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     
     
     UNION ALL
     
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, SUM(ENTITLEMENTS) ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,PISLEAVEENTITLEMENT B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='C'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.CALENDARYEAR=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     
     
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, 0 ENT, SUM(LEAVEDAYS) AVAIL
     FROM PISEMPLOYEEMASTER A, PISLEAVEAPPLICATION B, PISCATEGORYMASTER C
     WHERE A.COMPANYCODE = 'BJ0056'
         AND A.DIVISIONCODE = '0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE = C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE ='F'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL = B.WORKERSERIAL
         AND B.YEARCODE = '2020-2021'
         AND B.LEAVESANCTIONEDON IS NOT NULL
         AND B.LEAVEDATE <= TO_DATE('31/08/2020','DD/MM/YYYY')
     GROUP BY A.CATEGORYCODE, A.WORKERSERIAL, B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, 0 ENT, SUM(LEAVEDAYS) AVAIL
     FROM PISEMPLOYEEMASTER A, PISLEAVEAPPLICATION B, PISCATEGORYMASTER C
     WHERE A.COMPANYCODE = 'BJ0056'
         AND A.DIVISIONCODE = '0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE = C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE ='C'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL = B.WORKERSERIAL
         AND B.CALENDARYEAR = TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
         AND B.LEAVESANCTIONEDON IS NOT NULL
         AND B.LEAVEDATE <= TO_DATE('31/08/2020','DD/MM/YYYY')
     GROUP BY A.CATEGORYCODE, A.WORKERSERIAL, B.LEAVECODE
)
GROUP BY WORKERSERIAL, LEAVECODE















    UPDATE PISLEAVETRANSACTION A
    SET NOOFDAYS=
        (
            SELECT A.NOOFDAYS-B.DEDUC FROM TEMP_NOOFDAYS_DEDUCT B
            WHERE 
            B.DIVISIONCODE=A.DIVISIONCODE
           AND B.WORKERSERIAL=A.WORKERSERIAL
            AND B.LEAVECODE=A.LEAVECODE
        )       
    WHERE A.DIVISIONCODE='0001'
    AND A.LEAVECODE='PL'
    AND A.WORKERSERIAL IN (SELECT WORKERSERIAL FROM TEMP_NOOFDAYS_DEDUCT)   

INSERT INTO GBL_PIS_LEAVEBAL
SELECT 'BJ0056' COMPANYCODE,'0001' DVISIONCODE,TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM') YEARMONTH,D.WORKERSERIAL,E.TOKENNO,E.CATEGORYCODE,E.GRADECODE,D.LEAVECODE,D.OPENING OPENING,D.ENT ENTITLE,D.AVAIL AVAILED,(D.OPENING+D.ENT-D.AVAIL) BALANCE
FROM (
        SELECT L.WORKERSERIAL,L.LEAVECODE, NVL(OPENING,0) OPENING, NVL(ENT,0) ENT, NVL(AVAIL,0) AVAIL
        FROM TEMP_LEAVE T,(
                            SELECT A.WORKERSERIAL,B.LEAVECODE
                            FROM (
                                    SELECT DISTINCT WORKERSERIAL
                                    FROM TEMP_LEAVE
                                 ) A,
                                 (
                                    SELECT LEAVECODE from PISLEAVEMASTER
                                    WHERE COMPANYCODE='BJ0056'
                                        AND DIVISIONCODE='0001'
                                        AND WITHOUTPAYLEAVE<>'Y'
                                  ) B
                           ) L
        WHERE L.WORKERSERIAL=T.WORKERSERIAL(+)
            AND L.LEAVECODE=T.LEAVECODE(+)
     ) D, PISEMPLOYEEMASTER E
WHERE D.WORKERSERIAL=E.WORKERSERIAL