select * from pisleavetransaction

select * from pisleaveapplication


select * from pisleaveentitlement

UPDATE SYS_PARAMETER SET
PARAMETER_VALUE = 'Y'
WHERE PARAMETER_NAME='LEAVE BALANCE MAINTAIN PROPORTIONATE'


SELECT PARAMETER_VALUE FROM SYS_PARAMETER
WHERE PARAMETER_NAME='LEAVE BALANCE MAINTAIN PROPORTIONATE'

SELECT COUNT(PARAMETER_VALUE) FROM SYS_PARAMETER
WHERE PARAMETER_NAME='LEAVE BALANCE MAINTAIN PROPORTIONATE'




SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('LEAVE BALANCE MAINTAIN PROPORTIONATE', 'LEAVE BALANCE MAINTAIN PROPORTIONATE', 'Y', 'PIS', 'BJ0056', 
    TO_DATE('02/28/2015 22:45:18', 'MM/DD/YYYY HH24:MI:SS'), '9', '0001', 'SWT', 'SWT TO SET');
COMMIT;


SELECT * FROM PISLEAVEENTITLEMENT

SELECT * FROM PISLEAVETRANSACTION

INSERT INTO PISLEAVETRANSACTION

SELECT A.COMPANYCODE, A.DIVISIONCODE, A.YEARCODE,A.CALENDARYEAR, '202101' YEARMONTH, 
A.CATEGORYCODE, A.GRADECODE, A.WORKERSERIAL, A.TOKENNO, LEAVECODE,ROUND((ENTITLEMENTS/12)*FACTOR,2) NOOFDAYS,
'ADD' ADDLESS,'ENT' TRANSACTIONTYPE,SYSDATE WITHEFFECTFROM,'SWT' USERNAME,SYSDATE LASTMODIFIED,fn_generate_sysrowid SYSROWID 
FROM PISLEAVEENTITLEMENT A, PISEMPLOYEEMASTER  B,
(
    SELECT TOKENNO, WORKERSERIAL,ROUND(ATTN_SALD/ATTN_CALCF,2) FACTOR  FROM PISPAYTRANSACTION A
    WHERE COMPANYCODE='BJ0056'
    AND A.DIVISIONCODE='0001'
    AND A.YEARCODE='2020-2021'
    AND A.YEARMONTH='202008'
    AND ROUND(ATTN_SALD/ATTN_CALCF,2)  < 1
) C
WHERE A.COMPANYCODE='BJ0056'
AND A.DIVISIONCODE='0001'
AND A.YEARCODE='2020-2021'
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.WORKERSERIAL=B.WORKERSERIAL
AND A.WORKERSERIAL=C.WORKERSERIAL


SELECT TOKENNO, WORKERSERIAL,ROUND(ATTN_SALD/ATTN_CALCF,2) FACTOR  FROM PISPAYTRANSACTION A
WHERE COMPANYCODE='BJ0056'
AND A.DIVISIONCODE='0001'
AND A.YEARCODE='2020-2021'
AND A.YEARMONTH='202008'
AND ROUND(ATTN_SALD/ATTN_CALCF,2)  < 1



SELECT * FROM PISLEAVEENTITLEMENT


SELECT * FROM PISEMPLOYEEMASTER


SELECT * FROM PISLEAVETRANSACTION A
WHERE A.COMPANYCODE='BJ0056'
AND A.DIVISIONCODE='0001'
AND A.YEARCODE='2020-2021'
AND A.YEARMONTH='202101'
AND A.WORKERSERIAL IN 
(
    SELECT WORKERSERIAL FROM PISEMPLOYEEMASTER
    WHERE COMPANYCODE='BJ0056'
    AND DIVISIONCODE='0001'
    AND UNITCODE = '01'
    AND CATEGORYCODE = '10'
    AND GRADECODE = 'C'
)
AND A.CATEGORYCODE = '10'
AND A.GRADECODE = 'C'


--------------------------------------------------------------------------------






 EXEC PRC_PISLEAVEEARN_INSERT('BJ0056','0001','202101','PL')

SELECT * FROM PISLEAVETRANSACTION
WHERE TRANSACTIONTYPE='ENT'



SELECT * FROM PISLEAVETRANSACTION
WHERE YEARMONTH='202102' AND TRANSACTIONTYPE='ENT'

 EXEC PRC_PISLEAVEEARN_INSERT('BJ0056','0001','202102')



EXEC PROC_PIS_LEAVEBAL('BJ0056','0001','2020-2021','01/07/2020','31/07/2020')

SELECT * FROM GBL_PIS_LEAVEBAL


EXEC PRC_PIS_LEAVEBALANCE ('BJ0056','0001','2020-2021','202101')


SELECT * FROM GBL_PISLEAVEBALANCE


SELECT * FROM PISLEAVETRANSACTION
WHERE TOKENNO='00529'



CREATE TABLE TEMP_LEAVE
AS

SELECT WORKERSERIAL,LEAVECODE,SUM(OPENING) OPENING,SUM(ENT) ENT,SUM(AVAIL) AVAIL
FROM
(
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, SUM(NOOFDAYS) OPENING, 0 ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,PISLEAVETRANSACTION B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='F'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.TRANSACTIONTYPE='BF'
         AND B.YEARCODE='2020-2021'
         AND B.YEARMONTH<=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM')
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, SUM(NOOFDAYS) OPENING, 0 ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,PISLEAVETRANSACTION B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='C'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.TRANSACTIONTYPE='BF'
         AND B.CALENDARYEAR=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
         AND B.YEARMONTH<=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM')
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, SUM(ENTITLEMENTS) ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,
     (
         SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL,LEAVECODE,YEARCODE, SUM(NOOFDAYS) ENTITLEMENTS
         FROM PISLEAVETRANSACTION
         WHERE YEARCODE='2020-2021'
         AND TO_DATE(YEARMONTH,'YYYYMM') BETWEEN TO_DATE('01/08/2020','DD/MM/YYYY') AND TO_DATE('31/08/2020','DD/MM/YYYY') 
         GROUP BY COMPANYCODE, DIVISIONCODE, WORKERSERIAL,LEAVECODE,YEARCODE
     ) B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='F'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.YEARCODE='2020-2021'
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, SUM(ENTITLEMENTS) ENT, 0 AVAIL
     FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER C,
     (
         SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL,LEAVECODE,CALENDARYEAR, SUM(NOOFDAYS) ENTITLEMENTS
         FROM PISLEAVETRANSACTION
         WHERE CALENDARYEAR=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
         GROUP BY COMPANYCODE, DIVISIONCODE, WORKERSERIAL,LEAVECODE,CALENDARYEAR
     ) B
     WHERE A.COMPANYCODE='BJ0056'
         AND A.DIVISIONCODE='0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE=C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE='C'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL=B.WORKERSERIAL
         AND B.CALENDARYEAR=TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
     GROUP BY A.CATEGORYCODE,A.WORKERSERIAL,B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, 0 ENT, SUM(LEAVEDAYS) AVAIL
     FROM PISEMPLOYEEMASTER A, PISLEAVEAPPLICATION B, PISCATEGORYMASTER C
     WHERE A.COMPANYCODE = 'BJ0056'
         AND A.DIVISIONCODE = '0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE = C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE ='F'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL = B.WORKERSERIAL
         AND B.YEARCODE = '2020-2021'
         AND B.LEAVESANCTIONEDON IS NOT NULL
         AND B.LEAVEDATE <= TO_DATE('31/08/2020','DD/MM/YYYY')
     GROUP BY A.CATEGORYCODE, A.WORKERSERIAL, B.LEAVECODE
     UNION ALL
     SELECT A.CATEGORYCODE, A.WORKERSERIAL, LEAVECODE, 0 OPENING, 0 ENT, SUM(LEAVEDAYS) AVAIL
     FROM PISEMPLOYEEMASTER A, PISLEAVEAPPLICATION B, PISCATEGORYMASTER C
     WHERE A.COMPANYCODE = 'BJ0056'
         AND A.DIVISIONCODE = '0001'
         AND A.COMPANYCODE=C.COMPANYCODE
         AND A.DIVISIONCODE=C.DIVISIONCODE
         AND A.CATEGORYCODE = C.CATEGORYCODE
         AND C.LEAVECALENDARORFINYRWISE ='C'
         AND A.COMPANYCODE=B.COMPANYCODE
         AND A.DIVISIONCODE=B.DIVISIONCODE
         AND A.WORKERSERIAL = B.WORKERSERIAL
         AND B.CALENDARYEAR = TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYY')
         AND B.LEAVESANCTIONEDON IS NOT NULL
         AND B.LEAVEDATE <= TO_DATE('31/08/2020','DD/MM/YYYY')
     GROUP BY A.CATEGORYCODE, A.WORKERSERIAL, B.LEAVECODE
)
GROUP BY WORKERSERIAL, LEAVECODE

    UPDATE PISLEAVETRANSACTION A
    SET NOOFDAYS=
        (
            SELECT A.NOOFDAYS-B.DEDUC FROM TEMP_NOOFDAYS_DEDUCT B
            WHERE 
            B.DIVISIONCODE=A.DIVISIONCODE
            AND B.WORKERSERIAL=A.WORKERSERIAL
            AND B.LEAVECODE=A.LEAVECODE
        )       
    WHERE A.DIVISIONCODE='0001'
    AND A.LEAVECODE='PL'
    AND A.WORKERSERIAL IN (SELECT WORKERSERIAL FROM TEMP_NOOFDAYS_DEDUCT)
    
    SELECT * FROM 

