DROP TABLE WPSUNREALIZEDDATA CASCADE CONSTRAINTS;

CREATE TABLE WPSUNREALIZEDDATA
(
  COMPANYCODE         VARCHAR2(10 BYTE),
  DIVISIONCODE        VARCHAR2(10 BYTE),
  YEARCODE            VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE  DATE,
  FORTNIGHTENDDATE    DATE,
  WORKERSERIAL        VARCHAR2(10 BYTE),
  TOKENNO             VARCHAR2(10 BYTE),
  COMPONENTCODE       VARCHAR2(10 BYTE),
  COMPONENTAMOUNT     NUMBER(11,2),
  ACTUALAMOUNT        NUMBER(11,2),
  REFERENCE_FNEDATE   DATE,
  PAIDON              DATE,
  TRANTYPE            VARCHAR2(10 BYTE),
  MODULE              VARCHAR2(10 BYTE),
  REMARKS             VARCHAR2(100 BYTE),
  USERNAME            VARCHAR2(50 BYTE),
  SYSROSWID           VARCHAR2(50 BYTE),
  LASTMODIFIED        DATE                      DEFAULT SYSDATE,
  DOCNO               VARCHAR2(20 BYTE),
  DOCDATE             DATE,
  TRAN_SOURCE         VARCHAR2(20 BYTE)
) 

SELECT WM_CONCAT(COLUMN_NAME) FROM COLS 
WHERE TABLE_NAME = 'WPSCASHOTPAYMENTDETAILS'


SELECT  COLUMN_NAME  FROM COLS@WPS_2_KIOSK
WHERE TABLE_NAME = 'WPSCASHOTPAYMENTDETAILS'




SELECT COMPANYCODE,DIVISIONCODE,YEARCODE,FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,WORKERSERIAL,
TOKENNO,COMPONENTCODE,COMPONENTAMOUNT,ACTUALAMOUNT,REFERENCE_FNEDATE,PAIDON,TRANTYPE,MODULE,
REMARKS,USERNAME,SYSROSWID,LASTMODIFIED,DOCNO,DOCDATE,TRAN_SOURCE 
FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
WHERE PAYMENTLOCK = 'Y'