CREATE OR REPLACE FUNCTION FN_GET_COMP_VAL_PROJECTED
(
    P_COMPANYCODE VARCHAR2, 
    P_DIVISIONCODE VARCHAR2, 
    P_COMPNAME VARCHAR2, 
    P_TOKENNO VARCHAR2, 
    P_YEARCODE VARCHAR2 , 
    P_CTYPE  VARCHAR2 
) 
RETURN VARCHAR2
AS
LV_RESULT VARCHAR2(100);
LV_SQL    VARCHAR2(1000);

LV_COMPSUM VARCHAR2(20);
LV_COMPLAST VARCHAR2(20);
LV_COMPCNT VARCHAR2(20);
LV_MONTH_DIFF VARCHAR2(20);
LV_WORKERSERIAL VARCHAR2(20);

BEGIN


LV_WORKERSERIAL := P_TOKENNO;

BEGIN
    SELECT WORKERSERIAL INTO LV_WORKERSERIAL  FROM PISEMPLOYEEMASTER WHERE TOKENNO = P_TOKENNO;
EXCEPTION WHEN OTHERS THEN
    LV_WORKERSERIAL := P_TOKENNO;
END;


SELECT WORKERSERIAL INTO LV_WORKERSERIAL  FROM PISEMPLOYEEMASTER WHERE WORKERSERIAL = LV_WORKERSERIAL AND EMPLOYEESTATUS='ACTIVE';
    
    
   



LV_SQL := NULL;

LV_SQL := LV_SQL||'SELECT SUM(NVL('||P_COMPNAME||',0)) '|| P_COMPNAME ||' FROM PISPAYTRANSACTION'||CHR(10);
LV_SQL := LV_SQL||'WHERE WORKERSERIAL='''||LV_WORKERSERIAL||''''||CHR(10);
LV_SQL := LV_SQL||'AND YEARCODE = '''||P_YEARCODE||''' '||CHR(10);
LV_SQL := LV_SQL||'AND COMPANYCODE = '''||P_COMPANYCODE||''' '||CHR(10);
LV_SQL := LV_SQL||'AND DIVISIONCODE = '''||P_DIVISIONCODE||''' '||CHR(10);

--LV_SQL := LV_SQL||'AND YEARMONTH='''||P_YEARMONTHTO||''''||CHR(10);

EXECUTE IMMEDIATE LV_SQL INTO  LV_COMPSUM;


LV_SQL := NULL;
LV_SQL := LV_SQL||'SELECT NVL('||P_COMPNAME||',0) FROM PISPAYTRANSACTION A'||CHR(10);
LV_SQL := LV_SQL||'WHERE  COMPANYCODE='''||P_COMPANYCODE||''''||CHR(10);
LV_SQL := LV_SQL||'AND DIVISIONCODE='''||P_DIVISIONCODE||''''||CHR(10);
LV_SQL := LV_SQL||'AND WORKERSERIAL='''||LV_WORKERSERIAL||''''||CHR(10);
LV_SQL := LV_SQL||'AND YEARMONTH = '||CHR(10);
LV_SQL := LV_SQL||'('||CHR(10);
LV_SQL := LV_SQL||'    SELECT MAX(YEARMONTH) FROM PISPAYTRANSACTION'||CHR(10);
LV_SQL := LV_SQL||'    WHERE COMPANYCODE=A.COMPANYCODE'||CHR(10);
LV_SQL := LV_SQL||'    AND DIVISIONCODE=DIVISIONCODE'||CHR(10);
LV_SQL := LV_SQL||'    AND WORKERSERIAL=A.WORKERSERIAL'||CHR(10);
LV_SQL := LV_SQL||'    AND YEARCODE='''||P_YEARCODE||''''||CHR(10);
LV_SQL := LV_SQL||'    AND ATTN_WPAY = 0'||CHR(10);
LV_SQL := LV_SQL||')'||CHR(10);

EXECUTE IMMEDIATE LV_SQL INTO  LV_COMPLAST;

LV_SQL := NULL;
LV_SQL := LV_SQL||'SELECT CNT, TRUNC(MONTHS_BETWEEN(ENDDATE, TO_DATE(YEARMONTH,''YYYYMM''))) MONTH_DIFF'||CHR(10);
LV_SQL := LV_SQL||'FROM FINANCIALYEAR A, '||CHR(10);
LV_SQL := LV_SQL||'('||CHR(10);
LV_SQL := LV_SQL||'    SELECT COUNT(YEARMONTH) CNT,MAX(YEARMONTH) YEARMONTH FROM PISPAYTRANSACTION A'||CHR(10);
LV_SQL := LV_SQL||'    WHERE COMPANYCODE='''||P_COMPANYCODE||''''||CHR(10);
LV_SQL := LV_SQL||'    AND DIVISIONCODE='''||P_DIVISIONCODE||''''||CHR(10);
LV_SQL := LV_SQL||'    AND WORKERSERIAL='''||LV_WORKERSERIAL||''''||CHR(10);
LV_SQL := LV_SQL||'    AND YEARCODE='''||P_YEARCODE||''''||CHR(10);
LV_SQL := LV_SQL||') B'||CHR(10);
LV_SQL := LV_SQL||'WHERE TO_DATE(YEARMONTH, ''YYYYMM'') BETWEEN STARTDATE AND ENDDATE'||CHR(10);
LV_SQL := LV_SQL||'AND COMPANYCODE='''||P_COMPANYCODE||''''||CHR(10);
LV_SQL := LV_SQL||'AND DIVISIONCODE='''||P_DIVISIONCODE||''''||CHR(10);
LV_SQL := LV_SQL||'AND YEARCODE='''||P_YEARCODE||''''||CHR(10);

EXECUTE IMMEDIATE LV_SQL INTO  LV_COMPCNT, LV_MONTH_DIFF;



IF P_CTYPE = '12' THEN

    LV_SQL := 'SELECT '||LV_COMPSUM||' + ('||LV_COMPLAST||' * '||LV_MONTH_DIFF||') FROM DUAL';
ELSE
    
--    LV_SQL := 'SELECT '||LV_COMPSUM||' + ('||LV_COMPLAST||' * '||P_CTYPE||') FROM DUAL';

    LV_SQL := 'SELECT ('||LV_COMPLAST||' * '||P_CTYPE||') FROM DUAL';

END IF;

EXECUTE IMMEDIATE LV_SQL INTO  LV_RESULT;

RETURN LV_RESULT;

EXCEPTION WHEN OTHERS THEN

LV_RESULT := '0';
RETURN LV_RESULT;

END;
-- 
--
--SELECT * FROM PISPAYTRANSACTION A
--WHERE COMPANYCODE='0001'
--AND DIVISIONCODE='0002'
--AND TOKENNO='00504'
----AND TRANSACTIONTYPE='ASSIGNMENT'
--AND YEARMONTH = 
--(
--    SELECT MAX(YEARMONTH) FROM PISPAYTRANSACTION
--    WHERE COMPANYCODE=A.COMPANYCODE
--    AND DIVISIONCODE=DIVISIONCODE
--    AND WORKERSERIAL=A.WORKERSERIAL
--    AND YEARCODE='2020-2021'
--    AND ATTN_WPAY = 0
----    AND TRANSACTIONTYPE=A.TRANSACTIONTYPE
--)
--
--SELECT * FROM PISCOMPONENTASSIGNMENT
--WHERE TOKENNO='00504'
--
--SELECT (15250/31)*27 FROM DUAL
--
--13282.26
--
--
--SELECT CNT, TRUNC(MONTHS_BETWEEN(ENDDATE, TO_DATE(YEARMONTH,'YYYYMM'))) MONTH_DIFF
--FROM FINANCIALYEAR A, 
--(
--    SELECT COUNT(YEARMONTH) CNT,MAX(YEARMONTH) YEARMONTH FROM PISPAYTRANSACTION A
--    WHERE COMPANYCODE='0001'
--    AND DIVISIONCODE='0002'
--    AND TOKENNO='00504'
--    AND YEARCODE='2020-2021'
--)
--WHERE TO_DATE(YEARMONTH, 'YYYYMM') BETWEEN STARTDATE AND ENDDATE
--AND COMPANYCODE='0001'
--AND DIVISIONCODE='0002'
--AND YEARCODE='2020-2021'