'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AcPaymentAdvanceDirect_BMPL

    '''<summary>
    '''lblForHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCOMPCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOMPCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIVCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIVCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIVISIONNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIVISIONNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYEARCODE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYEARCODE1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOPTMODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPTMODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUSRNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUSRNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSYSROWID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSYSROWID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTDSGRIDDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDSGRIDDATA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtACLIABILITYDETAILS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtACLIABILITYDETAILS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSTARTDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTARTDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtENDDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENDDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIVISIONCODEFOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIVISIONCODEFOR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSystemVoucherNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSystemVoucherNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSYSTEMVOUCHERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSYSTEMVOUCHERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSystemVoucherdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSystemVoucherdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSYSTEMVOUCHERDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSYSTEMVOUCHERDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVoucherNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVoucherNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVOUCHERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVOUCHERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVoucherDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVoucherDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVOUCHERDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVOUCHERDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPARTYNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPARTYCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtACCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtACCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtISTDSAPPLICABLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtISTDSAPPLICABLE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMAINGROUPCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMAINGROUPCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNatureType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNatureType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVOUCHERNATURE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVOUCHERNATURE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RbtManualRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbtManualRef As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RbtSysRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbtSysRef As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtREFERENCETYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtREFERENCETYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblManualOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblManualOrderNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMANUALVOUCHERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMANUALVOUCHERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtORDERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORDERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRefDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskORDERDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskORDERDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAmtToPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmtToPay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAMOUNTTOPAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAMOUNTTOPAY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTDSOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTDSOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTDSONAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDSONAMOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDRCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDRCR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PanelTDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTDS As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtTotAdjustingAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotAdjustingAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotTDSON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotTDSON As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTOTALTDSON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTOTALTDSON As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNetTDSAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetTDSAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTOTALTDSAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTOTALTDSAMOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCashBankAc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCashBankAc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCASHBANKAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCASHBANKAC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCASHBANKACCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCASHBANKACCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCASHBANKGROUPTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCASHBANKGROUPTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAMOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBookSlNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBookSlNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHEQUEBOOKSLNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHEQUEBOOKSLNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChequeNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChequeNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHEQUENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHEQUENO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInstructionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInstructionNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtINSTRUCTIONNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtINSTRUCTIONNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChequeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChequeDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHEQUEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHEQUEDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDrawnon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDrawnon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCHEQUEDRAWNON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHEQUEDRAWNON As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPaidTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaidTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPAIDTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAIDTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNarration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNarration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNARRATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNARRATION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVoucherType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVoucherType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPAYMENTTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAYMENTTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllDiv As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBillType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAUTOMANUALMARK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAUTOMANUALMARK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMODULENAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMODULENAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDOCUMENTTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOCUMENTTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCHANNELCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHANNELCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGROUPTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGROUPTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtACTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtACTYPE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMODULE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMODULE As Global.System.Web.UI.WebControls.TextBox
End Class
