exec PROC_RPT_PIS_PAYSLIP_ED('BJ0056','0001','2020-2021','202101','''01''','','','')



SELECT COMPANYCODE, DIVISIONCODE,YEARCODE,NULL UNITCODE,CATEGORYCODE,GRADECODE , 
         TOKENNO, A.WORKERSERIAL,A.LEAVECODE, 
         sum(NOOFDAYS) ENTITLEMENTS , CARRYFORWARD
         FROM  PISLEAVETRANSACTION A,
         (
            SELECT WORKERSERIAL, CARRYFORWARD, LEAVECODE 
            FROM PISLEAVEENTITLEMENT
            WHERE COMPANYCODE='BJ0056'
            AND DIVISIONCODE='0001'
            AND YEARCODE='2020-2021'
         ) B
         WHERE A.WORKERSERIAL=B.WORKERSERIAL
         AND A.LEAVECODE=B.LEAVECODE  
         AND YEARCODE='2020-2021'
         and tokenno='00447'
         AND TRANSACTIONTYPE='ENT'
         --         AND YEARMONTH='202101'
         group by COMPANYCODE, DIVISIONCODE,YEARCODE,CATEGORYCODE,GRADECODE , TOKENNO, A.WORKERSERIAL,A.LEAVECODE, CARRYFORWARD
         
         
SELECT WORKERSERIAL, CARRYFORWARD, LEAVECODE 
FROM PISLEAVEENTITLEMENT
WHERE COMPANYCODE='BJ0056'
AND DIVISIONCODE='0001'
AND YEARCODE='2020-2021'
 


SELECT COMPANYCODE, DIVISIONCODE,YEARCODE,NULL UNITCODE,CATEGORYCODE,GRADECODE , TOKENNO, A.WORKERSERIAL,A.LEAVECODE, 
SUM(DECODE(TRANSACTIONTYPE,'ENT',NOOFDAYS,0)) ENTITLEMENTS,SUM(DECODE(TRANSACTIONTYPE,'BF',NOOFDAYS,0)) CARRYFORWARD
FROM  PISLEAVETRANSACTION A 
WHERE 1=1
AND YEARCODE='2020-2021'
AND YEARMONTH <= 202101
AND TOKENNO='00447'
GROUP BY COMPANYCODE, DIVISIONCODE,YEARCODE,CATEGORYCODE,GRADECODE , TOKENNO, A.WORKERSERIAL,A.LEAVECODE
  