 UPDATE GBL_PFLOANBLNC A SET (CAP_EMI, INT_EMI) = (SELECT CAP_EMI_TOBE, INT_EMI_TOBE 
 FROM PFLOAN_EMI_UPDATE B 
 WHERE A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.LOANCODE = B.LOANCODE) 
   
   
   SELECT *
 FROM PFLOAN_EMI_UPDATE B 
   
 
  CREATE TABLE PFLOAN_EMI_UPDATE AS 
  
 SELECT 'HP0072' COMPANYCODE,'0001' DIVISIONCODE, A.WORKERSERIAL, B.PFNO, B.LOANCODE, NVL(A.HAZIRA,0) HAZIRA ,  B.PFLOAN_BAL, B.PFLOAN_INT_BAL, 
 CAP_EMI, INT_EMI, TOT_EMI, SLAB_HRS_FROM, SLAB_HRS_TO, NOOF_EMI, /*ROUND(CAP_EMI*NOOF_EMI,0) CAP_EMI_TOBE,*/ 
 CASE WHEN PFLOAN_BAL >0 THEN ROUND(CAP_EMI*NOOF_EMI,0) ELSE 0 END CAP_EMI_TOBE, 
 CASE WHEN PFLOAN_BAL >0 THEN 0 WHEN PFLOAN_BAL<=0 AND PFLOAN_INT_BAL > 0 THEN ROUND(NVL(D.INTERESTINSTALLMENTAMT,0)*NOOF_EMI,0) ELSE 0 END INT_EMI_TOBE
 FROM GPSPAYSHEETDETAILS_SWT A, GBL_PFLOANBLNC B, PFLOAN_EMI_DEDN_SLAB C, PFLOANTRANSACTION D 
 WHERE A.PERIODFROM = '02-NOV-20' and A.PERIODTO = '08-NOV-20'  
   AND A.WORKERSERIAL = B.WORKERSERIAL  
   AND B.PFNO = D.PFNO AND B.LOANCODE = D.LOANCODE AND B.LOANDATE = D.LOANDATE 
   AND C.COMPANYCODE = 'HP0072' AND C.DIVISIONCODE = '0001' 
   AND NVL(A.HAZIRA,0) >= C.SLAB_HRS_FROM  
   AND NVL(A.HAZIRA,0) <= C.SLAB_HRS_TO  

   

UPDATE GBL_PFLOANBLNC SET INT_EMI = CAP_EMI - PFLOAN_BAL, CAP_EMI = PFLOAN_BAL 
WHERE CAP_EMI > PFLOAN_BAL 


SELECT * FROM GBL_PFLOANBLNC
WHERE PFNO ='1825'