SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%WAGE%PR%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''


SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''





SELECT * FROM GPS_ERROR_LOG
WHERE ERROR_QUERY LIKE '%0007202%'


DELETE FROM GPS_ERROR_LOG

DELETE FROM WPS_ERROR_LOG

PROC_GPSWAGESPROCESS_DEDN

SELECT * FROM GPSCOMPONENTMAST
WHERE COMPONENTCODE LIKE '%PF%'

SELECT * FROM GBL_PFLOANBLNC
WHERE PFNO='1825'


EXEC PROC_PFLOANBLNC('HP0072','0001','02/11/2020','08/11/2020')

EXEC  PROC_PFLOANBLNC('HP0072','0001','02/11/2020','08/11/2020',NULL,NULL,'GPS','NO');
    

SELECT CASE WHEN PFLOAN_INT_BAL > INT_EMI THEN INT_EMI ELSE PFLOAN_INT_BAL END , INT_EMI_DEDUCT_TYPE, NVL(INT_STOP,'N') 
--                            INTO lv_ComponentAmt, lv_EMI_DEDN_TYPE, lv_PFLN_INT_STOP  
FROM GBL_PFLOANBLNC 
WHERE PFNO = '1825'
AND LOANCODE = 'PF'
AND NVL(INT_STOP,'N') = 'N'
AND PFLOAN_INT_BAL > 0


 PROC_PFLOANBLNC(P_COMPCODE,P_DIVCODE,P_FNSTDT,P_FNENDT,NULL,NULL,'GPS','YES');
    
 
 
 
SELECT B.COMPANYCODE, B.DIVISIONCODE, A.WORKERSERIAL, A.CATEGORYCODE, A.GROSSWAGES, A.COMPONENTCODE, A.COMPONENTAMOUNT, B.CALCULATIONINDEX, 
NVL(C.APPLICABLE,'NO') APPLICABLE, NVL(B.COMPONENTGROUP,'XX') COMPONENTGROUP
,NVL(D.ISBLOCKED,'N') ISBLOCKED, NVL(D.APPLICABLE_PERCENT,0) APPLICABLE_PERCENT  
FROM GTT_SWT_PHASE_DEDN A, GPSCOMPONENTMAST B, 
(
    SELECT X.CATEGORYCODE, X.COMPONENTCODE, NVL(X.APPLICABLE,'NO') APPLICABLE
    FROM GPSCATEGORYVSCOMPONENT X, 
    (
        SELECT CATEGORYCODE, MAX(EFFECTIVEDATE) EFFECTIVEDATE 
        FROM GPSCATEGORYVSCOMPONENT 
        WHERE COMPANYCODE = P_COMPCODE AND DIVISIONCODE = P_DIVCODE
          AND EFFECTIVEDATE <= TO_DATE(P_FNSTDT,'DD/MM/YYYY')
        GROUP BY CATEGORYCODE  
    ) Y
    WHERE X.COMPANYCODE = P_COMPCODE AND X.DIVISIONCODE = P_DIVCODE   
      AND X.CATEGORYCODE = Y.CATEGORYCODE 
      AND X.EFFECTIVEDATE = Y.EFFECTIVEDATE
      AND X.APPLICABLE = 'YES'                     

) C--, SWT_PHASE_DEDN D
---- START BELOW BLOCK BY AMALESH ON 31/10/2018 FOR PERIOD WISE BLOCK COMPONENT CONSIDER IN THE CURSOR    
,(
     SELECT CATEGORYCODE, CATEGORYTYPE, COMPONENTCODE, NVL(ISAPPLICABLE,'Y') ISBLOCKED, NVL(APPLICABLE_PERCENT,0) APPLICABLE_PERCENT 
     FROM GPSWAGESCOMPONENTBLOCK
     WHERE COMPANYCODE = P_COMPCODE AND DIVISIONCODE = P_DIVCODE
       --AND MODULE = 'GPS' 
       AND PERIODFROM >= TO_DATE(P_FNSTDT,'DD/MM/YYYY')
       AND PERIODTO <= TO_DATE(P_FNENDT,'DD/MM/YYYY')
       AND CATEGORYTYPE = P_CATEGORYTYPE                    
) D
---- END BELOW BLOCK BY AMALESH ON 31/10/2018 FOR PERIOD WISE BLOCK COMPONENT CONSIDER IN THE CURSOR
WHERE B.COMPANYCODE = P_COMPCODE AND B.DIVISIONCODE = P_DIVCODE 
  AND B.COMPONENTCODE = A.COMPONENTCODE 
  AND B.COMPONENTCODE = C.COMPONENTCODE
  AND B.PHASE = P_PHASE
  AND A.CATEGORYCODE = C.CATEGORYCODE
  AND NVL(C.APPLICABLE,'NO') <> 'NO'
  AND NVL(A.GROSSWAGES,0) > 0
  AND A.CATEGORYCODE = D.CATEGORYCODE (+) AND A.COMPONENTCODE = D.COMPONENTCODE (+)
ORDER BY A.WORKERSERIAL, B.CALCULATIONINDEX 


PRCGPSWAGESPROCESS_B4SAVE


EXEC PRCGPS_WAGES_PROCESS('WAGES PROCESS','HP0072','0001','2020-2021','SWT','02/11/2020','08/11/2020','WORKER','P',NULL);                                   
    


SELECT * FROM GPS_ERROR_LOG
WHERE ERROR_QUERY LIKE '%0007202%'


DELETE FROM GPS_ERROR_LOG

DELETE FROM WPS_ERROR_LOG

SELECT * FROM GPSPAYSHEETDETAILS
WHERE WORKERSERIAL='0007202'
