SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%tax%prin%')

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE reaporttag='GST INVOICE PRINT'

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG='GST INVOICE PRINT'