PROC_CHECKLOGINVALIDATION



exec PROC_CHECKLOGINVALIDATION('0001','SWT','152412511')


select password,NOOFWRONGATTEMPT  from  login
                WHERE COMPANYCODE='0001'
                AND USERNAME='SWT'; 

select * from SYS_GBL_PROCOUTPUT_INFO

3

 SELECT NOOFWRONGATTEMPT, active  FROM LOGIN
        WHERE COMPANYCODE = '0001'
        AND USERNAME = 'SWT';
        
        
SELECT * FROM SYS_TFMAP 
WHERE SYS_TABLE_SEQUENCIER='9041'

LOGIN

SET DEFINE OFF;
Insert into GLOSTER_WEB.SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, 
    SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, 
    SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE, IS_EDITABLE, 
    ISCONVERT_TOUPPER)
 Values
   (9041, 'LOGIN', 'GBL_LOGIN', 'ACTIVE', 0, 
    'VARCHAR2', 1, 0, 'N', 'txtISACTIVE', 
    TO_TIMESTAMP('4/27/2015 11:56:55.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL, 'Y', 
    'Y');
COMMIT;


EXEC PROC_CREATE_GBL_TMP_TABLES(9041,0)