

SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('010503020278', NULL, 'Sales Bill Summary (Group wise)', 'REPORTS', 'SALES BILL SUMMARY GROUP WISE', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'SALES', NULL, 
    '''0002''', '''0002''', NULL, 'SALES/Pages/Report/pgReportSalesTemplate.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '010503020278', 'X', 'X', 'X', 
    'Y', 'X', 'X', 'X', 'SALES', 
    '201905201317530010061224');
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('153', '010503020278', 'X', 'X', 'X', 
    'Y', 'X', 'X', 'X', 'SALES', 
    '201806260955380008095557');
COMMIT;


SET DEFINE OFF;
Insert into REPORTPARAMETERMASTER
   (MODULENAME, REPORTTAG, REPORTTAG1, REPORTTAG2, REPORTTAG3, MAINTABLE, SUBREPORTTABLE, SUBREPORTTABLE1, SUBREPORTTABLE2, SUBREPORTTABLE3, SUBREPORTTABLE4, REPORTNAME)
 Values
   ('SALES', 'SALES BILL SUMMARY GROUP WISE', NULL, NULL, NULL, 
    'GTT_SALESBILLSUMMARY_GRPWISE', NULL, NULL, NULL, NULL, 
    NULL, 'SALES/Pages/Report/Transaction/rptSaleBillSummary_Groupwise.rdlc');
COMMIT;
