select * from menumaster_rnd
where menude


select * from jswrapper

SELECT GRATUITYAPPLICABLE||'~'||GRATUITYSETTELMENTDATE FROM PISEMPLOYEEMASTER


SELECT * 
FROM PISEMPLOYEEMASTER
where GRATUITYSETTELMENTDATE IS NOT NULL

SELECT * 
FROM WPSWORKERMAST
WHERE GRATUITYAPPLICABLE='Y'

where GRATUITYSETTELMENTDATE IS NOT NULL


GRATUITYAPPLICABLE||'~'||GRATUITYSETTELMENTDATE FROM WPSWORKERMAST

SELECT * FROM WO

SELECT * 
FROM WPSWORKERMAST
WHERE GRATUITYAPPLICABLE='Y'


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID = '6930'


SELECT EMPLOYEESTATUS,TOKENNO,EMPLOYEENAME WORKERNAME, WORKERSERIAL, CATEGORYCODE 
FROM  PISEMPLOYEEMASTER 
WHERE 1=1 --COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
--AND MODULE=<<MODULE>>
AND EMPLOYEESTATUS IN ('DEATH','DISMISSED','RESIGN','RETIRE') 
AND STATUSDATE IS NOT NULL        
AND GRATUITYSETTELMENTDATE IS NULL
UNION ALL       
SELECT WORKERSTATUS,TOKENNO,WORKERNAME, WORKERSERIAL, WORKERCATEGORYCODE
FROM WPSWORKERMAST
WHERE 1=1
--COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
--AND MODULE=<<MODULE>>
AND WORKERSTATUS IN ('DEATH','DISMISSED','RESIGN','RETIRE')
and DATEOFTERMINATIONADVICE IS NOT NULL
AND GRATUITYSETTELMENTDATE IS NULL
ORDER BY TOKENNO


SELECT * FROM WPSWORKERMAST