SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%worker%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0112'

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

 



SELECT * FROM MENUMASTER_RND
WHERE 1=1
AND PROJECTNAME='WPS'
AND MENUCODE NOT LIKE '0110%'
 

SELECT * FROM ROLEDETAILS
WHERE 1=1 --MENUCODE LIKE '0110%'
AND PROJECTNAME='WPS'
AND MENUCODE LIKE '0110%'
 



SELECT MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, 
EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, 
MENUDETAILS,'''0002''' EFFECTIVEDIVISION,'''0002'''  EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, 
FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE
 FROM MENUMASTER_RND
WHERE MENUCODE LIKE '0110%'
AND PROJECTNAME='WPS'


SELECT DISTINCT TNAME,TABTYPE FROM TAB
WHERE TNAME LIKE '%WPS%'
