
select * from companymast

CJ0101

select * from divisionmaster

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE LIKE '011_'



SELECT * FROM ROLEDETAILS
WHERE MENUCODE LIKE '0110'

AND ROLEID=1


update MENUMASTER_RND set 
active='Y'
WHERE MENUCODE='011001' 

SELECT * FROM ROLEDETAILS
WHERE MENUCODE='011001'

 
CREATE TABLE MENUMASTER_RND_BK080321 AS

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE LIKE '0110%'
AND PROJECTNAME='WPS'
 

CREATE TABLE ROLEDETAILS_BK080321 AS
SELECT * FROM ROLEDETAILS

WHERE MENUCODE LIKE '0110%'

AND PROJECTNAME='WPS'
 


SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0112'


FUNCTIONCALL_BEFORE,FUNCTIONCALL_AFTER


SELECT * FROM MENUMASTER_RND
WHERE MENUCODE LIKE '0110%'
AND PROJECTNAME='WPS'
 



DELETE * FROM ROLEDETAILS
WHERE MENUCODE LIKE '0110%'

AND PROJECTNAME='WPS'
 


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='4111'


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='4110'





FUNCTIONCALL_BEFORE,FUNCTIONCALL_AFTER


SELECT FUNCTIONCALL_BEFORE FROM MENUMASTER_RND
WHERE MENUCODE LIKE '0110%'
AND PROJECTNAME='WPS'
AND FUNCTIONCALL_BEFORE IS NOT NULL
UNION
SELECT FUNCTIONCALL_AFTER FROM MENUMASTER_RND
WHERE MENUCODE LIKE '0110%'
AND PROJECTNAME='WPS'
AND FUNCTIONCALL_BEFORE IS NOT NULL

UNION


SELECT DISTINCT TNAME,TABTYPE FROM TAB
WHERE TNAME LIKE '%WPS%'

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%stl pro%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''