declare 

    P_COMPANYCODE VARCHAR2(10),
    P_DIVISIONCODE  VARCHAR2(10),
    P_DOCUMENT_TYPE  VARCHAR2(100),
    P_SENDER_EMAIL_ID  VARCHAR2(100),
    P_SENDER_EMAIL_PWD  VARCHAR2(100),
    P_RECEIVER_EMAIL_ID  VARCHAR2(100),
    P_CC_EMAIL_ID  VARCHAR2(100),
    P_EMAIL_SUBJECT  VARCHAR2(1000),
    P_EMAIL_BODY   VARCHAR2(100),
    P_ATTACHMENT_FILENAME  VARCHAR2(100),
    P_ATTACHMENT_BLOB  BLOB


begin

    P_COMPANYCODE := '0001';
    P_DIVISIONCODE := '0002';
    P_DOCUMENT_TYPE := '0001'; 
    P_SENDER_EMAIL_ID := '0001';
    P_SENDER_EMAIL_PWD := '0001';
    P_RECEIVER_EMAIL_ID := '0001';
    P_CC_EMAIL_ID := '0001';
    P_EMAIL_SUBJECT := '0001'; 
    P_EMAIL_BODY := '0001'; 
    P_ATTACHMENT_FILENAME := '0001';
    P_ATTACHMENT_BLOB := '0001';

insert into GTT_EMAIL_DATA
(
    COMPANYCODE, DIVISIONCODE, DOCUMENT_TYPE, SENDER_EMAIL_ID, SENDER_EMAIL_PWD, 
    RECEIVER_EMAIL_ID, CC_EMAIL_ID, EMAIL_SUBJECT, EMAIL_BODY, ATTACHMENT_FILENAME, 
    ATTACHMENT_BLOB
) values 
(
    P_COMPANYCODE, 
    P_DIVISIONCODE, 
    P_DOCUMENT_TYPE, 
    P_SENDER_EMAIL_ID, 
    P_SENDER_EMAIL_PWD, 
    P_RECEIVER_EMAIL_ID, 
    P_CC_EMAIL_ID, 
    P_EMAIL_SUBJECT, 
    P_EMAIL_BODY, 
    P_ATTACHMENT_FILENAME, 
    P_ATTACHMENT_BLOB
)

end;

