DROP TABLE BIRLANEW.GTT_PIS_PF_LOANDEDN_REP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE BIRLANEW.GTT_PIS_PF_LOANDEDN_REP
(
  COMPANYCODE     VARCHAR2(10 BYTE),
  DIVISIONCODE    VARCHAR2(10 BYTE),
  UNITCODE        VARCHAR2(10 BYTE),
  UNITSHORTDESC   VARCHAR2(20 BYTE),
  CATEGORYCODE    VARCHAR2(10 BYTE),
  CATEGORYDESC    VARCHAR2(500 BYTE),
  DEPARTMENTCODE  VARCHAR2(10 BYTE),
  DEPARTMENTDESC  VARCHAR2(500 BYTE),
  TOKENNO         VARCHAR2(20 BYTE),
  PFNO            VARCHAR2(20 BYTE),
  EMPLOYEENAME    VARCHAR2(50 BYTE),
  PF_GROSS        NUMBER(15,5),
  PF_E            NUMBER(15,5),
  VPF             NUMBER(15,5),
  PF_C            NUMBER(15,5),
  FPF             NUMBER(15,5),
  LOAN_PFL        NUMBER(18,2),
  LINT_PFL        NUMBER(18,2),
  LNBL_PFL        NUMBER(18,2),
  LOANDATE        DATE,
  LOANAMOUNT      NUMBER(15,2),
  PF_E_YTD        NUMBER,
  VPF_YTD         NUMBER,
  PF_C_YTD        NUMBER,
  FPF_YTD         NUMBER
)
TABLESPACE BIRLANEW
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
