DROP TABLE BIRLANEW.GTT_PIS_EPSSTATEMENT_REP CASCADE CONSTRAINTS;

CREATE TABLE GLOBAL TEMPORARY BIRLANEW.GTT_PIS_EPSSTATEMENT_REP
(
  COMPANYCODE     VARCHAR2(10 BYTE),
  DIVISIONCODE    VARCHAR2(10 BYTE),
  UNITCODE        VARCHAR2(10 BYTE),
  UNITSHORTDESC   VARCHAR2(20 BYTE),
  CATEGORYCODE    VARCHAR2(10 BYTE),
  CATEGORYDESC    VARCHAR2(500 BYTE),
  DEPARTMENTCODE  VARCHAR2(10 BYTE),
  DEPARTMENTDESC  VARCHAR2(500 BYTE),
  SL_NO           NUMBER,
  TOKENNO         VARCHAR2(20 BYTE),
  EMPLOYEENAME    VARCHAR2(50 BYTE),
  PFNO            VARCHAR2(20 BYTE),
  PENSIONNO       VARCHAR2(20 BYTE),
  EPS_JNG_DT      DATE,
  EPS_CONT        NUMBER(15,5),
  EPS_OP          NUMBER,
  EPS_GROSS       NUMBER,
  EPS_YTD         NUMBER
)