DROP TABLE BIRLANEW.GTT_TEXT_REPORT CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE BIRLANEW.GTT_TEXT_REPORT
(
  LINENO      NUMBER(10),
  LINETAG     VARCHAR2(20 BYTE),
  LINETEXT    VARCHAR2(500 BYTE),
  LINESPCHAR  VARCHAR2(30 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


CREATE OR REPLACE TRIGGER BIRLANEW.TEXT_REPORT_ON_INSERT
BEFORE INSERT ON BIRLANEW.GTT_TEXT_REPORT
FOR EACH ROW
BEGIN
SELECT COUNT(*)+1
INTO :new.LINENO
FROM GTT_TEXT_REPORT;
END;
/
