
SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%leave%')

PIS/PAGES/Transaction/pgPISLeaveApplicationEntryWithGridDet_Common.aspx



SELECT LEAVEDATE,SUBSTR(TO_CHAR(TO_DATE(LEAVEDATE, 'DD/MM/YYYY'), 'DAY'),1,3) AS DAYNAME,'Full' AS LEAVEMODE,1 AS LEAVEDAYS FROM
(SELECT TO_CHAR(TO_DATE('01/07/2020', 'DD/MM/YYYY') - 1 + ROWNUM,'DD/MM/YYYY') AS LEAVEDATE
FROM ALL_OBJECTS WHERE TO_DATE('01/07/2020', 'DD/MM/YYYY') - 1 + ROWNUM <= TO_DATE('dd/mm/yyyy', 'DD/MM/YYYY'))A
  


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%PAY%SLIP%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE LIKE '010703030%'


SELECT * FROM ROLEDETAILS
WHERE MENUCODE LIKE '010703030%'