CREATE OR REPLACE PROCEDURE BIRLANEW.PROC_INSERT_TEXT_REPORT
(
    P_LINETEXT VARCHAR2,
    P_LINETAG VARCHAR2 DEFAULT NULL,
    P_LINESPCHAR VARCHAR2 DEFAULT NULL
)
AS 
    LV_SQLSTR           VARCHAR2(11);  
BEGIN
    INSERT INTO GTT_TEXT_REPORT(LINETAG, LINETEXT, LINESPCHAR) VALUES(P_LINETAG, P_LINETEXT, P_LINESPCHAR);
END;
/