
--GLOSTER LOGIN PAGE VALIDATION
select * from sys_parameter
 
SELECT SUBSTR(PARAMETER_VALUE,1,1) PARAMETER_VALUE 
FROM SYS_PARAMETER 
WHERE PARAMETER_NAME = 'LOGIN VALIDATION' 
AND ROWNUM=1

SELECT PARAMETER_VALUE 
FROM SYS_PARAMETER 
WHERE PARAMETER_NAME = 'STRONG PASSWORD CHARACTER' 
AND ROWNUM=1


SELECT SUBSTR(PARAMETER_VALUE,1,1) PARAMETER_VALUE 
FROM SYS_PARAMETER 
WHERE PARAMETER_NAME = 'MINIMUM PASSWORD LENGTH' 
AND ROWNUM=1


SELECT PARAMETER_VALUE 
FROM SYS_PARAMETER 
WHERE PARAMETER_NAME = 'NO OF WRONG PASSWORD ATTEMPT' 
AND ROWNUM=1

SELECT PARAMETER_VALUE 
FROM SYS_PARAMETER 
WHERE PARAMETER_NAME = 'MINIMUM USERNAME LENGTH' 
AND ROWNUM=1

SELECT PARAMETER_VALUE 
FROM SYS_PARAMETER 
WHERE PARAMETER_NAME = 'MAXIMUM USERNAME LENGTH' 
AND ROWNUM=1

SET DEFINE OFF;
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, 
    LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('LOGIN VALIDATION', 'USER LOGIN VALIDATION', 'YES', 'GENERAL', '0002', 
    SYSDATE, SYS_GUID(), '0010', 'SWT', 'SWT TO SET');
    
Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, 
    LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('STRONG PASSWORD CHARACTER', 'STRONG PASSWORD CHARACTER', '@.', 'GENERAL', '0002', 
    SYSDATE, SYS_GUID(), '0010', 'SWT', 'SWT TO SET');
COMMIT;

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, 
    LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('MINIMUM PASSWORD LENGTH', 'MINIMUM PASSWORD LENGTH', '7', 'GENERAL', '0002', 
    SYSDATE, SYS_GUID(), '0010', 'SWT', 'SWT TO SET');
COMMIT;

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, 
    LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('NO OF WRONG PASSWORD ATTEMPT', 'NO OF WRONG PASSWORD ATTEMPT', '3', 'GENERAL', '0002', 
    SYSDATE, SYS_GUID(), '0010', 'SWT', 'SWT TO SET');
COMMIT;

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, 
    LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('MINIMUM USERNAME LENGTH', 'MINIMUM USERNAME LENGTH', '3', 'GENERAL', '0002', 
    SYSDATE, SYS_GUID(), '0010', 'SWT', 'SWT TO SET');
COMMIT;

Insert into SYS_PARAMETER
   (PARAMETER_NAME, PARAMETER_DESC, PARAMETER_VALUE, PROJECTNAME, COMPANYCODE, 
    LASTMODIFIED, SYSROWID, DIVISIONCODE, USERNAME, ALLOW_CHANGE_FROM_INTERFACE)
 Values
   ('MAXIMUM USERNAME LENGTH', 'MAXIMUM USERNAME LENGTH', '20', 'GENERAL', '0002', 
    SYSDATE, SYS_GUID(), '0010', 'SWT', 'SWT TO SET');
COMMIT;


SELECT SYS_GUID() FROM DUAL


CREATE TABLE CHANGEPASSWORDMANAGER
(
    ADMINUSERNAME VARCHAR(30) NOT NULL,
    LOGINUSERNAME    VARCHAR2(30) NOT NULL,
    OLDPASSWORD VARCHAR2(30),
    NEWPASSWORD VARCHAR2(30),
    CHANGEDATE DATE
);


SELECT * FROM LOGIN

SELECT * FROM SYS_GBL_PROCOUTPUT_INFO


--ADD NO OF WRONG ATTEMPT
ALTER TABLE LOGIN
ADD NOOFWRONGATTEMPT NUMBER(2)