SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%off%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0107010114'

update  MENUMASTER_RND set URLSRC='PIS/PAGES/Transaction/pgOffDayWorking.aspx'
WHERE MENUCODE='0107010114'


SYS_GBL_PROCOUTPUT_INFO


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG LIKE '%TAG%'

SELECT * FROM SYS_TFMAP

EXEC PROC_CHECKOLDPASSWORD('SWT','TEST','ABC@123','123@ABC')

EXEC PROC_CHECKOLDPASSWORD('SWT','TEST','XYZ@123','123@XYZ')

EXEC PROC_CHECKOLDPASSWORD('SWT','TEST','QWE@123','123@REW')

EXEC PROC_CHECKOLDPASSWORD('SWT','TEST','ERT@432','657@QAS')

EXEC PROC_CHECKOLDPASSWORD('SWT','TEST','WED@345','GTF@WAS')

EXEC PROC_CHECKOLDPASSWORD('SWT','TEST','WSR@213','123@234')


SELECT * FROM SYS_GBL_PROCOUTPUT_INFO


SELECT COUNT(NEWPASSWORD) FROM CHANGEPASSWORDMANAGER
WHERE 'GTF@WAS' IN 
(
    (
        SELECT NEWPASSWORD FROM 
        (
            SELECT NEWPASSWORD, CHANGEDATE 
            FROM CHANGEPASSWORDMANAGER 
            ORDER BY CHANGEDATE DESC
        ) A
        WHERE ROWNUM <= 3
    )
)


SELECT COUNT(NEWPASSWORD) FROM 
(
    SELECT NEWPASSWORD, CHANGEDATE 
    FROM CHANGEPASSWORDMANAGER 
    ORDER BY CHANGEDATE DESC
) A
WHERE ROWNUM <= 3
AND NEWPASSWORD='GTF@WAS'


SELECT ROWNUM SLNO, NEWPASSWORD, CHANGEDATE 
FROM CHANGEPASSWORDMANAGER 
ORDER BY CHANGEDATE DESC