

SELECT LEVEL FROM DUAL CONNECT BY LEVEL <= 10


SELECT SUBSTR('@!#$%^&*(',LEVEL,1) XX FROM DUAL CONNECT BY LEVEL <= LENGTH('@!#$%^&*(')


SELECT GET_PASSWORDSTRENGTH('@!#$%^&*1234567890~abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ','ASWESDSKDF') FROM  DUAL 

