
Insert into DHAMAI.MENUMASTER_RND
   (MENUCODE, MENUDESC, MENUTYPE, MENUTAG, ENTRYPOSSIBLE, 
    EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, 
    PROJECTNAME, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, URLSRC, FUNCTIONCALL_BEFORE, 
    FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE)
 Values
   ('01100511', 'File Upload into Location', 'UTILITIES', 'FILE UPLOAD INTO LOCATION', 'Y', 
    'N', 'N', 'N', 'N', 'Y', 
    'GPS', '''0001''', '''0001''', 'GENERAL/Pages/Common/pgUploadFileIntoLocation.aspx', null, 
    null, 'N', 'N');
COMMIT;
 


Insert into DHAMAI.ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, 
    ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, 
    SYSROWID)
 Values
   ('1', '01100511', 'Y', 'X', 'X', 
    'X', 'X', 'X', 'X', 'GPS', 
    '202009211036100005744450');
COMMIT;



exec PROC_RPT_WAGESSUMMARY_DHAMAI('DT0091','0001','06/11/2020','12/11/2020','','')


CYCLE_ALLOW
CHARGE_ALLOW
NONPF_ALLOW
SPEC_ALLOW

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%import data%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE like '01100511'


SELECT * FROM ROLEDETAILS
WHERE MENUCODE='01100511'

WAGESSUMMARY_DHAMAI

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = 'WAGESSUMMARY_DHN'

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%wage%')



SELECT * FROM MENUMASTER_RND
WHERE MENUCODE IN ('01100402030101','01100402030110')

WAGES REGISTER(TEXT REPORT) DHUNSERI
PAY BOOK CONSOLIDATE DHUNSERI


PROC_WAGES_REGISTER_STDFRMT
PROC_WAGES_REGISTER_STDFRMT_bk

PROC_RPT_WAGESSUMMARY

SELECT * FROM GPSPAYSHEETDETAILS WHERE TOKENNO='2078'