DROP TABLE GTT_PFCONTRIBUTION_NEW CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_PFCONTRIBUTION_NEW
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  CLUSTERCODE    VARCHAR2(10 BYTE),
  CATEGORYCODE   VARCHAR2(10 BYTE),
  CATEGORYTYPE   VARCHAR2(20 BYTE),
  COMPANYNAME    VARCHAR2(100 BYTE),
  DIVISIONNAME   VARCHAR2(100 BYTE),
  WORKERSERIAL   VARCHAR2(10 BYTE),
  TOKENNO        VARCHAR2(10 BYTE),
  EMPLOYEENAME   VARCHAR2(100 BYTE),
  UANNO          VARCHAR2(50 BYTE),
  GROSS_EARNING  NUMBER(15,2),
  PF_E           NUMBER(15,2),
  AMOUNT         NUMBER(15,2),
  ADV_REF        NUMBER(15,2),
  ADV_REF_INT    NUMBER(15,2),
  REPORTHEADER   VARCHAR2(100 BYTE),
  EX1            VARCHAR2(100 BYTE),
  EX2            VARCHAR2(100 BYTE),
  EX3            NUMBER(11,4),
  EX4            NUMBER(11,4),
  PERIODFROM     DATE,
  PERIODTO       DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE;

