SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6014, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS QUALITY TYPE INFORMATION', NULL, 
    'SELECT QUALITYTYPECODE, QUALITYTYPEDESC 
FROM WPSQUALITYTYPEMAST 
WHERE COMPANYCODE=<<COMPANYCODE>>  
AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY 1', 'QUALITYTYPECODE~QUALITYTYPEDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6015, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS QUALITY UOM INFORMATION', NULL, 
    'SELECT QUALITYUOMCODE, QUALITYUOMDESC 
FROM WPSQUALITYUOMMAST 
WHERE COMPANYCODE=<<COMPANYCODE>>  
AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY 1 DESC ', 'QUALITYUOMCODE~QUALITYUOMDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6016, '""', 'COMPANYCODE~DIVISIONCODE~PRODUCTIONTYPE~PATTERN', 'WPS QUALITY INFORMATION', NULL, 
    'SELECT QUALITYCODE, QUALITYNAME 
FROM WPSQUALITYMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>>  
AND DIVISIONCODE=<<DIVISIONCODE>> 
AND PRODUCTIONTYPE=<<PRODUCTIONTYPE>>
ORDER BY 1 DESC ', 'QUALITYCODE~QUALITYNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6017, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS DEPARTMENT WISE OCCUPATION INFROMATION', NULL, 
    'SELECT OCCUPATIONCODE, OCCUPATIONNAME
  FROM WPSOCCUPATIONMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
 ORDER BY OCCUPATIONCODE', 'OCCUPATIONCODE~OCCUPATIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6018, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS MACHINE MASTER', NULL, 
    'SELECT MACHINECODE, MACHINENAME, PRODUCTIONTYPE  
FROM WPSMACHINEMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>>  
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
ORDER BY 1 ', 'MACHINECODE~MACHINENAME~PRODUCTIONTYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6019, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~PATTERN', 'WPS WORKER INFROMATION FROM ATTENDANCE', NULL, 
    'SELECT DISTINCT A.TOKENNO,B.WORKERNAME,A.WORKERSERIAL
  FROM WPSATTENDANCEDAYWISE A,WPSWORKERMAST B
 WHERE A.COMPANYCODE = <<COMPANYCODE>> 
   AND A.DIVISIONCODE =<<DIVISIONCODE>>
   AND A.DATEOFATTENDANCE=TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
   AND A.COMPANYCODE = B.COMPANYCODE 
   AND A.DIVISIONCODE =B.DIVISIONCODE
   AND A.TOKENNO=B.TOKENNO
 ORDER BY TOKENNO', 'A.TOKENNO~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6020, '""', 'COMPANYCODE~DIVISIONCODE~QUALITYUOMCODE~DEPARTMENTCODE~PATTERN', 'WPS PRODUCTION TYPE INFORMATION', NULL, 
    'SELECT DISTINCT PRODUCTIONTYPECODE,PRODUCTIONTYPEDESC,
                DEPARTMENTCODE,SECTIONCODE,OCCUPATIONCODE  
 FROM WPSPRODUCTIONTYPEMAST 
  WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>> 
 ORDER BY PRODUCTIONTYPECODE', 'PRODUCTIONTYPECODE~PRODUCTIONTYPEDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6026, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS WORKER ORDER INFROMATION', NULL, 
    'SELECT DEPARTMENTCODE ,DEPARTMENTNAME FROM WPSDEPARTMENTMASTER
     WHERE COMPANYCODE=<<COMPANYCODE>>
      AND DIVISIONCODE=<<DIVISIONCODE>>
      AND DEPARTMENTCODE NOT IN (
                                  SELECT DEPARTMENTCODE FROM WPSDEPARTMENTMASTER
                                     WHERE COMPANYCODE=<<COMPANYCODE>>
                                      AND DIVISIONCODE=<<DIVISIONCODE>>
                                      AND INSTR (<<DEPARTMENTCODE>>,DEPARTMENTCODE)>0
      )
      ORDER BY DEPARTMENTCODE', 'DEPARTMENTCODE~DEPARTMENTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6022, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~PATTERN', 'WPS BOOK INFORMATION', NULL, 
    'SELECT DISTINCT BOOKNO, TO_CHAR(DATEOFATTENDANCE,''DD/MM/YYYY'') DATEOFATTENDANCE
  FROM WPSATTENDANCEDAYWISE
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND YEARCODE=<<YEARCODE>>
   AND BOOKNO IS NOT NULL
 ORDER BY TO_DATE(DATEOFATTENDANCE,''DD/MM/YYYY'') DESC, BOOKNO DESC', 'BOOKNO~DATEOFATTENDANCE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6024, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS OCCUPATION INFROMATION', NULL, 
    'SELECT OCCUPATIONCODE,OCCUPATIONNAME FROM WPSOCCUPATIONMAST 
WHERE COMPANYCODE=<<COMPANYCODE>>
 AND DIVISIONCODE=<<DIVISIONCODE>>
 AND DEPARTMENTCODE=<<DEPARTMENTCODE>>', 'OCCUPATIONCODE~OCCUPATIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6025, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS WORKER ORDER INFROMATION', NULL, 
    'SELECT DISTINCT ORDERNO,to_char(ORDERDATE,''dd/mm/yyyy'') ORDERDATE FROM WPSWORKORDERWISERATEMASTER
     WHERE COMPANYCODE=<<COMPANYCODE>>
      AND DIVISIONCODE=<<DIVISIONCODE>>
      ORDER BY ORDERNO', 'ORDERNO~ORDERDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6027, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS LOAN TYPE INFORMATION', NULL, 
    'SELECT DISTINCT LOANTYPE  
  FROM PFLOANMASTER  
 WHERE COMPANYCODE=<<COMPANYCODE>>  
   AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY 1 DESC ', 'LOANTYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6028, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PF LOAN INFORMATION', NULL, 
    'SELECT DISTINCT LOANCODE,LOANDESC
FROM  PFLOANMASTER   
 WHERE COMPANYCODE=<<COMPANYCODE>>  
   --AND DIVISIONCODE=<<DIVISIONCODE>>
   AND LOANTYPE=<<LOANTYPE>> 
ORDER BY 1 DESC ', 'LOANCODE~LOANDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6029, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PF LOAN DATE', NULL, 
    'SELECT DISTINCT LOANDATE 
  FROM  PFLOANAPPLICATION   
 WHERE COMPANYCODE=<<COMPANYCODE>>  
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND PFNO=<<PFNO>> 
ORDER BY 1 DESC ', 'LOANDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6013, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE MASTER', NULL, 
    'SELECT MACHINECODE, MACHINENAME, PRODUCTIONTYPE, DEPARTMENTCODE  
FROM WPSMACHINEMASTER WHERE COMPANYCODE=<<COMPANYCODE>>  AND DIVISIONCODE=<<DIVISIONCODE>>
 AND PRODUCTIONTYPE=<<PRODUCTIONTYPE>>
ORDER BY 1 ', 'MACHINECODE~MACHINENAME~PRODUCTIONTYPE~DEPARTMENTCODE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6080, '""', 'COMPANYCODE~DIVISIONCODE~LOANCODE~PATTERN', 'WPS PF INFO', NULL, 
    'SELECT PFNO, EMPLOYEENAME, WORKERSERIAL, TOKENNO
  FROM PFEMPLOYEEMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND PFNO IN (SELECT DISTINCT PFNO
                  FROM PFLOANTRANSACTION
                 WHERE COMPANYCODE=<<COMPANYCODE>>
                   AND DIVISIONCODE=<<DIVISIONCODE>>
                   AND LOANCODE=<<LOANCODE>>
               )
 ORDER BY TOKENNO', 'PFNO~EMPLOYEENAME~WORKERSERIAL~TOKENNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6068, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~TOKENNO~PATTERN', 'WPS DEPT INFORMATION', NULL, 
    'SELECT DISTINCT DEPARTMENTCODE FROM WPSATTENDANCEDAYWISE
WHERE 1=1
AND COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
AND TOKENNO=<<TOKENNO>>
AND ATTENDANCETAG=''DEVICE''
AND DATEOFATTENDANCE=TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
ORDER BY DEPARTMENTCODE', 'DEPARTMENTCODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6069, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~TOKENNO~DEPARTMENTCODE~PATTERN', 'WPS SHIFT INFORMATION', NULL, 
    'SELECT SHIFTCODE FROM WPSATTENDANCEDAYWISE
WHERE 1=1
AND COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
AND TOKENNO=<<TOKENNO>>
AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
AND ATTENDANCETAG=''DEVICE''
AND DATEOFATTENDANCE=TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
ORDER BY SHIFTCODE', 'SHIFTCODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6078, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS CALENDAR DAY FOR HOLIDAY', NULL, 
    'select /* level as dow, */  UPPER(to_char(trunc(sysdate ,''D'') + level, ''Day'')) as day from dual connect by level <= 7 AND 1=1', 'DAY~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6001, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS DEPARTMENT INFROMATION', NULL, 
    'SELECT DEPARTMENTCODE, DEPARTMENTNAME
  FROM WPSDEPARTMENTMASTER 
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
 ORDER BY DEPARTMENTCODE', 'DEPARTMENTCODE~DEPARTMENTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6002, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS SECTION INFROMATION', NULL, 
    'SELECT SECTIONCODE, SECTIONNAME, GRADERATE GRD_RT, INCREMENTRATE INCR_RT
  FROM WPSSECTIONMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
 ORDER BY SECTIONCODE', 'SECTIONCODE~SECTIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6003, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS SECTION INFROMATION', NULL, 
    'SELECT SECTIONCODE, SECTIONNAME,DEPARTMENTCODE
  FROM WPSSECTIONMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND DEPARTMENTCODE=DECODE(NVL(<<DEPARTMENTCODE>>,''XX''),''XX'',DEPARTMENTCODE,<<DEPARTMENTCODE>>)
 ORDER BY SECTIONCODE', 'SECTIONCODE~SECTIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6004, '""', 'COMPANYCODE~DIVISIONCODE~SECTIONCODE~PATTERN', 'WPS OCCUPATION INFROMATION', NULL, 
    'SELECT OCCUPATIONCODE, OCCUPATIONNAME
  FROM WPSOCCUPATIONMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND DEPARTMENTCODE = <<DEPARTMENTCODE>>
   AND SECTIONCODE =<<SECTIONCODE>>
 ORDER BY OCCUPATIONCODE', 'OCCUPATIONCODE~OCCUPATIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6005, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS CATEGORY INFROMATION', NULL, 
    'SELECT WORKERCATEGORYCODE, WORKERCATEGORYNAME
  FROM WPSWORKERCATEGORYMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
 ORDER BY WORKERCATEGORYCODE', 'WORKERCATEGORYCODE~WORKERCATEGORYNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6006, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS WORKER INFROMATION', NULL, 
    'SELECT TOKENNO,WORKERNAME,WORKERSERIAL,B.DEPARTMENTNAME,A.WORKERCATEGORYCODE CATG, ESINO,A.UANNO UAN
  FROM WPSWORKERMAST A,
       WPSDEPARTMENTMASTER B
 WHERE A.COMPANYCODE = <<COMPANYCODE>> 
   AND A.DIVISIONCODE = <<DIVISIONCODE>>
   AND A.COMPANYCODE = B.COMPANYCODE
   AND A.DIVISIONCODE = B.DIVISIONCODE
   AND A.DEPARTMENTCODE = B.DEPARTMENTCODE
 ORDER BY TOKENNO', 'TOKENNO~WORKERNAME~WORKERSERIAL~DEPARTMENTNAME~ESINO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6007, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS CATEGORY VS COMPONENT', NULL, 
    'SELECT DISTINCT TO_CHAR(EFFECTIVEDATE,''DD/MM/RRRR'') EFFECTIVEDATE
  FROM WPSWORKERCATEGORYVSCOMPONENT
 WHERE 1=1 
   AND COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
 ORDER BY 1 DESC', 'EFFECTIVEDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6008, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PTAX SLAB', NULL, 
    'SELECT DISTINCT TO_CHAR(WITHEFFECTFROM,''DD/MM/RRRR'') WITHEFFECTFROM
  FROM PTAXSLAB
WHERE 1=1  
 ORDER BY 1 DESC', 'EFFECTIVEDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6009, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS STANDARD HOURS', NULL, 
    'SELECT DISTINCT TO_CHAR(FORTNIGHTSTARTDATE,''DD/MM/RRRR'') FORTNIGHTSTARTDATE,
       DEPARTMENTTYPECODE
  FROM WPSSTANDARDHOURS
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>  
 ORDER BY 1 DESC', 'FORTNIGHTSTARTDATE~DEPARTMENTTYPECODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6010, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS COMPONENT GROUP INFO', NULL, 
    'SELECT DISTINCT COMPONENTGROUP
  FROM WPSCOMPONENTGROUP 
WHERE 1=1  
 ORDER BY 1 DESC', 'COMPONENTGROUP~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6011, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS COMPONENT INFORMATION', NULL, 
    'SELECT COMPONENTCODE, COMPONENTNAME,COMPONENTTYPE,COMPONENTSHORTNAME 
  FROM WPSCOMPONENTMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>> 
 ORDER BY 1 DESC', 'COMPONENTCODE~COMPONENTNAME~COMPONENTTYPE~COMPONENTSHORTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6012, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PRODUCTION TYPE INFORMATION', NULL, 
    'SELECT PRODUCTIONTYPECODE, PRODUCTIONTYPEDESC, DEPARTMENTCODE, SECTIONCODE 
FROM WPSPRODUCTIONTYPEMAST WHERE COMPANYCODE=<<COMPANYCODE>>  AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY 1 DESC ', 'PRODUCTIONTYPECODE~PRODUCTIONTYPEDESC~DEPARTMENTCODE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6072, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS CONTRACTOR INFORMATION', NULL, 
    'SELECT CONTRACTORCODE,CONTRACTORNAME FROM WPSCONTRACTORMAST
WHERE 1=1
AND COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY 1', 'CONTRACTORCODE~CONTRACTORNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6073, '""', 'COMPANYCODE~DIVISIONCODE~WORKERSERIAL~LOANCODE~LOANDATE~PATTERN', 'LOAN APPLICATION INFO', NULL, 
    'SELECT DISTINCT APPLICATIONNO,TO_CHAR(LOANDATE,''DD/MM/YYYY'') LOANDATE FROM LOANTRANSACTION
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND WORKERSERIAL=<<WORKERSERIAL>>
  AND LOANCODE=<<LOANCODE>> 
  ORDER BY LOANDATE', 'APPLICATIONNO~LOANDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6076, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~PATTERN', 'WPS WORKER INFROMATION', NULL, 
    'SELECT TOKENNO,WORKERNAME,WORKERSERIAL FROM (
SELECT TOKENNO,WORKERNAME,WORKERSERIAL FROM WPSWORKERMAST
 WHERE WORKERSERIAL IN (    
     SELECT WORKERSERIAL FROM WPSWORKERMAST 
     MINUS
     SELECT WORKERSERIAL FROM WPSWORKERTOKENCHANGE 
      WHERE COMPANYCODE = <<COMPANYCODE>> AND DIVISIONCODE = <<DIVISIONCODE>>
        AND EFFECTIVEDATE||''~''||WORKERSERIAL IN ( 
                                            SELECT MAX(EFFECTIVEDATE)||''~''||WORKERSERIAL AA
                                              FROM WPSWORKERTOKENCHANGE   
                                             WHERE COMPANYCODE = <<COMPANYCODE>> AND DIVISIONCODE = <<DIVISIONCODE>> 
                                               AND EFFECTIVEDATE >= TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
                                             GROUP BY WORKERSERIAL
                                          )
                    )   
UNION
SELECT OLDTOKENNO TOKENNO,B.WORKERNAME,A.WORKERSERIAL 
FROM WPSWORKERTOKENCHANGE A,WPSWORKERMAST B
WHERE B.COMPANYCODE = <<COMPANYCODE>> AND B.DIVISIONCODE = <<DIVISIONCODE>>
 AND A.EFFECTIVEDATE||''~''||A.WORKERSERIAL IN ( 
                                    SELECT MAX(EFFECTIVEDATE)||''~''||WORKERSERIAL AA
                                      FROM WPSWORKERTOKENCHANGE   
                                     WHERE COMPANYCODE = <<COMPANYCODE>> AND DIVISIONCODE = <<DIVISIONCODE>> 
                                       AND EFFECTIVEDATE >= TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
                                     GROUP BY WORKERSERIAL
                                  )   
 AND B.WORKERSERIAL=A.WORKERSERIAL
) WHERE 1=1  
ORDER BY TOKENNO DESC', 'TOKENNO~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6059, '""', 'COMPANYCODE~DIVISIONCODE~FORTNIGHTSTARTDATE~FORTNIGHTENDDATE~PATTERN', 'WPS DOCUMENT INFO', NULL, 
    'SELECT DISTINCT A.DOCUMENTNO,TO_CHAR(A.DOCUMENTDATE,''DD/MM/YYYY'') DOCUMENTDATE,A.TOKENNO,B.WORKERNAME ,A.DEPARTMENTCODE ,C.DEPARTMENTNAME
 FROM WPSSTLENTRY A , WPSWORKERMAST B , WPSDEPARTMENTMASTER C
WHERE A.COMPANYCODE=<<COMPANYCODE>>
  AND A.DIVISIONCODE=<<DIVISIONCODE>>
  AND A.COMPANYCODE=B.COMPANYCODE(+)
  AND A.DIVISIONCODE=B.DIVISIONCODE(+)
  AND A.TOKENNO=B.TOKENNO(+)
  AND A.DEPARTMENTCODE=B.DEPARTMENTCODE(+)
  AND A.COMPANYCODE=C.COMPANYCODE
  AND A.DIVISIONCODE=C.DIVISIONCODE
  AND A.DEPARTMENTCODE=C.DEPARTMENTCODE
  AND A.FORTNIGHTSTARTDATE = TO_DATE(<<FORTNIGHTSTARTDATE>>,''DD/MM/YYYY'') 
  AND A.FORTNIGHTENDDATE = TO_DATE(<<FORTNIGHTENDDATE>>,''DD/MM/YYYY'')
  AND 1=1
 ORDER BY TO_DATE(DOCUMENTDATE,''DD/MM/YYYY'') DESC,SUBSTR(DOCUMENTNO,10,5) DESC', 'A.TOKENNO~A.DOCUMENTNO~A.DOCUMENTDATE~B.WORKERNAME~A.DEPARTMENTCODE~C.DEPARTMENTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6089, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS MACHINE MASTER', NULL, 
    'SELECT DISTINCT MACHINECODE, MACHINENAME, PRODUCTIONTYPE  
FROM WPSMACHINEMASTER A, DEPARTMENTMASTER B
WHERE A.COMPANYCODE=<<COMPANYCODE>>  
  AND A.DIVISIONCODE=<<DIVISIONCODE>>
  AND A.COMPANYCODE = B.COMPANYCODE
  AND A.DIVISIONCODE = B.DIVISIONCODE
  AND B.DEPARTMENTCODE = <<DEPARTMENTCODE>>
  AND A.DEPARTMENTCODE = B.DEPTGROUPCODE
ORDER BY 1 ', 'MACHINECODE~MACHINENAME~PRODUCTIONTYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6090, '""', 'COMPANYCODE~DIVISIONCODE~FORTNIGHTSTARTDATE~FORTNIGHTENDDATE~LEAVEENCASHMENT~PATTERN', 'WPS DOCUMENT INFO', NULL, 
    'SELECT DISTINCT A.DOCUMENTNO,TO_CHAR(A.DOCUMENTDATE,''DD/MM/YYYY'') DOCUMENTDATE,A.TOKENNO,B.WORKERNAME,TO_CHAR(A.STLFROMDATE,''DD/MM/YYYY'') FROMDATE,TO_CHAR(A.STLTODATE,''DD/MM/YYYY'') TODATE,A.DEPARTMENTCODE ,C.DEPARTMENTNAME
 FROM WPSSTLENTRY A , WPSWORKERMAST B , WPSDEPARTMENTMASTER C
WHERE A.COMPANYCODE=<<COMPANYCODE>>
  AND A.DIVISIONCODE=<<DIVISIONCODE>>
  AND A.COMPANYCODE=B.COMPANYCODE(+)
  AND A.DIVISIONCODE=B.DIVISIONCODE(+)
  AND A.TOKENNO=B.TOKENNO(+)
  AND A.DEPARTMENTCODE=B.DEPARTMENTCODE(+)
  AND A.COMPANYCODE=C.COMPANYCODE
  AND A.DIVISIONCODE=C.DIVISIONCODE
  AND A.DEPARTMENTCODE=C.DEPARTMENTCODE
  AND A.FORTNIGHTSTARTDATE = TO_DATE(<<FORTNIGHTSTARTDATE>>,''DD/MM/YYYY'') 
  AND A.FORTNIGHTENDDATE = TO_DATE(<<FORTNIGHTENDDATE>>,''DD/MM/YYYY'')
  AND A.LEAVEENCASHMENT=<<LEAVEENCASHMENT>>
  AND A.LEAVECODE=''STL''
  AND 1=1
 ORDER BY TO_DATE(DOCUMENTDATE,''DD/MM/YYYY'') DESC,SUBSTR(DOCUMENTNO,10,5) DESC', 'TOKENNO~DOCUMENTNO~DOCUMENTDATE~WORKERNAME~DEPARTMENTCODE~DEPARTMENTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6101, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'LOAN EMI APPLICATION INFO', NULL, 
    'SELECT DISTINCT APPLICATIONNO,TO_CHAR(WITHEFFECTFROM,''DD/MM/YYYY'') WITHEFFECTFROM FROM PFLOANEMICHANGE
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY APPLICATIONNO DESC', 'APPLICATIONNO~WITHEFFECTFROM~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6034, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'DAILY WAGES', NULL, 
    'SELECT DISTINCT TO_CHAR(DATEOFATTENDANCE, ''DD/MM/YYYY'') DATEOFATTENDANCE FROM WPSDAILYWAGES
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
ORDER BY DATEOFATTENDANCE DESC
', 'DATEOFATTENDANCE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6079, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'IMPORT INFO', NULL, 
    'SELECT LOANCODE,LOANDESC FROM PFLOANMASTER 
WHERE COMPANYCODE =<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
AND LOANTYPE IS NULL', 'LOANCODE~LOANDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6102, '""', 'COMPANYCODE~DIVISIONCODE~APPLICATIONNO~PATTERN', 'LOAN APPLICATION INFO', NULL, 
    '  SELECT DISTINCT APPLICATIONNO,TO_CHAR(LOANDATE,''DD/MM/YYYY'') LOANDATE , TOKENNO FROM LOANTRANSACTION
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY LOANDATE', 'APPLICATIONNO~LOANDATE~TOKENNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6065, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS HOLIDAY INFORMATION', NULL, 
    'SELECT TO_CHAR(HOLIDAYDATE,''DD/MM/YYYY'') HOLIDAYDATE 
FROM ( 
    SELECT DISTINCT HOLIDAYDATE   
    FROM PISHOLIDAYMASTER 
    WHERE COMPANYCODE=<<COMPANYCODE>>
      AND DIVISIONCODE=<<DIVISIONCODE>>
    ORDER BY  HOLIDAYDATE  desc
    )  ', 'HOLIDAYDATE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6070, '""', 'COMPANYCODE~DIVISIONCODE~COMPONENTCODE~PATTERN', 'WPS COMPONENT SLAB DATE', NULL, 
    'SELECT DISTINCT TO_CHAR(WITHEFFECTFROM,''DD/MM/YYYY'') WITHEFFECTFROM
  FROM COMPONENTSLABMASTER
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND COMPONENTCODE=<<COMPONENTCODE>>
  AND 1=1  
 ORDER BY 1 DESC', 'EFFECTIVEDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6071, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS COMPONENT ', NULL, 
    'SELECT COMPONENTSHORTNAME COMPONENTCODE,COMPONENTNAME 
  FROM WPSCOMPONENTMASTER 
WHERE  COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND 1=1  
 ORDER BY 1', 'COMPONENTCODE~COMPONENTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6075, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS LOAN INFORMATION', NULL, 
    'SELECT DISTINCT LOANCODE,LOANDESC
FROM  LOANMASTER   
 WHERE COMPANYCODE=<<COMPANYCODE>>  
   AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY 1 ', 'LOANCODE~LOANDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6087, '""', 'COMPANYCODE~DIVISIONCODE~SHIFTCODE~DATEOFATTENDANCE~PATTERN', 'WPS WORKER INFROMATION BY SHIFT AND ATTENDANCEDATE', NULL, 
    'SELECT * FROM (SELECT DISTINCT A.TOKENNO,A.WORKERNAME,A.WORKERSERIAL
  FROM WPSWORKERMAST A, WPSATTENDANCEDAYWISE B
 WHERE A.COMPANYCODE = <<COMPANYCODE>> 
   AND A.DIVISIONCODE =<<DIVISIONCODE>>
   AND A.COMPANYCODE=B.COMPANYCODE
   AND A.DIVISIONCODE=B.DIVISIONCODE
   AND B.DATEOFATTENDANCE=TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
   AND B.SHIFTCODE=<<SHIFTCODE>>)
 WHERE 1=1
 ORDER BY TOKENNO
 ', 'TOKENNO~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6088, '""', 'COMPANYCODE~DIVISIONCODE~SHIFTCODE~', 'SPELL INFROMATION', NULL, 
    'SELECT SPELLTYPE
       FROM WPSSPELLMASTER
      WHERE COMPANYCODE = <<COMPANYCODE>> 
        AND DIVISIONCODE =<<DIVISIONCODE>>
        AND SHIFTCODE = <<SHIFTCODE>>', 'SPELLTYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6083, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~PATTERN', 'WPS WORKER INFROMATION', NULL, 
    'SELECT * FROM (SELECT DISTINCT A.TOKENNO,A.WORKERNAME,A.WORKERSERIAL
       FROM WPSWORKERMAST A, WPSATTENDANCEDAYWISE B
      WHERE A.COMPANYCODE = <<COMPANYCODE>> 
        AND A.DIVISIONCODE =<<DIVISIONCODE>>
        AND B.DATEOFATTENDANCE = TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
        AND A.COMPANYCODE = B.COMPANYCODE
        AND A.DIVISIONCODE = B.DIVISIONCODE
      ORDER BY TOKENNO)', 'A.TOKENNO~A.WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6084, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~PATTERN', 'WPS WORKER INFROMATION', NULL, 
    'SELECT * FROM (SELECT DISTINCT A.TOKENNO,A.WORKERNAME,A.WORKERSERIAL
       FROM WPSWORKERMAST A, WPSWORKERACCIDENTDETAILS B
      WHERE A.COMPANYCODE = <<COMPANYCODE>> 
        AND A.DIVISIONCODE =<<DIVISIONCODE>>
        AND B.DATEOFATTENDANCE = TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
        AND A.COMPANYCODE = B.COMPANYCODE
        AND A.DIVISIONCODE = B.DIVISIONCODE
        AND A.WORKERSERIAL=B.WORKERSERIAL
      ORDER BY TOKENNO)', 'A.TOKENNO~A.WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6086, '""', 'COMPANYCODE~DIVISIONCODE~SHIFTCODE~TOKENNO~DATEOFATTENDANCE', 'SPELL INFROMATION', NULL, 
    'SELECT DISTINCT B.SPELLTYPE,B.MAXSPELLHOURS,A.SHIFTCODE
       FROM WPSATTENDANCEDAYWISE A, WPSSPELLMASTER B
      WHERE A.COMPANYCODE = <<COMPANYCODE>> 
        AND A.DIVISIONCODE =<<DIVISIONCODE>>
        AND A.DATEOFATTENDANCE = TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
        AND A.SHIFTCODE = <<SHIFTCODE>>
        AND A.TOKENNO = <<TOKENNO>>
        AND A.COMPANYCODE = B.COMPANYCODE
        AND A.DIVISIONCODE = B.DIVISIONCODE
        AND A.SHIFTCODE = B.SHIFTCODE
        AND A.SPELLTYPE = B.SPELLTYPE', 'SPELLTYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6085, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~PATTERN', 'WPS WORKER INFROMATION', NULL, 
    'SELECT * FROM (SELECT DISTINCT A.TOKENNO,A.WORKERNAME,A.WORKERSERIAL
       FROM WPSWORKERMAST A, WPSWORKERGATEPASSDETAILS B
      WHERE A.COMPANYCODE = <<COMPANYCODE>> 
        AND A.DIVISIONCODE =<<DIVISIONCODE>>
        AND B.DATEOFATTENDANCE = TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
        AND A.COMPANYCODE = B.COMPANYCODE
        AND A.DIVISIONCODE = B.DIVISIONCODE
        AND A.WORKERSERIAL=B.WORKERSERIAL
      ORDER BY TOKENNO)', 'A.TOKENNO~A.WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6051, '""', 'COMPANYCODE~DIVISIONCODE~PROJECTNO~PATTERN', 'WPS PRODUCTION TYPE INFORMATION', NULL, 
    'SELECT PRODUCTIONTYPECODE, PRODUCTIONTYPEDESC, DEPARTMENTCODE, SECTIONCODE 
FROM WPSPRODUCTIONTYPEMAST WHERE COMPANYCODE=<<COMPANYCODE>>  AND DIVISIONCODE=<<DIVISIONCODE>> 
 AND DEPARTMENTCODE IN (SELECT DISTINCT DEPARTMENTCODE FROM WPSWORKORDERWISERATEMASTER
                         WHERE COMPANYCODE=<<COMPANYCODE>>  AND DIVISIONCODE=<<DIVISIONCODE>>
                           AND ORDERNO=<<PROJECTNO>>)
ORDER BY 1 DESC ', 'PRODUCTIONTYPECODE~PRODUCTIONTYPEDESC~DEPARTMENTCODE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6052, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PROJECT NO', NULL, 
    'SELECT DISTINCT ORDERNO, TO_CHAR(ORDERDATE,''DD/MM/YYYY'') ORDERDATE FROM WPSWORKORDERWISERATEMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>  AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY ORDERNO', 'ORDERNO~ORDERDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6053, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS LOAN STOP APPLICATION NO', NULL, 
    'SELECT DISTINCT APPLICATIONNO, TO_CHAR(APPLICATIONDATE,''DD/MM/YYYY'') APPLICATIONDATE,MODULE
  FROM PFLOANDEDUCTIONSTOP
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY APPLICATIONNO', 'APPLICATIONNO~APPLICATIONDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6054, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PF INFO', NULL, 
    'SELECT PFNO, WORKERNAME, WORKERSERIAL, TOKENNO
  FROM WPSWORKERMAST
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY WORKERSERIAL', 'PFNO~WORKERNAME~WORKERSERIAL~TOKENNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6055, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PF LOAN INFO', NULL, 
    'SELECT LOANCODE, LOANDESC
  FROM PFLOANMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY LOANCODE', 'LOANCODE~LOANDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6056, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~ORDERNO~PATTERN', 'WPS PROJECT AND DEPARTMENT WISE OCCUPATION INFROMATION', NULL, 
    'SELECT OCCUPATIONCODE, OCCUPATIONNAME
  FROM WPSOCCUPATIONMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
   AND OCCUPATIONCODE IN (SELECT DISTINCT OCCUPATIONCODE FROM WPSWORKORDERWISERATEMASTER
                           WHERE COMPANYCODE = <<COMPANYCODE>> 
                             AND DIVISIONCODE =<<DIVISIONCODE>>
                             AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
                             AND ORDERNO=<<ORDERNO>>
                         )
 ORDER BY OCCUPATIONCODE', 'OCCUPATIONCODE~OCCUPATIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6057, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PROJECT INFO', NULL, 
    'SELECT DISTINCT PRODUCTIONNO||''~''||TO_CHAR(STARTDATE,''DD/MM/YYYY'')||''~''||PRODUCTIONTYPECODE||''~''||DEPARTMENTCODE||''~''||SHIFTCODE XX
  FROM WPSPRODUCTIONSUMMARY
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND PRODUCTIONNO IS NOT NULL
 ORDER BY XX', 'XX~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6060, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS WORKER INFO', NULL, 
    'SELECT DISTINCT TOKENNO,WORKERSERIAL,WORKERNAME FROM WPSWORKERMAST
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY TOKENNO,WORKERSERIAL', 'TOKENNO~WORKERSERIAL~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6061, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS LOAN INFO', NULL, 
    'SELECT LOANCODE,LOANDESC FROM WPSWORKERLOANMASTER
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY LOANCODE', 'LOANCODE~LOANDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6064, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~ATTENDANCETAG~PATTERN', 'WPS BOOK INFORMATION', NULL, 
    'SELECT DISTINCT BOOKNO, TO_CHAR(DATEOFATTENDANCE,''DD/MM/YYYY'') DATEOFATTENDANCE, DEPARTMENTCODE, SHIFTCODE
  FROM WPSATTENDANCEDAYWISE
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND YEARCODE=<<YEARCODE>>
   AND ATTENDANCETAG=<<ATTENDANCETAG>>
   AND BOOKNO IS NOT NULL
 ORDER BY TO_DATE(DATEOFATTENDANCE,''DD/MM/YYYY'') DESC, BOOKNO DESC', 'BOOKNO~DATEOFATTENDANCE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6063, '""', 'COMPANYCODE~DIVISIONCODE~TOKENNO~LOANCODE~PATTERN', 'WPS LOAN INFO', NULL, 
    'SELECT DISTINCT TO_CHAR(LOANDATE,''DD/MM/YYYY'') LOANDATE 
FROM NORMALLOANAPPLICATION 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>
AND TOKENNO=<<TOKENNO>>
AND LOANCODE=<<LOANCODE>>
ORDER BY LOANDATE', 'LOANDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6058, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS COPONENT INFO', NULL, 
    'SELECT COMPONENT FROM (
SELECT TABLE_NAME||''.''||COLUMN_NAME COMPONENT FROM COLS 
 WHERE TABLE_NAME =''COMPONENT''  
UNION ALL
SELECT TABLE_NAME||''.''||COLUMN_NAME COMPONENT FROM COLS 
 WHERE TABLE_NAME =''MAST''
UNION ALL
SELECT TABLE_NAME||''.''||COLUMN_NAME COMPONENT FROM COLS  
 WHERE TABLE_NAME =''ATTN''
UNION ALL
SELECT ''SECMST.''||COLUMN_NAME FROM COLS 
 WHERE TABLE_NAME LIKE ''VW_WPSSECTIONMAST%''
   AND COLUMN_NAME NOT LIKE ''%NAME%'' AND COLUMN_NAME NOT IN (''COMPANYCODE'',''DIVISIONCODE'',''LISTINDEX'',''ATTN_GRID_TAG'',''DEFAULTSECTION'')
)
WHERE 1=1   
ORDER BY 1', 'COMPONENT~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6066, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS DATEOFATTENDENCE INFORMATION', NULL, 
    'SELECT DISTINCT TO_CHAR(DATEOFATTENDANCE,''DD/MM/YYYY'') DATEOFATTENDANCE FROM WPSATTENDANCEDAYWISE
WHERE 1=1
AND COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
AND  ATTENDANCETAG=''DEVICE''', 'DATEOFATTENDANCE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6067, '""', 'COMPANYCODE~DIVISIONCODE~DATEOFATTENDANCE~PATTERN', 'WPS TOKEN INFORMATION', NULL, 
    'SELECT A.TOKENNO , B.WORKERNAME FROM WPSATTENDANCEDAYWISE A, WPSWORKERMAST B
WHERE 1=1
AND A.COMPANYCODE=<<COMPANYCODE>>
AND A.DIVISIONCODE=<<DIVISIONCODE>>
AND A.ATTENDANCETAG=''DEVICE''
AND A.DATEOFATTENDANCE=TO_DATE(<<DATEOFATTENDANCE>>,''DD/MM/YYYY'')
AND A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.TOKENNO=B.TOKENNO', 'TOKENNO~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6033, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'LEAVE TYPE MASTER', NULL, 
    'SELECT LEAVECODE,LEAVEDESC FROM WPSLEAVEMASTER
WHERE 1=1
  AND COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND LEAVECODE<>''STL''
ORDER BY LEAVECODE', 'LEAVECODE~LEAVEDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6077, '""', 'PATTERN~', 'IMPORT INFO', NULL, 
    'SELECT DISTINCT ATTENDATE 
FROM WPSATTENDANCECSVRAWDATA  
 WHERE 1=1
 AND NVL(APPROVED,''N'')=''N'' 
 AND NVL(VERIFIED,''N'')=''Y'' 
 AND TRIM((ATTENDATE)) NOT IN (SELECT DISTINCT TO_CHAR(DATEOFATTENDANCE,''DD/MM/YYYY'') FROM WPSATTENDANCEDAYWISE WHERE ATTENDANCETAG=''MANUAL UPLOAD'') 
ORDER BY 1 ', 'DATEOFATTENDANCE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6200, '""', 'COMPANYCODE~DIVISIONCODE', 'EMPLOYEE STATUS', NULL, 
    'SELECT ''DEATH'' STATUS FROM DUAL
UNION
SELECT ''ACTIVE'' STATUS FROM DUAL
UNION
SELECT ''RETIRED'' STATUS FROM DUAL
UNION
SELECT ''TERMINATE'' STATUS FROM DUAL
UNION
SELECT ''NAME REMOVED'' STATUS FROM DUAL', NULL, 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6201, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS SECTION INFROMATION', NULL, 
    'SELECT SECTIONCODE, SECTIONNAME
  FROM WPSSECTIONMAST
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   --AND DEPARTMENTCODE=DECODE(NVL(<<DEPARTMENTCODE>>,''XX''),''XX'',DEPARTMENTCODE,<<DEPARTMENTCODE>>)
 ORDER BY SECTIONCODE', 'SECTIONCODE~SECTIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6114, '""', 'COMPANYCODE~DIVISIONCODE', 'WPS EMPLOYEE DATA', NULL, 
    'SELECT TOKENNO, WORKERNAME, FATHERNAME,WORKERSERIAL,WORKERCATEGORYCODE, DEPARTMENTCODE FROM WPSWORKERMAST 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY WORKERSERIAL', 'TOKENNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6115, '""', 'COMPANYCODE~DIVISIONCODE', 'WPS NPS EFFECTIVEDATE', NULL, 
    'SELECT DISTINCT TO_CHAR(EFFECTIVEDATE,''dd/MM/yyyy'') EFFECTIVEDATE FROM WPSNPFADJUSTMENTPARAMETER
WHERE COMPANYCODE=<<COMPANYCODE>> AND DIVISIONCODE=<<DIVISIONCODE>>', 'EFFECTIVEDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6116, '""', NULL, 'WPS NPS ADJUSTMENTTYPE', NULL, 
    'SELECT ''LUMPSUM'' AS TYPE FROM DUAL
UNION ALL
SELECT ''HOURBASED'' AS TYPE FROM DUAL', 'TYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6117, '""', NULL, 'WPS NPS HOURTYPE', NULL, 
    'SELECT ''NORMAL'' AS HTYPE FROM DUAL
UNION ALL
SELECT ''NORMAL+OT'' AS HTYPE FROM DUAL', 'HTYPE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6118, '""', 'COMPANYCODE~DIVISIONCODE', 'WPS NPS GETDATA', NULL, 
    'SELECT A.EFFECTIVEDATE, A.TOKENNO,B.WORKERNAME,A.ADJUSTMENTTYPE,A.HOURTYPE,A.WORKINGHOUR,A.NPFAMOUNT,A.COMPANYCODE,A.DIVISIONCODE,A.WORKERSERIAL FROM WPSNPFADJUSTMENTPARAMETER A, WPSWORKERMAST B
WHERE A.COMPANYCODE=<<COMPANYCODE>> AND A.DIVISIONCODE=<<DIVISIONCODE>>
AND A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE AND A.WORKERSERIAL=B.MCODE
ORDER BY TOKENNO', 'TOKENNO~WORKERNAME~ADJUSTMENTTYPE~HOURTYPE~WORKINGHOUR~NPFAMOUNT~COMPANYCODE~DIVISIONCODE~WORKERSERIAL~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6119, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'REEDSPACE CODE', NULL, 
    'SELECT REEDSPACE FROM WPSREEDSPACEMAST 
WHERE COMPANYCODE=<<COMPANYCODE>> AND  DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY REEDSPACE', 'REEDSPACE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6204, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~STARTDATE~PATTERN', 'PRODUCTION NUMBER', NULL, 
    'SELECT DISTINCT PRODUCTIONNO
FROM WPSPRODUCTIONSUMMARY
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
AND YEARCODE = <<YEARCODE>>
AND STARTDATE = TO_DATE(<<STARTDATE>>,''DD/MM/YYYY'')
ORDER BY PRODUCTIONNO', 'PRODUCTIONNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6203, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~PATTERN', 'PRODUCTION DATE', NULL, 
    'SELECT DISTINCT TO_CHAR(STARTDATE,''DD/MM/YYYY'') STARTDATE FROM WPSPRODUCTIONSUMMARY
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
AND YEARCODE = <<YEARCODE>> 
ORDER BY STARTDATE DESC', 'STARTDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6202, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~QUALITYCODE~PATTERN', 'PRODUCTION MACHINE INFORMATION', NULL, 
    'SELECT MACHINECODE, MACHINENAME
FROM
(
    SELECT M.MACHINECODE, M.MACHINENAME, MAX(P.EFFECTIVEDATE) EFFECTIVEDATE  FROM 
        WPSMACHINEMASTER M, WPSMACHINELOOMMAPPING P, WPSDAILYLOOMALLOCATION L
        WHERE M.COMPANYCODE = P.COMPANYCODE
        AND M.DIVISIONCODE = P.DIVISIONCODE
        AND M.MACHINECODE = P.MACHINECODE
        AND M.COMPANYCODE = L.COMPANYCODE 
        AND M.DIVISIONCODE = L.DIVISIONCODE 
        AND M.MACHINECODE = L.MACHINECODE 
        AND M.COMPANYCODE = <<COMPANYCODE>>
        AND M.DIVISIONCODE = <<DIVISIONCODE>>
        AND M.DEPARTMENTCODE = <<DEPARTMENTCODE>>
        AND L.QUALITYCODE = <<QUALITYCODE>>
    GROUP BY M.MACHINECODE, M.MACHINENAME
)', 'MACHINECODE~MACHINENAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6205, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS SARDAR INFORMATION', NULL, 
    'SELECT SARDERNO, SARDERDESC 
FROM WPSLINESARDERMAST
WHERE COMPANYCODE = <<COMPANYCODE>>
        AND DIVISIONCODE = <<DIVISIONCODE>>
        AND DEPARTMENTCODE = <<DEPARTMENTCODE>>
        AND GROUPTYPE=''SARDAR''', 'SARDERNO~SARDERDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6206, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS PF INFO', NULL, 
    'SELECT TOKENNO, WORKERNAME
  FROM WPSWORKERMAST
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY WORKERNAME', 'WORKERSERIAL~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6207, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS QUALITY INFORMATION', NULL, 
    'SELECT QUALITYCODE, QUALITYNAME FROM WPSQUALITYMASTER A, WPSPRODUCTIONTYPEMAST B
WHERE A.COMPANYCODE=B.COMPANYCODE
    AND A.DIVISIONCODE=B.DIVISIONCODE
    AND A.PRODUCTIONTYPE=B.PRODUCTIONTYPECODE
    AND A.COMPANYCODE=<<COMPANYCODE>>
    AND A.DIVISIONCODE=<<DIVISIONCODE>>
    AND B.DEPARTMENTCODE=<<DEPARTMENTCODE>>
ORDER BY QUALITYCODE', 'QUALITYCODE~QUALITYNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6208, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS MACHINE INFORMATION', NULL, 
    'SELECT MACHINECODE,MACHINENAME FROM WPSMACHINEMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
ORDER BY MACHINECODE', 'MACHINECODE~MACHINENAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6209, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'PRODUCTION MACHINE INFORMATION', NULL, 
    'SELECT MACHINECODE, MACHINENAME
FROM
(
    SELECT M.MACHINECODE, M.MACHINENAME, MAX(P.EFFECTIVEDATE) EFFECTIVEDATE  FROM 
        WPSMACHINEMASTER M, WPSMACHINELOOMMAPPING P, WPSDAILYLOOMALLOCATION L
        WHERE M.COMPANYCODE = P.COMPANYCODE
        AND M.DIVISIONCODE = P.DIVISIONCODE
        AND M.MACHINECODE = P.MACHINECODE
        AND M.COMPANYCODE = L.COMPANYCODE 
        AND M.DIVISIONCODE = L.DIVISIONCODE 
        AND M.MACHINECODE = L.MACHINECODE 
        AND M.COMPANYCODE = <<COMPANYCODE>>
        AND M.DIVISIONCODE = <<DIVISIONCODE>>
        AND M.DEPARTMENTCODE = <<DEPARTMENTCODE>>
    GROUP BY M.MACHINECODE, M.MACHINENAME
)', 'MACHINECODE~MACHINENAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6210, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~QUALITYCODE~PATTERN', 'QUALITY ALLOCATION DATE', NULL, 
    'SELECT DISTINCT TO_CHAR(DATEOFENTRY,''DD/MM/YYYY'') DATEOFENTRY
FROM WPSDAILYLOOMALLOCATION 
WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    and DEPARTMENTCODE=<<DEPARTMENTCODE>> 
    AND QUALITYCODE=<<QUALITYCODE>>
ORDER BY DATEOFENTRY DESC
', 'DATEOFENTRY~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6211, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'PRODUCTION MACHINE INFORMATION', NULL, 
    'SELECT MACHINECODE, MACHINENAME
FROM WPSMACHINEMASTER
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
AND DEPARTMENTCODE = <<DEPARTMENTCODE>>
AND MACHINECODE LIKE ''R%''', 'MACHINECODE~MACHINENAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6906, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS QUALITY TYPE CODE', NULL, 
    'SELECT QUALITYTYPECODE, QUALITYTYPEDESC
FROM  WPSQUALITYTYPEMAST 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>', 'QUALITYTYPECODE~QUALITYTYPEDESC', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6907, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE LINE MAPPING EFFECTIVE DATE', NULL, 
    'SELECT TO_CHAR(EFFECTIVEDATE, ''DD/MM/YYYY'') EFFECTIVEDATE
FROM
(
SELECT DISTINCT EFFECTIVEDATE
FROM WPSMACHINELINEMAPPING
WHERE COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
AND DEPARTMENTCODE = <<DEPARTMENTCODE>>
AND MAPPINGTAG=<<MAPPINGTAG>>
ORDER BY EFFECTIVEDATE DESC
)', 'EFFECTIVEDATE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6908, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE LINE MAPPING DEPARTMENT', NULL, 
    'SELECT DISTINCT A.DEPARTMENTCODE, B.DEPARTMENTNAME
FROM WPSMACHINELINEMAPPING A,WPSDEPARTMENTMASTER B
WHERE A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE = B.DIVISIONCODE
AND A.DEPARTMENTCODE=B.DEPARTMENTCODE 
AND A.COMPANYCODE=<<COMPANYCODE>>
AND A.DIVISIONCODE = <<DIVISIONCODE>>
AND A.MAPPINGTAG=<<MAPPINGTAG>>
ORDER BY DEPARTMENTCODE', 'DEPARTMENTCODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6914, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE INFO', NULL, 
    'SELECT MACHINECODE,MACHINENAME  FROM WPSMACHINEMASTER
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>
AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
ORDER BY MACHINECODE', 'MACHINECODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6909, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE LINE MAPPING LINE NO', NULL, 
    'SELECT TO_NUMBER(SARDERNO) SRL_NO,SARDERDESC DESCRIPSION  FROM WPSLINESARDERMAST
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>
AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
AND GROUPTYPE=<<GROUPTYPE>>
ORDER BY SRL_NO', 'SRL_NO', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6910, '""', 'COMPANYCODE~DIVISIONCODE~ATTENDATE~PATTERN', 'WPS SECTION INFROMATION', NULL, 
    'SELECT DISTINCT  B.SECTIONCODE, B.SECTIONNAME 
FROM WPSATTENDANCECSVRAWDATA A, WPSSECTIONMAST B
WHERE 1=1
AND B.COMPANYCODE=<<COMPANYCODE>>
AND B.DIVISIONCODE=<<DIVISIONCODE>>
AND TO_DATE(A.ATTENDATE,''DD/MM/YYYY'') = TO_DATE(<<ATTENDATE>>,''DD/MM/YYYY'') 
AND A.VERIFIED=''Y'' 
AND A.APPROVED=''N''
AND A.SECTION=B.SECTIONCODE', 'SECTIONCODE~SECTIONNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6912, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS RELATION', NULL, 
    'SELECT ''FATHER'' AS RELATION FROM DUAL
UNION 
SELECT ''MOTHER'' FROM DUAL
UNION 
SELECT ''DAUGHTER'' FROM DUAL
UNION 
SELECT ''SON'' FROM DUAL
UNION 
SELECT ''SISTER'' FROM DUAL
UNION 
SELECT ''BROTHER'' FROM DUAL
UNION 
SELECT ''HUSBAND'' FROM DUAL
UNION 
SELECT ''WIFE'' FROM DUAL', 'RELATION~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6905, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS SUB CONTRACTOR NO', NULL, 
    'SELECT SUBCONTRACTORNO,SUBCONTRACTORNAME,CONTRACTORNO,CONTRACTORNAME
FROM  WPSSUBCONTRACTORMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>', 'SUBCONTRACTORNO~SUBCONTRACTORNAME~CONTRACTORNO~CONTRACTORNAME', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6903, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS CONTRACTOR NO', NULL, 
    'SELECT CONTRACTORNO 
FROM  WPSCONTRACTORMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>', 'CONTRACTORNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6915, '""', 'COMPANYCODE~DIVISIONCODE~LEAVECODE~PATTERN', 'WPS LEAVE INFO', NULL, 
    'SELECT DISTINCT A.DOCUMENTNO,TO_CHAR(A.DOCUMENTDATE,''DD/MM/YYYY'') DOCUMENTDATE,A.TOKENNO,B.WORKERNAME,TO_CHAR(A.STLFROMDATE,''DD/MM/YYYY'') FROMDATE,TO_CHAR(A.STLTODATE,''DD/MM/YYYY'') TODATE,A.DEPARTMENTCODE ,C.DEPARTMENTNAME
 FROM WPSSTLENTRY A , WPSWORKERMAST B , WPSDEPARTMENTMASTER C
WHERE A.COMPANYCODE=<<COMPANYCODE>> 
  AND A.DIVISIONCODE=<<DIVISIONCODE>>
  AND A.COMPANYCODE=B.COMPANYCODE(+)
  AND A.DIVISIONCODE=B.DIVISIONCODE(+)
  AND A.TOKENNO=B.TOKENNO(+)
  AND A.DEPARTMENTCODE=B.DEPARTMENTCODE(+)
  AND A.COMPANYCODE=C.COMPANYCODE
  AND A.DIVISIONCODE=C.DIVISIONCODE
  AND A.DEPARTMENTCODE=C.DEPARTMENTCODE
  AND A.LEAVEENCASHMENT=''N''
  AND A.LEAVECODE=<<LEAVECODE>>
 ORDER BY TO_DATE(DOCUMENTDATE,''DD/MM/YYYY'') DESC,SUBSTR(DOCUMENTNO,10,5) DESC', 'TOKENNO~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6901, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS BANK CODE', NULL, 
    'SELECT IFSCCODE 
FROM SALESBANKMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>', 'IFSCCODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6902, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS CONTRACTOR NO', NULL, 
    'SELECT CONTRACTORNO 
FROM  WPSCONTRACTORMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>', 'CONTRACTORNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6916, '""', 'COMPANYCODE~DIVISIONCODE~PRODUCTIONTYPE~PATTERN', 'MAX EFFECTIVE DATE', NULL, 
    'SELECT DISTINCT TO_CHAR(EFFECTIVEDATE,''DD/MM/YYYY'') EFFECTIVEDATE FROM WPSQUALITYRATE_ON_REEDSPACE
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
AND PRODUCTIONTYPE = <<PRODUCTIONTYPE>>', 'EFFECTIVEDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6919, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE GROUP INFO', NULL, 
    'SELECT MACHINEGROUPCODE,MACHINEGROUPDESC 
FROM WPSMACHINEGROUPMAST 
WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE = <<DIVISIONCODE>>', 'MACHINEGROUPCODE~MACHINEGROUPDESC', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6917, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'MAX EFFECTIVE DATE', NULL, 
    'SELECT TO_CHAR(EFFECTIVEDATE,''DD/MM/YYYY'') EFFECTIVEDATE FROM
(
SELECT DISTINCT EFFECTIVEDATE FROM WPSWORKERWISERATEUPDATE
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
ORDER BY EFFECTIVEDATE DESC
)', 'EFFECTIVEDATE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6918, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS MACHINE INFO', NULL, 
    'SELECT MACHINECODE,MACHINENAME, MACHINEREEDSPACE, LOOMYESNO  FROM MACHINEMASTER
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>>
AND DEPARTMENTCODE=<<DEPARTMENTCODE>>
ORDER BY MACHINECODE', 'MACHINECODE~MACHINENAME~MACHINEREEDSPACE~LOOMYESNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6920, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE LOOM MAPPING EFFECTIVE DATE', NULL, 
    'SELECT DISTINCT TO_CHAR(EFFECTIVEDATE, ''DD/MM/YYYY'') EFFECTIVEDATE
FROM WPSMACHINELOOMMAPPING
WHERE COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
AND DEPARTMENTCODE = <<DEPARTMENTCODE>>
ORDER BY EFFECTIVEDATE', 'EFFECTIVEDATE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6922, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE LOOM MAPPING EFFECTIVE DATE', NULL, 
    'SELECT USRID, USRNAME  FROM TAB_LOGIN
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>', 'USRID~USRNAME', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6923, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS TAB USER MASTER', NULL, 
    'SELECT USRID, USRNAME  FROM TAB_LOGIN
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>', 'USRID~USRNAME', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6921, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS MACHINE LOOM MAPPING EFFECTIVE DATE', NULL, 
    'SELECT DISTINCT  TO_CHAR(FORTNIGHTSTARTDATE) FORTNIGHTSTARTDATE, TO_CHAR(FORTNIGHTENDDATE) FORTNIGHTENDDATE,
MODULENAME FROM TAB_USERINPUTAPPLICABLE
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>
ORDER BY FORTNIGHTSTARTDATE DESC', 'FORTNIGHTSTARTDATE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6924, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'SHIFTCODE', NULL, 
    'SELECT SHIFTCODE, SHIFTNAME FROM WPSSHIFTMAST
WHERE COMPANYCODE = <<COMPANYCODE>>
AND DIVISIONCODE = <<DIVISIONCODE>>', 'SHIFTCODE~SHIFTNAME', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6925, '""', 'COMPANYCODE~DIVISIONCODE~FORTNIGHTSTARTDATE~FORTNIGHTENDDATE~PATTERN', 'WPS HOLIDAY INFORMATION', NULL, 
    'SELECT TO_CHAR(HOLIDAYDATE,''DD/MM/YYYY'') HOLIDAYDATE 
FROM ( 
    SELECT DISTINCT HOLIDAYDATE   
    FROM WPSHOLIDAYMASTER 
    WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND HOLIDAYDATE >= TO_DATE(<<FORTNIGHTSTARTDATE>>,''DD/MM/YYYY'')
    AND HOLIDAYDATE <= TO_DATE(<<FORTNIGHTENDDATE>>,''DD/MM/YYYY'')
    ORDER BY  HOLIDAYDATE  desc
    )      ', 'HOLIDAYDATE', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6926, '""', 'COMPANYCODE~DIVISIONCODE~TOKENNO~TRANSACTIONTYPE~PATTERN', 'POLICY INFROMATION', NULL, 
    'SELECT POLICYNO,TO_CHAR(POLICYDATE,''DD/MM/YYYY'') POLICYDATE FROM LICMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND MODULE=''WPS''
    AND TRANSACTIONTYPE=<<TRANSACTIONTYPE>>
    AND TOKENNO=<<TOKENNO>>', 'POLICYNO~POLICYDATE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6927, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'LOAN INFROMATION', NULL, 
    'SELECT LOANCODE,LOANDESC FROM LOANMASTER
WHERE COMPANYCODE=<<COMPANYCODE>>  AND DIVISIONCODE=<<DIVISIONCODE>>  ', 'LOANCODE~LOANDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6928, '""', 'COMPANYCODE~DIVISIONCODE~LOANCODE~CATE', 'WPS WORKER INFROMATION', NULL, 
    'SELECT TOKENNO,NAME,WORKERSERIAL,DEPT, CATG, ESI, UAN FROM (
    SELECT ''PIS'' AS CATE,''A'' AS EMODE, A.TOKENNO,A.EMPLOYEENAME NAME,A.WORKERSERIAL,B.DEPARTMENTDESC DEPT,A.CATEGORYCODE CATG,A.ESINO ESI,A.UANNO UAN
    FROM PISEMPLOYEEMASTER A, PISDEPARTMENTMASTER B, LOANTRANSACTION C
    WHERE A.COMPANYCODE = <<COMPANYCODE>> 
    AND A.DIVISIONCODE = <<DIVISIONCODE>>
    AND C.LOANCODE = <<LOANCODE>>
    AND A.COMPANYCODE = B.COMPANYCODE
    AND A.DIVISIONCODE = B.DIVISIONCODE
    AND A.DEPARTMENTCODE = B.DEPARTMENTCODE
    AND A.COMPANYCODE = C.COMPANYCODE
    AND A.DIVISIONCODE = C.DIVISIONCODE
    AND A.WORKERSERIAL = C.WORKERSERIAL
  UNION ALL   
    SELECT  ''WPS'' AS CATE,''A'' AS EMODE, A.TOKENNO,A.WORKERNAME NAME,A.WORKERSERIAL,B.DEPARTMENTNAME DEPT,A.WORKERCATEGORYCODE CATG,A.ESINO ESI,A.UANNO UAN
    FROM WPSWORKERMAST A, WPSDEPARTMENTMASTER B, LOANTRANSACTION C
    WHERE A.COMPANYCODE = <<COMPANYCODE>> 
    AND A.DIVISIONCODE = <<DIVISIONCODE>>
    AND C.LOANCODE = <<LOANCODE>>
    AND A.COMPANYCODE = B.COMPANYCODE
    AND A.DIVISIONCODE = B.DIVISIONCODE
    AND A.DEPARTMENTCODE = B.DEPARTMENTCODE
    AND A.COMPANYCODE = C.COMPANYCODE
    AND A.DIVISIONCODE = C.DIVISIONCODE
    AND A.WORKERSERIAL = C.WORKERSERIAL
    UNION ALL  
          SELECT CATE,EMODE, TOKENNO,NAME,WORKERSERIAL,DEPT, CATG, ESI, UAN FROM 
           (
                SELECT ''ALL'' AS CATE,''D'' AS EMODE, A.TOKENNO,A.EMPLOYEENAME NAME,A.WORKERSERIAL,B.DEPARTMENTDESC DEPT,A.CATEGORYCODE CATG,A.ESINO ESI,A.UANNO UAN
                FROM PISEMPLOYEEMASTER A, PISDEPARTMENTMASTER B, LOANTRANSACTION C
                WHERE A.COMPANYCODE = <<COMPANYCODE>> 
                AND A.DIVISIONCODE = <<DIVISIONCODE>>
                AND C.LOANCODE = <<LOANCODE>>
                AND A.COMPANYCODE = B.COMPANYCODE
                AND A.DIVISIONCODE = B.DIVISIONCODE
                AND A.DEPARTMENTCODE = B.DEPARTMENTCODE
                AND A.COMPANYCODE = C.COMPANYCODE
                AND A.DIVISIONCODE = C.DIVISIONCODE
                AND A.WORKERSERIAL = C.WORKERSERIAL
              UNION ALL   
                SELECT  ''ALL'' AS CATE,''D'' AS EMODE, A.TOKENNO,A.WORKERNAME NAME,A.WORKERSERIAL,B.DEPARTMENTNAME DEPT,A.WORKERCATEGORYCODE CATG,A.ESINO ESI,A.UANNO UAN
                FROM WPSWORKERMAST A, WPSDEPARTMENTMASTER B, LOANTRANSACTION C
                WHERE A.COMPANYCODE = <<COMPANYCODE>> 
                AND A.DIVISIONCODE = <<DIVISIONCODE>>
                AND C.LOANCODE = <<LOANCODE>>
                AND A.COMPANYCODE = B.COMPANYCODE
                AND A.DIVISIONCODE = B.DIVISIONCODE
                AND A.DEPARTMENTCODE = B.DEPARTMENTCODE
                AND A.COMPANYCODE = C.COMPANYCODE
                AND A.DIVISIONCODE = C.DIVISIONCODE
                AND A.WORKERSERIAL = C.WORKERSERIAL         
            )
           WHERE  WORKERSERIAL IN (SELECT WORKERSERIAL FROM LOANINTERESTCALCSTOP)
       )
    WHERE CATE=<<CATE>>
    AND EMODE=<<EMODE>>
    ORDER BY TOKENNO', 'TOKENNO~WORKERSERIAL~NAME~ESI', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6929, '""', NULL, 'CON CATEGORY', NULL, 
    'SELECT CATEGORYCODE, CATEGORYNAME FROM WPSCONCATEGORYMASTER', NULL, 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6212, '""', 'COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~PATTERN', 'WPS SARDAR INFORMATION', NULL, 
    'SELECT SARDERNO, SARDERDESC 
FROM WPSLINESARDERMAST
WHERE COMPANYCODE = <<COMPANYCODE>>
        AND DIVISIONCODE = <<DIVISIONCODE>>
        AND DEPARTMENTCODE = <<DEPARTMENTCODE>>
        AND GROUPTYPE=<<SARDERTYPE>>', 'SARDERNO~SARDERDESC', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6930, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'EMPLOYEE/WORKER INFROMATION', NULL, 
    ' 
--       SELECT TOKENNO,EMPLOYEENAME WORKERNAME, WORKERSERIAL, CATEGORYCODE 
--    FROM  PISEMPLOYEEMASTER 
--    WHERE COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
--    AND MODULE=<<MODULE>>
--    AND EMPLOYEESTATUS IN (''DEATH'',''DISMISSED'',''RESIGN'',''RETIRE'') 
--    AND STATUSDATE IS NOT NULL        
--    UNION ALL       
--    SELECT TOKENNO,WORKERNAME, WORKERSERIAL, WORKERCATEGORYCODE
--    FROM WPSWORKERMAST
--    WHERE
--    COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
--    AND MODULE=<<MODULE>>
--    AND WORKERSTATUS IN (''DEATH'',''DISMISSED'',''RESIGN'',''RETIRE'')
--    and DATEOFTERMINATIONADVICE IS NOT NULL
--    ORDER BY TOKENNO
    
   SELECT TOKENNO,EMPLOYEENAME WORKERNAME, WORKERSERIAL, CATEGORYCODE 
    FROM  PISEMPLOYEEMASTER 
    WHERE COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
    AND MODULE=<<MODULE>>
    AND EMPLOYEESTATUS IN (''DEATH'',''DISMISSED'',''RESIGN'',''RETIRE'') 
    AND STATUSDATE IS NOT NULL        
    AND GRATUITYSETTELMENTDATE IS NULL
    UNION ALL       
    SELECT TOKENNO,WORKERNAME, WORKERSERIAL, WORKERCATEGORYCODE
    FROM WPSWORKERMAST
    WHERE
    COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
    AND MODULE=<<MODULE>>
    AND WORKERSTATUS IN (''DEATH'',''DISMISSED'',''RESIGN'',''RETIRE'')
    and DATEOFTERMINATIONADVICE IS NOT NULL
    AND GRATUITYSETTELMENTDATE IS NULL
    ORDER BY TOKENNO', 'TOKENNO~WORKERSERIAL~TOKENNO', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6935, '""', 'COMPANYCODE~DIVISIONCODE~DOCUMENTDATE~LEAVEENCASHMENT~PATTERN', 'WPS DOCUMENT INFO', NULL, 
    'SELECT DISTINCT A.DOCUMENTNO,TO_CHAR(A.DOCUMENTDATE,''DD/MM/YYYY'') DOCUMENTDATE,A.TOKENNO,B.WORKERNAME,TO_CHAR(A.STLFROMDATE,''DD/MM/YYYY'') FROMDATE,TO_CHAR(A.STLTODATE,''DD/MM/YYYY'') TODATE,A.DEPARTMENTCODE ,C.DEPARTMENTNAME
 FROM WPSSTLENTRY A , WPSWORKERMAST B , WPSDEPARTMENTMASTER C
WHERE A.COMPANYCODE=<<COMPANYCODE>>
  AND A.DIVISIONCODE=<<DIVISIONCODE>>
  AND A.COMPANYCODE=B.COMPANYCODE(+)
  AND A.DIVISIONCODE=B.DIVISIONCODE(+)
  AND A.TOKENNO=B.TOKENNO(+)
  AND A.DEPARTMENTCODE=C.DEPARTMENTCODE(+)
  AND A.COMPANYCODE=C.COMPANYCODE
  AND A.DIVISIONCODE=C.DIVISIONCODE
  AND A.DEPARTMENTCODE=C.DEPARTMENTCODE
  AND A.DOCUMENTDATE= TO_DATE(<<DOCUMENTDATE>>,''DD/MM/YYYY'')
  --AND A.FORTNIGHTSTARTDATE = TO_DATE(<<FORTNIGHTSTARTDATE>>,''DD/MM/YYYY'') 
  --AND A.FORTNIGHTENDDATE = TO_DATE(<<FORTNIGHTENDDATE>>,''DD/MM/YYYY'')
  AND A.LEAVEENCASHMENT=<<LEAVEENCASHMENT>>
  AND A.LEAVECODE=''STL''
  AND 1=1
 ORDER BY TO_DATE(DOCUMENTDATE,''DD/MM/YYYY'') DESC,SUBSTR(DOCUMENTNO,10,5) DESC', 'TOKENNO~DOCUMENTNO~DOCUMENTDATE~WORKERNAME~DEPARTMENTCODE~DEPARTMENTNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6936, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'WPS WORKER INFROMATION', NULL, 
    'SELECT TOKENNO,WORKERNAME,WORKERSERIAL
  FROM WORKERVIEW 
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE = <<DIVISIONCODE>>
 ORDER BY TOKENNO', 'TOKENNO~WORKERNAME~WORKERSERIAL~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6504, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'WORKER INFO', NULL, 
    'SELECT DISTINCT WORKERSERIAL,TOKENNO,WORKERNAME FROM WORKERVIEWGRATUITY
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND MODULE=<<MODULE>>
  ORDER BY TOKENNO,WORKERSERIAL', 'TOKENNO~WORKERSERIAL~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6506, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'WORKER INFO', NULL, 
    'SELECT DISTINCT TOKENNO,WORKERNAME FROM WORKERVIEWGRATUITY
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND MODULE=<<MODULE>>
  AND WORKERSERIAL IN 
  ( 
    SELECT DISTINCT WORKERSERIAL FROM GRATUITYSETTLEMENT
    WHERE COMPANYCODE=<<COMPANYCODE>>
      AND DIVISIONCODE=<<DIVISIONCODE>>
      AND MODULE=<<MODULE>>
  )   
  ORDER BY TOKENNO', 'TOKENNO~WORKERNAME~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6931, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'QUARTER LINE INFORMATION', NULL, 
    'SELECT LINENO, LINEDESC  
  FROM QUARTERLINEMASTER 
 WHERE COMPANYCODE=<<COMPANYCODE>> 
   AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY LINENO', 'LINENO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6932, '""', 'COMPANYCODE~DIVISIONCODE~LINENO~PATTERN', 'QUARTER  INFORMATION', NULL, 
    'SELECT DISTINCT QUARTERNO  FROM QUARTERMASTER WHERE COMPANYCODE=<<COMPANYCODE>> AND DIVISIONCODE=<<DIVISIONCODE>>  AND LINENO=<<LINENO>>
ORDER BY QUARTERNO', 'QUARTERNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6933, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'GRADE  INFORMATION', NULL, 
    'SELECT GRADECODE,GRADEDESC FROM WPSGRADEMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> AND DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY GRADECODE', 'GRADECODE~GRADEDESC~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6934, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'QUARTER  INFORMATION', NULL, 
    'SELECT DISTINCT METERNO,QUARTERNO  FROM QUARTERMASTER WHERE COMPANYCODE=<<COMPANYCODE>> AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY METERNO', 'METERNO~QUARTERNO~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6939, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~YEARCODE~PATTERN', 'EMPLOYEE/WORKER INFROMATION', NULL, 
    '  SELECT A.TOKENNO, WORKERNAME,GRATUITYSETTLEMENTNO, A.WORKERSERIAL, A.CATEGORYCODE,     YEARCODE  
    FROM GRATUITYSETTLEMENT A, WPSWORKERMAST B 
    WHERE A.COMPANYCODE=B.COMPANYCODE
    AND A.DIVISIONCODE=B.DIVISIONCODE
    AND A.WORKERSERIAL=B.WORKERSERIAL
    AND A.COMPANYCODE = <<COMPANYCODE>> 
    AND A.divisioncode = <<DIVISIONCODE>> 
    AND A.YEARCODE=<<YEARCODE>> 
    ORDER BY GRATUITYSETTLEMENTNO DESC', 'TOKENNO~WORKERSERIAL~TOKENNO', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6300, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'FINANCIAL YEAR INFORMATION', NULL, 
    'SELECT DISTINCT YEARCODE 
FROM FINANCIALYEAR
ORDER BY YEARCODE', 'YEARCODE~', 'WPS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6505, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'WORKER INFO', NULL, 
    'SELECT DISTINCT TOKENNO,WORKERNAME FROM WORKERVIEWGRATUITY
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND MODULE=<<MODULE>>
  AND WORKERSERIAL IN 
  ( 
    SELECT DISTINCT WORKERSERIAL FROM GRATUITYENTITLEMENTYEAR
    WHERE COMPANYCODE=<<COMPANYCODE>>
      AND DIVISIONCODE=<<DIVISIONCODE>>
      AND MODULE=<<MODULE>>
  )   
  ORDER BY TOKENNO', 'TOKENNO~WORKERNAME~', 'WPS');
COMMIT;
