

SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107', 'X', 'PIS', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, 'Y', 'Y', 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('010701', 'X', 'Masters Information', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070101', 'X', 'Masters', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010101', NULL, 'Unit Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgUnitMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010102', NULL, 'Category Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISCategoryMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010103', NULL, 'Grade Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISGradeMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010104', NULL, 'Department Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISDepartmentMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010105', NULL, 'Designation Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISDesignationMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010106', NULL, 'Loan Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'N', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISLoanMaster.aspx', NULL, 
    NULL, NULL, 'PRCLOANMAST_AFTERSAVE', NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010107', NULL, 'Leave Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISLeaveMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010108', NULL, 'Bank Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISBankMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010109', NULL, 'Doctor Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISDoctorMaster.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010110', NULL, 'Component Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgPISComponentMaster.aspx', NULL, 
    NULL, 'prcPISCompnt_Bf_MainSave', 'prc_PISCOMPNENTMAST_AFTERSAVE', NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010111', NULL, 'Employee Master', 'MASTERS', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Master/pgEmployeeMast_Birla.aspx', NULL, 
    NULL, 'prcPIS_Emp_b4Save', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070102', 'X', 'Mapping', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107010201', NULL, 'Grade Component Mapping', 'TRANSACTIONS', 'GRADE COMP MAP', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISGradecomponentmapping.aspx', NULL, 
    NULL, 'prcPISGradeCompoMapp_b4Save', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('010702', 'X', 'Transactions', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070201', NULL, 'Component Assignment', 'TRANSACTIONS', 'ASSIGNMENT', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISComponentAssignment.aspx', NULL, 
    NULL, 'prcAssignment_Bf_MainSave', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070202', NULL, 'Month Attendance', 'TRANSACTIONS', 'ATTENDANCE', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISMonthAttendanceWithLeave.aspx', NULL, 
    NULL, 'prcAttendance_Bf_MainSave', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070203', NULL, 'Month Adjustment', 'TRANSACTIONS', 'MONTH ADJUSTMENT', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'Y', 'Y', 'N', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISMonthAdjustment.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070204', 'X', 'Leave', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISLeaveApplicationEntry.aspx', NULL, 
    NULL, 'prcLeave_Bf_MainSave', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020401', NULL, 'Leave Entitlement', 'TRANSACTIONS', 'LEAVE ENTITLEMENT', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISLeaveEntitleMent_New.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020402', NULL, 'Leave Application Entry', 'TRANSACTIONS', 'LEAVE ENTRY GRID', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISLeaveApplicationEntryWithGridDet_Common.aspx', NULL, 
    NULL, 'prcLeave_Bf_MainSave', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020403', NULL, 'Leave Application Sanctioned Entry', 'TRANSACTIONS', 'LEAVE SANCTIONED', 
    NULL, NULL, 'N', 'Y', 'Y', 
    'N', 'N', 'N', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISLeaveApplicationEntryWithGridDet_Common.aspx', NULL, 
    NULL, 'prcLeave_Bf_MainSave', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020404', NULL, 'Work Against Offday', 'TRANSACTIONS', 'PIS OFF DAY ADJUSTMENT', 
    'LEAVE ADJUSTMENT AGAINST OFFDAY WORK', NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgOffDayWorking.aspx', NULL, 
    NULL, 'PRCPIS_OFFDAY_ADJUST_B4SAVE', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020405', NULL, 'Out Duty Entry', 'TRANSACTIONS', 'PIS OUT DUTY', 
    NULL, NULL, 'N', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgOutDutyEntry.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070206', 'X', 'Process', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020601', NULL, 'PIS Salary Process', 'TRANSACTIONS', 'SALARY PROCESS', 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISProcess.aspx', NULL, 
    NULL, NULL, 'prcSalary_Bf_MainSave', NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020602', NULL, 'PIS Arrear Process', 'TRANSACTIONS', 'ARREAR PROCESS', 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/PAGES/Transaction/pgPISProcess.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070207', 'X', 'Loan', 'GROUP', NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'WPS/Pages/Transaction/pgWPSLoanTransaction.aspx', NULL, 
    NULL, 'prcWPS_LoanEntry_b4Save', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020701', NULL, 'Loan Entry', 'TRANSACTIONS', 'PIS LOAN TRANSACTION', 
    'PIS', NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'GENERAL/Pages/Common/pgGeneralLoanTransaction.aspx', NULL, 
    NULL, 'prcWPS_LoanEntry_b4Save', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020702', NULL, 'Loan Stop Entry', 'TRANSACTIONS', 'LOAN STOP ENTRY', 
    NULL, NULL, 'Y', 'N', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'GENERAL/Pages/Common/pgLOANSTOPENTRY.aspx', NULL, 
    NULL, 'prcALL_LoanStop_b4Save', NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020703', NULL, 'Loan EMI Change', 'TRANSACTIONS', 'LOAN EMI CHANGE', 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'GENERAL/Pages/Common/pgLOANEMICHANGE.aspx', NULL, 
    NULL, 'prcALL_LoanEMICng_b4Save', NULL, 'Y', NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107020704', NULL, 'Loan Interrest Calculation', 'TRANSACTIONS', 'LOAN INT CALCULATION', 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Transaction/pgLoanInterestCalculation.aspx', NULL, 
    NULL, NULL, NULL, 'Y', NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('010703', 'X', 'Reports', 'GROUP', NULL, 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070301', 'X', 'Master', 'GROUP', NULL, 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030101', NULL, 'Category Information', 'REPORTS', 'PIS CATEGORY', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030102', NULL, 'Grade Information', 'REPORTS', 'PIS GRADE', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030103', NULL, 'Department Information', 'REPORTS', 'PIS DEPARTMENT', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030104', NULL, 'Leave Information', 'REPORTS', 'PIS LEAVE', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030105', NULL, 'Loan Information', 'REPORTS', 'PIS LOAN', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030106', NULL, 'Bank Information', 'REPORTS', 'PIS BANK', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030107', NULL, 'Designation Information', 'REPORTS', 'PIS DESIGNATION', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030108', NULL, 'Doctor Information', 'REPORTS', 'PIS DOCTOR', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030109', NULL, 'Master Assignment', 'REPORTS', 'MASTER ASSIGNMENT', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070302', 'X', 'Leave Related', 'GROUP', NULL, 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030201', NULL, 'Leave Register', 'REPORTS', 'PIS LEAVE REGISTER', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030202', NULL, 'Leave Balance', 'REPORTS', 'PIS LEAVE BALANCE', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030203', NULL, 'Off Day Adjustment Checklist', 'REPORTS', 'DAY OFF ADJUSTMENT CHECKLIST', 
    NULL, NULL, 'N', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'DAY OFF ADJUSTMENT CHECKLIST', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070303', 'X', 'Transaction', 'GROUP', NULL, 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030301', NULL, 'Salary Register', 'REPORTS', 'PIS SALARY REGISTER', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030302', NULL, 'PIS Component Register', 'REPORTS', 'PIS COMPONENT REGISTER', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030303', NULL, 'Pay Slip', 'REPORTS', 'PIS PAY SLIP ED', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030304', NULL, 'ATM Control', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'ATM CONTROL', 'PROC_RPT_ATMCONTROL_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'')', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030305', NULL, 'Bank Loan and Compulsory Savings', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'BANK LOAN AND COMPULSORY SAVINGS', 'PROC_RPT_BANKLOAN_COMPSAV_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030306', NULL, 'EPS Statement', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'EPS STATEMENT BIRLA', 'PROC_RPT_EPSSTATEMENT_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030307', NULL, 'ESI Statement', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'ESI STATEMENT BIRLA', 'PROC_RPT_ESISTATEMENT_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030308', NULL, 'PF and Loan Deduction', 'REPORTS', 'PIS TEXT REPORT BIRLA', 
    'PF AND LOAN DEDUCTION', 'PROC_RPT_PF_LOANDEDN_TEXT(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030309', NULL, 'PTAX Deduction', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'PTAX DEDUCTION TEXT', 'PROC_RPT_PTAXDEDN_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030310', NULL, 'AXIS Bank Payroll', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'AXIS BANK PAYROLL', 'PROC_RPT_AXISBANKPAYROLL_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030311', NULL, 'AXIS Smart Card', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'AXIS SMART CARD', 'PROC_RPT_AXIS_SMARTCARD_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030312', NULL, 'UCO Bank ATM List', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'UCO BANK ATM LIST', 'PROC_RPT_UCO_ATMLIST_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030313', NULL, 'UCO Bank Excel Upload', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'UCO BANK EXCEL UPLOAD', 'PROC_RPT_UCO_BANKUPLOAD_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030314', NULL, 'UCO Bank Non ATM List', 'REPORTS', 'PIS TEXT REPORT BIRLA', 
    'UCO BANK ATM LIST', 'PROC_RPT_UCO_NONATMLIST_TEXT(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030315', NULL, 'Staff EPS Statement Upload', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'STAFF EPS STATEMENT UPLOAD', 'PROC_RPT_STAFF_EPSUPLOAD_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030316', NULL, 'PF Loan Balance Report', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'PF LOAN BALANCE REPORT', 'PROC_RPT_PF_LOANBALANCE_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030318', NULL, 'Other Loan Balance Report', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'OTHER LOAN BALANCE REPORT', 'PROC_RPT_OTHER_LOANBALANCE_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030319', NULL, 'YTD Salary Amount', 'REPORTS', 'YTD SALARY AMOUNT BIRLA', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030320', NULL, 'Income Tax Deduction', 'REPORTS', 'INCOME TAX DEDUCTION BIRLA', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030321', NULL, 'Staff Leave Liability', 'REPORTS', 'STAFF LEAVE LIABILITY', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030322', NULL, 'Retirement List', 'REPORTS', 'RETIREMENT LIST BIRLA', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030323', NULL, 'Superannuation Liability', 'REPORTS', 'SUPERANNUATION LIABILITY BIRLA', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030324', NULL, 'UCO Bank Furnishing Allowance', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'UCO FURNISHING ALLOWANCE', 'PROC_RPT_FURNISHINGALW_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''UCO BANK'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030325', NULL, 'Axis Bank Furnishing Allowance', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'AXIS FURNISHING ALLOWANCE', 'PROC_RPT_FURNISHINGALW_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''AXIS BANK'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030326', NULL, 'Non ATM Furnishing Allowance', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'NON ATM FURNISHING ALLOWANCE', 'PROC_RPT_FURNISHINGALW_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''NON ATM'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030328', NULL, 'Unrealized Reports', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'UNREALIZED COMPONENTS REPORTS', 'PROC_RPT_UNREALIZED_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''NON ATM'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070304', 'X', 'GENERAL LOAN', 'GROUP', NULL, 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030401', NULL, 'Loan Sanction', 'REPORTS', 'LOAN SANCTION', 
    'PIS', NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070305', 'X', 'Check List', 'GROUP', NULL, 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030501', NULL, 'Month Attendance', 'REPORTS', 'MONTH ATTENDANCE', 
    NULL, NULL, 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, 'Y', NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030502', NULL, 'Variable Check List', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'VARIABLE CHECK LIST', 'PROC_RPT_VARIABLECHECKLST_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('0107030503', NULL, 'Staff Loan Check List', 'REPORTS', 'PIS EXCEL REPORT BIRLA', 
    'STAFF LOAN CHECK LIST', 'PROC_RPT_STAFFLNCHECKLST_EXL(''COMPANYCODE'',''DIVISIONCODE'',''YEARCODE'',''txtYEARMONTH'',''btnUnit'',''btnCategory'') ', 'N', 'N', 'N', 
    'Y', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Report/pgReportPISTemplate.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('010704', 'X', 'Utilities', 'GROUP', NULL, 
    NULL, NULL, 'N', 'Y', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'pgUnderConstruction.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070401', NULL, 'Payroll Posting', 'TRANSACTIONS', NULL, 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'PIS/Pages/Utilities/AcPayrollPosting.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE)
 Values
   ('01070402', NULL, 'Electric Reading Data Import', 'TRANSACTIONS', 'ELECTRIC Import Dynamic', 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'N', 'N', 'Y', 'PIS', NULL, 
    '''0002''', '''0002''', NULL, 'GENERAL/Pages/Common/pgImportfromExcel_Electric.aspx', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
COMMIT;
