SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7001, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS CATEGORY INFORMATION', NULL, 
    'SELECT CATEGORYCODE,CATEGORYDESC 
   FROM PISCATEGORYMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY CATEGORYCODE
', 'CATEGORYCODE~CATEGORYDESC~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7002, '""', 'COMPANYCODE~DIVISIONCODE~CATEGORYCODE~PATTERN', 'PIS GRADE INFORMATION', NULL, 
    'SELECT GRADECODE,GRADEDESC FROM PISGRADEMASTER
  WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND CATEGORYCODE=<<CATEGORYCODE>>
    ORDER BY GRADECODE', 'GRADECODE~GRADEDESC~
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7003, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS DEPARTMENT INFORMATION', NULL, 
    'SELECT DEPARTMENTCODE, DEPARTMENTDESC 
   FROM PISDEPARTMENTMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY DEPARTMENTCODE
', 'DEPARTMENTCODE~DEPARTMENTDESC~
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7004, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS DESIGNATION INFORMATION', NULL, 
    'SELECT DESIGNATIONCODE, DESIGNATIONDESC
   FROM PISDESIGNATIONMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY DESIGNATIONCODE
', 'DESIGNATIONCODE~DESIGNATIONDESC~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7028, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'UNIT INFORMATION', NULL, 
    'SELECT DISTINCT UNITCODE,UNITNAME
  FROM PISUNITMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY UNITCODE', 'UNITCODE~UNITNAME~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7005, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS LOAN INFORMATION', NULL, 
    'SELECT LOANCODE, LOANDESC
   FROM LOANMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY LOANCODE
', 'LOANCODE~LOANDESC~

', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7007, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS LEAVE INFORMATION', NULL, 
    'SELECT LEAVECODE, LEAVEDESC
   FROM PISLEAVEMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY LEAVECODE
', 'LEAVECODE~LEAVEDESC~

', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7008, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS BANK INFORMATION', NULL, 
    'SELECT BANKCODE, BANKDESC
   FROM PISBANKMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY BANKCODE
', 'BANKCODE~BANKDESC~



', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7009, '""', 'COMPANYCODE~DIVISIONCODE~BANKCODE~PATTERN', 'MICR NO AND IFSC CODE INFORMATION', NULL, 
    'SELECT MICRNO,IFSCCODE FROM PISBANKMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>> 
AND BANKCODE=<<BANKCODE>>', 'MICRNO~IFSCCODE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7010, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'DOCTOR INFORMATION', NULL, 
    'SELECT DOCTORCODE,DOCTORNAME FROM PISDOCTORMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>> 
AND DIVISIONCODE=<<DIVISIONCODE>> 
ORDER BY DOCTORCODE', 'DOCTORCODE~DOCTORNAME~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7011, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS CATEGORY GRADEWISE INFORMATION', NULL, 
    'SELECT  CATEGORYCODE, CATEGORYDESC 
  FROM PISCATEGORYMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY CATEGORYCODE, CATEGORYDESC
', 'CATEGORYCODE~CATEGORYDESC~

', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7012, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS EMPLOYEE INFORMATION', NULL, 
    'SELECT TOKENNO,EMPLOYEENAME FROM PISEMPLOYEEMASTER
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY TOKENNO,EMPLOYEENAME
', 'TOKENNO~EMPLOYEENAME~
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7013, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS EMPLOYEE LEAVE INFORMATION', NULL, 
    ' SELECT DISTINCT DOCUMENTNO, TOKENNO, LEAVECODE, TO_CHAR(LEAVEAPPLIEDON) LEAVEAPPLIEDON
 FROM PISLEAVEAPPLICATION A
    WHERE A.COMPANYCODE=<<COMPANYCODE>>
    AND A.DIVISIONCODE=<<DIVISIONCODE>>
    AND A.LEAVESANCTIONEDON IS NULL
   ORDER BY DOCUMENTNO
', 'DOCUMENTNO~TOKENNO~LEAVECODE~LEAVEAPPLIEDON~
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7014, '""', 'COMPANYCODE~DIVISIONCODE~DOCUMENTNO~PATTERN', 'PIS EMPLOYEE LEAVE INFORMATION', NULL, 
    'SELECT DISTINCT A.EMPLOYEECODE,B.EMPLOYEENAME
 FROM PISLEAVEAPPLICATION A, PISEMPLOYEEMASTER B
    WHERE A.COMPANYCODE=<<COMPANYCODE>>
     AND A.DIVISIONCODE=<<DIVISIONCODE>>
     AND A.DOCUMENTNO=<<DOCUMENTNO>>
     AND A.COMPANYCODE=B.COMPANYCODE
     AND A.DIVISIONCODE=B.DIVISIONCODE
     AND A.UNITCODE=B.UNITCODE
     AND A.CATEGORYCODE=B.CATEGORYCODE
     AND A.GRADECODE=B.GRADECODE
     AND A.WORKERSERIAL=B.WORKERSERIAL
     AND A.TOKENNO=B.TOKENNO
        ORDER BY EMPLOYEECODE', 'DOCUMENTNO', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7015, '""', 'COMPANYCODE~DIVISIONCODE~EMPLOYEECODE~PATTERN', 'PIS EMPLOYEEWISE LEAVE INFORMATION', NULL, 
    'SELECT DISTINCT A.LEAVECODE,B.LEAVEDESC
 FROM PISLEAVEAPPLICATION A, PISLEAVEMASTER B
    WHERE A.COMPANYCODE=<<COMPANYCODE>>
     AND A.DIVISIONCODE=<<DIVISIONCODE>>
     AND A.TOKENNO=<<EMPLOYEECODE>>
     AND A.COMPANYCODE=B.COMPANYCODE
     AND A.DIVISIONCODE=B.DIVISIONCODE
     AND A.LEAVECODE=B.LEAVECODE
     ORDER BY LEAVECODE', 'LEAVECODE~LEAVEDESC', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7016, '""', 'COMPANYCODE~DIVISIONCODE~EMPLOYEECODE~LEAVECODE~YEARCODE~PATTERN', 'PIS EMPLOYEEWISE LEAVE INFORMATION', NULL, 
    ' SELECT DISTINCT TO_CHAR(A.LEAVEAPPLIEDON,''DD/MM/YYYY'') LEAVEAPPLIEDON
 FROM PISLEAVEAPPLICATION A, PISLEAVEMASTER B
    WHERE A.COMPANYCODE=<<COMPANYCODE>>
     AND A.DIVISIONCODE=<<DIVISIONCODE>>
     AND A.TOKENNO=<<EMPLOYEECODE>>
     AND A.LEAVECODE=<<LEAVECODE>>
     AND A.YEARCODE=<<YEARCODE>>
     AND A.COMPANYCODE=B.COMPANYCODE
     AND A.DIVISIONCODE=B.DIVISIONCODE
     AND A.LEAVECODE=B.LEAVECODE
   ORDER BY TO_DATE(LEAVEAPPLIEDON,''DD/MM/YYYY'') DESC', 'LEAVECODE~LEAVEDESC', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7017, '""', 'COMPANYCODE~DIVISIONCODE~UNITCODE~CATEGORYCODE~GRADECODE~PATTERN', 'PIS EMPLOYEE INFORMATION', NULL, 
    'SELECT TOKENNO EMPLOYEECODE,WORKERSERIAL EMPLOYEEID,EMPLOYEENAME 
   FROM PISEMPLOYEEMASTER
  WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND UNITCODE=<<UNITCODE>>
    AND CATEGORYCODE=<<CATEGORYCODE>>
    AND GRADECODE=<<GRADECODE>>
  ORDER BY TOKENNO,EMPLOYEENAME
', 'EMPLOYEECODE~EMPLOYEEID~EMPLOYEENAME
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7018, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~PATTERN', 'PIS CATEGORY INFORMATION', NULL, 
    'SELECT CATEGORYCODE,CATEGORYDESC FROM PISCATEGORYMASTER
          WHERE COMPANYCODE=<<COMPANYCODE>>
          AND DIVISIONCODE=<<DIVISIONCODE>>
          AND CATEGORYCODE IN (
                SELECT DISTINCT CATEGORYCODE FROM PISLEAVEENTITLEMENT
                  WHERE COMPANYCODE=<<COMPANYCODE>>
                  AND DIVISIONCODE=<<DIVISIONCODE>>
                  AND YEARCODE=<<YEARCODE>>
          )
     ORDER BY CATEGORYCODE
', 'CATEGORYCODE~CATEGORYDESC
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7019, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~CATEGORYCODE~PATTERN', 'PIS GRADE INFORMATION', NULL, 
    'SELECT GRADECODE,GRADEDESC FROM PISGRADEMASTER
        WHERE COMPANYCODE=<<COMPANYCODE>>
          AND DIVISIONCODE=<<DIVISIONCODE>>
          AND CATEGORYCODE=<<CATEGORYCODE>>
          AND GRADECODE IN (
          SELECT DISTINCT GRADECODE FROM PISLEAVEENTITLEMENT
                  WHERE COMPANYCODE=<<COMPANYCODE>>
                  AND DIVISIONCODE=<<DIVISIONCODE>>
                  AND YEARCODE=<<YEARCODE>>
                  AND CATEGORYCODE=<<CATEGORYCODE>>
          ) 
          ORDER BY GRADECODE  
', 'GRADECODE~GRADEDESC
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7020, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~CATEGORYCODE~GRADECODE~PATTERN', 'PIS LEAVE INFORMATION', NULL, 
    'SELECT LEAVECODE,LEAVEDESC FROM PISLEAVEMASTER
         WHERE COMPANYCODE=<<COMPANYCODE>>
          AND DIVISIONCODE=<<DIVISIONCODE>>
          AND LEAVECODE IN (
                SELECT DISTINCT LEAVECODE FROM PISLEAVEENTITLEMENT
                  WHERE COMPANYCODE=<<COMPANYCODE>>
                  AND DIVISIONCODE=<<DIVISIONCODE>>
                  AND YEARCODE=<<YEARCODE>>
                  AND CATEGORYCODE=<<CATEGORYCODE>>
                  AND GRADECODE=<<GRADECODE>>
          )
          ORDER BY LEAVECODE
', 'LEAVECODE~LEAVEDESC
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7021, '""', 'COMPANYCODE~DIVISIONCODE~YEARCODE~CATEGORYCODE~GRADECODE~LEAVECODE~PATTERN', 'PIS EMPLOYEE INFORMATION', NULL, 
    'SELECT EMPLOYEECODE,EMPLOYEENAME FROM PISEMPLOYEEMASTER
      WHERE COMPANYCODE=<<COMPANYCODE>>
        AND DIVISIONCODE=<<DIVISIONCODE>>
        AND EMPLOYEECODE IN (
             SELECT DISTINCT EMPLOYEECODE FROM PISLEAVEENTITLEMENT
                  WHERE COMPANYCODE=<<COMPANYCODE>>
                    AND DIVISIONCODE=<<DIVISIONCODE>>
                    AND YEARCODE=<<YEARCODE>>
                    AND CATEGORYCODE=<<CATEGORYCODE>>
                    AND GRADECODE=<<GRADECODE>>
                    AND LEAVECODE=<<LEAVECODE>>
        )
        ORDER BY EMPLOYEECODE
', 'EMPLOYEECODE~EMPLOYEENAME
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7022, '""', 'COMPANYCODE~DIVISIONCODE~YEARMONTH~PATTERN', 'COMPONENT INFORMATION', NULL, 
    'SELECT COMPONENTCODE, COMPONENTSHORTNAME, COMPONENTTYPE
  FROM PISCOMPONENTMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND YEARMONTH=<<YEARMONTH>>
 ORDER BY COMPONENTCODE', 'COMPONENTCODE~COMPONENTSHORTNAME~COMPONENTTYPE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7023, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'COMPONENT TYPE INFORMATION', NULL, 
    'SELECT SRL, TYPE
  FROM (
        SELECT 1 SRL, ''EARNING'' TYPE FROM DUAL
        UNION
        SELECT 2 SRL, ''DEDUCTION'' TYPE FROM DUAL
        UNION
        SELECT 3 SRL, ''OTHERS'' TYPE FROM DUAL
       )
WHERE 1=1
ORDER BY SRL', 'TYPE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7024, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'LIABILITY INFORMATION', NULL, 
    'SELECT A.ACCODE, A.ACHEAD, A.MAINGROUPCODE, B.GROUPHEAD, A.ACTYPE
FROM ACACLEDGER A, ACACGROUP B    
WHERE A.COMPANYCODE = <<COMPANYCODE>>
  AND A.DIVISIONCODE LIKE  ''%''||<<DIVISIONCODE>>||''%''        
  AND A.ACTYPE = ''LIABILITIES''        
  AND A.COMPANYCODE = B.COMPANYCODE        
  AND A.MAINGROUPCODE = B.GROUPCODE        
ORDER BY A.ACHEAD', 'A.ACCODE~A.ACHEAD~A.MAINGROUPCODE~B.GROUPHEAD~A.ACTYPE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7025, '""', 'COMPANYCODE~DIVISIONCODE~ACTYPE~COMPONENTCODE~ACCODE~PATTERN', 'SUB TYPE INFORMATION', NULL, 
    'SELECT A.ACCODE, A.ACHEAD, A.MAINGROUPCODE, B.GROUPHEAD, A.ACTYPE        
FROM ACACLEDGER A, ACACGROUP B        
WHERE A.COMPANYCODE = <<COMPANYCODE>>       
  AND INSTR(<<ACTYPE>>,A.ACTYPE)>0
  AND A.COMPANYCODE = B.COMPANYCODE            
  AND A.MAINGROUPCODE = B.GROUPCODE            
  AND MAINGROUPCODE  = <<ACCODE>>
ORDER BY A.ACHEAD', 'A.ACCODE~A.ACHEAD~A.MAINGROUPCODE~B.GROUPHEAD~A.ACTYPE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7026, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'COMPONENT GROUP INFORMATION', NULL, 
    'SELECT DISTINCT COMPONENTGROUP, COMPONENTGROUPNAME
  FROM PISCOMPONENTTYPEMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY COMPONENTGROUP', 'COMPONENTGROUP~COMPONENTGROUPNAME~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7027, '""', 'COLUMN_NAME~PATTERN', 'COMPONENT FORMULA INFORMATION', NULL, 
    'SELECT COMPONENT, COLUMN_NAME FROM (
SELECT ''PISMAST.''||COLUMN_NAME COMPONENT, COLUMN_NAME FROM COLS WHERE TABLE_NAME = ''PISMAST'' AND COLUMN_NAME NOT IN (''COMPANYCODE'',''DIVISIONCODE'',<<COLUMN_NAME>>) 
UNION ALL
SELECT ''PISASSIGN.''||COLUMN_NAME COMPONENT, COLUMN_NAME FROM COLS WHERE TABLE_NAME = ''PISASSIGN'' AND COLUMN_NAME NOT IN (''COMPANYCODE'',''DIVISIONCODE'',<<COLUMN_NAME>>) 
UNION ALL
SELECT ''PISATTN.''||COLUMN_NAME COMPONENT, COLUMN_NAME FROM COLS WHERE TABLE_NAME = ''PISATTN''  AND COLUMN_NAME NOT IN (''COMPANYCODE'',''DIVISIONCODE'',<<COLUMN_NAME>>) 
UNION ALL
SELECT ''PISCOMP.''||COLUMN_NAME COMPONENT, COLUMN_NAME FROM COLS WHERE TABLE_NAME = ''PISCOMP'' AND COLUMN_NAME NOT IN (''COMPANYCODE'',''DIVISIONCODE'',<<COLUMN_NAME>>)
UNION ALL
SELECT ''PISPREV.''||COLUMN_NAME COMPONENT, COLUMN_NAME FROM COLS WHERE TABLE_NAME = ''PISPREV'' AND COLUMN_NAME NOT IN (''COMPANYCODE'',''DIVISIONCODE'',<<COLUMN_NAME>>)  
) WHERE 1=1 ORDER BY COLUMN_NAME', 'COLUMN_NAME~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7029, '""', 'COMPANYCODE~DIVISIONCODE~UNITCODE~CATEGORYCODE~GRADECODE~DEPARTMENTCODE~PATTERN', 'PIS EMPLOYEE INFORMATION', NULL, 
    'SELECT TOKENNO EMPLOYEECODE,EMPLOYEENAME, WORKERSERIAL EMPLOYEEID from PISEMPLOYEEMASTER
  WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND UNITCODE=<<UNITCODE>>
    AND CATEGORYCODE=<<CATEGORYCODE>>
    AND GRADECODE=<<GRADECODE>>
    AND DEPARTMENTCODE=NVL(<<DEPARTMENTCODE>>,DEPARTMENTCODE)
  ORDER BY EMPLOYEECODE,EMPLOYEEID,EMPLOYEENAME', 'TOKENNO~EMPLOYEENAME~WORKERSERIAL~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7030, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS BOSS INFORMATION', NULL, 
    'SELECT TOKENNO,EMPLOYEENAME FROM PISEMPLOYEEMASTER
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  AND TOKENNO<><<TOKENNO>>
  ORDER BY TOKENNO,EMPLOYEENAME
', 'TOKENNO~EMPLOYEENAME~
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7031, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'WORKER INFROMATION', NULL, 
    'SELECT TOKENNO,WORKERNAME,WORKERSERIAL
  FROM WORKERVIEW
 WHERE COMPANYCODE = <<COMPANYCODE>> 
   AND DIVISIONCODE =<<DIVISIONCODE>>
   AND MODULE=<<MODULE>>
 ORDER BY TOKENNO', 'TOKENNO~WORKERNAME~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7032, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'LOAN APPLICATION INFROMATION', NULL, 
    'SELECT APPLICATIONNO, TO_CHAR(APPLICATIONDATE,''DD/MM/YYYY'') APPLICATIONDATE, LOANCODE
  FROM LOANDEDUCTIONSTOP
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND MODULE=<<MODULE>>
 ORDER BY APPLICATIONNO DESC', 'APPLICATIONNO~APPLICATIONDATE~LOANCODE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7033, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~LOANCODE~PATTERN', 'WORKER INFROMATION', NULL, 
    'SELECT TOKENNO, WORKERNAME, WORKERSERIAL
  FROM WORKERVIEW
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND MODULE=<<MODULE>>
   AND TOKENNO IN (
                   SELECT DISTINCT TOKENNO
                     FROM LOANTRANSACTION
                    WHERE COMPANYCODE=<<COMPANYCODE>>
                      AND DIVISIONCODE=<<DIVISIONCODE>>
                      AND MODULE=<<MODULE>>
                      AND LOANCODE=<<LOANCODE>>
                  )', 'TOKENNO~WORKERNAME~WORKERSERIAL~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7035, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'LOAN APPLICATION INFROMATION', NULL, 
    'SELECT APPLICATIONNO, TO_CHAR(APPLICATIONDATE,''DD/MM/YYYY'') APPLICATIONDATE, LOANCODE
  FROM LOANEMICHANGE
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND MODULE=<<MODULE>>
 ORDER BY APPLICATIONNO DESC', 'APPLICATIONNO~APPLICATIONDATE~LOANCODE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7036, '""', 'COMPANYCODE~DIVISIONCODE~MODULE~PATTERN', 'LOAN APPLICATION INFROMATION', NULL, 
    'SELECT APPLICATIONNO, TO_CHAR(APPLICATIONDATE,''DD/MM/YYYY'') APPLICATIONDATE, LOANCODE
  FROM PFLOANEMICHANGE
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
   AND MODULE=<<MODULE>>
 ORDER BY APPLICATIONNO DESC', 'APPLICATIONNO~APPLICATIONDATE~LOANCODE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7040, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS EMPLOYEE LEAVE INFORMATION', NULL, 
    ' SELECT DISTINCT DOCUMENTNO, TOKENNO, LEAVECODE, TO_CHAR(LEAVEAPPLIEDON) LEAVEAPPLIEDON
 FROM PISLEAVEAPPLICATION A
    WHERE A.COMPANYCODE=<<COMPANYCODE>>
    AND A.DIVISIONCODE=<<DIVISIONCODE>>
   ORDER BY DOCUMENTNO
', 'DOCUMENTNO~TOKENNO~LEAVECODE~LEAVEAPPLIEDON~
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7501, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS CATEGORY INFORMATION', NULL, 
    'SELECT CATEGORYCODE,CATEGORYDESC 
   FROM PISCATEGORYMASTER 
  WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY CATEGORYCODE
', 'CATEGORYCODE~CATEGORYDESC~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (6100, '""', 'COMPANYCODE~DIVISIONCODE~WORKERSERIAL~PATTERN', 'LOAN INFROMATION', NULL, 
    'SELECT APPLICATIONNO,L.TOKENNO,WORKERNAME EMPLOYEENAME,LOANCODE,TO_CHAR(LOANDATE,''DD/MM/YYYY'') LOANDATE, L.MODULE
FROM LOANTRANSACTION L, VW_WPSPISMASTER /* PISEMPLOYEEMASTER*/  E
WHERE L.COMPANYCODE=E.COMPANYCODE
      AND L.DIVISIONCODE=E.DIVISIONCODE
      AND L.WORKERSERIAL=E.WORKERSERIAL
      AND L.COMPANYCODE=<<COMPANYCODE>>  
      AND L.DIVISIONCODE=<<DIVISIONCODE>>
      AND L.WORKERSERIAL=<<WORKERSERIAL>>
      AND L.LOANCODE = <<LOANCODE>>
ORDER BY L.LOANDATE DESC', 'TOKENNO~EMPLOYEENAME~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7071, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'LOAN INFORMATION', NULL, 
    'SELECT LOANCODE,LOANDESC,DEDUCTIONTYPE FROM LOANMASTER
WHERE COMPANYCODE=<<COMPANYCODE>>  
AND DIVISIONCODE=<<DIVISIONCODE>> 
AND INTERESTTYPE=''R''
AND MODULE=''PIS''
ORDER BY LOANCODE
', 'LOANCODE~LOANDESC~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7506, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS DAY OFF ADJUSTMENT INFORMATION', NULL, 
    ' SELECT DOCUMENTNO, TO_CHAR(DOCUMENTDATE,''DD/MM/YYYY'')DOCUMENTDATE, TOKENNO, TO_CHAR(LEAVEDATE,''DD/MM/YYYY'')LEAVEDATE, TO_CHAR(ADJUSTMENTDATE,''DD/MM/YYYY'')ADJUSTMENTDATE  FROM PISOFFDAYWORKINGADJUSTMENT
WHERE COMPANYCODE=<<COMPANYCODE>>
  AND DIVISIONCODE=<<DIVISIONCODE>>
  ORDER BY DOCUMENTNO DESC,TOKENNO', 'TOKENNO~DOCUMENTNO
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7507, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS EMPLOYEE INFORMATION', NULL, 
    'SELECT A.TOKENNO, EMPLOYEENAME, TO_CHAR(DUTYDATE,''DD/MM/YYYY'')DUTYDATE, TIMEFROM, TIMETO FROM PISOUTSIDEDUTYDETAILS A, PISEMPLOYEEMASTER B
WHERE A.WORKERSERIAL=B.WORKERSERIAL
AND A.COMPANYCODE=<<COMPANYCODE>>
AND A.DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY TOKENNO,EMPLOYEENAME,DUTYDATE DESC 
', 'TOKENNO
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7502, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS INVESTMENT INFORMATION', NULL, 
    'SELECT COLUMNSUBHEADING2 HEADING FROM PISITAXPARAM 
WHERE COMPANYCODE=<<COMPANYCODE>> 
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND COLUMNSOURCE=''PISPAYINVESTMENT'' 
AND COLUMNSUBHEADING2 IS NOT NULL
', 'HEADING', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7041, '""', 'COMPANYCODE~DIVISIONCODE~EMPLOYEECODE~LEAVECODE~PATTERN', 'PIS EMPLOYEE LEAVE INFORMATION', NULL, 
    'SELECT DISTINCT DOCUMENTNO, TOKENNO, LEAVECODE, TO_CHAR(LEAVEAPPLIEDON) LEAVEAPPLIEDON
 FROM PISLEAVEAPPLICATION A
    WHERE A.COMPANYCODE=<<COMPANYCODE>>
    AND A.DIVISIONCODE=<<DIVISIONCODE>>
    AND A.TOKENNO=<<EMPLOYEECODE>>
    AND A.LEAVECODE=<<LEAVECODE>>
   ORDER BY DOCUMENTNO
', 'DOCUMENTNO~TOKENNO~LEAVECODE~LEAVEAPPLIEDON
', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7042, '""', 'COMPANYCODE~DIVISIONCODE~TOKENNO~TRANSACTIONTYPE~PATTERN', 'POLICY INFROMATION', NULL, 
    'SELECT POLICYNO,TO_CHAR(POLICYDATE,''DD/MM/YYYY'') POLICYDATE FROM LICMASTER 
WHERE COMPANYCODE=<<COMPANYCODE>>
    AND DIVISIONCODE=<<DIVISIONCODE>>
    AND MODULE=''PIS''
    AND TRANSACTIONTYPE=<<TRANSACTIONTYPE>>
    AND TOKENNO=<<TOKENNO>>', 'POLICYNO~POLICYDATE~', 'PIS');
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (7508, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'PIS OFF DAY INFORMATION', NULL, 
    'SELECT DOCUMENTNO, TO_CHAR(DOCUMENTDATE,''DD/MM/YYYY'')DOCUMENTDATE,A.TOKENNO,EMPLOYEENAME,TO_CHAR(LEAVEDATE,''DD/MM/YYYY'') LEAVEDATE FROM PISOFFDAYWORKINGADJUSTMENT A, PISEMPLOYEEMASTER B
WHERE A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.WORKERSERIAL=B.WORKERSERIAL
AND A.COMPANYCODE=<<COMPANYCODE>>
AND A.DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY DOCUMENTDATE DESC, DOCUMENTNO DESC ', 'DOCUMENTNO~DOCUMENTDATE~A.TOKENNO~EMPLOYEENAME~', 'PIS');
COMMIT;

