GBL_PISPROCESS~<root>
  <data>
    <COMPANYCODE>0001</COMPANYCODE>
    <DIVISIONCODE>002</DIVISIONCODE>
    <YEARCODE>2020-2021</YEARCODE>
    <UNITCODE>002</UNITCODE>
    <CATEGORYCODE>01</CATEGORYCODE>
    <GRADECODE>01</GRADECODE>
    <WORKERSERIAL>000080</WORKERSERIAL>
    <TOKENNO>0015</TOKENNO>
    <YEARMONTH>202007</YEARMONTH>
    <TRANSACTIONTYPE>ARREAR PROCESS</TRANSACTIONTYPE>
    <ARREARFROM>202004</ARREARFROM>
    <ARREARTO>202006</ARREARTO>
    <OPERATIONMODE>A</OPERATIONMODE>
    <USERNAME>SWT</USERNAME>
  </data>
</root>

COMPANYCODE
DIVISIONCODE
TRANSACTIONTYPE
YEARMONTH
UNITCODE
CATEGORYCODE
GRADECODE
TOKENNO
WORKERSERIAL
ARREARFROM
ARREARTO
OPERATIONMODE
USERNAME
SYSROWID


delete from gbl_pisprocess

select * from gbl_pisprocess


INSERT INTO gbl_pisprocess
SELECT '0001' COMPANYCODE,'002' DIVISIONCODE,'ARREAR PROCESS' TRANSACTIONTYPE,'202007' YEARMONTH, 
'002' UNITCODE,'01' CATEGORYCODE,'01' GRADECODE,'0015' TOKENNO,'000080' WORKERSERIAL, 
'202004' ARREARFROM,'202006' ARREARTO,'A' OPERATIONMODE,'SWT' USERNAME,SYS_GUID() SYSROWID
FROM DUAL


exec  BAGGAGE_WEB.prcArrear_Bf_MainSave()

000080	0015



SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER=''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP='GBL_PISPROCESS'


update SYS_TFMAP SET SYS_TABLENAME_ACTUAL = 'NONE' 
WHERE SYS_TABLENAME_TEMP='GBL_PISPROCESS'

 

SELECT * FROM PISEMPLOYEEMASTER

PRC_PISSALARYPROCESS_DEDN



DELETE FROM PIS_ERROR_LOG

SELECT * FROM PIS_ERROR_LOG


CREATE TABLE WAGESPROCESSTYPE_PHASE_BK AS
SELECT * FROM WAGESPROCESSTYPE_PHASE


EXEC PRC_PIS_SALARY_PROCESS( '0001','002', 'ARREAR','SWT','202004','202007','002','01','01','','000080' )

INSERT INTO WAGESPROCESSTYPE_PHASE

SELECT COMPANYCODE, DIVISIONCODE,'ARREAR' PROCESSTYPE, PROCEDURE_NAME, PHASE, CALCULATIONINDEX, PARAM_1, PARAM_2, PARAM_3 
FROM WAGESPROCESSTYPE_PHASE  
WHERE COMPANYCODE = '0001' 
AND DIVISIONCODE = '002'
--AND PROCESSTYPE = 'SALARY'
AND PROCESSTYPE = 'ARREAR'
ORDER BY PHASE, CALCULATIONINDEX


INSERT INTO WAGESPROCESSTYPE_PHASE
SELECT COMPANYCODE, DIVISIONCODE, 'ARREAR'  PROCESSTYPE, PROCEDURE_NAME, PHASE, CALCULATIONINDEX, PARAM_1, PARAM_2, PARAM_3, PARAM_4, PARAM_5, MODULE 
FROM WAGESPROCESSTYPE_PHASE  
WHERE COMPANYCODE = '0001' 
AND DIVISIONCODE = '002'
AND PROCESSTYPE = 'SALARY'
--AND PROCESSTYPE = 'ARREAR'
ORDER BY PHASE, CALCULATIONINDEX

DELETE FROM WAGESPROCESSTYPE_PHASE  
WHERE COMPANYCODE = '0001' 
AND DIVISIONCODE = '002'
--AND PROCESSTYPE = 'SALARY'
AND PROCESSTYPE = 'ARREAR'


ORDER BY PHASE, CALCULATIONINDEX

                            
PRC_PISSALARYPROCESS_UPDATE

PRC_PIS_SALARY_PROCESS( 'BJ0056','002', 'ARREAR','SWT','202005','202007','002','01','01','','000080' )

PRC_PIS_SALARY_PROCESS( 'BJ0056','002', 'ARREAR','SWT','202006','202007','002','01','01','','000080' )

[Error] Execution (81: 1): ORA-20100: ~RAISE ERROR START~ORA-04063: view "BAGGAGE_WEB.PISCOMP" has errors
ORA-06512: at "BAGGAGE_WEB.PRC_PISSALARYPROCESS_DEDN", line 142
ORA-00942: table or view does not exist~RAISE ERROR END~
ORA-06512: at "BAGGAGE_WEB.PRC_PIS_SALARY_PROCESS", line 40
ORA-06512: at line 1

PISCOMP

SELECT * FROM PISARREARTRANSACTION

SELECT * FROM PISARREARTRANSACTION


CREATE TABLE PISARREARTRANSACTION AS
SELECT * FROM PISPAYTRANSACTION_SWT WHERE 1=2


CREATE GLOBAL TEMPORARY TABLE GTT_PISARREARTRANSACTION AS
SELECT * FROM PISPAYTRANSACTION_SWT WHERE 1=2

DROP TABLE PISARREARTRANSACTION


DROP TABLE GTT_PISARREARTRANSACTION





PRC_PISSALARY_NONARREAR_UPDT





SELECT DOCUMENTNO, LTRIM(MAX(SYS_CONNECT_BY_PATH(TODATE,'~')) KEEP (DENSE_RANK LAST ORDER BY DOCUMENTNO),'~') AS ANNUALSCH 
FROM ( SELECT DOCUMENTNO, TODATE, ROW_NUMBER() OVER (PARTITION BY DOCUMENTNO ORDER BY DOCUMENTNO) AS curr, ROW_NUMBER() OVER (PARTITION BY DOCUMENTNO ORDER BY DOCUMENTNO) -1 AS prev 
FROM 
( 
SELECT DISTINCT D.DOCUMENTNO, TO_CHAR(D.TODATE,'YYYYMM'), TO_CHAR(D.TODATE,'MON-YY') TODATE 
FROM STORESDELIVERYSCHEDULE D 
WHERE D.COMPANYCODE='0001' 
AND D.DIVISIONCODE='002' 
AND D.DOCUMENTTYPE='PURCHASE ORDER DRAFT' 
ORDER BY D.DOCUMENTNO, TO_CHAR(D.TODATE,'YYYYMM') 
) xyz 
) 
GROUP BY DOCUMENTNO CONNECT BY prev = PRIOR curr AND PRIOR DOCUMENTNO = DOCUMENTNO START WITH curr = 1 
ORDER BY DOCUMENTNO 



select SUBSTR (RTRIM (XMLAGG(XMLELEMENT (e,SAUDANO|| ', ')).EXTRACT ('//text()'),','),1,4000)
FROM JWPROFORMAINVOICEVIEW B
WHERE A.PROFORMAINVNO=B.PROFORMAINVNO

SELECT * FROM PISPAYTRANSACTION
WHERE TOKENNO='70156'



