SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0107020602'

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%arrear%')

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''


prcArrear_Bf_MainSave

prcArrear_Bf_MainSave


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLE_SEQUENCIER=''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL=''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP=''




CREATE TABLE PISPAYTRANSACTION_SWT AS
SELECT * FROM 
PISPAYTRANSACTION WHERE 1=2

SELECT * FROM 
PISPAYTRANSACTION_SWT

 CREATE OR REPLACE VIEW PISCOMP 
 AS 
 
 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.TOKENNO, A.YEARMONTH, 
 A.ATTN_SALD, A.ATTN_WRKD, A.ATTN_WPAY, A.ATTN_ADJD, A.ATTN_TOTD, ATTN_CALCF, A.ATTN_LDAY, A.ATTN_OFFD,A.LDAY_PL,A.LDAY_SL /*A.LDAY_PL, A.LDAY_CL, A.LDAY_SL*/ 
 , NVL(A.TOTLOANAMT,0) AS TOTLOANAMT, NVL(A.TOTLOANINT,0) AS TOTLOANINT, NVL(A.ESI_GROSS,0) AS ESI_GROSS, NVL(A.PEN_GROSS,0) AS PEN_GROSS, NVL(A.TOTEARN,0) AS TOTEARN, NVL(A.LOAN_HBLDG,0) AS LOAN_HBLDG, NVL(A.LOAN_EDU,0) AS LOAN_EDU, NVL(A.LOAN_MRG,0) AS LOAN_MRG, NVL(A.ESI_C,0) AS ESI_C, NVL(A.ESI_E,0) AS ESI_E, NVL(A.LINT_MRG,0) AS LINT_MRG, NVL(A.BASIC,0) AS BASIC, NVL(A.GROSSEARN,0) AS GROSSEARN, NVL(A.HRA_RT,0) AS HRA_RT, NVL(A.SARR_ARRD,0) AS SARR_ARRD, NVL(A.BASIC_RT,0) AS BASIC_RT, NVL(A.HRA,0) AS HRA, NVL(A.TOTALDED,0) AS TOTALDED, NVL(A.CANTEEN,0) AS CANTEEN, NVL(A.PF_C,0) AS PF_C, NVL(A.PF_E,0) AS PF_E, NVL(A.PTAX,0) AS PTAX, NVL(A.NETSALARY,0) AS NETSALARY, NVL(A.FPF,0) AS FPF, NVL(A.LCUM_PL,0) AS LCUM_PL, NVL(A.LVBL_PL,0) AS LVBL_PL, NVL(A.LVBL_SL,0) AS LVBL_SL, NVL(A.CONV_ALW,0) AS CONV_ALW, NVL(A.ATN_INCTV,0) AS ATN_INCTV, NVL(A.PUNC_ALW,0) AS PUNC_ALW, NVL(A.WASH_ALW,0) AS WASH_ALW, NVL(A.EDU_ALW,0) AS EDU_ALW, NVL(A.ATN_ALW,0) AS ATN_ALW, NVL(A.SHIFTB_HRS,0) AS SHIFTB_HRS, NVL(A.SHIFTC_HRS,0) AS SHIFTC_HRS, NVL(A.CLEAN_ALW,0) AS CLEAN_ALW, NVL(A.INSP_ALW,0) AS INSP_ALW, NVL(A.CHRG_HAND,0) AS CHRG_HAND, NVL(A.PERF_ALW,0) AS PERF_ALW, NVL(A.SHIFTA_HRS,0) AS SHIFTA_HRS, NVL(A.SHIFT_ALW,0) AS SHIFT_ALW, NVL(A.LGBK_ALW,0) AS LGBK_ALW, NVL(A.MISC_DEDN,0) AS MISC_DEDN, NVL(A.LINT_EDU,0) AS LINT_EDU, NVL(A.LINT_HBLDG,0) AS LINT_HBLDG, NVL(A.SARR_ARRE,0) AS SARR_ARRE, NVL(A.FSTL_EARN,0) AS FSTL_EARN, NVL(A.FSTL_DED,0) AS FSTL_DED, NVL(A.LCUM_CL,0) AS LCUM_CL, NVL(A.LVBL_CL,0) AS LVBL_CL, NVL(A.HRA_PER,0) AS HRA_PER, NVL(A.GR_ESI_OTH,0) AS GR_ESI_OTH, NVL(A.PF_GROSS,0) AS PF_GROSS, NVL(A.LOP,0) AS LOP, NVL(A.SHIFT_B,0) AS SHIFT_B, NVL(A.SHIFT_A,0) AS SHIFT_A, NVL(A.SHIFT_C,0) AS SHIFT_C, NVL(A.GELESI,0) AS GELESI, NVL(A.PTAX_GROSS,0) AS PTAX_GROSS, NVL(A.HRA_GROSS,0) AS HRA_GROSS, NVL(A.SALRATE,0) AS SALRATE, NVL(A.LNBL_HBLDG,0) AS LNBL_HBLDG, NVL(A.LIBL_HBLDG,0) AS LIBL_HBLDG, NVL(A.LNBL_EDU,0) AS LNBL_EDU, NVL(A.LIBL_EDU,0) AS LIBL_EDU, NVL(A.LNBL_MRG,0) AS LNBL_MRG, NVL(A.LIBL_MRG,0) AS LIBL_MRG 
 FROM PISPAYTRANSACTION_SWT A 
 WHERE A.COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND A.YEARMONTH = '202004' 
   AND A.TRANSACTIONTYPE = 'NEW SALARY' 
 ORDER BY A.WORKERSERIAL 



SELECT * FROM PISPAYTRANSACTION


SELECT * FROM PISPAYTRANSACTION_SWT


SELECT * FROM PISARREARTRANSACTION


PRC_PIS_SALARY_PROCESS( '0001','002', 'ARREAR','SWT','202005','202007','002','01','01','','000080' )

COMP=0001,DIV = 002, YEARMONTH = 202005, EFF.YEARMONTH202007,PHASE=3


 SELECT WM_CONCAT('NVL('||COMPONENTCODE||',0) AS '||COMPONENTCODE), WM_CONCAT('A.'||COMPONENTCODE), WM_CONCAT('B.'||COMPONENTCODE)
       -- INTO  lv_Component, lv_UpdtDestnComp, lv_UpdtSourceComp
        FROM PISCOMPONENTMASTER
        WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002'
        AND PHASE = 3
        AND NVL(INCLUDEPAYROLL,'N') = 'Y'
        AND NVL(INCLUDEARREAR,'N') <> 'Y'
        AND YEARMONTH = ( 
                          SELECT MAX(YEARMONTH) YEARMONTH FROM PISCOMPONENTMASTER
                          WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002'
                            AND YEARMONTH <= '202007'
                        )  
       ORDER BY NVL(CALCULATIONINDEX,0);