      


DROP TABLE GBL_LOANBLNC CASCADE CONSTRAINTS;

CREATE TABLE GBL_LOANBLNC
(
  COMPANYCODE          VARCHAR2(10 BYTE),
  DIVISIONCODE         VARCHAR2(10 BYTE),
  WORKERSERIAL         VARCHAR2(10 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  MODULE               VARCHAR2(10 BYTE),
  LOANCODE             VARCHAR2(10 BYTE),
  LOANDATE             DATE,
  LOAN_BAL             NUMBER(18,2),
  LOAN_INT_BAL         NUMBER(18,2),
  LN_CAP_DEDUCT        NUMBER(18,2),
  LN_INT_DEDUCT        NUMBER(18,2),
  CAP_EMI              NUMBER(18,2),
  INT_EMI              NUMBER(18,2),
  TOT_EMI              NUMBER(18,2),
  CAP_STOP             VARCHAR2(1 BYTE),
  INT_STOP             VARCHAR2(1 BYTE),
  CAP_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  INT_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE)
)
     

DROP TABLE GTT_RPTLOANREGISTER CASCADE CONSTRAINTS;

CREATE TABLE GTT_RPTLOANREGISTER
(
  COMPANYCODE         VARCHAR2(10 BYTE),
  DIVISIONCODE        VARCHAR2(10 BYTE),
  COMPANYNAME         VARCHAR2(200 BYTE),
  DIVISIONNAME        VARCHAR2(200 BYTE),
  FORTNIGHTSTARTDATE  DATE,
  FORTNIGHTENDDATE    DATE,
  SHIFTCODE           VARCHAR2(3 BYTE),
  WORKERSERIAL        VARCHAR2(10 BYTE),
  TOKENNO             VARCHAR2(10 BYTE),
  WORKERNAME          VARCHAR2(200 BYTE),
  EXTYPEPARAM         VARCHAR2(4000 BYTE),
  DEPARTMENTCODE      VARCHAR2(20 BYTE),
  EMPLOYEESTATUS      VARCHAR2(20 BYTE),
  LOANDATE            DATE,
  LOANAMOUNT          NUMBER(15,5),
  YEARMONTH           VARCHAR2(10 BYTE),
  LOANCODE            VARCHAR2(50 BYTE),
  MODULE              VARCHAR2(20 BYTE),
  LOAN_BAL            NUMBER(15,5),
  LOAN_INT_BAL        NUMBER(15,5),
  REPORTNAME          VARCHAR2(50 BYTE),
  GENERATEON          VARCHAR2(50 BYTE),
  EX1                 NUMBER,
  EX2                 NUMBER,
  EX3                 NUMBER,
  EX4                 NUMBER,
  EX9                 NUMBER,
  EX10                NUMBER,
  EX11                NUMBER,
  EX12                NUMBER,
  EX5                 VARCHAR2(100 BYTE),
  EX6                 VARCHAR2(100 BYTE),
  EX7                 VARCHAR2(100 BYTE),
  EX8                 VARCHAR2(100 BYTE),
  EX13                VARCHAR2(100 BYTE),
  EX14                VARCHAR2(100 BYTE),
  EX15                VARCHAR2(1000 BYTE),
  EX16                VARCHAR2(2000 BYTE)
)
           

DROP TABLE LOANDEDUCTIONTYPE CASCADE CONSTRAINTS;

CREATE TABLE LOANDEDUCTIONTYPE
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  DEDUCTIONTYPE  VARCHAR2(50 BYTE),
  SRLNO          NUMBER(2)
)
 


DROP TABLE PFLOANDEDUCTIONTYPE CASCADE CONSTRAINTS;

CREATE TABLE PFLOANDEDUCTIONTYPE
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  DEDUCTIONTYPE  VARCHAR2(50 BYTE),
  SRLNO          NUMBER(2)
)
 


DROP TABLE PFLOANDURATIONSALB CASCADE CONSTRAINTS;

CREATE TABLE PFLOANDURATIONSALB
(
  COMPANYCODE                VARCHAR2(10 BYTE),
  DIVISIONCODE               VARCHAR2(10 BYTE),
  NOOFINSTALLMENTFROM        NUMBER(6,2),
  NOOFINSTALLMENTTO          NUMBER(6,2),
  APPLICABLEYEARFORINTEREST  NUMBER(6,2),
  MODULE                     VARCHAR2(10 BYTE)  DEFAULT 'WPS'
)
 

DROP TABLE PFLOAN_EMI_DEDN_SLAB CASCADE CONSTRAINTS;

CREATE TABLE PFLOAN_EMI_DEDN_SLAB
(
  COMPANYCODE     VARCHAR2(10 BYTE),
  DIVISIONCODE    VARCHAR2(10 BYTE),
  WITHEFFECTFROM  DATE,
  SLAB_HRS_FROM   NUMBER(11,2),
  SLAB_HRS_TO     NUMBER(11,2),
  NOOF_EMI        NUMBER(11,2),
  SYSROWID        VARCHAR2(50 BYTE),
  USERNAME        VARCHAR2(100 BYTE),
  LASTMODIFIED    DATE                          DEFAULT SYSDATE
)
 


DROP TABLE LOANTRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE LOANTRANSACTION
(
  COMPANYCODE             VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  MODULE                  VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  CATEGORYCODE            VARCHAR2(10 BYTE),
  GRADECODE               VARCHAR2(10 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  TOKENNO                 VARCHAR2(10 BYTE),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANTYPE                VARCHAR2(20 BYTE),
  LOANCF                  VARCHAR2(1 BYTE),
  AMOUNT                  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  NOOFINSTALLMENTS        NUMBER(18,6),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  ACTUALLOANDATE          DATE,
  COMMITEDRECOVERYPERIOD  NUMBER(18,6),
  LOANCLAIMAMOUNT         NUMBER(18,2),
  SANCTIONEDAMOUNT        NUMBER(18,2),
  INTERESTDEDNMONTHLY     VARCHAR2(3 BYTE),
  PAYABLEAMOUNT           NUMBER(15,2),
  APPLICATIONNO           VARCHAR2(50 BYTE),
  AMOUNTINHAND            NUMBER(15,2),
  INTERESTAMOUNT          NUMBER(15,2),
  CAPITALINSTALLMENTAMT   NUMBER(15,2),
  INTERESTINSTALLMENTAMT  NUMBER(15,2),
  TOTALEMIAMOUNT          NUMBER(18,2),
  LOANAMOUNTADJUSTED      NUMBER(18,2),
  LOANINTAMOUNTADJUSTED   NUMBER(18,2),
  AGAINSTLOANDATE         DATE,
  AGAINSTLOANCODE         VARCHAR2(10 BYTE),
  ADJUSTMENTDATE          DATE,
  REMARKS                 VARCHAR2(100 BYTE),
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  DEDUCTIONSTARTDATE      DATE,
  SYSROWID                VARCHAR2(50 BYTE),
  USERNAME                VARCHAR2(100 BYTE),
  LASTMODIFIED            DATE                  DEFAULT SYSDATE,
  REPAYCAPITAL            NUMBER(11,2),
  REPAYINTEREST           NUMBER(11,2),
  OLD_WORKERSERIAL        VARCHAR2(10 BYTE),
  LOANSTOP                CHAR(1 BYTE)          DEFAULT 'N',
  CURR_CAP_EMI            NUMBER(11,2)          DEFAULT 0,
  CURR_INT_EMI            NUMBER(11,2)          DEFAULT 0,
  PREV_LOAN_CAP_EMI       NUMBER(11,2)          DEFAULT 0,
  PREV_LOAN_INT_EMI       NUMBER(11,2)          DEFAULT 0
)
 

DROP TABLE PFLOANEMICHANGE CASCADE CONSTRAINTS;

CREATE TABLE PFLOANEMICHANGE
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  MODULE            VARCHAR2(10 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(50 BYTE),
  PFNO              VARCHAR2(20 BYTE),
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  WITHEFFECTFROM    DATE,
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  OLD_EMI_CAPITAL   NUMBER(18),
  OLD_EMI_INTEREST  NUMBER(18),
  NEW_EMI_CAPITAL   NUMBER(18),
  NEW_EMI_INTEREST  NUMBER(18),
  LASTMODIFIED      DATE                        DEFAULT SYSDATE,
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  OLD_EMI_TOTAL     NUMBER(18),
  NEW_EMI_TOTAL     NUMBER(18),
  REMARKS           VARCHAR2(50 BYTE)
)
 

DROP TABLE PFLOANDEDUCTIONSTOP CASCADE CONSTRAINTS;

CREATE TABLE PFLOANDEDUCTIONSTOP
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  FULLMILL          VARCHAR2(1 BYTE),
  PFNO              VARCHAR2(50 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  LOANSTOPFROMDATE  DATE,
  LOANSTOPTODATE    DATE,
  LOANSTARTFROM     DATE,
  MODULE            VARCHAR2(10 BYTE),
  REMARKS           VARCHAR2(50 BYTE),
  CAPITAL           VARCHAR2(1 BYTE),
  INTEREST          VARCHAR2(1 BYTE),
  LASTMODIFIED      DATE                        DEFAULT SYSDATE,
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  SRL               NUMBER(5),
  SLNO              NUMBER(4)
)
 

DROP TABLE LOANMASTER CASCADE CONSTRAINTS;

CREATE TABLE LOANMASTER
(
  COMPANYCODE            VARCHAR2(10 BYTE),
  DIVISIONCODE           VARCHAR2(10 BYTE),
  MODULE                 VARCHAR2(10 BYTE),
  LOANCODE               VARCHAR2(5 BYTE),
  LOANDESC               VARCHAR2(100 BYTE),
  LOANNAME               VARCHAR2(100 BYTE),
  LOANCF                 VARCHAR2(1 BYTE)       DEFAULT 'F',
  LOANINDEX              NUMBER(3),
  REFUNDTYPE             VARCHAR2(25 BYTE),
  REMARKS                VARCHAR2(50 BYTE),
  WITHEFFECTFROM         DATE,
  REGULARDEDUCTION       VARCHAR2(1 BYTE)       DEFAULT 'Y',
  LOANTYPE               VARCHAR2(20 BYTE),
  MAXIMUMLOANAMOUNT      NUMBER(15,2),
  LOANGROUP              VARCHAR2(20 BYTE),
  INTERESTPERCENTAGE     NUMBER(5,2),
  INTERESTTYPE           VARCHAR2(1 BYTE)       DEFAULT 'F',
  PRVLOANRECOVERPERCENT  NUMBER(6,2),
  DEDUCTIONTYPE          VARCHAR2(50 BYTE),
  SYSROWID               VARCHAR2(50 BYTE),
  USERNAME               VARCHAR2(100 BYTE),
  LASTMODIFIED           DATE                   DEFAULT SYSDATE,
  CAP_EMI_DEDUCT_TYPE    VARCHAR2(20 BYTE),
  INT_EMI_DEDUCT_TYPE    VARCHAR2(20 BYTE)
)
 


DROP TABLE GBL_LOANMASTER CASCADE CONSTRAINTS;

CREATE TABLE GBL_LOANMASTER
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  LOANCODE       VARCHAR2(10 BYTE),
  LOANDESC       VARCHAR2(500 BYTE),
  LOANCF         CHAR(1 BYTE),
  REFUNDTYPE     VARCHAR2(25 BYTE),
  MODULE         VARCHAR2(25 BYTE),
  OPERATIONMODE  VARCHAR2(1 BYTE),
  USERNAME       VARCHAR2(100 BYTE),
  SYSROWID       VARCHAR2(100 BYTE),
  DEDUCTIONTYPE  VARCHAR2(50 BYTE)
) 

DROP TABLE LOANBREAKUP CASCADE CONSTRAINTS;

CREATE TABLE LOANBREAKUP
(
  COMPANYCODE           VARCHAR2(10 BYTE),
  DIVISIONCODE          VARCHAR2(10 BYTE),
  MODULE                VARCHAR2(10 BYTE),
  YEARCODE              VARCHAR2(10 BYTE),
  YEARMONTH             VARCHAR2(10 BYTE),
  CATEGORYCODE          VARCHAR2(10 BYTE),
  GRADECODE             VARCHAR2(10 BYTE),
  WORKERSERIAL          VARCHAR2(10 BYTE),
  TOKENNO               VARCHAR2(50 BYTE),
  LOANCODE              VARCHAR2(10 BYTE),
  LOANDATE              DATE,
  EFFECTYEARMONTH       VARCHAR2(10 BYTE),
  INTERESTPERCENTAGE    NUMBER(5,2),
  AMOUNT                NUMBER(15,2),
  REPAYAMOUNT           NUMBER(15,2),
  REPAYCAPITAL          NUMBER(15,2),
  REPAYINTEREST         NUMBER(15,2),
  TRANSACTIONTYPE       VARCHAR2(10 BYTE),
  EFFECTFORTNIGHT       DATE,
  PAIDON                DATE,
  DEDUCTEDAMT           NUMBER(18,2),
  ADJUSTMENTTAG         VARCHAR2(20 BYTE),
  SYSROWID              VARCHAR2(50 BYTE),
  USERNAME              VARCHAR2(100 BYTE),
  LASTMODIFIED          DATE,
  REMARKS               VARCHAR2(100 BYTE),
  ISPAID                VARCHAR2(4 BYTE),
  EMPLOYEECOMPANYCODE   VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE  VARCHAR2(10 BYTE),
  DEDUCTFROM            VARCHAR2(50 BYTE)       DEFAULT 'SALARY'
)
 


DROP TABLE LOANINTEREST CASCADE CONSTRAINTS;

CREATE TABLE LOANINTEREST
(
  COMPANYCODE           VARCHAR2(10 BYTE)       NOT NULL,
  DIVISIONCODE          VARCHAR2(10 BYTE)       NOT NULL,
  YEARCODE              VARCHAR2(10 BYTE),
  YEARMONTH             VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE    DATE,
  FORTNIGHTENDDATE      DATE,
  TOKENNO               VARCHAR2(10 BYTE),
  WORKERSERIAL          VARCHAR2(10 BYTE),
  LOANCODE              VARCHAR2(10 BYTE),
  LOANDATE              DATE,
  LOANAMOUNT            NUMBER(15,2),
  INTERESTAPPLICABLEON  NUMBER(15,2),
  INTERESTPERCENTAGE    NUMBER(5,2),
  INTERESTAMOUNT        NUMBER(18,2),
  MODULE                VARCHAR2(10 BYTE),
  TRANSACTIONTYPE       VARCHAR2(50 BYTE),
  REMARKS               VARCHAR2(50 BYTE),
  USERNAME              VARCHAR2(100 BYTE)      NOT NULL,
  SYSROWID              VARCHAR2(50 BYTE)       NOT NULL,
  LASTMODIFIED          DATE                    DEFAULT SYSDATE
)     

DROP TABLE PFMAXLOANDATE CASCADE CONSTRAINTS;

CREATE TABLE PFMAXLOANDATE
(
  WORKERSERIAL  VARCHAR2(10 BYTE),
  PFNO          VARCHAR2(10 BYTE),
  LOANCODE      VARCHAR2(10 BYTE),
  LOANDATE      DATE
)
   
DROP TABLE SYS_SWT_PF_LOAN_SANCTION_PARAM CASCADE CONSTRAINTS;

CREATE TABLE SYS_SWT_PF_LOAN_SANCTION_PARAM
(
  COMPANYCODE           VARCHAR2(10 BYTE),
  DIVISIONCODE          VARCHAR2(10 BYTE),
  LOANCODE              VARCHAR2(10 BYTE),
  PARAM_NAME            VARCHAR2(100 BYTE),
  PARAM_DESC            VARCHAR2(100 BYTE),
  APPLICABLE_COMPONENT  VARCHAR2(10 BYTE),
  PROC_NAME             VARCHAR2(200 BYTE),
  HELP_QRY              VARCHAR2(4000 BYTE),
  PIORITY_INDEX         NUMBER(3)
)
 

DROP TABLE LOANSANCTION_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE LOANSANCTION_DETAILS
(
  COMPANYCODE           VARCHAR2(10 BYTE),
  DIVISIONCODE          VARCHAR2(10 BYTE),
  YEARCODE              VARCHAR2(20 BYTE),
  PFNO                  VARCHAR2(10 BYTE),
  TOKENNO               VARCHAR2(10 BYTE),
  WORKERSERIAL          VARCHAR2(10 BYTE),
  LOANDATE              DATE,
  LOANCODE              VARCHAR2(10 BYTE),
  PARAM_NAME            VARCHAR2(100 BYTE),
  PF_E                  NUMBER(18,2),
  PF_C                  NUMBER(18,2),
  VPF                   NUMBER(18,2),
  OTHER                 NUMBER(18,2),
  EMPLOYEECOMPANYCODE   VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE  VARCHAR2(10 BYTE)
) 

DROP TABLE LOANDEDUCTIONSTOP CASCADE CONSTRAINTS;

CREATE TABLE LOANDEDUCTIONSTOP
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  FULLMILL          VARCHAR2(1 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  LOANSTOPFROMDATE  DATE,
  LOANSTOPTODATE    DATE,
  LOANSTARTFROM     DATE,
  MODULE            VARCHAR2(10 BYTE),
  REMARKS           VARCHAR2(50 BYTE),
  CAPITAL           VARCHAR2(1 BYTE),
  INTEREST          VARCHAR2(1 BYTE),
  LASTMODIFIED      DATE                        DEFAULT SYSDATE,
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  SLNO              NUMBER(5)
)
 

DROP TABLE LOANEMICHANGE CASCADE CONSTRAINTS;

CREATE TABLE LOANEMICHANGE
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  MODULE            VARCHAR2(10 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(50 BYTE),
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  WITHEFFECTFROM    DATE,
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  OLD_EMI_CAPITAL   NUMBER(18),
  OLD_EMI_INTEREST  NUMBER(18),
  NEW_EMI_CAPITAL   NUMBER(18),
  NEW_EMI_INTEREST  NUMBER(18),
  LASTMODIFIED      DATE                        DEFAULT SYSDATE,
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  OLD_EMI_TOTAL     NUMBER(18),
  NEW_EMI_TOTAL     NUMBER(18),
  REMARKS           VARCHAR2(50 BYTE)
)
 

DROP TABLE PFLOANTRANSACTION_TEMP CASCADE CONSTRAINTS;

CREATE TABLE PFLOANTRANSACTION_TEMP
(
  COMPANYCODE                VARCHAR2(10 BYTE)  NOT NULL,
  DIVISIONCODE               VARCHAR2(10 BYTE),
  EMPLOYEECOMPANYCODE        VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE       VARCHAR2(10 BYTE),
  YEARCODE                   VARCHAR2(10 BYTE),
  YEARMONTH                  VARCHAR2(10 BYTE),
  CATEGORYCODE               VARCHAR2(10 BYTE),
  GRADECODE                  VARCHAR2(10 BYTE),
  PFNO                       VARCHAR2(10 BYTE)  NOT NULL,
  WORKERSERIAL               VARCHAR2(10 BYTE),
  TOKENNO                    VARCHAR2(10 BYTE),
  LOANCODE                   VARCHAR2(10 BYTE),
  LOANDATE                   DATE,
  LOANTYPE                   VARCHAR2(20 BYTE),
  AMOUNT                     NUMBER(15,2),
  INTERESTPERCENTAGE         NUMBER(5,2),
  NOOFINSTALLMENTS           NUMBER(4),
  ACTUALLOANAMOUNT           NUMBER(15,2),
  ACTUALLOANDATE             DATE,
  COMMITEDRECOVERYPERIOD     NUMBER(4),
  LOANCLAIMAMOUNT            NUMBER(15,2),
  INTERESTDEDNMONTHLY        NUMBER(15,2),
  LOANAMOUNTADJUSTED         NUMBER(15,2),
  LOANINTAMOUNTADJUSTED      NUMBER(15,2),
  AGAINSTLOANDATE            DATE,
  AGAINSTLOANCODE            VARCHAR2(10 BYTE),
  PAYABLEAMOUNT              NUMBER,
  APPLICATIONNO              VARCHAR2(50 BYTE),
  AMOUNTINHAND               NUMBER(15,2),
  INTERESTAMOUNT             NUMBER(15,2),
  CAPITALINSTALLMENTAMT      NUMBER(15,2),
  INTERESTINSTALLMENTAMT     NUMBER(15,2),
  REPAYCAPITAL               NUMBER(15,2),
  REPAYINTEREST              NUMBER(15,2),
  ADJUSTMENTDATE             DATE,
  REMARKS                    VARCHAR2(100 BYTE),
  DEPARTMENTCODE             VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE         DATE,
  LOANNL                     NUMBER(15,2),
  NEXTLOAN                   NUMBER(15,2),
  ACTUALINTERESTAMOUNT       NUMBER(15,2),
  NEWINTERESTAMOUNT          NUMBER(15,2),
  DEDUCTIONSTARTDATE         DATE,
  INTERESTBALANCEAMOUNT      NUMBER(15,2),
  CAPITALBALANCEAMOUNT       NUMBER(15,2),
  CAPITALINSTALLMENTAMOUNT   NUMBER(15,2),
  INTERESTINSTALLMENTAMOUNT  NUMBER(15,2),
  ADJUSTEDLOANDATE           DATE,
  TOTALEMIAMOUNT             NUMBER(15,2),
  PF_E                       NUMBER(15,2),
  PF_C                       NUMBER(15,2),
  VPF                        NUMBER(15,2),
  MINBALANCE                 NUMBER(15,2),
  ACTUALBALANCE              NUMBER(15,2),
  MODULE                     VARCHAR2(10 BYTE)  NOT NULL,
  PFGROSS                    NUMBER(15,2),
  VOUCHERNO                  VARCHAR2(50 BYTE),
  VOUCHERDATE                DATE,
  SYSTEMVOUCHERNO            VARCHAR2(100 BYTE),
  SYSTEMVOUCHERDATE          DATE,
  CHEQUENO                   VARCHAR2(50 BYTE),
  CHEQUEDATE                 DATE,
  ELIGIBLE                   CHAR(1 BYTE),
  LASTMODIFIED               DATE,
  USERNAME                   VARCHAR2(100 BYTE),
  SYSROWID                   VARCHAR2(50 BYTE)  NOT NULL,
  LOANCF                     VARCHAR2(1 BYTE),
  SANCTIONEDAMOUNT           NUMBER(18,2)
)
    

DROP TABLE PFLOANAPPLICATION CASCADE CONSTRAINTS;

CREATE TABLE PFLOANAPPLICATION
(
  COMPANYCODE                VARCHAR2(10 BYTE)  NOT NULL,
  DIVISIONCODE               VARCHAR2(10 BYTE),
  EMPLOYEECOMPANYCODE        VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE       VARCHAR2(10 BYTE),
  YEARCODE                   VARCHAR2(10 BYTE),
  YEARMONTH                  VARCHAR2(10 BYTE),
  CATEGORYCODE               VARCHAR2(10 BYTE),
  GRADECODE                  VARCHAR2(10 BYTE),
  PFNO                       VARCHAR2(10 BYTE)  NOT NULL,
  WORKERSERIAL               VARCHAR2(10 BYTE),
  TOKENNO                    VARCHAR2(10 BYTE),
  LOANCODE                   VARCHAR2(10 BYTE),
  LOANDATE                   DATE,
  LOANTYPE                   VARCHAR2(20 BYTE),
  AMOUNT                     NUMBER(15,2),
  INTERESTPERCENTAGE         NUMBER(5,2),
  NOOFINSTALLMENTS           NUMBER(4),
  AGAINSTCOMPONENT           VARCHAR2(10 BYTE),
  OPENINGBALANCE             NUMBER(15,2),
  RATIOPERCENT               NUMBER(5,2),
  COMPONENTAMOUNT            NUMBER(15,2),
  CLOSINGBALANCE             NUMBER(15,2),
  ACTUALLOANAMOUNT           NUMBER(15,2),
  ACTUALLOANDATE             DATE,
  COMMITEDRECOVERYPERIOD     NUMBER(4),
  LOANCLAIMAMOUNT            NUMBER(15,2),
  INTERESTDEDNMONTHLY        NUMBER(15,2),
  LOANAMOUNTADJUSTED         NUMBER(15,2),
  LOANINTAMOUNTADJUSTED      NUMBER(15,2),
  AGAINSTLOANDATE            DATE,
  AGAINSTLOANCODE            VARCHAR2(10 BYTE),
  PAYABLEAMOUNT              NUMBER(15,2),
  APPLICATIONNO              VARCHAR2(50 BYTE),
  AMOUNTINHAND               NUMBER(15,2),
  INTERESTAMOUNT             NUMBER(15,2),
  CAPITALINSTALLMENTAMT      NUMBER(15,2),
  INTERESTINSTALLMENTAMT     NUMBER(15,2),
  REPAYCAPITAL               NUMBER(15,2),
  REPAYINTEREST              NUMBER(15,2),
  ADJUSTMENTDATE             DATE,
  REMARKS                    VARCHAR2(100 BYTE),
  DEPARTMENTCODE             VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE         DATE,
  LOANNL                     NUMBER(15,2),
  NEXTLOAN                   NUMBER(15,2),
  ACTUALINTERESTAMOUNT       NUMBER(15,2),
  NEWINTERESTAMOUNT          NUMBER(15,2),
  DEDUCTIONSTARTDATE         DATE,
  INTERESTBALANCEAMOUNT      NUMBER(15,2),
  CAPITALBALANCEAMOUNT       NUMBER(15,2),
  CAPITALINSTALLMENTAMOUNT   NUMBER(15,2),
  INTERESTINSTALLMENTAMOUNT  NUMBER(15,2),
  ADJUSTEDLOANDATE           DATE,
  TOTALEMIAMOUNT             NUMBER(15,2),
  PF_E                       NUMBER(15,2),
  PF_C                       NUMBER(15,2),
  VPF                        NUMBER(15,2),
  MINBALANCE                 NUMBER(15,2),
  ACTUALBALANCE              NUMBER(15,2),
  MODULE                     VARCHAR2(10 BYTE)  NOT NULL,
  PFGROSS                    NUMBER(15,2),
  VOUCHERNO                  VARCHAR2(50 BYTE),
  VOUCHERDATE                DATE,
  SYSTEMVOUCHERNO            VARCHAR2(100 BYTE),
  SYSTEMVOUCHERDATE          DATE,
  CHEQUENO                   VARCHAR2(50 BYTE),
  CHEQUEDATE                 DATE,
  ELIGIBLE                   CHAR(1 BYTE),
  LASTMODIFIED               DATE,
  USERNAME                   VARCHAR2(100 BYTE),
  SYSROWID                   VARCHAR2(50 BYTE)  NOT NULL,
  LOANCF                     VARCHAR2(1 BYTE),
  SANCTIONEDAMOUNT           NUMBER(18,2),
  PREV_LOAN_INT_EMI          NUMBER(11,2)       DEFAULT 0,
  CURR_CAP_EMI               NUMBER(11,2)       DEFAULT 0,
  CURR_INT_EMI               NUMBER(11,2)       DEFAULT 0,
  PREV_LOAN_CAP_EMI          NUMBER(11,2)       DEFAULT 0
)
 

ALTER TABLE PFLOANTRANSACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE PFLOANTRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE PFLOANTRANSACTION
(
  COMPANYCODE                VARCHAR2(10 BYTE)  NOT NULL,
  DIVISIONCODE               VARCHAR2(10 BYTE),
  EMPLOYEECOMPANYCODE        VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE       VARCHAR2(10 BYTE),
  YEARCODE                   VARCHAR2(10 BYTE),
  YEARMONTH                  VARCHAR2(10 BYTE),
  CATEGORYCODE               VARCHAR2(10 BYTE),
  GRADECODE                  VARCHAR2(10 BYTE),
  PFNO                       VARCHAR2(10 BYTE)  NOT NULL,
  WORKERSERIAL               VARCHAR2(10 BYTE),
  TOKENNO                    VARCHAR2(10 BYTE),
  LOANCODE                   VARCHAR2(10 BYTE),
  LOANDATE                   DATE,
  LOANTYPE                   VARCHAR2(20 BYTE),
  AMOUNT                     NUMBER(15,2),
  INTERESTPERCENTAGE         NUMBER(5,2),
  NOOFINSTALLMENTS           NUMBER(4),
  AGAINSTCOMPONENT           VARCHAR2(10 BYTE),
  OPENINGBALANCE             NUMBER(15,2),
  RATIOPERCENT               NUMBER(5,2),
  COMPONENTAMOUNT            NUMBER(15,2),
  CLOSINGBALANCE             NUMBER(15,2),
  ACTUALLOANAMOUNT           NUMBER(15,2),
  ACTUALLOANDATE             DATE,
  COMMITEDRECOVERYPERIOD     NUMBER(4),
  LOANCLAIMAMOUNT            NUMBER(15,2),
  INTERESTDEDNMONTHLY        VARCHAR2(10 BYTE),
  LOANAMOUNTADJUSTED         NUMBER(15,2),
  LOANINTAMOUNTADJUSTED      NUMBER(15,2),
  AGAINSTLOANDATE            DATE,
  AGAINSTLOANCODE            VARCHAR2(10 BYTE),
  PAYABLEAMOUNT              NUMBER(15,2),
  APPLICATIONNO              VARCHAR2(50 BYTE),
  AMOUNTINHAND               NUMBER(15,2),
  INTERESTAMOUNT             NUMBER(15,2),
  CAPITALINSTALLMENTAMT      NUMBER(15,2),
  INTERESTINSTALLMENTAMT     NUMBER(15,2),
  REPAYCAPITAL               NUMBER(15,2),
  REPAYINTEREST              NUMBER(15,2),
  ADJUSTMENTDATE             DATE,
  REMARKS                    VARCHAR2(100 BYTE),
  DEPARTMENTCODE             VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE         DATE,
  LOANNL                     NUMBER(15,2),
  NEXTLOAN                   NUMBER(15,2),
  ACTUALINTERESTAMOUNT       NUMBER(15,2),
  NEWINTERESTAMOUNT          NUMBER(15,2),
  DEDUCTIONSTARTDATE         DATE,
  INTERESTBALANCEAMOUNT      NUMBER(15,2),
  CAPITALBALANCEAMOUNT       NUMBER(15,2),
  CAPITALINSTALLMENTAMOUNT   NUMBER(15,2),
  INTERESTINSTALLMENTAMOUNT  NUMBER(15,2),
  ADJUSTEDLOANDATE           DATE,
  TOTALEMIAMOUNT             NUMBER(15,2),
  PF_E                       NUMBER(15,2),
  PF_C                       NUMBER(15,2),
  VPF                        NUMBER(15,2),
  MINBALANCE                 NUMBER(15,2),
  ACTUALBALANCE              NUMBER(15,2),
  MODULE                     VARCHAR2(10 BYTE)  NOT NULL,
  PFGROSS                    NUMBER(15,2),
  VOUCHERNO                  VARCHAR2(50 BYTE),
  VOUCHERDATE                DATE,
  SYSTEMVOUCHERNO            VARCHAR2(100 BYTE),
  SYSTEMVOUCHERDATE          DATE,
  CHEQUENO                   VARCHAR2(50 BYTE),
  CHEQUEDATE                 DATE,
  ELIGIBLE                   CHAR(1 BYTE),
  LASTMODIFIED               DATE,
  USERNAME                   VARCHAR2(100 BYTE),
  SYSROWID                   VARCHAR2(50 BYTE)  NOT NULL,
  LOANCF                     VARCHAR2(1 BYTE),
  SANCTIONEDAMOUNT           NUMBER(18,2),
  PREV_LOAN_CAP_EMI          NUMBER(11,2)       DEFAULT 0,
  PREV_LOAN_INT_EMI          NUMBER(11,2)       DEFAULT 0,
  CURR_INT_EMI               NUMBER(11,2)       DEFAULT 0,
  CURR_CAP_EMI               NUMBER(11,2)       DEFAULT 0
)
 

DROP TABLE PFLOANBREAKUP CASCADE CONSTRAINTS;

CREATE TABLE PFLOANBREAKUP
(
  COMPANYCODE           VARCHAR2(10 BYTE),
  DIVISIONCODE          VARCHAR2(10 BYTE),
  EMPLOYEECOMPANYCODE   VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE  VARCHAR2(10 BYTE),
  YEARCODE              VARCHAR2(10 BYTE),
  YEARMONTH             VARCHAR2(10 BYTE),
  CATEGORYCODE          VARCHAR2(10 BYTE),
  GRADECODE             VARCHAR2(10 BYTE),
  PFNO                  VARCHAR2(20 BYTE),
  TOKENNO               VARCHAR2(50 BYTE),
  WORKERSERIAL          VARCHAR2(10 BYTE),
  LOANCODE              VARCHAR2(10 BYTE),
  LOANDATE              DATE,
  EFFECTYEARMONTH       VARCHAR2(10 BYTE),
  INTERESTPERCENTAGE    NUMBER(5,2),
  AMOUNT                NUMBER(15,2),
  TRANSACTIONTYPE       VARCHAR2(10 BYTE),
  EFFECTFORTNIGHT       DATE,
  PAIDON                DATE,
  ISPAID                VARCHAR2(4 BYTE),
  DEDUCTEDAMT           NUMBER(18,2),
  ADJUSTMENTTAG         VARCHAR2(20 BYTE),
  REMARKS               VARCHAR2(300 BYTE),
  REPAYAMOUNT           NUMBER(15,2),
  REPAYCAPITAL          NUMBER(15,2),
  REPAYINTEREST         NUMBER(15,2),
  REPAYREBATE           NUMBER(15,2),
  FINALSETTLEMENTTAG    VARCHAR2(1 BYTE),
  REPAYDATE             DATE,
  MODULE                VARCHAR2(10 BYTE),
  DELETERESION          VARCHAR2(100 BYTE),
  VOUCHERNO             VARCHAR2(100 BYTE),
  VOUCHERDATE           DATE,
  SYSTEMVOUCHERNO       VARCHAR2(100 BYTE),
  SYSTEMVOUCHERDATE     DATE,
  CHEQUENO              VARCHAR2(100 BYTE),
  CHEQUEDATE            DATE,
  SYSROWID              VARCHAR2(50 BYTE),
  USERNAME              VARCHAR2(100 BYTE),
  LASTMODIFIED          DATE,
  ISCASHREPAYMENT       VARCHAR2(1 BYTE),
  DEDUCTFROM            VARCHAR2(50 BYTE)       DEFAULT 'SALARY'
)   

DROP TABLE PFLOANCRITERIA CASCADE CONSTRAINTS;

CREATE TABLE PFLOANCRITERIA
(
  COMPANAYCODE              VARCHAR2(10 BYTE),
  DIVISIONCODE              VARCHAR2(10 BYTE),
  LOANCODE                  VARCHAR2(10 BYTE),
  LOANTYPE                  VARCHAR2(50 BYTE),
  ELIGIBLEAGE               NUMBER(6,2),
  ELIGIBLEYEARS             NUMBER(3),
  ELIGIBLEPECENTAGE         NUMBER(7,2),
  PFGROSSMONTH              NUMBER(4),
  RONDOFFLOANAMOUNT         NUMBER(15,2),
  MINIMUMLOANAMOUNT         NUMBER(15,2),
  MAXIMUMLOANAMOUNT         NUMBER(15,2),
  PREV_LOAN_DUE_PERCENTAGE  NUMBER(6,2),
  PF_E_PERCENTAGE           NUMBER(6,2),
  PF_C_PERCENTAGE           NUMBER(6,2),
  VPF_PERCENTAGE            NUMBER(6,2),
  LOANTAKEN_NOOFTIMES       NUMBER(3),
  MINIMUMPFBALANCE          NUMBER(11,2),
  MODULE                    VARCHAR2(10 BYTE),
  CURRENTCOMPANYCODE        VARCHAR2(10 BYTE),
  CURRENTDIVISIONCODE       VARCHAR2(10 BYTE),
  USERNAME                  VARCHAR2(100 BYTE),
  LASTMODIFIED              DATE,
  SYSROWID                  VARCHAR2(50 BYTE)
)
  


DROP TABLE PFLOANINTEREST CASCADE CONSTRAINTS;

CREATE TABLE PFLOANINTEREST
(
  COMPANYCODE           VARCHAR2(10 BYTE),
  DIVISIONCODE          VARCHAR2(10 BYTE),
  YEARCODE              VARCHAR2(10 BYTE),
  YEARMONTH             VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE    DATE,
  FORTNIGHTENDDATE      DATE,
  PFNO                  VARCHAR2(20 BYTE),
  LOANCODE              VARCHAR2(10 BYTE),
  LOANDATE              DATE,
  LOANAMOUNT            NUMBER(15,2),
  INTERESTAPPLICABLEON  NUMBER(15,2),
  INTERESTPERCENTAGE    NUMBER(5,2),
  INTERESTAMOUNT        NUMBER(18,2),
  EMPLOYEECOMPANYCODE   VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE  VARCHAR2(10 BYTE),
  MODULE                VARCHAR2(10 BYTE),
  TRANSACTIONTYPE       VARCHAR2(50 BYTE),
  REMARKS               VARCHAR2(100 BYTE),
  USERNAME              VARCHAR2(100 BYTE),
  SYSROWID              VARCHAR2(50 BYTE),
  WORKERSERIAL          VARCHAR2(10 BYTE),
  TOKENNO               VARCHAR2(10 BYTE)
)
   

DROP TABLE PFLOANMASTER CASCADE CONSTRAINTS;

CREATE TABLE PFLOANMASTER
(
  COMPANYCODE                 VARCHAR2(10 BYTE),
  DIVISIONCODE                VARCHAR2(10 BYTE),
  PFTRUSTCODE                 VARCHAR2(10 BYTE),
  LOANCODE                    VARCHAR2(5 BYTE)  NOT NULL,
  LOANDESC                    VARCHAR2(100 BYTE) NOT NULL,
  LOANSHORTNAME               VARCHAR2(50 BYTE),
  LOANCF                      VARCHAR2(1 BYTE)  NOT NULL,
  LOANINDEX                   NUMBER(3),
  REFUNDTYPE                  VARCHAR2(25 BYTE) NOT NULL,
  AGAINSTCOMPONENT            VARCHAR2(10 BYTE),
  RATIOPERCENT                NUMBER(7,2),
  REMARKS                     VARCHAR2(100 BYTE),
  WITHEFFECTFROM              DATE,
  REGULARDEDUCTION            VARCHAR2(1 BYTE),
  HOURSDEPENDENT              VARCHAR2(1 BYTE),
  LOANTYPE                    VARCHAR2(20 BYTE),
  LOANADJTYPE                 VARCHAR2(1 BYTE),
  MAXIMUMLOANAMOUNT           NUMBER(15,2),
  ADJLOANCODE                 VARCHAR2(10 BYTE),
  PFENTITLEMENTPERIOD         NUMBER(15,2),
  LOANGROUP                   VARCHAR2(20 BYTE),
  INTERESTPERCENTAGE          NUMBER(5,2),
  INTERESTTYPE                VARCHAR2(1 BYTE),
  PRVLOANRECOVERPERCENT       NUMBER(6,2),
  INTERESTDEDNMONTHLY         VARCHAR2(5 BYTE),
  NOOFTRANSACTIONPOSSIBLE     NUMBER(9),
  LOANCOMBITIONFORRECORDSCHK  VARCHAR2(500 BYTE),
  MINBALANCE                  NUMBER(15,2),
  LASTMODIFIED                DATE,
  TEST                        VARCHAR2(100 BYTE),
  ACCODE                      VARCHAR2(50 BYTE),
  PFGROSSMONTH                NUMBER(4),
  PF_E                        NUMBER(7,2),
  PF_C                        NUMBER(7,2),
  VPF                         NUMBER(7,2),
  SYSROWID                    VARCHAR2(50 BYTE),
  USERNAME                    VARCHAR2(100 BYTE),
  DEDUCTIONTYPE               VARCHAR2(50 BYTE),
  CAP_EMI_DEDUCT_TYPE         VARCHAR2(20 BYTE),
  INT_EMI_DEDUCT_TYPE         VARCHAR2(20 BYTE),
  INTEREST_CHRG_GRACEDAYS_1   NUMBER(7,2),
  INTEREST_CHRG_GRACEDAYS_2   NUMBER(7,2),
  INTEREST_CHRG_GRACEDAYS_3   NUMBER(7,2)
)
    

DROP TABLE LOANINTERESTCALCSTOP CASCADE CONSTRAINTS;

CREATE TABLE LOANINTERESTCALCSTOP
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  EFFECTIVEDATE  DATE,
  WORKERSERIAL   VARCHAR2(10 BYTE),
  TOKENNO        VARCHAR2(10 BYTE),
  LOANCODE       VARCHAR2(10 BYTE),
  LOANDATE       DATE,
  LOANINTSTOP    VARCHAR2(1 BYTE)               DEFAULT 'Y',
  MODULE         VARCHAR2(10 BYTE),
  SYSROWID       VARCHAR2(50 BYTE),
  USERNAME       VARCHAR2(100 BYTE),
  LASTMODIFIED   DATE                           DEFAULT SYSDATE
)
                         

DROP TABLE GBL_PFLOANELIGIBLE CASCADE CONSTRAINTS;

CREATE TABLE GBL_PFLOANELIGIBLE
(
  COMPANYCODE   VARCHAR2(10 BYTE),
  DIVISIONCODE  VARCHAR2(10 BYTE),
  PFNO          VARCHAR2(10 BYTE),
  WORKERSERIAL  VARCHAR2(10 BYTE),
  TOKENNO       VARCHAR2(10 BYTE),
  LOANCODE      VARCHAR2(10 BYTE),
  PF_E_AMOUNT   NUMBER(11,2)                    DEFAULT 0,
  PF_C_AMOUNT   NUMBER(11,2)                    DEFAULT 0,
  VP_AMOUNT     NUMBER(11,2)                    DEFAULT 0,
  TOTAL_AMOUNT  NUMBER(11,2)                    DEFAULT 0,
  REMARKS       VARCHAR2(150 BYTE)
)
        


DROP TABLE GTT_REP_OP_PFLOANBLNC CASCADE CONSTRAINTS;

CREATE TABLE GTT_REP_OP_PFLOANBLNC
(
  WORKERSERIAL         VARCHAR2(10 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  PFNO                 VARCHAR2(10 BYTE),
  LOANCODE             VARCHAR2(10 BYTE),
  LOANDATE             DATE,
  PFLOAN_BAL           NUMBER(18,2),
  PFLOAN_INT_BAL       NUMBER(18,2),
  PFLN_CAP_DEDUCT      NUMBER(18,2),
  PFLN_INT_DEDUCT      NUMBER(18,2),
  CAP_EMI              NUMBER(18,2),
  INT_EMI              NUMBER(18,2),
  TOT_EMI              NUMBER(18,2),
  CAP_STOP             VARCHAR2(1 BYTE),
  INT_STOP             VARCHAR2(1 BYTE),
  CAP_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  INT_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  MODULE               VARCHAR2(10 BYTE)
)
 


DROP TABLE GTT_REP_CL_PFLOANBLNC CASCADE CONSTRAINTS;

CREATE TABLE GTT_REP_CL_PFLOANBLNC
(
  WORKERSERIAL         VARCHAR2(10 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  PFNO                 VARCHAR2(10 BYTE),
  LOANCODE             VARCHAR2(10 BYTE),
  LOANDATE             DATE,
  PFLOAN_BAL           NUMBER(18,2),
  PFLOAN_INT_BAL       NUMBER(18,2),
  PFLN_CAP_DEDUCT      NUMBER(18,2),
  PFLN_INT_DEDUCT      NUMBER(18,2),
  CAP_EMI              NUMBER(18,2),
  INT_EMI              NUMBER(18,2),
  TOT_EMI              NUMBER(18,2),
  CAP_STOP             VARCHAR2(1 BYTE),
  INT_STOP             VARCHAR2(1 BYTE),
  CAP_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  INT_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  MODULE               VARCHAR2(10 BYTE)
)  

DROP TABLE GTT_PF_LOANBAL_TOTAL CASCADE CONSTRAINTS;

CREATE TABLE GTT_PF_LOANBAL_TOTAL
(
  CAP_OPN_PRINCIPAL      NUMBER(15,2),
  CAP_LOANSANCTION       NUMBER(15,2),
  CAP_LOANREPAIDPAYSLIP  NUMBER(15,2),
  CAP_LOANREPAIDSETT     NUMBER(15,2),
  CAP_CL_PRINCIPAL       NUMBER(15,2),
  INT_OPN_PRINCIPAL      NUMBER(15,2),
  INT_LOANSANCTION       NUMBER(15,2),
  INT_LOANREPAIDPAYSLIP  NUMBER(15,2),
  INT_LOANREPAIDSETT     NUMBER(15,2),
  INT_CL_PRINCIPAL       NUMBER(15,2),
  INT_ADJUSTMENT         NUMBER
) 

DROP TABLE GBL_PREV_LOANBALANCE CASCADE CONSTRAINTS;

CREATE TABLE GBL_PREV_LOANBALANCE
(
  WORKERSERIAL    VARCHAR2(10 BYTE),
  LOANCODE        VARCHAR2(10 BYTE),
  LOANDATE        DATE,
  PFLOAN_BAL      NUMBER(15,2),
  PFLOAN_INT_BAL  NUMBER(15,2)
)
 

DROP TABLE PFLOANSANCTIONPARAM CASCADE CONSTRAINTS;

CREATE TABLE PFLOANSANCTIONPARAM
(
  COMPANYCODE     VARCHAR2(10 BYTE),
  DIVISIONCODE    VARCHAR2(10 BYTE),
  LOANCODE        VARCHAR2(10 BYTE),
  QUERYINDEX      NUMBER(5,2),
  PARAMCODE       VARCHAR2(30 BYTE),
  PARAMNAME       VARCHAR2(100 BYTE),
  PARAMVALUE      NUMBER(11,2),
  PARAMVALUEFROM  NUMBER(11,2),
  PARAMVALUETO    NUMBER(11,2),
  QUERYSTRING     VARCHAR2(3000 BYTE),
  PROC_NAME       VARCHAR2(50 BYTE),
  USERNAME        VARCHAR2(50 BYTE),
  SYSROWID        VARCHAR2(50 BYTE),
  LASTMODIFIED    DATE,
  ERROR_MSG       VARCHAR2(1000 BYTE)
)     


DROP TABLE PFLOANINTEREST_24022021 CASCADE CONSTRAINTS;

CREATE TABLE PFLOANINTEREST_24022021
(
  COMPANYCODE           VARCHAR2(10 BYTE),
  DIVISIONCODE          VARCHAR2(10 BYTE),
  YEARCODE              VARCHAR2(10 BYTE),
  YEARMONTH             VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE    DATE,
  FORTNIGHTENDDATE      DATE,
  PFNO                  VARCHAR2(20 BYTE),
  LOANCODE              VARCHAR2(10 BYTE),
  LOANDATE              DATE,
  LOANAMOUNT            NUMBER(15,2),
  INTERESTAPPLICABLEON  NUMBER(15,2),
  INTERESTPERCENTAGE    NUMBER(5,2),
  INTERESTAMOUNT        NUMBER(18,2),
  EMPLOYEECOMPANYCODE   VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE  VARCHAR2(10 BYTE),
  MODULE                VARCHAR2(10 BYTE),
  TRANSACTIONTYPE       VARCHAR2(50 BYTE),
  REMARKS               VARCHAR2(100 BYTE),
  USERNAME              VARCHAR2(100 BYTE),
  SYSROWID              VARCHAR2(50 BYTE),
  WORKERSERIAL          VARCHAR2(10 BYTE),
  TOKENNO               VARCHAR2(10 BYTE)
)
      

DROP TABLE GTT_PF_LOANBALANCE CASCADE CONSTRAINTS;

CREATE TABLE GTT_PF_LOANBALANCE
(
  TOKENNO                 VARCHAR2(10 BYTE),
  AMOUNT                  NUMBER(15,2),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANAMOUNTADJUSTED      NUMBER(15,2),
  LOANINTAMOUNTADJUSTED   NUMBER(15,2),
  INTERESTAMOUNT          NUMBER(15,2),
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  ACTUALINTERESTAMOUNT    NUMBER(15,2),
  SANCTIONEDAMOUNT        NUMBER(15,2),
  CAPREPAY                NUMBER,
  INTREPAY                NUMBER,
  CAPREPAYSETTLEMENT      NUMBER,
  PRINCIPALCLBAL          NUMBER,
  INTREPAYSETTLEMENT      NUMBER,
  INTCLBAL                NUMBER,
  WORKERTOKENNO           VARCHAR2(10 BYTE),
  WORKERNAME              VARCHAR2(50 BYTE),
  PFLOAN_BAL              NUMBER(15,2),
  PFLOAN_INT_BAL          NUMBER(15,2),
  PFLN_CAP_DEDUCT         NUMBER(15,2),
  COMNAME                 VARCHAR2(200 BYTE),
  ACTIVE                  VARCHAR2(1 BYTE),
  CAPITALINSTALLMENTAMT   NUMBER,
  INTERESTINSTALLMENTAMT  NUMBER,
  PFNO                    VARCHAR2(10 BYTE),
  PRINT                   VARCHAR2(100 BYTE),
  CAP_EMI                 NUMBER(11,2),
  INT_EMI                 NUMBER(11,2),
  OPNPRINCIPAL            NUMBER,
  OPN_INT_PRINCIPAL       NUMBER,
  TAG                     NUMBER,
  INT_PFNO                VARCHAR2(20 BYTE),
  INT_TOKENNO             VARCHAR2(20 BYTE),
  INT_NAME                VARCHAR2(200 BYTE),
  LOANDATE                DATE,
  WORKERSERIAL            VARCHAR2(10 BYTE),
  INT_ADJUSTMENT          NUMBER
)
 

DROP TABLE LOANAPPLICATION CASCADE CONSTRAINTS;

CREATE TABLE LOANAPPLICATION
(
  COMPANYCODE             VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  MODULE                  VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  CATEGORYCODE            VARCHAR2(10 BYTE),
  GRADECODE               VARCHAR2(10 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  TOKENNO                 VARCHAR2(10 BYTE),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANTYPE                VARCHAR2(20 BYTE),
  LOANCF                  VARCHAR2(1 BYTE),
  AMOUNT                  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  NOOFINSTALLMENTS        NUMBER(18,6),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  ACTUALLOANDATE          DATE,
  COMMITEDRECOVERYPERIOD  NUMBER(18,6),
  LOANCLAIMAMOUNT         NUMBER(18,2),
  SANCTIONEDAMOUNT        NUMBER(18,2),
  INTERESTDEDNMONTHLY     VARCHAR2(3 BYTE),
  PAYABLEAMOUNT           NUMBER(15,2),
  APPLICATIONNO           VARCHAR2(50 BYTE),
  AMOUNTINHAND            NUMBER(15,2),
  INTERESTAMOUNT          NUMBER(15,2),
  CAPITALINSTALLMENTAMT   NUMBER(15,2),
  INTERESTINSTALLMENTAMT  NUMBER(15,2),
  TOTALEMIAMOUNT          NUMBER(18,2),
  LOANAMOUNTADJUSTED      NUMBER(18,2),
  LOANINTAMOUNTADJUSTED   NUMBER(18,2),
  AGAINSTLOANDATE         DATE,
  AGAINSTLOANCODE         VARCHAR2(10 BYTE),
  ADJUSTMENTDATE          DATE,
  REMARKS                 VARCHAR2(100 BYTE),
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  DEDUCTIONSTARTDATE      DATE,
  SYSROWID                VARCHAR2(50 BYTE),
  USERNAME                VARCHAR2(100 BYTE),
  LASTMODIFIED            DATE                  DEFAULT SYSDATE,
  REPAYCAPITAL            NUMBER(11,2),
  REPAYINTEREST           NUMBER(11,2),
  OLD_WORKERSERIAL        VARCHAR2(10 BYTE),
  LOANSTOP                CHAR(1 BYTE)          DEFAULT 'N',
  CURR_CAP_EMI            NUMBER(11,2)          DEFAULT 0,
  CURR_INT_EMI            NUMBER(11,2)          DEFAULT 0,
  PREV_LOAN_CAP_EMI       NUMBER(11,2)          DEFAULT 0,
  PREV_LOAN_INT_EMI       NUMBER(11,2)          DEFAULT 0
)
    


DROP TABLE PFLOANINTERESTADJUSMENT CASCADE CONSTRAINTS;

CREATE TABLE PFLOANINTERESTADJUSMENT
(
  COMPANYCODE        VARCHAR2(10 BYTE),
  DIVISIONCODE       VARCHAR2(10 BYTE),
  PFNO               VARCHAR2(10 BYTE),
  TOKENNO            VARCHAR2(10 BYTE),
  WORKERSERIAL       VARCHAR2(10 BYTE),
  LOANCODE           VARCHAR2(10 BYTE),
  LOANDATE           DATE,
  ASONCAPITALBAL     NUMBER(15,2),
  ASONINTERESTBAL    NUMBER(15,2),
  SANCTIONAMOUNT     NUMBER(15,2),
  INTERESTAMOUNT     NUMBER(15,2),
  MERGELOANAMOUNT    NUMBER(15,2),
  ADJINTERESTAMOUNT  NUMBER(15,2),
  ADJUSTMENTAMOUNT   NUMBER(15,2),
  ADJUSTEDAMOUNT     NUMBER(15,2),
  ADJUSTMENTDATE     DATE,
  REMARKS            VARCHAR2(200 BYTE),
  LASTMODIFIED       DATE                       DEFAULT SYSDATE,
  USERNAME           VARCHAR2(10 BYTE)
)                

DROP TABLE PFLOAN_EMI_UPDATE CASCADE CONSTRAINTS;

CREATE TABLE PFLOAN_EMI_UPDATE
(
  WORKERSERIAL    VARCHAR2(10 BYTE)             NOT NULL,
  PFNO            VARCHAR2(10 BYTE),
  LOANCODE        VARCHAR2(10 BYTE),
  TOTHRS          NUMBER,
  PFLOAN_BAL      NUMBER(18,2),
  PFLOAN_INT_BAL  NUMBER(18,2),
  CAP_EMI         NUMBER(18,2),
  INT_EMI         NUMBER(18,2),
  TOT_EMI         NUMBER(18,2),
  SLAB_HRS_FROM   NUMBER(11,2),
  SLAB_HRS_TO     NUMBER(11,2),
  NOOF_EMI        NUMBER(11,2),
  CAP_EMI_TOBE    NUMBER,
  INT_EMI_TOBE    NUMBER
) 

DROP TABLE GBL_PFLOAN_EMI_ZERO CASCADE CONSTRAINTS;

CREATE TABLE GBL_PFLOAN_EMI_ZERO
(
  PFNO  VARCHAR2(10 BYTE)                       NOT NULL
)

PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE GTT_AGPLOANSANCTION CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_AGPLOANSANCTION
(
  TOKENNO                 VARCHAR2(50 BYTE),
  EMPLOYEENAME            VARCHAR2(100 BYTE),
  LOANCODE                VARCHAR2(50 BYTE),
  LOANDATE                DATE,
  AMOUNT                  NUMBER(15,2),
  NOOFINSTALLMENTS        NUMBER(18,6),
  LOANCLAIMAMOUNT         NUMBER(18,2),
  SANCTIONEDAMOUNT        NUMBER(18,2),
  AMOUNTINHAND            NUMBER(15,2),
  CAPITALINSTALLMENTAMT   NUMBER(18,2),
  INTERESTINSTALLMENTAMT  NUMBER(18,2),
  TOTALEMIAMOUNT          NUMBER(18,2),
  LOANAMOUNTADJUSTED      NUMBER(18,2),
  AGAINSTLOANDATE         DATE,
  AGAINSTLOANCODE         VARCHAR2(100 BYTE),
  COMPANYNAME             VARCHAR2(100 BYTE),
  DIVISIONNAME            VARCHAR2(100 BYTE),
  DIVISIONADDRESS         VARCHAR2(200 BYTE),
  DIVISIONADDRESS1        VARCHAR2(200 BYTE),
  RUNDATE                 VARCHAR2(100 BYTE),
  FROMTODATE              VARCHAR2(100 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_NRLOAN CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_NRLOAN
(
  PFNO      VARCHAR2(10 BYTE),
  LOANDATE  VARCHAR2(50 BYTE),
  LN_PF_E   VARCHAR2(100 BYTE),
  LN_PF_C   VARCHAR2(100 BYTE),
  LN_PF_V   VARCHAR2(100 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_PFLOANREGD CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_PFLOANREGD
(
  COMPANYCODE                 VARCHAR2(10 BYTE) NOT NULL,
  DIVISIONCODE                VARCHAR2(10 BYTE) NOT NULL,
  TOKENNO                     VARCHAR2(20 BYTE),
  AMOUNT                      NUMBER(15,2),
  LOANCODE                    VARCHAR2(50 BYTE),
  LOANDATE                    DATE,
  ACTUALLOANAMOUNT            NUMBER,
  LOANAMOUNTADJUSTED          NUMBER(15,2),
  LOANINTAMOUNTADJUSTED       NUMBER(15,2),
  INTERESTAMOUNT              NUMBER(15,2),
  REMARKS                     VARCHAR2(100 BYTE),
  DEPARTMENTCODE              VARCHAR2(10 BYTE),
  ACTUALINTERESTAMOUNT        NUMBER(15,2),
  LASTMODIFIED                DATE,
  SANCTIONEDAMOUNT            NUMBER(18,2),
  PRINTDATE                   CHAR(25 BYTE),
  WORKERTOKENNO               VARCHAR2(10 BYTE),
  WORKERNAME                  VARCHAR2(50 BYTE),
  PFLOAN_BAL                  NUMBER(18,2),
  PFLOAN_INT_BAL              NUMBER(18,2),
  PFLN_CAP_DEDUCT             NUMBER(18,2),
  COMPANYNAME                 VARCHAR2(100 BYTE) NOT NULL,
  DIVISIONNAME                VARCHAR2(100 BYTE),
  ACTIVE                      VARCHAR2(1 BYTE),
  CAPITALINSTALLMENTAMT       NUMBER(18,2),
  INTERESTINSTALLMENTAMT      NUMBER(18,2),
  NOOFINSTALLMENTS            NUMBER(18,2),
  PFNO                        VARCHAR2(10 BYTE),
  PFLOAN_BAL_SUM              NUMBER(18,2),
  PFLOAN_INT_BAL_SUM          NUMBER(18,2),
  CAPITALINSTALLMENTAMT_SUM   NUMBER(18,2),
  INTERESTINSTALLMENTAMT_SUM  NUMBER(18,2)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANBLNC CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANBLNC
(
  WORKERSERIAL         VARCHAR2(10 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  PFNO                 VARCHAR2(10 BYTE),
  LOANCODE             VARCHAR2(10 BYTE),
  LOANDATE             DATE,
  PFLOAN_BAL           NUMBER(18,2),
  PFLOAN_INT_BAL       NUMBER(18,2),
  PFLN_CAP_DEDUCT      NUMBER(18,2),
  PFLN_INT_DEDUCT      NUMBER(18,2),
  CAP_EMI              NUMBER(18,2),
  INT_EMI              NUMBER(18,2),
  TOT_EMI              NUMBER(18,2),
  CAP_STOP             VARCHAR2(1 BYTE),
  INT_STOP             VARCHAR2(1 BYTE),
  CAP_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  INT_EMI_DEDUCT_TYPE  VARCHAR2(20 BYTE),
  MODULE               VARCHAR2(10 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_LOANEMICHANGE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_LOANEMICHANGE
(
  APPLICATIONNO    VARCHAR2(30 BYTE),
  APPLICATIONDATE  DATE,
  TOKENNO          VARCHAR2(10 BYTE),
  PFNO             VARCHAR2(10 BYTE),
  WORKERNAME       VARCHAR2(100 BYTE),
  OLDEMI           NUMBER(15,2),
  NEWEMI           NUMBER(15,2),
  OLDINTEREST      NUMBER(15,2),
  NEWINTEREST      NUMBER(15,2),
  COMPANYNAME      VARCHAR2(100 BYTE),
  RUNDATE          VARCHAR2(100 BYTE),
  FROMTODATE       VARCHAR2(100 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_PF_LOAN_EMI_CHANGE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_PF_LOAN_EMI_CHANGE
(
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   VARCHAR2(10 BYTE),
  WITHEFFECTFROM    VARCHAR2(10 BYTE),
  LOANCODE          VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(50 BYTE),
  PFNO              VARCHAR2(20 BYTE),
  WORKERNAME        VARCHAR2(500 BYTE),
  NEW_EMI_CAPITAL   NUMBER(18,2),
  NEW_EMI_INTEREST  NUMBER(18,2)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GBL_LOANTRANSACTION CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANTRANSACTION
(
  SANCTIONEDAMOUNT        NUMBER(18,2),
  DEDUCTIONSTARTDATE      DATE,
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  GRADECODE               VARCHAR2(10 BYTE),
  INTERESTAMOUNT          NUMBER(15,2),
  INTERESTDEDNMONTHLY     VARCHAR2(3 BYTE),
  INTERESTINSTALLMENTAMT  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  LOANAMOUNTADJUSTED      NUMBER(18,2),
  LOANCLAIMAMOUNT         NUMBER(18,2),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANINTAMOUNTADJUSTED   NUMBER(18,2),
  LOANTYPE                VARCHAR2(20 BYTE),
  MODULE                  VARCHAR2(10 BYTE),
  NOOFINSTALLMENTS        NUMBER(18,6),
  OPERATIONMODE           VARCHAR2(1 BYTE),
  PAYABLEAMOUNT           NUMBER(15,2),
  REMARKS                 VARCHAR2(100 BYTE),
  REPAYCAPITAL            NUMBER(15,2),
  REPAYINTEREST           NUMBER(15,2),
  SYSROWID                VARCHAR2(50 BYTE),
  TOKENNO                 VARCHAR2(10 BYTE),
  TOTALEMIAMOUNT          NUMBER(18,2),
  USERNAME                VARCHAR2(100 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  ACTUALLOANDATE          DATE,
  ADJUSTMENTDATE          DATE,
  AGAINSTLOANCODE         VARCHAR2(10 BYTE),
  AGAINSTLOANDATE         DATE,
  AMOUNT                  NUMBER(15,2),
  AMOUNTINHAND            NUMBER(15,2),
  APPLICATIONNO           VARCHAR2(50 BYTE),
  CAPITALINSTALLMENTAMT   NUMBER(15,2),
  CATEGORYCODE            VARCHAR2(10 BYTE),
  COMMITEDRECOVERYPERIOD  NUMBER(18,6),
  COMPANYCODE             VARCHAR2(10 BYTE),
  LOANCF                  VARCHAR2(1 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANSANCTION_DETAILS CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANSANCTION_DETAILS
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  YEARCODE       VARCHAR2(20 BYTE),
  PFNO           VARCHAR2(10 BYTE),
  TOKENNO        VARCHAR2(10 BYTE),
  WORKERSERIAL   VARCHAR2(10 BYTE),
  OPERATIONMODE  VARCHAR2(1 BYTE),
  LOANCODE       VARCHAR2(10 BYTE),
  PARAM_NAME     VARCHAR2(100 BYTE),
  PF_E           NUMBER(18,2),
  PF_C           NUMBER(18,2),
  VPF            NUMBER(18,2),
  OTHER          NUMBER(18,2),
  LOANDATE       DATE,
  SYSROWID       VARCHAR2(50 BYTE)              NOT NULL
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GTT_RPTLOANBALANCE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_RPTLOANBALANCE
(
  TOKENNO         VARCHAR2(10 BYTE),
  EMPLOYEENAME    VARCHAR2(50 BYTE),
  DEPARTMENTCODE  VARCHAR2(10 BYTE)             NOT NULL,
  LOANCODE        VARCHAR2(10 BYTE),
  LOAN_BAL        NUMBER(18,2),
  REPORTHEADER    VARCHAR2(500 BYTE),
  COMPANYNAME     VARCHAR2(500 BYTE),
  DIVISIONNAME    VARCHAR2(500 BYTE),
  EX1             NUMBER(10,2),
  EX2             NUMBER(10,2),
  EX4             NUMBER(10,2),
  EX5             NUMBER(10,2),
  EX6             NUMBER(10,2),
  EX7             NUMBER(10,2),
  EX8             NUMBER(10,2),
  EX9             VARCHAR2(500 BYTE),
  EX10            VARCHAR2(500 BYTE),
  EX11            DATE
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANMASTER CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANMASTER
(
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  LOANCODE       VARCHAR2(10 BYTE),
  OPERATIONMODE  VARCHAR2(1 BYTE),
  LOANDESC       VARCHAR2(500 BYTE),
  LOANCF         CHAR(1 BYTE),
  REFUNDTYPE     VARCHAR2(25 BYTE),
  PF_E           NUMBER(7,2),
  PF_C           NUMBER(7,2),
  VPF            NUMBER(7,2),
  USERNAME       VARCHAR2(100 BYTE),
  SYSROWID       VARCHAR2(100 BYTE),
  REMARKS        VARCHAR2(100 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANDEDUCTIONSTOP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANDEDUCTIONSTOP
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  FULLMILL          VARCHAR2(1 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  SLNO              NUMBER(5),
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  LOANSTOPFROMDATE  DATE,
  LOANSTOPTODATE    DATE,
  LOANSTARTFROM     DATE,
  MODULE            VARCHAR2(10 BYTE),
  REMARKS           VARCHAR2(50 BYTE),
  CAPITAL           VARCHAR2(1 BYTE),
  INTEREST          VARCHAR2(1 BYTE),
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  OPERATIONMODE     VARCHAR2(1 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANENTRYBULK CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANENTRYBULK
(
  APPLICABEL          VARCHAR2(2 BYTE),
  LOANCODE            VARCHAR2(20 BYTE),
  PAIDON              DATE,
  CATEGORYCODE        VARCHAR2(20 BYTE),
  INTERESTPERCENTAGE  NUMBER(10),
  YEARCODE            VARCHAR2(20 BYTE),
  WORKERNAME          VARCHAR2(100 BYTE),
  LOANTYPE            VARCHAR2(30 BYTE),
  WORKERSERIAL        VARCHAR2(20 BYTE),
  STARTDATE           DATE,
  BALANCECAP          NUMBER(18,2),
  MODULE              VARCHAR2(10 BYTE),
  USERNAME            VARCHAR2(20 BYTE),
  LOANDATE            DATE,
  PAYBLEAMOUNT        NUMBER(18,2),
  AMOUNT              NUMBER(18,2),
  BALANCEINT          NUMBER(18,2),
  REMARKS             VARCHAR2(100 BYTE),
  LOANCF              VARCHAR2(2 BYTE),
  GRADECODE           VARCHAR2(20 BYTE),
  ENDDATE             DATE,
  OPERATIONMODE       VARCHAR2(2 BYTE),
  EMIAMOUNT           NUMBER(18,2),
  DEDNDATE            DATE,
  COMPANYCODE         VARCHAR2(10 BYTE),
  DIVISIONCODE        VARCHAR2(10 BYTE),
  TOKENNO             VARCHAR2(30 BYTE),
  SYSROWID            VARCHAR2(50 BYTE)         NOT NULL
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANEMICHANGE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANEMICHANGE
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  MODULE            VARCHAR2(10 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  OPERATIONMODE     VARCHAR2(1 BYTE),
  TOKENNO           VARCHAR2(50 BYTE),
  PFNO              VARCHAR2(20 BYTE),
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  WITHEFFECTFROM    DATE,
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  OLD_EMI_CAPITAL   NUMBER(18),
  OLD_EMI_TOTAL     NUMBER(18),
  OLD_EMI_INTEREST  NUMBER(18),
  NEW_EMI_CAPITAL   NUMBER(18),
  NEW_EMI_TOTAL     NUMBER(18),
  NEW_EMI_INTEREST  NUMBER(18),
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  REMARKS           VARCHAR2(50 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANREPAY CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANREPAY
(
  PAIDON         DATE,
  BALANCEINT     NUMBER(18,2),
  USERNAME       VARCHAR2(30 BYTE),
  MODULE         VARCHAR2(30 BYTE),
  REMARKS        VARCHAR2(200 BYTE),
  STARTDATE      DATE,
  ENDDATE        DATE,
  AMOUNTCAP      NUMBER(18,2),
  LOANCODE       VARCHAR2(20 BYTE),
  AMOUNTINT      NUMBER(18,2),
  APPLICABEL     VARCHAR2(2 BYTE),
  WORKERSERIAL   VARCHAR2(20 BYTE),
  WORKERNAME     VARCHAR2(100 BYTE),
  BALANCECAP     NUMBER(18,2),
  YEARCODE       VARCHAR2(20 BYTE),
  OPERATIONMODE  VARCHAR2(2 BYTE),
  LOANDATE       DATE,
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  TOKENNO        VARCHAR2(20 BYTE),
  SYSROWID       VARCHAR2(50 BYTE)              NOT NULL
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANDEDUCTIONSTOP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANDEDUCTIONSTOP
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  FULLMILL          VARCHAR2(1 BYTE),
  PFNO              VARCHAR2(50 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  LOANSTOPFROMDATE  DATE,
  LOANSTOPTODATE    DATE,
  LOANSTARTFROM     DATE,
  MODULE            VARCHAR2(10 BYTE),
  REMARKS           VARCHAR2(50 BYTE),
  CAPITAL           VARCHAR2(1 BYTE),
  INTEREST          VARCHAR2(1 BYTE),
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  OPERATIONMODE     VARCHAR2(1 BYTE),
  SLNO              NUMBER(4)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANINTERESTCALCSTOP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANINTERESTCALCSTOP
(
  LOANINTSTOP    VARCHAR2(2 BYTE),
  MODULE         VARCHAR2(5 BYTE),
  USERNAME       VARCHAR2(100 BYTE),
  OPERATIONMODE  VARCHAR2(1 BYTE),
  SYSROWID       VARCHAR2(50 BYTE),
  COMPANYCODE    VARCHAR2(10 BYTE),
  DIVISIONCODE   VARCHAR2(10 BYTE),
  EFFECTIVEDATE  DATE,
  LOANCODE       VARCHAR2(10 BYTE),
  LOANDATE       DATE,
  WORKERSERIAL   VARCHAR2(10 BYTE),
  TOKENNO        VARCHAR2(10 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANBALACE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANBALACE
(
  TOKENNO          VARCHAR2(10 BYTE),
  PFNO             VARCHAR2(20 BYTE),
  LOANCODE         VARCHAR2(20 BYTE),
  LOANDATE         DATE,
  PFLOAN_BAL       NUMBER(15,2),
  PFLOANINT_BAL    NUMBER(15,2),
  PFCAP_DEDUCTION  NUMBER(15,2),
  PFINT_DEDUCTION  NUMBER(15,2)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_WPSLOANEMICHANGE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_WPSLOANEMICHANGE
(
  APPLICATIONNO    VARCHAR2(30 BYTE),
  APPLICATIONDATE  DATE,
  TOKENNO          VARCHAR2(10 BYTE),
  PFNO             VARCHAR2(10 BYTE),
  WORKERNAME       VARCHAR2(100 BYTE),
  OLDEMI           NUMBER(15,2),
  NEWEMI           NUMBER(15,4),
  COMPANYNAME      VARCHAR2(100 BYTE),
  RUNDATE          VARCHAR2(100 BYTE),
  FROMTODATE       VARCHAR2(100 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANINTERESTADJUSMENT CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANINTERESTADJUSMENT
(
  OPERATIONMODE      VARCHAR2(1 BYTE),
  PFNO               VARCHAR2(10 BYTE),
  SANCTIONAMOUNT     NUMBER(15,2),
  ASONINTERESTBAL    NUMBER(15,2),
  ADJUSTMENTDATE     DATE,
  USERNAME           VARCHAR2(10 BYTE),
  ADJUSTMENTAMOUNT   NUMBER(15,2),
  MERGELOANAMOUNT    NUMBER(15,2),
  ADJINTERESTAMOUNT  NUMBER(15,2),
  REMARKS            VARCHAR2(200 BYTE),
  ASONCAPITALBAL     NUMBER(15,2),
  ADJUSTEDAMOUNT     NUMBER(15,2),
  INTERESTAMOUNT     NUMBER(15,2),
  COMPANYCODE        VARCHAR2(10 BYTE),
  DIVISIONCODE       VARCHAR2(10 BYTE),
  TOKENNO            VARCHAR2(10 BYTE),
  WORKERSERIAL       VARCHAR2(10 BYTE),
  LOANCODE           VARCHAR2(10 BYTE),
  LOANDATE           DATE,
  SYSROWID           VARCHAR2(50 BYTE)          NOT NULL
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANTRANSACTION CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANTRANSACTION
(
  TOTALEMIAMOUNT          NUMBER(15,2),
  USERNAME                VARCHAR2(100 BYTE),
  VOUCHERDATE             DATE,
  VOUCHERNO               VARCHAR2(50 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  ACTUALBALANCE           NUMBER(15,2),
  ACTUALINTERESTAMOUNT    NUMBER(15,2),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  ACTUALLOANDATE          DATE,
  ADJUSTEDLOANDATE        DATE,
  ADJUSTMENTDATE          DATE,
  AGAINSTCOMPONENT        VARCHAR2(10 BYTE),
  AGAINSTLOANCODE         VARCHAR2(10 BYTE),
  AGAINSTLOANDATE         DATE,
  AMOUNT                  NUMBER(15,2),
  AMOUNTINHAND            NUMBER(15,2),
  APPLICATIONNO           VARCHAR2(50 BYTE),
  CAPITALBALANCEAMOUNT    NUMBER(15,2),
  CAPITALINSTALLMENTAMT   NUMBER(15,2),
  CATEGORYCODE            VARCHAR2(10 BYTE),
  CHEQUEDATE              DATE,
  SYSTEMVOUCHERNO         VARCHAR2(50 BYTE),
  TOKENNO                 VARCHAR2(10 BYTE),
  VPF                     NUMBER(15,2),
  CHEQUENO                VARCHAR2(50 BYTE),
  CLOSINGBALANCE          NUMBER(15,2),
  COMMITEDRECOVERYPERIOD  NUMBER(4),
  COMPANYCODE             VARCHAR2(10 BYTE),
  COMPONENTAMOUNT         NUMBER(15,2),
  DEDUCTIONSTARTDATE      DATE,
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  LOANINTAMOUNTADJUSTED   NUMBER(15,2),
  ELIGIBLE                VARCHAR2(1 BYTE),
  EMPLOYEECOMPANYCODE     VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE    VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  GRADECODE               VARCHAR2(10 BYTE),
  INTERESTAMOUNT          NUMBER(15,2),
  INTERESTBALANCEAMOUNT   NUMBER(15,2),
  INTERESTDEDNMONTHLY     NUMBER(15,2),
  INTERESTINSTALLMENTAMT  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  LOANAMOUNTADJUSTED      NUMBER(15,2),
  LOANCLAIMAMOUNT         NUMBER(15,2),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANNL                  NUMBER(15,2),
  LOANTYPE                VARCHAR2(20 BYTE),
  MINBALANCE              NUMBER(15,2),
  MODULE                  VARCHAR2(10 BYTE),
  NEWINTERESTAMOUNT       NUMBER(15,2),
  NEXTLOAN                NUMBER(15,2),
  OPENINGBALANCE          NUMBER(15,2),
  PAYABLEAMOUNT           NUMBER(15,2),
  PF_C                    NUMBER(15,2),
  PF_E                    NUMBER(15,2),
  PFGROSS                 NUMBER(15,2),
  PFNO                    VARCHAR2(10 BYTE),
  RATIOPERCENT            NUMBER(5,2),
  REMARKS                 VARCHAR2(100 BYTE),
  REPAYCAPITAL            NUMBER(15,2),
  REPAYINTEREST           NUMBER(15,2),
  SYSROWID                VARCHAR2(50 BYTE),
  SYSTEMVOUCHERDATE       DATE,
  LOANCF                  VARCHAR2(1 BYTE),
  SANCTIONEDAMOUNT        NUMBER(15,2),
  NOOFINSTALLMENTS        NUMBER(4),
  OPERATIONMODE           VARCHAR2(1 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GTT_LOANREGISTER CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_LOANREGISTER
(
  COMPANYCODE             VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  MODULE                  VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  CATEGORYCODE            VARCHAR2(10 BYTE),
  GRADECODE               VARCHAR2(10 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  TOKENNO                 VARCHAR2(10 BYTE),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANTYPE                VARCHAR2(20 BYTE),
  LOANCF                  VARCHAR2(1 BYTE),
  AMOUNT                  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  NOOFINSTALLMENTS        NUMBER(18,6),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  ACTUALLOANDATE          DATE,
  COMMITEDRECOVERYPERIOD  NUMBER(18,6),
  LOANCLAIMAMOUNT         NUMBER(18,2),
  SANCTIONEDAMOUNT        NUMBER(18,2),
  INTERESTDEDNMONTHLY     VARCHAR2(3 BYTE),
  PAYABLEAMOUNT           NUMBER(15,2),
  APPLICATIONNO           VARCHAR2(50 BYTE),
  AMOUNTINHAND            NUMBER(15,2),
  INTERESTAMOUNT          NUMBER(15,2),
  CAPITALINSTALLMENTAMT   NUMBER(15,2),
  INTERESTINSTALLMENTAMT  NUMBER(15,2),
  TOTALEMIAMOUNT          NUMBER(18,2),
  REPAYCAPITAL            NUMBER(15,2),
  REPAYINTEREST           NUMBER(15,2),
  LOANAMOUNTADJUSTED      NUMBER(18,2),
  LOANINTAMOUNTADJUSTED   NUMBER(18,2),
  AGAINSTLOANDATE         DATE,
  AGAINSTLOANCODE         VARCHAR2(10 BYTE),
  ADJUSTMENTDATE          DATE,
  REMARKS                 VARCHAR2(100 BYTE),
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  DEDUCTIONSTARTDATE      DATE,
  SYSROWID                VARCHAR2(50 BYTE),
  USERNAME                VARCHAR2(100 BYTE),
  LASTMODIFIED            DATE                  DEFAULT SYSDATE,
  WORKERTOKENNO           VARCHAR2(10 BYTE),
  WORKERNAME              VARCHAR2(100 BYTE),
  LOAN_BAL                NUMBER(18,2),
  LOAN_INT_BAL            NUMBER(18,2),
  COMPANYNAME             VARCHAR2(100 BYTE),
  DIVISIONNAME            VARCHAR2(100 BYTE),
  PRINTDATE               VARCHAR2(50 BYTE),
  ACTIVE                  VARCHAR2(10 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_LOANSTOP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_LOANSTOP
(
  APPLICATIONNO     VARCHAR2(30 BYTE),
  APPLICATIONDATE   DATE,
  TOKENNO           VARCHAR2(10 BYTE),
  PFNO              VARCHAR2(10 BYTE),
  WORKERNAME        VARCHAR2(100 BYTE),
  LOANSTOPFROMDATE  DATE,
  LOANSTOPTODATE    DATE,
  COMPANYNAME       VARCHAR2(100 BYTE),
  RUNDATE           VARCHAR2(100 BYTE),
  FROMTODATE        VARCHAR2(100 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANAPPLICATION CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANAPPLICATION
(
  OPERATIONMODE           VARCHAR2(1 BYTE),
  AMOUNTINHAND            NUMBER(15,2),
  APPLICATIONNO           VARCHAR2(50 BYTE),
  CAPITALBALANCEAMOUNT    NUMBER(15,2),
  CAPITALINSTALLMENTAMT   NUMBER(15,2),
  CATEGORYCODE            VARCHAR2(10 BYTE),
  CHEQUEDATE              DATE,
  SYSTEMVOUCHERNO         VARCHAR2(50 BYTE),
  TOKENNO                 VARCHAR2(10 BYTE),
  VPF                     NUMBER(15,2),
  CHEQUENO                VARCHAR2(50 BYTE),
  CLOSINGBALANCE          NUMBER(15,2),
  COMMITEDRECOVERYPERIOD  NUMBER(4),
  COMPANYCODE             VARCHAR2(10 BYTE),
  COMPONENTAMOUNT         NUMBER(15,2),
  DEDUCTIONSTARTDATE      DATE,
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  ELIGIBLE                VARCHAR2(1 BYTE),
  EMPLOYEECOMPANYCODE     VARCHAR2(10 BYTE),
  EMPLOYEEDIVISIONCODE    VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  GRADECODE               VARCHAR2(10 BYTE),
  INTERESTAMOUNT          NUMBER(15,2),
  INTERESTBALANCEAMOUNT   NUMBER(15,2),
  INTERESTDEDNMONTHLY     NUMBER(15,2),
  INTERESTINSTALLMENTAMT  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  LOANAMOUNTADJUSTED      NUMBER(15,2),
  LOANCLAIMAMOUNT         NUMBER(15,2),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANINTAMOUNTADJUSTED   NUMBER(15,2),
  LOANNL                  NUMBER(15,2),
  LOANTYPE                VARCHAR2(20 BYTE),
  MINBALANCE              NUMBER(15,2),
  MODULE                  VARCHAR2(10 BYTE),
  NEWINTERESTAMOUNT       NUMBER(15,2),
  NEXTLOAN                NUMBER(15,2),
  OPENINGBALANCE          NUMBER(15,2),
  PAYABLEAMOUNT           NUMBER(15,2),
  PF_C                    NUMBER(15,2),
  PF_E                    NUMBER(15,2),
  PFGROSS                 NUMBER(15,2),
  PFNO                    VARCHAR2(10 BYTE),
  RATIOPERCENT            NUMBER(5,2),
  REMARKS                 VARCHAR2(100 BYTE),
  REPAYCAPITAL            NUMBER(15,2),
  REPAYINTEREST           NUMBER(15,2),
  SYSROWID                VARCHAR2(50 BYTE),
  SYSTEMVOUCHERDATE       DATE,
  LOANCF                  VARCHAR2(1 BYTE),
  SANCTIONEDAMOUNT        NUMBER(15,2),
  NOOFINSTALLMENTS        NUMBER(4),
  ACTUALLOANDATE          DATE,
  ADJUSTEDLOANDATE        DATE,
  ADJUSTMENTDATE          DATE,
  AGAINSTCOMPONENT        VARCHAR2(10 BYTE),
  AGAINSTLOANCODE         VARCHAR2(10 BYTE),
  AGAINSTLOANDATE         DATE,
  AMOUNT                  NUMBER(15,2),
  TOTALEMIAMOUNT          NUMBER(15,2),
  USERNAME                VARCHAR2(100 BYTE),
  VOUCHERDATE             DATE,
  VOUCHERNO               VARCHAR2(50 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  ACTUALBALANCE           NUMBER(15,2),
  ACTUALINTERESTAMOUNT    NUMBER(15,2),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  PREV_LOAN_CAP_EMI       NUMBER(15,2),
  PREV_LOAN_INT_EMI       NUMBER(15,2),
  CURR_CAP_EMI            NUMBER(15,2),
  CURR_INT_EMI            NUMBER(15,2)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANDEDUCTIONSTOPMULTI CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANDEDUCTIONSTOPMULTI
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  FULLMILL          VARCHAR2(1 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  LOANSTOPFROMDATE  DATE,
  LOANSTOPTODATE    DATE,
  LOANSTARTFROM     DATE,
  MODULE            VARCHAR2(10 BYTE),
  REMARKS           VARCHAR2(50 BYTE),
  CAPITAL           VARCHAR2(1 BYTE),
  INTEREST          VARCHAR2(1 BYTE),
  OPERATIONMODE     VARCHAR2(1 BYTE),
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;
 
DROP TABLE GTT_RPT_PFLOANSTOP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_RPT_PFLOANSTOP
(
  WORKERSERIAL    VARCHAR2(10 BYTE),
  TOKENNO         VARCHAR2(10 BYTE),
  PFNO            VARCHAR2(10 BYTE),
  EMPLOYEENAME    VARCHAR2(100 BYTE),
  COMPANYNAME     VARCHAR2(100 BYTE),
  COMPANYADDRESS  VARCHAR2(100 BYTE),
  CAPTION         VARCHAR2(100 BYTE),
  EX1             VARCHAR2(100 BYTE),
  EX2             VARCHAR2(100 BYTE),
  EX3             VARCHAR2(100 BYTE),
  EX4             VARCHAR2(100 BYTE),
  EX5             VARCHAR2(100 BYTE),
  EX6             VARCHAR2(100 BYTE),
  EX7             VARCHAR2(100 BYTE),
  EX8             VARCHAR2(100 BYTE),
  EX9             VARCHAR2(100 BYTE),
  EX10            VARCHAR2(100 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_PFLOANDEDUCTIONSTOPMULTI CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_PFLOANDEDUCTIONSTOPMULTI
(
  COMPANYCODE          VARCHAR2(10 BYTE),
  DIVISIONCODE         VARCHAR2(10 BYTE),
  FULLMILL             VARCHAR2(1 BYTE),
  DEDUCTIONPERCENTAGE  NUMBER(15,2),
  PFNO                 VARCHAR2(50 BYTE),
  WORKERSERIAL         VARCHAR2(10 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  YEARCODE             VARCHAR2(10 BYTE),
  LOANCODE             VARCHAR2(10 BYTE),
  LOANDATE             DATE,
  APPLICATIONNO        VARCHAR2(50 BYTE),
  APPLICATIONDATE      DATE,
  LOANSTOPFROMDATE     DATE,
  LOANSTOPTODATE       DATE,
  LOANSTARTFROM        DATE,
  MODULE               VARCHAR2(10 BYTE),
  REMARKS              VARCHAR2(50 BYTE),
  CAPITAL              VARCHAR2(1 BYTE),
  INTEREST             VARCHAR2(1 BYTE),
  USERNAME             VARCHAR2(100 BYTE),
  SYSROWID             VARCHAR2(50 BYTE),
  OPERATIONMODE        VARCHAR2(1 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GTT_LOANSANCTION_PRAM CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_LOANSANCTION_PRAM
(
  COMPANYCODE   VARCHAR2(10 BYTE),
  DIVISIONCODE  VARCHAR2(10 BYTE),
  YEARCODE      VARCHAR2(20 BYTE),
  PFNO          VARCHAR2(10 BYTE),
  TOKENNO       VARCHAR2(10 BYTE),
  WORKERSERIAL  VARCHAR2(10 BYTE),
  LOANDATE      DATE,
  LOANCODE      VARCHAR2(10 BYTE),
  PARAM_NAME    VARCHAR2(100 BYTE),
  PF_E          NUMBER(18,2),
  PF_C          NUMBER(18,2),
  VPF           NUMBER(18,2),
  OTHER         NUMBER(18,2),
  ISELLIGIBLE   CHAR(1 BYTE),
  REMARKS       VARCHAR2(500 BYTE),
  TABINDEX      VARCHAR2(2 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GTT_PF_LOANCHECKLIST CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_PF_LOANCHECKLIST
(
  COMPANYNAME                 VARCHAR2(100 BYTE),
  DIVISIONNAME                VARCHAR2(100 BYTE),
  TOKENNO                     VARCHAR2(20 BYTE),
  AMOUNT                      NUMBER(15,2),
  LOANCODE                    VARCHAR2(50 BYTE),
  LOANDATE                    VARCHAR2(50 BYTE),
  ACTUALLOANAMOUNT            NUMBER,
  LOANAMOUNTADJUSTED          NUMBER(15,2),
  LOANINTAMOUNTADJUSTED       NUMBER(15,2),
  INTERESTAMOUNT              NUMBER(15,2),
  REMARKS                     VARCHAR2(100 BYTE),
  DEPARTMENTCODE              VARCHAR2(10 BYTE),
  ACTUALINTERESTAMOUNT        NUMBER(15,2),
  LASTMODIFIED                DATE,
  SANCTIONEDAMOUNT            NUMBER(18,2),
  PRINTDATE                   VARCHAR2(200 BYTE),
  WORKERTOKENNO               VARCHAR2(10 BYTE),
  WORKERNAME                  VARCHAR2(50 BYTE),
  PFLOAN_BAL                  NUMBER(18,2),
  PFLOAN_INT_BAL              NUMBER(18,2),
  PFLN_CAP_DEDUCT             NUMBER(18,2),
  ACTIVE                      VARCHAR2(1 BYTE),
  CAPITALINSTALLMENTAMT       NUMBER(18,2),
  INTERESTINSTALLMENTAMT      NUMBER(18,2),
  NOOFINSTALLMENTS            NUMBER(18,2),
  PFNO                        VARCHAR2(10 BYTE),
  PFLOAN_BAL_SUM              NUMBER(18,2),
  PFLOAN_INT_BAL_SUM          NUMBER(18,2),
  CAPITALINSTALLMENTAMT_SUM   NUMBER(18,2),
  INTERESTINSTALLMENTAMT_SUM  NUMBER(18,2),
  RMODE                       NUMBER,
  SRLNO                       NUMBER(10),
  CAP_EMI                     NUMBER(18,2),
  INT_EMI                     NUMBER(18,2),
  APPLIEDYEAR                 VARCHAR2(30 BYTE),
  EX1                         NUMBER,
  EX2                         NUMBER,
  EX3                         NUMBER,
  EX4                         NUMBER,
  EX9                         NUMBER,
  EX10                        VARCHAR2(100 BYTE),
  EX11                        VARCHAR2(100 BYTE),
  EX12                        VARCHAR2(100 BYTE),
  EX5                         VARCHAR2(100 BYTE),
  EX6                         VARCHAR2(100 BYTE),
  EX7                         VARCHAR2(100 BYTE),
  EX8                         VARCHAR2(100 BYTE),
  EX13                        VARCHAR2(100 BYTE),
  EX14                        VARCHAR2(100 BYTE),
  EX15                        VARCHAR2(100 BYTE),
  EX16                        VARCHAR2(100 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GBL_LOANEMICHANGE CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_LOANEMICHANGE
(
  COMPANYCODE       VARCHAR2(10 BYTE),
  DIVISIONCODE      VARCHAR2(10 BYTE),
  YEARCODE          VARCHAR2(10 BYTE),
  MODULE            VARCHAR2(10 BYTE),
  WORKERSERIAL      VARCHAR2(10 BYTE),
  TOKENNO           VARCHAR2(50 BYTE),
  APPLICATIONNO     VARCHAR2(50 BYTE),
  APPLICATIONDATE   DATE,
  WITHEFFECTFROM    DATE,
  LOANCODE          VARCHAR2(10 BYTE),
  LOANDATE          DATE,
  OLD_EMI_TOTAL     NUMBER(18),
  OLD_EMI_CAPITAL   NUMBER(18),
  OLD_EMI_INTEREST  NUMBER(18),
  NEW_EMI_CAPITAL   NUMBER(18),
  NEW_EMI_TOTAL     NUMBER(18),
  NEW_EMI_INTEREST  NUMBER(18),
  OPERATIONMODE     VARCHAR2(1 BYTE),
  USERNAME          VARCHAR2(100 BYTE),
  SYSROWID          VARCHAR2(50 BYTE),
  REMARKS           VARCHAR2(50 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;


DROP TABLE GTT_PFLOANREGISTER CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_PFLOANREGISTER
(
  COMPANYCODE             VARCHAR2(10 BYTE)     NOT NULL,
  DIVISIONCODE            VARCHAR2(10 BYTE)     NOT NULL,
  TOKENNO                 VARCHAR2(20 BYTE),
  AMOUNT                  NUMBER(15,2),
  LOANCODE                VARCHAR2(50 BYTE),
  LOANDATE                DATE,
  ACTUALLOANAMOUNT        NUMBER,
  LOANAMOUNTADJUSTED      NUMBER(15,2),
  LOANINTAMOUNTADJUSTED   NUMBER(15,2),
  INTERESTAMOUNT          NUMBER(15,2),
  REMARKS                 VARCHAR2(100 BYTE),
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  ACTUALINTERESTAMOUNT    NUMBER(15,2),
  LASTMODIFIED            DATE,
  SANCTIONEDAMOUNT        NUMBER(18,2),
  PRINTDATE               CHAR(25 BYTE),
  WORKERTOKENNO           VARCHAR2(10 BYTE),
  WORKERNAME              VARCHAR2(50 BYTE),
  PFLOAN_BAL              NUMBER(18,2),
  PFLOAN_INT_BAL          NUMBER(18,2),
  PFLN_CAP_DEDUCT         NUMBER(18,2),
  COMPANYNAME             VARCHAR2(100 BYTE)    NOT NULL,
  DIVISIONNAME            VARCHAR2(100 BYTE),
  ACTIVE                  VARCHAR2(1 BYTE),
  CAPITALINSTALLMENTAMT   NUMBER(18,2),
  INTERESTINSTALLMENTAMT  NUMBER(18,2),
  NOOFINSTALLMENTS        NUMBER(18,2)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE GBL_WPSWORKERLOANTRANSACTION CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GBL_WPSWORKERLOANTRANSACTION
(
  COMPANYCODE             VARCHAR2(10 BYTE),
  DIVISIONCODE            VARCHAR2(10 BYTE),
  YEARCODE                VARCHAR2(10 BYTE),
  YEARMONTH               VARCHAR2(10 BYTE),
  WORKERCATEGORYCODE      VARCHAR2(10 BYTE),
  GRADECODE               VARCHAR2(10 BYTE),
  WORKERSERIAL            VARCHAR2(10 BYTE),
  LOANCODE                VARCHAR2(10 BYTE),
  LOANDATE                DATE,
  LOANTYPE                VARCHAR2(1 BYTE),
  AMOUNT                  NUMBER(15,2),
  INTERESTPERCENTAGE      NUMBER(5,2),
  NOOFINSTALLMENTS        NUMBER(3),
  AGAINSTCOMPONENT        VARCHAR2(25 BYTE),
  OPENINGBALANCE          NUMBER(15,2),
  RATIOPERCENT            NUMBER(15,2),
  COMPONENTAMOUNT         NUMBER(15,2),
  CLOSINGBALANCE          NUMBER(15,2),
  REMARKS                 VARCHAR2(100 BYTE),
  ACTUALLOANAMOUNT        NUMBER(15,2),
  ACTUALLOANDATE          DATE,
  COMMITEDRECOVERYPERIOD  NUMBER(3),
  DEPARTMENTCODE          VARCHAR2(10 BYTE),
  FORTNIGHTSTARTDATE      DATE,
  LOANNL                  NUMBER(18),
  NEXTLOAN                NUMBER(15),
  ACTUALINTERESTAMOUNT    NUMBER(18,2),
  NEWINTERESTAMOUNT       NUMBER(18,2),
  LOANAMOUNTADJUSTED      NUMBER(18,2),
  LOANINTAMOUNTADJUSTED   NUMBER(18,2),
  ADVICENO                VARCHAR2(10 BYTE),
  ADVICEDATE              DATE,
  REPAYCAPITAL            NUMBER(18,2),
  REPAYINTEREST           NUMBER(18,2),
  ADJUSTMENTDATE          DATE,
  CAPITALINSTALLMENTAMT   NUMBER(18,2),
  INTERESTINSTALLMENTAMT  NUMBER(18,2),
  PF_E                    NUMBER(18,2),
  PF_C                    NUMBER(18,2),
  APPLICATIONAMOUNT       NUMBER(18,2),
  TOKENNO                 VARCHAR2(10 BYTE),
  OPERATIONMODE           VARCHAR2(1 BYTE),
  USERNAME                VARCHAR2(100 BYTE),
  SECTIONCODE             VARCHAR2(10 BYTE),
  PARENTSHIFT             VARCHAR2(10 BYTE),
  LOANDESC                VARCHAR2(100 BYTE),
  CANCELYN                VARCHAR2(1 BYTE),
  LASTMODIFIED            DATE                  DEFAULT SYSDATE
)
ON COMMIT DELETE ROWS
NOCACHE;

 

DROP TABLE LOANADJFROMARREAR CASCADE CONSTRAINTS;

CREATE TABLE LOANADJFROMARREAR
(
  COMPANYCODE     VARCHAR2(10 BYTE),
  DIVISIONCODE    VARCHAR2(10 BYTE),
  YEARCODE        VARCHAR2(10 BYTE),
  YEARMONTH       VARCHAR2(10 BYTE),
  SALDATEFROM     VARCHAR2(10 BYTE),
  SALDATETO       VARCHAR2(10 BYTE),
  WORKERSERIAL    VARCHAR2(10 BYTE),
  TOKENNO         VARCHAR2(10 BYTE),
  LOANCODE        VARCHAR2(10 BYTE),
  LOANDATE        DATE,
  LOANAMOUNT      NUMBER(10,2),
  LOANPAIDAMOUNT  NUMBER(10,2),
  LOANBALAMOUNT   NUMBER(10,2),
  INTERESTAMOUNT  NUMBER(10,2),
  INTPAIDAMOUNT   NUMBER(10,2),
  INTBALAMOUNT    NUMBER(10,2),
  CAPEMIAMOUNT    NUMBER(10,2),
  INTEMIAMOUNT    NUMBER(10,2),
  CAPREPAYAMOUNT  NUMBER(10,2),
  INTREPAYAMOUNT  NUMBER(10,2),
  USERNAME        VARCHAR2(100 BYTE),
  LASTMODIFIED    DATE                          DEFAULT SYSDATE,
  SYSROWID        VARCHAR2(50 BYTE)
)
 

DROP TABLE PFLOANENTRYDATE CASCADE CONSTRAINTS;

CREATE TABLE PFLOANENTRYDATE
(
  COMPANYCODE        VARCHAR2(10 BYTE),
  DIVISIONCODE       VARCHAR2(10 BYTE),
  LOANCODE           VARCHAR2(10 BYTE),
  ENTRYDATE          DATE,
  VALIDITYDATE_FROM  DATE,
  VALIDITYDATE_TO    DATE,
  USERNAME           VARCHAR2(50 BYTE),
  LASTMODIFIED       DATE,
  SYSROWID           VARCHAR2(50 BYTE)
) 

CREATE INDEX IDX_LOANDEDUCTI_07122019061516 ON LOANDEDUCTIONSTOP
(COMPANYCODE, DIVISIONCODE, YEARCODE, APPLICATIONNO, APPLICATIONDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANDEDUCTI_21122018064716 ON LOANDEDUCTIONSTOP
(COMPANYCODE, DIVISIONCODE, WORKERSERIAL, YEARCODE, APPLICATIONNO, 
APPLICATIONDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANEMICHAN_26122018063801 ON LOANEMICHANGE
(COMPANYCODE, DIVISIONCODE, YEARCODE, MODULE, APPLICATIONNO)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANINTERES_16112019122310 ON LOANINTERESTCALCSTOP
(COMPANYCODE, DIVISIONCODE, EFFECTIVEDATE, LOANCODE, LOANDATE, 
WORKERSERIAL, TOKENNO)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANMASTER_08082018053212 ON LOANMASTER
(COMPANYCODE, DIVISIONCODE, LOANCODE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANSANCTIO_11012019025903 ON LOANSANCTION_DETAILS
(COMPANYCODE, DIVISIONCODE, YEARCODE, PFNO, PARAM_NAME, 
WORKERSERIAL, LOANDATE, LOANCODE, TOKENNO)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANTRANSAC_21122018012043 ON LOANTRANSACTION
(DIVISIONCODE, LOANCLAIMAMOUNT, COMPANYCODE, LOANDATE, WORKERSERIAL, 
LOANCODE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANTRANSAC_27072016040013 ON LOANTRANSACTION
(COMPANYCODE, DIVISIONCODE, WORKERSERIAL, LOANDATE, LOANCODE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LOANTRANSAC_28082018122928 ON LOANTRANSACTION
(DIVISIONCODE, LOANCODE, COMPANYCODE, WORKERSERIAL, LOANDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANAPPLI_11012019025902 ON PFLOANAPPLICATION
(COMPANYCODE, PFNO, LOANDATE, DIVISIONCODE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANBREAKUP ON PFLOANBREAKUP
(COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, PFNO, 
LOANCODE, LOANDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANDEDUC_17042017040452 ON PFLOANDEDUCTIONSTOP
(COMPANYCODE, DIVISIONCODE, YEARCODE, APPLICATIONNO, APPLICATIONDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANEMICH_17042017041606 ON PFLOANEMICHANGE
(COMPANYCODE, DIVISIONCODE, YEARCODE, MODULE, APPLICATIONNO)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANINTER_07092020083434 ON PFLOANINTERESTADJUSMENT
(COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL, LOANCODE, 
LOANDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANTRANSACTION ON PFLOANTRANSACTION
(COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, PFNO, 
LOANCODE, LOANDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PFLOANTRANS_11012019054629 ON PFLOANTRANSACTION
(COMPANYCODE, PFNO, LOANDATE, DIVISIONCODE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PFLOANTRANSACTION_PK ON PFLOANTRANSACTION
(COMPANYCODE, PFNO, LOANCODE, LOANDATE)
LOGGING

PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TRG_SYSROWID_00000000000001667
 before insert ON GBL_LOANENTRYBULK for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001468" 
 before insert ON GBL_LOANEMICHANGE for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001611" 
 before insert ON GBL_PFLOANDEDUCTIONSTOP for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001612" 
 before insert ON GBL_LOANINTERESTCALCSTOP for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001473" 
 before insert ON GBL_LOANSANCTION_DETAILS for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001474" 
 before insert ON GBL_PFLOANTRANSACTION for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001161" 
 before insert ON GBL_LOANTRANSACTION for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001465" 
 before insert ON GBL_LOANDEDUCTIONSTOPMULTI for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001466" 
 before insert ON GBL_PFLOANDEDUCTIONSTOPMULTI for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001263" 
 before insert ON GBL_PFLOANEMICHANGE for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001266" 
 before insert ON GBL_PFLOANMASTER for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001180" 
 before insert ON LOANTRANSACTION for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER "TRG_SYSROWID_00000000000001622" 
 before insert ON GBL_LOANDEDUCTIONSTOP for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER TRG_SYSROWID_00000000000001675
 before insert ON GBL_PFLOANAPPLICATION for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER TRG_SYSROWID_00000000000001736
 before insert ON GBL_PFLOANINTERESTADJUSMENT for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


CREATE OR REPLACE TRIGGER TRG_SYSROWID_00000000000001645
 before insert ON GBL_LOANREPAY for each row
declare 
    wlastnumber  number(11); 
    wsysrowid    varchar2(30); 
 begin    
 if nvl(:new.sysrowid,'~N~') ='~N~' or upper(:new.sysrowid) = 'NULL' then 
    select seq_sysrowid.nextval 
    into wlastnumber 
    from dual;     
    wsysrowid := to_char(sysdate,'YYYYMMDDHH24MISS') || lpad(wlastnumber,10,'0');
   :new.sysrowid := wsysrowid;  
end if;
 end;
/


ALTER TABLE PFLOANTRANSACTION ADD (
  CONSTRAINT PFLOANTRANSACTION_PK
 PRIMARY KEY
 (COMPANYCODE, PFNO, LOANCODE, LOANDATE)
    USING INDEX 
    
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

