SELECT * FROM PFLOANTRANSACTION
WHERE LOANDATE='22-JUN-2020'
AND ACTUALLOANDATE='15-JUL-2020'



SELECT SUM(LOANCLAIMAMOUNT) FROM PFLOANTRANSACTION
WHERE LOANDATE='22-JUN-2020'
AND ACTUALLOANDATE='15-JUL-2020'

CREATE TABLE PFLOANTRANSACTION_090221 AS
SELECT * FROM PFLOANTRANSACTION



UPDATE PFLOANTRANSACTION
SET ACTUALLOANDATE= LOANDATE
WHERE LOANDATE='22-JUN-2020'
AND ACTUALLOANDATE='15-JUL-2020'
AND LOANCODE='MPL'

SELECT * FROM PFLOANTRANSACTION
WHERE TOKENNO='71533'


SELECT SUM(LOANCLAIMAMOUNT) FROM PFLOANTRANSACTION
WHERE LOANDATE='26-JUN-2020'
AND ACTUALLOANDATE='15-JUL-2020'


UPDATE PFLOANTRANSACTION
SET ACTUALLOANDATE= LOANDATE
WHERE LOANDATE='26-JUN-2020'
AND ACTUALLOANDATE='15-JUL-2020'
AND LOANCODE='MPL'