SELECT * FROM(
 SELECT 'NO'SELECTED,CHANNELCODE,SALEBILLNO,TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESBILLMASTER 
WHERE COMPANYCODE='BJ0056' 
AND DIVISIONCODE='0001' 
AND CHANNELCODE='DOMESTIC|SALES|LOCAL' 
AND BUYERCODE='SPS004' 
AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('20/02/2021','DD/MM/YYYY') 
AND SALEBILLNO NOT IN 
( 
   SELECT SALEBILLNO FROM SALESOTHERBILLREFDETAILS 
   WHERE COMPANYCODE='BJ0056' 
   AND DIVISIONCODE='0001' 
   AND PARTYCODE='SPA013'
   AND SCRAPSALEBILLNO='BJM/2021/GS0212' 
   AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('20/02/2021','DD/MM/YYYY') 
) 
UNION ALL
SELECT 'YES'SELECTED,CHANNELCODE,SALEBILLNO,TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESOTHERBILLREFDETAILS 
   WHERE COMPANYCODE='BJ0056' 
   AND DIVISIONCODE='0001' 
   AND PARTYCODE='SPA013'
   AND SCRAPSALEBILLNO='BJM/2021/GS0212' 
   AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('20/02/2021','DD/MM/YYYY') 
)
ORDER BY SELECTED DESC,CHANNELCODE,SALEBILLNO,SALEBILLDATE


 SELECT * FROM( 
 SELECT 'NO'SELECTED,CHANNELCODE,SALEBILLNO,TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESBILLMASTER  
WHERE COMPANYCODE='BJ0056'  
AND DIVISIONCODE='0001'  
AND CHANNELCODE='DOMESTIC|SALES|SCRAP'  
AND BUYERCODE='SPA013'  
AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('20/02/2021','DD/MM/YYYY')  
AND SALEBILLNO NOT IN  
(  
   SELECT SALEBILLNO FROM SALESOTHERBILLREFDETAILS  
   WHERE COMPANYCODE='BJ0056'  
   AND DIVISIONCODE='0001'  
   AND PARTYCODE='SPA013' 
   AND SCRAPSALEBILLNO='BJM/2021/GS0212'  
   AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('20/02/2021','DD/MM/YYYY')  
)  
UNION ALL 
SELECT 'YES'SELECTED,CHANNELCODE,SALEBILLNO,TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESOTHERBILLREFDETAILS  
   WHERE COMPANYCODE='BJ0056'  
   AND DIVISIONCODE='0001'  
   AND PARTYCODE='SPA013' 
   AND SCRAPSALEBILLNO='BJM/2021/GS0212'  
   AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('20/02/2021','DD/MM/YYYY')  
) 
ORDER BY SELECTED DESC,CHANNELCODE,SALEBILLNO,SALEBILLDATE 

QUERYMASTER

DELETE FROM SALESOTHERBILLREFDETAILS
WHERE SCRAPSALEBILLNO='BJM/2021/GS0214'