DROP TABLE SALESOTHERBILLREFDETAILS CASCADE CONSTRAINTS;

CREATE TABLE SALESOTHERBILLREFDETAILS
(
  CHANNELCODE         VARCHAR2(100 BYTE)        NOT NULL,
  SCRAPSALEBILLNO    VARCHAR2(30 BYTE),
  SCRAPSALEBILLDATE  DATE,
  SALEBILLNO         VARCHAR2(30 BYTE)         NOT NULL,
  SALEBILLDATE       DATE,
  PARTYCODE           VARCHAR2(10 BYTE),
  COMPANYCODE         VARCHAR2(10 BYTE)         NOT NULL,
  DIVISIONCODE        VARCHAR2(10 BYTE)         NOT NULL,
  YEARCODE            VARCHAR2(9 BYTE)          NOT NULL,
  USERNAME            VARCHAR2(100 BYTE)        NOT NULL,
  SYSROWID            VARCHAR2(50 BYTE)         NOT NULL,
  LASTMODIFIED        DATE                      DEFAULT SYSDATE
)

SELECT * FROM LOGIN


EXEC PROC_CREATE_SYSTFMAP('SALESOTHERBILLREFDETAILS','COMPANYCODE, DIVISIONCODE, SCRAPSALEBILLNO') 

DELETE FROM SYS_TFMAP WHERE  SYS_TABLE_SEQUENCIER = 15022


SELECT * FROM SYS_TFMAP WHERE  SYS_TABLE_SEQUENCIER = 15022

EXEC PROC_CREATE_GBL_TMP_TABLES(15022,0)

GBL_SALESOTHERBILLREFDETAILS
GBL_SALESOTHERBILLREFDETAILS

BJM/2021/GS0213


SALESOTHERBILLMASTER

SALESCHARGEDETAILS

SELECT * FROM ACVOUCHER WHERE VOUCHERNO='BJM/2021/GS0213'


SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='3200'

SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (3200, '""', 'COMPANYCODE~DIVISIONCODE~PATTERN', 'OTHER QUALITY DESC', NULL, 
    'SELECT DISTINCT ITEMDESC 
FROM SALESOTHERBILLDETAIL 
WHERE COMPANYCODE=<<COMPANYCODE>>
AND DIVISIONCODE=<<DIVISIONCODE>>
ORDER BY ITEMDESC', 'ITEMDESC~', 'SALES');
COMMIT;


 SELECT 'NO'SELECTED,CHANNELCODE,SALEBILLNO,TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESBILLMASTER 
WHERE COMPANYCODE='BJ0056' 
AND DIVISIONCODE='0001' 
AND CHANNELCODE='DOMESTIC|SALES|GOVERNMENT' 
AND BUYERCODE='SPA013' 
AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('30/01/2020','DD/MM/YYYY') 
AND SALEBILLNO NOT IN 
( 
   SELECT SALEBILLNO FROM SALESOTHERBILLREFDETAILS 
   WHERE COMPANYCODE='BJ0056' 
   AND DIVISIONCODE='0001' 
   AND CHANNELCODE='DOMESTIC|SALES|GOVERNMENT' 
   AND BUYERCODE='SPA013' 
   AND SALEBILLDATE BETWEEN TO_DATE('01/01/2016','DD/MM/YYYY') AND TO_DATE('30/01/2020','DD/MM/YYYY') 
) 

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%sale other%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0105020905'

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

prcOth_Bill_Before_MainSave

PRCOTH_BILL_BEFORE_MAINSAVE 

PRCOTH_BILL_BEFORE_COMMIT 


SYS_AUTOGEN_PARAMS

SELECT * FROM SALESOTHERBILLMASTER

SELECT * FROM SALESOTHERBILLDETAIL

CREATE TABLE WW AS
 select companycode, divisioncode, divisioncodefor, yearcode, systemvoucherno, systemvoucherdate, transaction_type, transaction_nature, 
               is_tran_with_registered_party, accodefor, accode, voucherserialno, drcr, 
               gstn_sender, gstn_sender_name, gstn_sender_address,gstn_sender_statecode, gstn_sender_statename, 
               gstn_recipient, gstn_recipient_name, gstn_recipient_address, gstn_recipient_statecode,gstn_recipient_statename, 
               gstn_consinee, gstn_consinee_name, gstn_consinee_address, gstn_consinee_statecode, gstn_consinee_statename, 
               place_of_supply_statecode, place_of_supply_statename,
               invoice_no, invoice_date, debit_credit_note_no, debit_credit_note_date, 
               shipping_bill_no, shipping_bill_date, is_reverse_charge_by_recipient, serial_no, hsn_sac_code, hsn_sac_description, is_goods_or_service, 
               is_exempted, input_credit_available, item_description, uom, quantity, rate_per_unit, hsn_sac_amount, discount_per_unit, discount_percentage, 
               discount_amount, hsn_sac_assessable_amount, tax_percentage, igst_rate, igst_amount, cgst_rate, cgst_amount, sgst_rate, sgst_amount, 
               cess_rate, cess_amount, sysrowid, username, lastmodified, partycode
        from gbl_acgstdetails_entry_sales;
        
        
    ALTER TABLE acgstdetails_entry ADD    SELF_INVOICE_NO VARCHAR2(100)
     
    gbl_acgstdetails_entry_sales
    
    
        , SELF_INVOICE_NO, SELF_INVOICE_DATE
        
   SELECT 'YES' SELECTED, CHANNELCODE, SALEBILLNO, TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESOTHERBILLREFDETAILS 
   WHERE COMPANYCODE='BJ0056' 
   AND DIVISIONCODE='0001' 
   AND PARTYCODE='SPA013' 
   AND SCRAPSALEBILLNO = 'BJM/2021/GS0212' 

   SELECT 'YES' SELECTED, CHANNELCODE, SALEBILLNO, TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESOTHERBILLREFDETAILS 
   WHERE COMPANYCODE='BJ0056' 
   AND DIVISIONCODE='0001' 
   AND PARTYCODE='SPA013' 
   AND SCRAPSALEBILLNO = 'BJM/2021/GS0212' 
   
-- 
  
SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='3049'

SET DEFINE OFF;
Insert into SYS_HELP_QRY
   (QRY_ID, QRY_STRING, PARAMETER_STRING, QRY_SHORTDESC, QRY_RETURN_TABLE_NAME, WEB_QRY_STRING, SEARCH_COLUMNLIST, MODULENAME)
 Values
   (3049, '""', 'COMPANYCODE~MODULE~PARTYTYPE~PARTYCODE~PATTERN', 'BUYER ADDRESS INFORMATION', NULL, 
    'SELECT DISTINCT ADDRESSCODE, ADDRESS
  FROM PARTYADDRESS
 WHERE 1=1
   AND COMPANYCODE = <<COMPANYCODE>>
   AND MODULE = <<MODULE>>
   AND PARTYTYPE = <<PARTYTYPE>>
   AND PARTYCODE = <<PARTYCODE>>
 ORDER BY ADDRESSCODE', 'ADDRESSCODE~ADDRESS~', 'SALES');
COMMIT;
  

 SELECT 'NO'SELECTED,CHANNELCODE,SALEBILLNO,TO_CHAR(SALEBILLDATE,'DD/MM/YYYY')SALEBILLDATE FROM SALESBILLMASTER 
WHERE COMPANYCODE='BJ0056' 
AND DIVISIONCODE='0001' 
AND CHANNELCODE='DOMESTIC|SALES|LOCAL' 
AND BUYERCODE='SPA012' 
AND SALEBILLDATE BETWEEN TO_DATE('01/01/2011','DD/MM/YYYY') AND TO_DATE('01/01/2021','DD/MM/YYYY') 
AND SALEBILLNO NOT IN 
( 
   SELECT SALEBILLNO FROM SALESOTHERBILLREFDETAILS 
   WHERE COMPANYCODE='BJ0056' 
   AND DIVISIONCODE='0001' 
   AND CHANNELCODE='DOMESTIC|SALES|LOCAL' 
   AND PARTYCODE='SPA012' 
   AND SALEBILLDATE BETWEEN TO_DATE('01/01/2011','DD/MM/YYYY') AND TO_DATE('01/01/2021','DD/MM/YYYY') 
) 