
  update pisemployeemaster
  set companycode=  'CJ0101'
  
  
  update pisdepartmentmaster
  set companycode=  'CJ0101'
  
   
SELECT * FROM PISCOMPONENTMASTER



 SELECT  A.WORKERSERIAL||'~'||A.TOKENNO||'~'|| A.EMPLOYEENAME||'~'|| A.ATTNIDENTIFICATION||'~'||A.DEPARTMENTCODE||'~'||A.GRADECODE||'~'||G.GRADEDESC||'~'|| A.CATEGORYCODE||'~'||
         A.DESIGNATIONCODE||'~'||S.DESIGNATIONDESC ||'~'|| A.ADDRESS_PERMANENT||'~'||A.ADDRESS_PRESENT||'~'||A.BOSSCODE||'~'||O.BOSSNAME||'~'|| A.UNITCODE||'~'||A.FATHERNAME||'~'||A.GUARDIANNAME||'~'||A.SPOUSENAME||'~'||
         A.SEX||'~'|| A.MARITIALSTATUS||'~'||A.QUARTERALLOTED||'~'|| A.QUARTERNO||'~'||A.PFAPPLICABLE||'~'|| A.EPFAPPLICABLE||'~'|| A.PTAXAPPLICABLE||'~'|| 
         TO_CHAR(DATEOFBIRTH,'DD/MM/RRRR') ||'~'||TO_CHAR(DATEOFJOIN,'DD/MM/RRRR')||'~'||TO_CHAR(DATEOFRETIRE,'DD/MM/RRRR')||'~'|| 
         TO_CHAR(EXTENDEDRETIREDATE,'DD/MM/RRRR') ||'~'||TO_CHAR(DATEOFCONFIRMATION,'DD/MM/RRRR')||'~'||TO_CHAR(PFENTITLEDATE,'DD/MM/RRRR') ||'~'||
         TO_CHAR(PFSETTELMENTDATE,'DD/MM/RRRR') ||'~'||TO_CHAR(DATEOFTERMINATIONADVICE,'DD/MM/RRRR') ||'~'||TO_CHAR(STATUSDATE,'DD/MM/RRRR') ||'~'|| 
         ESINO||'~'|| PFNO||'~'||PFACCODE||'~'||A.PENSIONNO||'~'||A.BANKCODE||'~'||A.PAYMODE||'~'||M.BANKNAME||'~'||A.BANKACCNUMBER||'~'||A.BANKACCHOLDINGNAME||'~'||A.UANNO||'~'||
         MOBILENO||'~'|| PHONE||'~'|| GRATUITYOPENINGYEARS||'~'|| TO_CHAR(GRATUITYSETTELMENTDATE,'DD/MM/RRRR') ||'~'||A.COSTCENTRECODE||'~'||
         PAYMENTSTATUS||'~'|| GRATUITYAPPLICABLE||'~'||A.BONUSAPPLICABLE||'~'||A.ACADEMICQUALIFICATION||'~'||A.PROFESSIONQUALIFICATION||'~'||A.REMARKS||'~'||A.EMPLOYEESTATUS||'~'||
         B.DEPARTMENTDESC||'~'||D.CATEGORYDESC||'~'||A.PANCARDNO||'~'|| A.AADHARNO||'~'||A.SNFACCODE||'~'||A.IFSCCODE||'~'||A.LEAVINGSERVICE||'~'||A.EMAILID||'~'||A.VOTERID||'~'|| 
         A.STATE_PERMANENT||'~'|| A.STATE_PRESENT||'~'||A.CITY_PERMANENT||'~'|| A.CITY_PRESENT||'~'|| A.PIN_PERMANENT||'~'|| A.PIN_PRESENT||'~'||A.COSTCENTRECODE||'~'||A.PTAXSTATE||'~'||A.WORKERCODE||'~'||TO_CHAR(LASTPROMOTIONDATE,'DD/MM/RRRR')
         ||'~'||A.IMAGEURL||'~'||A.SUPERANUATIONNUMBER||'~'||TO_CHAR(A.SUPERANUATIONDATE,'DD/MM/YYYY')||'~'||A.RELIGION||'~'||A.PRANNUMBER||'~'||A.GRATUITYNUMBER
 FROM PISEMPLOYEEMASTER A,PISDEPARTMENTMASTER B,PISCATEGORYMASTER D, PISGRADEMASTER G, SALESBANKMASTER M,PISDESIGNATIONMASTER S, 
 (SELECT TOKENNO BOSSCODE,EMPLOYEENAME BOSSNAME FROM PISEMPLOYEEMASTER WHERE COMPANYCODE = 'CJ0101' AND DIVISIONCODE ='0001' ) O
 WHERE A.COMPANYCODE = 'CJ0101' AND A.DIVISIONCODE = '0001' 
   AND A.TOKENNO= '00001' 
   AND A.COMPANYCODE=B.COMPANYCODE AND A.DIVISIONCODE=B.DIVISIONCODE 
   AND A.DEPARTMENTCODE=B.DEPARTMENTCODE 
   AND A.COMPANYCODE=M.COMPANYCODE (+) AND A.DIVISIONCODE=M.DIVISIONCODE (+)
   AND A.BANKCODE=M.BANKCODE (+)
   AND A.COMPANYCODE=D.COMPANYCODE  AND A.DIVISIONCODE=D.DIVISIONCODE 
   AND A.CATEGORYCODE=D.CATEGORYCODE
   AND A.COMPANYCODE=G.COMPANYCODE (+) AND A.DIVISIONCODE=G.DIVISIONCODE (+)
   AND A.CATEGORYCODE=G.CATEGORYCODE (+) AND A.GRADECODE=G.GRADECODE (+) 
   AND A.COMPANYCODE=S.COMPANYCODE (+) AND A.DIVISIONCODE=S.DIVISIONCODE (+)
   AND A.DESIGNATIONCODE=S.DESIGNATIONCODE (+)
   AND A.BOSSCODE=O.BOSSCODE (+)
   
   
   SELECT * FROM PISEMPLOYEEMASTER
   
   SELECT * FROM PISCATEGORYMASTER
   
   
   SELECT * FROM PISDESIGNATIONMASTER
   
   
   SELECT * FROM PISGRADEMASTER
   
  update PISGRADEMASTER
  set companycode=  'CJ0101'
  
  
  
  SELECT * FROM SYS_TFMAP
  WHERE SYS_TABLE_SEQUENCIER = '10014'
  
  SELECT * FROM SYS_TFMAP
  WHERE SYS_TABLENAME_ACTUAL = 'PISEMPLOYEEMASTER'
  
  
  SELECT * FROM SYS_TFMAP
  WHERE SYS_TABLENAME_TEMP = ''
  
  
 SELECT * FROM SYS_HELP_QRY
 WHERE QRY_ID='7028'
 
 
 SELECT DISTINCT UNITCODE,UNITNAME
  FROM PISUNITMASTER
 WHERE COMPANYCODE=<<COMPANYCODE>>
   AND DIVISIONCODE=<<DIVISIONCODE>>
 ORDER BY UNITCODE
 
 SELECT * FROM DIVISIONMASTER
 
 SELECT * FROM PISCOMPONENTMASTER
 
 
 
SELECT 'UPDATE '||TABLE_NAME|| ' SET DIVISIONCODE=''0005'' WHERE DIVISIONCODE=''0001'';'  FROM COLS
WHERE COLUMN_NAME = 'DIVISIONCODE'
AND TABLE_NAME LIKE 'PIS%'