select * from piscomponentmaster
where 



PROC_RPT_PIS_PAYSLIP_ED('BJ0056','0001','2020-2021','202010','''01''','','','')

PROC_RPT_PIS_PAYSLIP_ED('BJ0056','0001','2020-2021','202010','''01''','','','')

EXEC PROC_PIS_CHECKLIST('BJ0056','0001','2020-2021','01/08/2020','31/08/2020','''OT_HRS'',''OEPF'',''OE_NPF'',''OTHR_DEDN''','','','')


SELECT * FROM MENUMASTER_RND
WHERE MENUDESC LIKE 'PF and Loan%'

PROC_RPT_BANKLOAN_COMPSAV_EXL('COMPANYCODE','DIVISIONCODE','YEARCODE','txtYEARMONTH','btnUnit','btnCategory') 

PROC_RPT_PF_LOANDEDN_TEXT('COMPANYCODE','DIVISIONCODE','YEARCODE','txtYEARMONTH','btnUnit','btnCategory') 

select * from pispaytransaction
where yearmonth='202010'
and pf_e <> pf_c
and pf_e > 0




exec PROC_RPT_PF_LOANDEDN_TEXT('BJ0056','0001','2020-2021','202010','''01''','') 




INSERT INTO GTT_PIS_PF_LOANDEDN_REP
(
    COMPANYCODE, DIVISIONCODE, UNITCODE, UNITSHORTDESC, CATEGORYCODE, CATEGORYDESC, 
    DEPARTMENTCODE,DEPARTMENTDESC, TOKENNO, PFNO, EMPLOYEENAME,PF_GROSS, PF_E, VPF, PF_C, FPF, LOAN_PFL, 
    LINT_PFL, LNBL_PFL, LOANDATE, LOANAMOUNT, PF_E_YTD, VPF_YTD, PF_C_YTD, FPF_YTD
)
SELECT A.COMPANYCODE, A.DIVISIONCODE, A.UNITCODE,B.UNITSHORTDESC, A.CATEGORYCODE, C.CATEGORYDESC, 
A.DEPARTMENTCODE, D.DEPARTMENTDESC,A.TOKENNO,E.PFNO, E.EMPLOYEENAME,NVL(A.PF_GROSS,0), NVL(A.PF_E,0),NVL(A.VPF,0),NVL(A.PF_C,0),NVL(A.FPF,0), NVL(A.LOAN_PFL,0), 
NVL(A.LINT_PFL,0), NVL(A.LNBL_PFL,0), F.LOANDATE, NVL(F.LOANAMOUNT,0), NVL(G.PF_E_YTD,0) , NVL(G.VPF_YTD,0)  , NVL(G.PF_C_YTD,0) , NVL(G.FPF_YTD,0) 
FROM 
(
    SELECT COMPANYCODE, DIVISIONCODE, UNITCODE, CATEGORYCODE, DEPARTMENTCODE, TOKENNO,
    PF_E,VPF,PF_C,FPF, LOAN_PFL, LINT_PFL, LNBL_PFL,PF_GROSS
    FROM PISPAYTRANSACTION
    WHERE COMPANYCODE='BJ0056'
    AND DIVISIONCODE='0001'
    AND YEARCODE='2020-2021'
    AND YEARMONTH='202010'
    AND UNITCODE IN ('01')
) A, PISUNITMASTER B, PISCATEGORYMASTER C, PISDEPARTMENTMASTER D, PISEMPLOYEEMASTER E,
(
    SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, LOANCODE, LOANDATE, ACTUALLOANAMOUNT LOANAMOUNT 
    FROM PFLOANTRANSACTION A
    WHERE LOANDATE = 
    (
        SELECT MAX(LOANDATE) FROM PFLOANTRANSACTION
        WHERE COMPANYCODE=A.COMPANYCODE
        AND DIVISIONCODE=A.DIVISIONCODE 
        AND TOKENNO=A.TOKENNO
        AND LOANCODE=A.LOANCODE
    )
    AND LOANCODE='PFL'
) F,
(
    SELECT COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL, SUM(PF_E) PF_E_YTD , SUM(VPF) VPF_YTD  , SUM(PF_C) PF_C_YTD , SUM(FPF) FPF_YTD 
    FROM PISPAYTRANSACTION
    WHERE YEARCODE='2020-2021'
    GROUP BY COMPANYCODE, DIVISIONCODE, TOKENNO, WORKERSERIAL
) G
WHERE A.COMPANYCODE=B.COMPANYCODE
AND A.DIVISIONCODE=B.DIVISIONCODE
AND A.UNITCODE=B.UNITCODE
AND A.COMPANYCODE=C.COMPANYCODE
AND A.DIVISIONCODE=C.DIVISIONCODE
AND A.CATEGORYCODE=C.CATEGORYCODE
AND A.COMPANYCODE=D.COMPANYCODE
AND A.DIVISIONCODE=D.DIVISIONCODE
AND A.DEPARTMENTCODE=D.DEPARTMENTCODE
AND A.COMPANYCODE=E.COMPANYCODE
AND A.DIVISIONCODE=E.DIVISIONCODE
AND A.TOKENNO=E.TOKENNO
AND A.COMPANYCODE=F.COMPANYCODE(+)
AND A.DIVISIONCODE=F.DIVISIONCODE(+)
AND A.TOKENNO=F.TOKENNO(+)
AND A.COMPANYCODE=G.COMPANYCODE(+)
AND A.DIVISIONCODE=G.DIVISIONCODE(+)
AND A.TOKENNO=G.TOKENNO(+)


----------------------------------------------------------------------------------------------

SELECT RTRIM (XMLAGG (XMLELEMENT (E, X.COLNAME||SRL || ',')ORDER BY X.COLNAME).EXTRACT ('//text()'), ',') COMPONENTNAMELIST
FROM (
SELECT ROWNUM SRL, 'COMP' COLNAME FROM(
   select nvl(phase,999)+nvl(calculationindex,9999) srl, 'PISCOMP.'||componentcode componentcode from piscomponentmaster
   where companycode='BJ0056'
       and divisioncode='0001'
       and componentcode||yearmonth in
           (   select distinct componentcode||max(yearmonth) from piscomponentmaster
               where companycode='BJ0056'
                   and divisioncode='0001'                   and nvl(ATTENDANCEENTRYAPPLICABLE,'N') = 'Y'
                   and to_number(yearmonth)<=to_number(TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM'))
                   and componentcode in ('OT_HRS','OEPF','OE_NPF','OTHR_DEDN')
               group by componentcode
           )
)
) X



INSERT INTO GTT_PISCHECK_LIST( WORKERSERIAL, TOKENNO, EMPLOYEENAME, UNITCODE, CATEGORYCODE, GRADECODE, DEPARTMENTCODE, DEPARTMENTDESC,COMPANYNAME, DIVISIONNAME, FROMTODATE, SALARYDAYS, PRESENTDAYS, HOLIDAYS ,
COMP1,COMP2,COMP3,COMP4
)

SELECT '0' WORKERSERIAL,NULL TOKENNO,NULL EMPLOYEENAME,NULL UNITCODE,NULL CATEGORYCODE,NULL GRADECODE,NULL DEPARTMENTCODE,NULL DEPARTMENTDESC,C.COMPANYNAME, D.DIVISIONNAME,'Check list For the month '||TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'MM-YYYY') FROMTODATE,NULL SALARYDAYS,NULL PRESENTDAYS,NULL HOLIDAYS ,
'OT_HRS','OEPF','OE_NPF','OTHR_DEDN'
FROM COMPANYMAST C, DIVISIONMASTER D WHERE C.COMPANYCODE=D.COMPANYCODE AND C.COMPANYCODE= 'BJ0056' AND D.DIVISIONCODE = '0001' 
UNION ALL
SELECT A.WORKERSERIAL,A.TOKENNO,E.EMPLOYEENAME,A.UNITCODE,A.CATEGORYCODE,A.GRADECODE,A.DEPARTMENTCODE,D.DEPARTMENTDESC,M.COMPANYNAME, V.DIVISIONNAME,'Check list For the month '||TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'MM-YYYY') FROMTODATE,A.SALARYDAYS,A.PRESENTDAYS,A.HOLIDAYS  ,
TO_CHAR(PISCOMP.OT_HRS),TO_CHAR(PISCOMP.OEPF),TO_CHAR(PISCOMP.OE_NPF),TO_CHAR(PISCOMP.OTHR_DEDN) 
FROM PISMONTHATTENDANCE A,PISEMPLOYEEMASTER E, PISDEPARTMENTMASTER D,COMPANYMAST M, DIVISIONMASTER V, (
      SELECT * FROM PISCOMPONENTASSIGNMENT
     WHERE COMPANYCODE='BJ0056'
         AND DIVISIONCODE='0001'
         AND TRANSACTIONTYPE='ATTENDANCE'
         AND WORKERSERIAL||YEARMONTH IN (
             SELECT WORKERSERIAL||MAX(YEARMONTH) FROM PISCOMPONENTASSIGNMENT
             WHERE COMPANYCODE='BJ0056' AND DIVISIONCODE='0001'
                 AND TO_NUMBER(YEARMONTH)<=TO_NUMBER(TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM'))
                 AND TRANSACTIONTYPE='ATTENDANCE'
             GROUP BY WORKERSERIAL
         )
 ) PISCOMP
WHERE A.COMPANYCODE=E.COMPANYCODE
AND A.DIVISIONCODE=E.DIVISIONCODE
AND A.WORKERSERIAL=E.WORKERSERIAL
AND A.COMPANYCODE=D.COMPANYCODE
AND A.DIVISIONCODE=D.DIVISIONCODE
AND A.DEPARTMENTCODE=D.DEPARTMENTCODE
AND A.WORKERSERIAL=PISCOMP.WORKERSERIAL
AND A.COMPANYCODE='BJ0056'
AND A.DIVISIONCODE='0001'
AND A.COMPANYCODE=M.COMPANYCODE
AND A.COMPANYCODE=V.COMPANYCODE
AND A.DIVISIONCODE=V.DIVISIONCODE
AND A.YEARCODE='2020-2021'
AND TO_NUMBER(A.YEARMONTH)=TO_NUMBER(TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM'))


SELECT * FROM PISMONTHATTENDANCE
WHERE OT_HRS >0



 SELECT * FROM PISCOMPONENTASSIGNMENT
     WHERE COMPANYCODE='BJ0056'
         AND DIVISIONCODE='0001'
         AND TRANSACTIONTYPE='ATTENDANCE'
         AND OEPF >0
          AND YEARMONTH='202010'
         
         AND WORKERSERIAL||YEARMONTH IN (
             SELECT WORKERSERIAL||MAX(YEARMONTH) FROM PISCOMPONENTASSIGNMENT
             WHERE COMPANYCODE='BJ0056' AND DIVISIONCODE='0001'
                 AND TO_NUMBER(YEARMONTH)<=TO_NUMBER(TO_CHAR(TO_DATE('01/08/2020','DD/MM/YYYY'),'YYYYMM'))
                 AND TRANSACTIONTYPE='ATTENDANCE'
             GROUP BY WORKERSERIAL
  
 
 
 
            
SELECT EMP_CODE TOKENNO FROM BJM_BANK_LOAN             
MINUS
SELECT TOKENNO FROM LOANTRANSACTION
WHERE TOKENNO IN 
(
    SELECT DISTINCT EMP_CODE FROM BJM_BANK_LOAN
)
AND LOANCODE='BL'
AND LOANDATE='01-APR-2020'

SELECT * FROM BJM_BANK_LOAN
WHERE EMP_CODE IN (
SELECT EMP_CODE TOKENNO FROM BJM_BANK_LOAN             
MINUS
SELECT TOKENNO FROM LOANTRANSACTION
WHERE TOKENNO IN 
(
    SELECT DISTINCT EMP_CODE FROM BJM_BANK_LOAN
)
AND LOANCODE='BL'
AND LOANDATE='01-APR-2020'
)


SELECT * FROM LOANTRANSACTION
WHERE TOKENNO IN (
SELECT EMP_CODE TOKENNO FROM BJM_BANK_LOAN             
MINUS
SELECT TOKENNO FROM LOANTRANSACTION
WHERE TOKENNO IN 
(
    SELECT DISTINCT EMP_CODE FROM BJM_BANK_LOAN
)
AND LOANCODE='BL'
AND LOANDATE='01-APR-2020'
)



SELECT 
'UPDATE LOANTRANSACTION SET ACTUALLOANAMOUNT = '||ACTUAL_LN_AMT||' WHERE TOKENNO='''||TOKENNO||''' AND LOANCODE=''BL'' AND LOANDATE=''01-APR-2020'';' CC
FROM ( 

SELECT A.TOKENNO,A.AMOUNT, A.ACTUALLOANAMOUNT,B.ACTUAL_LN_AMT,A.ACTUALLOANDATE, B.ACTUAL_LN_DT FROM LOANTRANSACTION A, BJM_BANK_LOAN B
WHERE TOKENNO IN 
(
    SELECT DISTINCT EMP_CODE FROM BJM_BANK_LOAN
)
AND LOANCODE='BL'
AND LOANDATE='01-APR-2020'
AND A.TOKENNO=B.EMP_CODE

)

UPDATE 


CREATE TABLE LOANTRANSACTION_181120 AS
SELECT * FROM LOANTRANSACTION


SELECT 
'UPDATE LOANTRANSACTION SET ACTUALLOANAMOUNT = '||25000||' WHERE TOKENNO='''||00660||''' AND LOANCODE=''BL'' AND LOANDATE=''01-APR-2020'';'
FROM DUAL

-------------------------------------------------------------------------------------------