EXEC PROC_PFSTATUS('2020-2021','NJ0002','0010','01/02/2021','28/02/2021','ALL')


~PF ACCOUNTS/Pages/Report/Transaction/rpt_PFSTATUS.rdlc~GTT_PFSTATUS


 INSERT INTO GTT_PFSTATUS 
 
 
SELECT '2020-2021' YEARCODE, A.PFNO, B.EMPLOYEENAME, D.COMPANYNAME, E.DIVISIONNAME, 
SUM(OB_PF_E) OB_PF_E, SUM(OB_PF_C) OB_PF_C, SUM(OB_VPF) OB_VPF,
SUM(LN_PF_E) LN_PF_E, SUM(LN_PF_C) LN_PF_C, SUM(LN_VPF) LN_VPF, 
SUM(SAL_PF_E) CONT_PF_E, SUM(SAL_PF_C) CONT_PF_C, SUM(SAL_VPF) CONT_VPF,
SUM(INT_PF_E) INT_PF_E, SUM(INT_PF_C) INT_PF_C, SUM(INT_VPF) INT_VPF,
SUM(CB_PF_E)+ SUM(INT_PF_E) CB_PF_E, SUM(CB_PF_C) + SUM(INT_PF_C) CB_PF_C, SUM(CB_VPF) + SUM(INT_VPF) CB_VPF,
B.PFSETTLEMENTDATE ,C.LOANBALANCE, 
F.PFBALANCE, F.OTHEREARNING, F.PFLOANCAPITALBAL, F.PFLOANINTERESTBAL, F.OTHERDEDUCTION , F.NETPAYABLE AS SETTLEMENTAMOUNT , 'As on 28/02/2021', B.TOKENNO
FROM 
(
    SELECT PFNO,
    CASE WHEN TRANSACTIONTYPE = 'PF INTEREST OPENING BALANCE' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  OB_PF_E,
    CASE WHEN TRANSACTIONTYPE = 'PF INTEREST OPENING BALANCE' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  OB_PF_C,
    CASE WHEN TRANSACTIONTYPE = 'PF INTEREST OPENING BALANCE' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  OB_VPF,
    0  LN_PF_E,
    0  LN_PF_C,
    0  LN_VPF,
    0  SAL_PF_E,
    0  SAL_PF_C,
    0  SAL_VPF,
    CASE WHEN TRANSACTIONTYPE = 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'PF_E' THEN NVL(INT_AMT,0) ELSE 0 END  INT_PF_E,
    CASE WHEN TRANSACTIONTYPE = 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'PF_C' THEN NVL(INT_AMT,0) ELSE 0 END  INT_PF_C,
    CASE WHEN TRANSACTIONTYPE = 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'VPF' THEN NVL(INT_AMT,0) ELSE 0 END  INT_VPF,
    0  CB_PF_E,
    0  CB_PF_C,
    0  CB_VPF
    FROM PFTRANSACTIONDETAILS
    WHERE YEARCODE = '2020-2021' 
    UNION ALL
    SELECT PFNO,
    CASE WHEN TRANSACTIONTYPE = 'SALARY' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  OB_PF_E,
    CASE WHEN TRANSACTIONTYPE = 'SALARY' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  OB_PF_C,
    CASE WHEN TRANSACTIONTYPE = 'SALARY' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  OB_VPF,
    CASE WHEN TRANSACTIONTYPE = 'LOAN' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  LN_PF_E,
    CASE WHEN TRANSACTIONTYPE = 'LOAN' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  LN_PF_C,
    CASE WHEN TRANSACTIONTYPE = 'LOAN' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  LN_VPF,
    0  SAL_PF_E,
    0  SAL_PF_C,
    0  SAL_VPF,
    0  INT_PF_E,
    0  INT_PF_C,
    0  INT_VPF,
    CASE WHEN TRANSACTIONTYPE <> 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  CB_PF_E,
    CASE WHEN TRANSACTIONTYPE <> 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  CB_PF_C,
    CASE WHEN TRANSACTIONTYPE <> 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  CB_VPF
    FROM PFTRANSACTIONDETAILS
    WHERE YEARCODE = '2020-2021' 
      AND STARTDATE <TO_DATE('01/02/2021','DD/MM/YYYY') 
    UNION ALL
    SELECT PFNO,
    0  OB_PF_E,
    0  OB_PF_C,
    0  OB_VPF,
    CASE WHEN TRANSACTIONTYPE = 'LOAN' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  LN_PF_E,
    CASE WHEN TRANSACTIONTYPE = 'LOAN' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  LN_PF_C,
    CASE WHEN TRANSACTIONTYPE = 'LOAN' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  LN_VPF,
    CASE WHEN TRANSACTIONTYPE = 'SALARY' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  SAL_PF_E,
    CASE WHEN TRANSACTIONTYPE = 'SALARY' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  SAL_PF_C,
    CASE WHEN TRANSACTIONTYPE = 'SALARY' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  SAL_VPF,
    0  INT_PF_E,
    0  INT_PF_C,
    0  INT_VPF,
    CASE WHEN TRANSACTIONTYPE <> 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'PF_E' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  CB_PF_E,
    CASE WHEN TRANSACTIONTYPE <> 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'PF_C' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  CB_PF_C,
    CASE WHEN TRANSACTIONTYPE <> 'PF INTEREST CALCULATION' AND COMPONENTCODE = 'VPF' THEN NVL(COMPONENTAMOUNT,0) ELSE 0 END  CB_VPF
    FROM PFTRANSACTIONDETAILS
    WHERE YEARCODE = '2020-2021' 
      AND STARTDATE >=TO_DATE('01/02/2021','DD/MM/YYYY') 
      AND ENDDATE <=TO_DATE('28/02/2021','DD/MM/YYYY') 
) A, PFEMPLOYEEMASTER B, COMPANYMAST D, DIVISIONMASTER E, 
( 
    SELECT A.PFNO,A.LOANCODE,A.LOANDATE,A.AMOUNT LOAN_AMT,B.AMOUNT REALISE_AMT,NVL(A.AMOUNT,0) - NVL(B.AMOUNT,0) LOANBALANCE 
    FROM 
    (
        SELECT PFNO, LOANCODE, LOANDATE, CASE WHEN NVL(CAPITALBALANCEAMOUNT,0) > NVL(AMOUNT,0) THEN CAPITALBALANCEAMOUNT ELSE AMOUNT END AMOUNT  
        FROM PFLOANTRANSACTION 
        WHERE COMPANYCODE = 'NJ0002' 
        AND DIVISIONCODE = '0010'  
    ) A, 
    ( 
        SELECT PFNO,LOANCODE,LOANDATE, 
        SUM(CASE WHEN TRANSACTIONTYPE IN ('CAPITAL', 'REPAYCAP','REPAYINT', 'INTEREST') 
        THEN AMOUNT ELSE NVL(REPAYCAPITAL,0) + nvl(REPAYINTEREST,0) END) AS AMOUNT
        FROM PFLOANBREAKUP
        WHERE COMPANYCODE = 'NJ0002' 
        AND DIVISIONCODE = '0010'  
        AND PAIDON <= TO_DATE('28/02/2021','DD/MM/YYYY') 
        GROUP BY PFNO,LOANCODE,LOANDATE   
    ) B,   
    ( 
        SELECT LOANCODE 
          FROM PFLOANMASTER 
         WHERE COMPANYCODE = 'NJ0002' 
           AND DIVISIONCODE = '0010' 
           AND REFUNDTYPE = 'REFUNDABLE' 
    ) C 
    WHERE A.PFNO = B.PFNO (+) 
    AND A.LOANCODE = B.LOANCODE (+) 
    AND A.LOANDATE = B.LOANDATE (+) 
    AND A.LOANCODE = C.LOANCODE 
    AND A.LOANDATE = 
    ( 
        SELECT MAX(LOANDATE) 
        FROM PFLOANTRANSACTION 
        WHERE PFNO = A.PFNO 
        AND LOANCODE = A.LOANCODE 
        AND LOANDATE <= TO_DATE('28/02/2021','DD/MM/YYYY') 
    )    
) C , 
( 
    SELECT COMPANYCODE, DIVISIONCODE, YEARCODE, PFNO, NVL(PFBALANCE,0) PFBALANCE, NVL(OTHEREARNING,0) OTHEREARNING, 
         NVL(PFLOANCAPITALBAL,0) PFLOANCAPITALBAL , NVL(PFLOANINTERESTBAL,0) PFLOANINTERESTBAL,  
         NVL(OTHERDEDUCTION,0) OTHERDEDUCTION , NVL(NETPAYABLE,0) NETPAYABLE 
      FROM PFSETTLEMENT 
     WHERE COMPANYCODE = 'NJ0002' 
       AND DIVISIONCODE  = '0010' 
)F 
WHERE A.PFNO = B.PFNO 
AND A.PFNO = C.PFNO (+) 
AND B.COMPANYCODE ='NJ0002' 
AND B.DIVISIONCODE ='0010' 
AND B.COMPANYCODE = D.COMPANYCODE 
AND B.DIVISIONCODE = E.DIVISIONCODE 
AND B.COMPANYCODE = E.COMPANYCODE 
AND B.COMPANYCODE = F.COMPANYCODE (+) 
AND B.DIVISIONCODE = F.DIVISIONCODE  (+)
AND B.PFNO = F.PFNO (+)  
GROUP BY A.PFNO, B.EMPLOYEENAME, B.PFSETTLEMENTDATE ,C.LOANBALANCE, D.COMPANYNAME, E.DIVISIONNAME ,F.PFBALANCE, F.OTHEREARNING, F.PFLOANCAPITALBAL,
         F.PFLOANINTERESTBAL, F.OTHERDEDUCTION , F.NETPAYABLE , B.TOKENNO
ORDER BY A.PFNO

SELECT * FROM PFLOANTRANSACTION
WHERE TOKENNO='01370'


20330


SELECT * FROM PFLOANBREAKUP
WHERE TOKENNO='01370'
AND TRANSACTIONTYPE='CAPITAL'


SELECT * FROM PFLOANBREAKUP
WHERE TOKENNO='01370'
AND TRANSACTIONTYPE='INTEREST'

SELECT * FROM PFLOANBREAKUP
WHERE TOKENNO='01370'
AND TRANSACTIONTYPE='CAPITAL'


SELECT SUM(AMOUNT) FROM PFLOANBREAKUP
WHERE TOKENNO='01370'
AND TRANSACTIONTYPE='INTEREST'

20330

2220


--------------------------------------------------------------------------------
SELECT A.PFNO,A.LOANCODE,A.LOANDATE,A.AMOUNT LOAN_AMT,B.AMOUNT REALISE_AMT,NVL(A.AMOUNT,0) - NVL(B.AMOUNT,0) LOANBALANCE 
FROM 
(
    SELECT PFNO, LOANCODE, LOANDATE, CASE WHEN NVL(CAPITALBALANCEAMOUNT,0) > NVL(AMOUNT,0) THEN CAPITALBALANCEAMOUNT ELSE AMOUNT END AMOUNT  
    FROM PFLOANTRANSACTION 
    WHERE COMPANYCODE = 'NJ0002' 
    AND DIVISIONCODE = '0010'  
    AND TOKENNO='00061' --'01370'
) A, 
( 
    SELECT PFNO,LOANCODE,LOANDATE, 
    SUM(CASE WHEN TRANSACTIONTYPE IN ('CAPITAL', 'REPAYCAP')  --,'REPAYINT', 'INTEREST'
    THEN AMOUNT ELSE NVL(REPAYCAPITAL,0) + nvl(REPAYINTEREST,0) END) AS AMOUNT
    FROM PFLOANBREAKUP
    WHERE COMPANYCODE = 'NJ0002' 
    AND DIVISIONCODE = '0010'  
    AND PAIDON <= TO_DATE('28/02/2021','DD/MM/YYYY') 
    GROUP BY PFNO,LOANCODE,LOANDATE   
) B,   
( 
    SELECT LOANCODE 
      FROM PFLOANMASTER 
     WHERE COMPANYCODE = 'NJ0002' 
       AND DIVISIONCODE = '0010' 
       AND REFUNDTYPE = 'REFUNDABLE' 
) C 
WHERE A.PFNO = B.PFNO (+) 
AND A.LOANCODE = B.LOANCODE (+) 
AND A.LOANDATE = B.LOANDATE (+) 
AND A.LOANCODE = C.LOANCODE 
AND A.LOANDATE = 
( 
    SELECT MAX(LOANDATE) 
    FROM PFLOANTRANSACTION 
    WHERE PFNO = A.PFNO 
    AND LOANCODE = A.LOANCODE 
    AND LOANDATE <= TO_DATE('28/02/2021','DD/MM/YYYY') 
)
    

--------------------------------------------------------------------------------

