
insert into wpscashotpaymentdetails@WPS_2_KIOSK
select * from wpscashotpaymentdetails

select * from sys_parameter
WHERE PARAMETER_NAME='KIOSK DBLINK'



select DISTINCT PROCEDURE_NAME from WPSWAGESPROCESSTYPE_PHASE

PRCWPS_COMPONENT_AFTERSAVE

PROC_WPSDAILYPROCESS_TRANSFER


PROC_WPSDAILYPROCESS_TRANSFER

PROC_WPSWAGESPROCESS_UPDATE

PROC_WPSWAGESPROCESS_INSERT


SELECT * FROM WPSWAGESDETAILS
WHERE FORTNIGHTSTARTDATE='16-DEC-20'
--1600

EXEC prcWPS_Wages_Process('WAGES PROCESS','0003','0032','2020-2021','SWT','16/12/2020','31/12/2020','') 

SELECT * FROM WPS_ERROR_LOG


DELETE FROM WPS_ERROR_LOG


PRCWPS_WAGES_PROCESS

PROC_WPSWAGES_OTHER_COMP_UPDT

PROC_WPSVIEWCREATION


EXEC prcWPS_Wages_Process('DAILY WAGES PROCESS','0003','0032','2020-2021','SWT','19/12/2020','19/12/2020','') 

SELECT * FROM WPSDAILYWAGESDETAILS
WHERE TOKENNO='HW7394G'

EXEC PROC_CASHOT_EXPORTTOKIOSK('0003','0032','16/12/2020','19/12/2020')

SELECT * FROM SYS_GBL_PROCOUTPUT_INFO


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%DAILY%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='01100507'

SELECT * FROM ROLEDETAILS
WHERE MENUCODE='01100412'

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''


SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE, AUDITTABLE)
 Values
('01100508', NULL, 'Cash OT Export To KIOSK', 'UTILITIES', 'CASH OT EXPORT TO KIOSK', 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'WPS', NULL, 
    '''0032''', '''0032''', NULL, 'WPS/Pages/Utilities/pgCashOTExportToKIOSK.aspx', NULL, 
    NULL, NULL, NULL, 'Y', NULL, 
    NULL, NULL, NULL);
COMMIT;

SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '01100508', 'Y', 'X', 'X', 
    'X', 'X', 'X', 'X', 'WPS', 
    '201903051523240001188468');
COMMIT;



SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE, AUDITTABLE)
 Values
   ('01100412', NULL, 'Daily Wages Process', 'PROCESS', 'DAILY WAGES PROCESS', 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'WPS', NULL, 
    NULL, '''0032''', NULL, 'WPS/Pages/Process/pgWPSDailyWagesProcess.aspx', NULL, 
    NULL, NULL, NULL, 'Y', NULL, 
    NULL, NULL, NULL);
COMMIT;

SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '01100412', 'Y', 'N', 'N', 
    'X', 'X', 'X', 'X', 'WPS', 
    '201504301142320000273797');
COMMIT;
