DROP TABLE WPSCASHOTPAYMENTDETAILS

CREATE TABLE WPSCASHOTPAYMENTDETAILS
(
    COMPANYCODE VARCHAR2(10) NOT NULL,
    DIVISIONCODE VARCHAR2(10) NOT NULL,
    PAYMENTFROMDATE DATE NOT NULL,
    PAYMENTTODATE DATE NOT NULL,
    TOKENNO VARCHAR2(10) NOT NULL,
    WORKERSERIAL VARCHAR2(10) NOT NULL,
    OTHOURS NUMBER(10,2),
    OTAMOUNT NUMBER(10,2),
    ESI_OT NUMBER(10,2),
    NETPAY NUMBER(12,2),
    PAYMENTLOCK VARCHAR2(1) DEFAULT 'N',
    ISTRANSFER VARCHAR2(1) DEFAULT 'N'
)

SELECT * FROM WPSDAILYWAGESDETAILS

SELECT WM_CONCAT(COLUMN_NAME) FROM COLS
WHERE TABLE_NAME = 'WPSCASHOTPAYMENTDETAILS'


SELECT WM_CONCAT(COLUMN_NAME) FROM COLS
WHERE TABLE_NAME = 'WPSCASHOTPAYMENTDETAILS'

INSERT INTO WPSCASHOTPAYMENTDETAILS
SELECT COMPANYCODE,DIVISIONCODE,FORTNIGHTSTARTDATE PAYMENTFROMDATE, FORTNIGHTENDDATE PAYMENTTODATE,
TOKENNO, WORKERSERIAL, OVERTIMEHOURS OTHOURS,CASHOT_AMOUNT OTAMOUNT,DAILY_ESI ESI_OT, 
ACTUALPAYBLEAMOUNT NETPAY,'N' PAYMENTLOCK,'N' ISTRANSFER 
FROM WPSDAILYWAGESDETAILS

SELECT * FROM WPSCASHOTPAYMENTDETAILS

WHERE NETPAY IS NULL



SELECT * FROM MAST
WHERE TOKENNO IN ('36469')




SELECT  ROUND((ROUND((NVL(MAST.ADHOCRATE,0)+NVL(MAST.FIXEDBASIC,0) + NVL(MAST.ADDLBASIC_RATE,0) + NVL(MAST.DARATE,0))/208,2))*8,0) FROM MAST
WHERE TOKENNO IN ('36469')



WHERE COMPO

 ROUND((ROUND((NVL(MAST.ADHOCRATE,0)+NVL(MAST.FIXEDBASIC,0) + NVL(MAST.ADDLBASIC_RATE,0) + NVL(MAST.DARATE,0))/208,2))*ATTN.OVERTIMEHOURS,0)
 
 
 
 
 EXEC PROC_CASHOT_EXPORTTOKIOSK('0002','0022','16/12/2020',''16/12/2020)