CREATE TABLE WPSCASHOTPAYMENTDETAILS
(
    COMPANYCODE VARCHAR2(10) NOT NULL,
    DIVISIONCODE VARCHAR2(10) NOT NULL,
    PAYMENTFROMDATE DATE,
    PAYMENTTODATE DATE,
    OTHOURS NUMBER(10,2),
    OTAMOUNT NUMBER(10,2),
    ESI_OT NUMBER(10,2),
    NETPAY NUMBER(12,2),
    PAYMENTLOCK VARCHAR2(1) DEFAULT 'N',
    ISTRANSFER VARCHAR2(1) DEFAULT 'N'
)

SELECT * FROM WPSDAILYWAGESDETAILS