
COMPANYCODE~DIVISIONCODE~YEARCODE~YEARMONTH~PFMODULE~PFDIVISION~OPERATIONMODE~USERNAME~

GBL_PF_SALARY_POSTING

COMPANYCODE~DIVISIONCODE~DEPARTMENTCODE~SECTIONCODE~SHIFTCODE~YEARCODE~DYNAMIC~


SELECT A.PFNO, E.EMPLOYEENAME EMPLOYEENAME, A.PF_E, A.PF_C, A.VPF, A.LOANPRINCIPLE, A.LOANINTEREST, 
E.COMPANYCODE, E.DIVISIONCODE, <<YEARCODE>> YEARCODE, A.YEARMONTH, <<PFMODULE>> PFMODULE, <<PFDIVISION>> PFDIVISION, A.WORKERSERIAL, 
A.TOKENNO, NULL ACCODE, NULL CHEQUENO, NULL CHEQUEDATE, NULL VOUCHERDATE, NULL DRAWNON, NULL REFVOUCHERNO, NULL NARRATION, 
NULL SYSROWID, <<OPERATIONMODE>> OPERATIONMODE, <<USERNAME>> USERNAME 
FROM 
( 
    SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, SUM(PF_E) PF_E, SUM(PF_C) PF_C, SUM(VPF) VPF, SUM(CAPITAL) LOANPRINCIPLE, SUM(INTEREST) LOANINTEREST 
    FROM 
    ( 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, COMPONENTAMOUNT PF_E, 0 PF_C, 0 VPF, 0 CAPITAL, 0 INTEREST 
        FROM PFTRANSACTIONDETAILS 
        WHERE COMPANYCODE=<<COMPANYCODE>> 
        AND DIVISIONCODE=<<DIVISIONCODE>>
        AND YEARCODE=<<YEARCODE>>
        AND TRANSACTIONTYPE='SALARY' 
        AND COMPONENTCODE='PF_E' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, COMPONENTAMOUNT PF_C, 0 VPF, 0 CAPITAL, 0 INTEREST 
        FROM PFTRANSACTIONDETAILS 
        WHERE COMPANYCODE=<<COMPANYCODE>> 
        AND DIVISIONCODE=<<DIVISIONCODE>>
        AND YEARCODE=<<YEARCODE>>
        AND TRANSACTIONTYPE='SALARY' 
        AND COMPONENTCODE='PF_C' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, 0 PF_C, COMPONENTAMOUNT VPF, 0 CAPITAL, 0 INTEREST 
        FROM PFTRANSACTIONDETAILS 
        WHERE COMPANYCODE=<<COMPANYCODE>> 
        AND DIVISIONCODE=<<DIVISIONCODE>>
        AND YEARCODE=<<YEARCODE>>
        AND TRANSACTIONTYPE='SALARY' 
        AND COMPONENTCODE='VPF' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, 0 PF_C, 0 VPF, AMOUNT CAPITAL, 0 INTEREST 
        FROM PFLOANBREAKUP 
        WHERE COMPANYCODE=<<COMPANYCODE>> 
        AND DIVISIONCODE=<<DIVISIONCODE>>
        AND YEARCODE=<<YEARCODE>>
        AND TRANSACTIONTYPE='CAPITAL' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, 0 PF_C, 0 VPF, 0 CAPITAL, AMOUNT INTEREST 
        FROM PFLOANBREAKUP 
        WHERE COMPANYCODE=<<COMPANYCODE>> 
        AND DIVISIONCODE=<<DIVISIONCODE>>
        AND YEARCODE=<<YEARCODE>>
        AND TRANSACTIONTYPE='INTEREST'  
    )  
    GROUP BY TOKENNO, WORKERSERIAL, PFNO, YEARMONTH 
) A,  PFEMPLOYEEMASTER E --WORKERVIEW E 
WHERE A.WORKERSERIAL=E.WORKERSERIAL 
AND E.COMPANYCODE=<<COMPANYCODE>> 
AND E.DIVISIONCODE=<<DIVISIONCODE>>
AND A.YEARMONTH=<<YEARMONTH>>
ORDER BY PFNO 


QUERYMASTER


SELECT FN_GET_FORM_QRY_WEB (37, 'COMPANYCODE:NJ0002~DIVISIONCODE:0010~YEARCODE:2020-2021~YEARMONTH:202004~PFMODULE:ALL~PFDIVISION:0001~OPERATIONMODE:A~USERNAME:SWT~' ) FROM DUAL 


SELECT A.PFNO, E.EMPLOYEENAME EMPLOYEENAME, A.PF_E, A.PF_C, A.VPF, A.LOANPRINCIPLE, A.LOANINTEREST, 
E.COMPANYCODE, E.DIVISIONCODE, '2020-2021' YEARCODE, A.YEARMONTH, 'ALL' PFMODULE, '0001' PFDIVISION, A.WORKERSERIAL, 
A.TOKENNO, NULL ACCODE, NULL CHEQUENO, NULL CHEQUEDATE, NULL VOUCHERDATE, NULL DRAWNON, NULL REFVOUCHERNO, NULL NARRATION, 
NULL SYSROWID, 'A' OPERATIONMODE, 'SWT' USERNAME 
FROM 
( 
    SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, SUM(PF_E) PF_E, SUM(PF_C) PF_C, SUM(VPF) VPF, SUM(CAPITAL) LOANPRINCIPLE, SUM(INTEREST) LOANINTEREST 
    FROM 
    ( 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, COMPONENTAMOUNT PF_E, 0 PF_C, 0 VPF, 0 CAPITAL, 0 INTEREST 
        FROM PFTRANSACTIONDETAILS 
        WHERE COMPANYCODE='NJ0002' 
        AND DIVISIONCODE='0010'
        AND YEARCODE='2020-2021'
        AND TRANSACTIONTYPE='SALARY' 
        AND COMPONENTCODE='PF_E' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, COMPONENTAMOUNT PF_C, 0 VPF, 0 CAPITAL, 0 INTEREST 
        FROM PFTRANSACTIONDETAILS 
        WHERE COMPANYCODE='NJ0002' 
        AND DIVISIONCODE='0010'
        AND YEARCODE='2020-2021'
        AND TRANSACTIONTYPE='SALARY' 
        AND COMPONENTCODE='PF_C' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, 0 PF_C, COMPONENTAMOUNT VPF, 0 CAPITAL, 0 INTEREST 
        FROM PFTRANSACTIONDETAILS 
        WHERE COMPANYCODE='NJ0002' 
        AND DIVISIONCODE='0010'
        AND YEARCODE='2020-2021'
        AND TRANSACTIONTYPE='SALARY' 
        AND COMPONENTCODE='VPF' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, 0 PF_C, 0 VPF, AMOUNT CAPITAL, 0 INTEREST 
        FROM PFLOANBREAKUP 
        WHERE COMPANYCODE='NJ0002' 
        AND DIVISIONCODE='0010'
        AND YEARCODE='2020-2021'
        AND TRANSACTIONTYPE='CAPITAL' 
        UNION ALL 
        SELECT TOKENNO, WORKERSERIAL, PFNO, YEARMONTH, 0 PF_E, 0 PF_C, 0 VPF, 0 CAPITAL, AMOUNT INTEREST 
        FROM PFLOANBREAKUP 
        WHERE COMPANYCODE='NJ0002' 
        AND DIVISIONCODE='0010'
        AND YEARCODE='2020-2021'
        AND TRANSACTIONTYPE='INTEREST'  
    )  
    GROUP BY TOKENNO, WORKERSERIAL, PFNO, YEARMONTH 
) A,  PFEMPLOYEEMASTER E --WORKERVIEW E 
WHERE A.WORKERSERIAL=E.WORKERSERIAL 
AND E.COMPANYCODE='NJ0002' 
AND E.DIVISIONCODE='0010'
AND A.YEARMONTH='202004'
ORDER BY PFNO 



SELECT * FROM MENUMASTER_RND
WHERE MENUDESC LIKE 'Re Log%'