CREATE OR REPLACE FORCE VIEW VW_RUKA_STOCK_DETAILS_DUMMY
(
   COMPANYCODE,
   DIVISIONCODE,
   TRANSACTIONDATE,
   ORDERNO,
   ORDERDATE,
   MKTGRDCODE,
   MILLGRDCODE,
   ORDERSERIALNO,
   BALES_ORDERED,
   QTY_ORDERED,
   BALES_RECEIVED,
   QTY_RECEIVED,
   BALES_CANC_ADJ,
   QTY_CANC_ADJ
)
AS
   SELECT   POM.COMPANYCODE,
            POM.DIVISIONCODE,
            POM.ORDERDATE AS TRANSACTIONDATE,
            POM.ORDERNO,
            POM.ORDERDATE,
            POD.MKTGRDCODE,
            POD.MILLGRDCODE,
            POD.ORDERSERIALNO,
            POD.NOOFBALES AS BALES_ORDERED,
            POD.WEIGHTINQT AS QTY_ORDERED,
            0 AS BALES_RECEIVED,
            0.00 AS QTY_RECEIVED,
            0 AS BALES_CANC_ADJ,
            0.00 AS QTY_CANC_ADJ
     FROM   JUTEPURCHASEORDERMASTER POM, JUTEPURCHASEORDERDETAILS POD
    WHERE       POM.COMPANYCODE = POD.COMPANYCODE
            AND POM.DIVISIONCODE = POD.DIVISIONCODE
            AND POM.ORDERNO = POD.ORDERNO
            --            AND POM.ORDERNO NOT LIKE '%DUM%'
            AND NVL (POM.LOCKED, 'NO') = 'YES'
   UNION ALL
   SELECT   MRM.COMPANYCODE,
            MRM.DIVISIONCODE,
            MRM.MILLRCPTDATE AS TRANSACTIONDATE,
            MRM.ORDERNO,
            MRM.ORDERDATE,
            MRD.MKTGRDCODEPO AS MKTGRDCODE,
            MRD.MILLGRDCODEPO AS MILLGRDCODE,
            MRD.ORDERSERIALNO,
            0 AS BALES_ORDERED,
            0.00 AS QTY_ORDERED,
            MRD.NOOFBALES_ASPERPO AS BALES_RECEIVED,
            MRD.ACTUALWTINQT AS QTY_RECEIVED,
            0 AS BALES_CANC_ADJ,
            0.00 AS QTY_CANC_ADJ
     FROM   JUTEMILLRECEIPTMAST MRM, JUTEMILLRECEIPTDETAILS MRD
    WHERE       MRM.COMPANYCODE = MRD.COMPANYCODE
            AND MRM.DIVISIONCODE = MRD.DIVISIONCODE
            AND MRM.MILLRCPTNO = MRD.MILLRCPTNO
   UNION ALL
   SELECT   POM.COMPANYCODE,
            POM.DIVISIONCODE,
            POD.TRANSACTIONDATE AS TRANSACTIONDATE,
            POM.ORDERNO,
            POD.ORDERDATE,
            POD.MKTGRDCODE,
            POD.MILLGRDCODE,
            POD.ORDERSERIALNO,
            0 AS BALES_ORDERED,
            0.00 AS QTY_ORDERED,
            0 AS BALES_RECEIVED,
            0.00 AS QTY_RECEIVED,
            POD.NOOFBALES_ADJUSTED AS BALES_CANC_ADJ,
            POD.WEIGHTINQT_ADJUSTED AS QTY_CANC_ADJ
     FROM   JUTEPURCHASEORDERMASTER POM, JUTEPURCHASEORDERDETAILS_CANC POD
    WHERE       POM.COMPANYCODE = POD.COMPANYCODE
            AND POM.DIVISIONCODE = POD.DIVISIONCODE
            AND POM.ORDERNO = POD.ORDERNO
--            AND POM.ORDERNO NOT LIKE '%DUM%';;

