DROP TABLE GTT_PISPAYSLIP_ED_BIRLA CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_PISPAYSLIP_ED_BIRLA
(
  COMPANYCODE         VARCHAR2(10 BYTE),
  DIVISIONCODE        VARCHAR2(10 BYTE),
  YEARMONTH           VARCHAR2(10 BYTE),
  UNITCODE            VARCHAR2(10 BYTE),
  DEPARTMENTCODE      VARCHAR2(10 BYTE),
  CATEGORYCODE        VARCHAR2(10 BYTE),
  GRADECODE           VARCHAR2(10 BYTE),
  WORKERSERIAL        VARCHAR2(10 BYTE),
  TOKENNO             VARCHAR2(20 BYTE),
  COMPONENTCODE       VARCHAR2(30 BYTE),
  COMPONENTVALUE      NUMBER(10,2),
  COMPONENTSHORTNAME  VARCHAR2(75 BYTE),
  PHASE               NUMBER(4),
  CALCULATIONINDEX    NUMBER(10),
  COMPONENTTYPE       VARCHAR2(50 BYTE),
  COMPANYNAME         VARCHAR2(100 BYTE),
  DIVISIONNAME        VARCHAR2(100 BYTE),
  REPORTHEADER        VARCHAR2(150 BYTE),
  COMP_LOGO           VARCHAR2(550 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


