
DROP TABLE CJIL_WEB.WPSWORKERWISERATEUPDATE CASCADE CONSTRAINTS;

CREATE TABLE CJIL_WEB.WPSWORKERWISERATEUPDATE
(
  COMPANYCODE         VARCHAR2(10 BYTE)         NOT NULL,
  DIVISIONCODE        VARCHAR2(10 BYTE)         NOT NULL,
  WORKERSERIAL        VARCHAR2(10 BYTE)         NOT NULL,
  TOKENNO             VARCHAR2(10 BYTE),
  EFFECTIVEDATE       DATE                      NOT NULL,
  DEPARTMENTCODE      VARCHAR2(10 BYTE),
  WORKERCATEGORYCODE  VARCHAR2(10 BYTE),
  FBASIC              NUMBER(18,5)              DEFAULT 0,
  FBASIC_PEICERT      NUMBER(18,5)              DEFAULT 0,
  DA                  NUMBER(18,2)              DEFAULT 0,
  ADHOC               NUMBER(18,2)              DEFAULT 0,
  ATN_INCENTIVE       NUMBER(11,2)              DEFAULT 0,
  USERNAME            VARCHAR2(100 BYTE)        NOT NULL,
  SYSROWID            VARCHAR2(50 BYTE)         NOT NULL,
  LASTMODIFIED        DATE                      DEFAULT SYSDATE,
  TSA                 NUMBER(18,2)              DEFAULT 0,
  NS_RT               NUMBER(11,5)              DEFAULT 0
);


 

DROP TABLE CJIL_WEB.WPSGRADEMASTER CASCADE CONSTRAINTS;

CREATE TABLE CJIL_WEB.WPSGRADEMASTER
(
  COMPANYCODE    VARCHAR2(10 BYTE)              NOT NULL,
  DIVISIONCODE   VARCHAR2(10 BYTE)              NOT NULL,
  GRADECODE      VARCHAR2(10 BYTE)              NOT NULL,
  GRADEDESC      VARCHAR2(50 BYTE),
  GRADEINCRRATE  NUMBER(18,4),
  USERNAME       VARCHAR2(100 BYTE)             NOT NULL,
  LASTMODIFIED   DATE                           DEFAULT SYSDATE,
  SYSROWID       VARCHAR2(50 BYTE)              NOT NULL
)