 EXEC PRC_PF_COMPONENT_SHARE('NJ0002','0010' ,'2021-2022','006670','MPL','09/04/2021','A')
  
 
 
    DELETE FROM GTT_LOANSANCTION_PRAM;
    
    
    SELECT *  FROM GTT_LOANSANCTION_PRAM;
 
 SELECT * FROM PFEMPLOYEEMASTER
 WHERE TOKENNO='83878'
 
 SELECT MAX(YEARCODE) FROM PFTRANSACTIONDETAILS WHERE YEARCODE <= '2021-2022' AND TRANSACTIONTYPE = 'PF INTEREST OPENING BALANCE'
 
 
 INSERT INTO GTT_LOANSANCTION_PRAM
(COMPANYCODE, DIVISIONCODE, YEARCODE,PFNO,TOKENNO ,
 WORKERSERIAL, LOANDATE, LOANCODE,PARAM_NAME,PF_E,PF_C , VPF,OTHER )
 
 
SELECT 'NJ0001' COMPANYCODE,'0010' DIVISIONCODE ,
'2021-2022' YEARCODE,'SP1901' PFNO,'83878' TOKENNO ,
'006670' WORKERSERIAL,TO_DATE('09/04/2021','DD/MM/YYYY') LOANDATE,'MPL' LOANCODE,PARAM_NAME,
NULL PF_E,NULL PF_C ,NULL VPF,NULL OTHER 
  FROM SYS_SWT_PF_LOAN_SANCTION_PARAM
WHERE LOANCODE='MPL'
order BY PIORITY_INDEX
    

SELECT * FROM SYS_SWT_PF_LOAN_SANCTION_PARAM
WHERE LOANCODE='MPL'


select decode(rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Ratio'' ')
FROM 
(  
    SELECT PARAMVALUE PERCENTAGE, 'PF_C' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_C_PERCENTAGE' AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
    union
    SELECT PARAMVALUE PERCENTAGE, 'PF_E' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_E_PERCENTAGE' AND   COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
    union
    SELECT PARAMVALUE PERCENTAGE, 'VPF'  COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='VPF_PERCENTAGE'  AND  COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
) X 


SELECT * FROM PFLOANSANCTIONPARAM
WHERE LOANCODE='MPL'