
INSERT INTO GTT_LOANSANCTION_PRAM
(COMPANYCODE, DIVISIONCODE, YEARCODE,PFNO,TOKENNO ,
 WORKERSERIAL, LOANDATE, LOANCODE,PARAM_NAME,PF_E,PF_C , VPF,OTHER )
 
SELECT 'NJ0002' COMPANYCODE,'0010' DIVISIONCODE ,
'2021-2022' YEARCODE,'SP1901' PFNO,'83878' TOKENNO ,
'006670' WORKERSERIAL,TO_DATE('09/04/2021','DD/MM/YYYY') LOANDATE,'MPL' LOANCODE,PARAM_NAME,
NULL PF_E,NULL PF_C ,NULL VPF,NULL OTHER 
  FROM SYS_SWT_PF_LOAN_SANCTION_PARAM
WHERE LOANCODE='MPL'
order BY PIORITY_INDEX


SELECT FN_ELIGIBLEFORPFL('NJ0002','0010','SP1901','MPL','09/04/2021') FROM DUAL

select decode(rtrim(xmlagg(xmlelement(e,x.componentcode||' = '||x.COMPONENTAMOUNT||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.componentcode||' = '||x.COMPONENTAMOUNT||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Actual Balance'' ')
FROM 
(
    SELECT COMPONENTCODE, SUM(COMPONENTAMOUNT) COMPONENTAMOUNT 
    FROM
    (
        SELECT COMPONENTCODE, COMPONENTAMOUNT FROM PFTRANSACTIONDETAILS
         WHERE COMPANYCODE='<<COMPANYCODE>>'
           --AND DIVISIONCODE='<<DIVISIONCODE>>' 
           AND YEARCODE='<<YEARCODE>>'
           AND YEARMONTH <= TO_CHAR(TO_NUMBER(TO_char(to_date('<<LOANDATE>>','DD/MM/YYYY'),'YYYYMM'))) --||CASE WHEN TO_NUMBER(TO_char(to_date('<<LOANDATE>>','DD/MM/YYYY'),'MM'))>=4 AND TO_char(to_date('<<LOANDATE>>','DD/MM/YYYY'),'MM')<=9 THEN '09' ELSE '03' END
           AND PFNO='<<PFNO>>'
           AND COMPONENTCODE<>'EPF'
         UNION ALL
        SELECT 'PF_E' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
         UNION ALL
        SELECT 'PF_C' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
         UNION ALL
        SELECT 'VPF' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
    )
    GROUP BY COMPONENTCODE 
) X


select decode(rtrim(xmlagg(xmlelement(e,x.componentcode||' = '||x.COMPONENTAMOUNT||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.componentcode||' = '||x.COMPONENTAMOUNT||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Actual Balance'' ')
FROM 
(
    SELECT COMPONENTCODE, SUM(COMPONENTAMOUNT) COMPONENTAMOUNT 
    FROM
    (
        SELECT COMPONENTCODE, COMPONENTAMOUNT FROM PFTRANSACTIONDETAILS
         WHERE COMPANYCODE='NJ0002'
           --AND DIVISIONCODE='0010' 
           AND YEARCODE= ( SELECT MAX(YEARCODE) FROM PFTRANSACTIONDETAILS WHERE YEARCODE <= '2021-2022' AND TRANSACTIONTYPE = 'PF INTEREST OPENING BALANCE')           
           AND YEARMONTH <= TO_CHAR(TO_NUMBER(TO_char(to_date('09/04/2021','DD/MM/YYYY'),'YYYYMM'))) --||CASE WHEN TO_NUMBER(TO_char(to_date('09/04/2021','DD/MM/YYYY'),'MM'))>=4 AND TO_char(to_date('09/04/2021','DD/MM/YYYY'),'MM')<=9 THEN '09' ELSE '03' END
           AND PFNO='SP1901'
           AND COMPONENTCODE<>'EPF'
         UNION ALL
        SELECT 'PF_E' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
         UNION ALL
        SELECT 'PF_C' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
         UNION ALL
        SELECT 'VPF' COMPONENTCODE, 0 COMPONENTAMOUNT FROM DUAL
    )
    GROUP BY COMPONENTCODE 
) X

select decode(rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Ratio'' ')
FROM 
(  
    SELECT PARAMVALUE PERCENTAGE, 'PF_C' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_C_PERCENTAGE' AND COMPANYCODE='<<COMPANYCODE>>' AND DIVISIONCODE='<<DIVISIONCODE>>' AND LOANCODE='<<LOANCODE>>'
    union
    SELECT PARAMVALUE PERCENTAGE, 'PF_E' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_E_PERCENTAGE' AND COMPANYCODE='<<COMPANYCODE>>' AND DIVISIONCODE='<<DIVISIONCODE>>' AND LOANCODE='<<LOANCODE>>'
    union
    SELECT PARAMVALUE PERCENTAGE, 'VPF'  COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='VPF_PERCENTAGE'  AND COMPANYCODE='<<COMPANYCODE>>' AND DIVISIONCODE='<<DIVISIONCODE>>' AND LOANCODE='<<LOANCODE>>'
) X 
select decode(rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),','),'',null, 'UPDATE GTT_LOANSANCTION_PRAM SET '||rtrim(xmlagg(xmlelement(e,x.COMPOMENT||' = '||x.PERCENTAGE||',') ).extract('//text()'),',')|| ' WHERE PARAM_NAME = ''Ratio'' ')
FROM 
(  
    SELECT PARAMVALUE PERCENTAGE, 'PF_C' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_C_PERCENTAGE' AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
    union
    SELECT PARAMVALUE PERCENTAGE, 'PF_E' COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='PF_E_PERCENTAGE' AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
    union
    SELECT PARAMVALUE PERCENTAGE, 'VPF'  COMPOMENT FROM PFLOANSANCTIONPARAM WHERE PARAMCODE='VPF_PERCENTAGE'  AND COMPANYCODE='NJ0002' AND DIVISIONCODE='0010' AND LOANCODE='MPL'
) X