SELECT * FROM WPSCASHOTPAYMENTDETAILS

SELECT * FROM TAB
WHERE TNAME LIKE '%UNREAL%'

SELECT * FROM WPSUNREALIZEDDATA

SELECT * FROM TAB
WHERE TNAME LIKE '%UNREAL%'


SELECT COMPANYCODE,DIVISIONCODE,YEARCODE,FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,WORKERSERIAL,
TOKENNO,COMPONENTCODE,COMPONENTAMOUNT,ACTUALAMOUNT,REFERENCE_FNEDATE,PAIDON,TRANTYPE,MODULE,
REMARKS,'SWT' USERNAME,SYS_GUID() SYSROSWID,SYSDATE LASTMODIFIED,NULL DOCNO,NULL DOCDATE,'KIOSK' TRAN_SOURCE 
FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
WHERE PAYMENTLOCK = 'Y'

PROC_CASHOT_IMPORTFROMKIOSK



PROC_CASHOT_EXPORTTOKIOSK


INSERT INTO  WPSUNREALIZEDDATA
(
    COMPANYCODE,DIVISIONCODE,YEARCODE,FORTNIGHTSTARTDATE,FORTNIGHTENDDATE,WORKERSERIAL,TOKENNO,
    COMPONENTCODE,COMPONENTAMOUNT,ACTUALAMOUNT,REFERENCE_FNEDATE,PAIDON,TRANTYPE,MODULE,REMARKS,
    USERNAME,SYSROSWID,LASTMODIFIED,DOCNO,DOCDATE,TRAN_SOURCE
)    


SELECT
COMPANYCODE,DIVISIONCODE,'2020-2021' YEARCODE,PAYMENTFROMDATE FORTNIGHTSTARTDATE,PAYMENTTODATE FORTNIGHTENDDATE,WORKERSERIAL,TOKENNO,
'CASHOT_AMT' COMPONENTCODE,NETPAY COMPONENTAMOUNT,NETPAY ACTUALAMOUNT,NULL REFERENCE_FNEDATE,PAYMENTDATE PAIDON,'UNREALIZED' TRANTYPE, 
'WPS' MODULE,'DATA IMPORT FROM CASH OT PAYMENT' REMARKS,'SWT' USERNAME,FN_GENERATE_SYSROWID SYSROSWID,SYSDATE LASTMODIFIED,
NULL DOCNO, NULL DOCDATE, NULL TRAN_SOURCE
FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND PAYMENTFROMDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTTODATE <= TO_DATE('25/12/2020','DD/MM/YYYY')

AND PAYMENTLOCK='Y'
AND ISTRANSFER='N'


select * from WPSUNREALIZEDDATA


EXEC PROC_CASHOT_IMPORTFROMKIOSK('0003','0032','16/12/2020','16/12/2021')

select * from SYS_GBL_PROCOUTPUT_INFO



--------------------------------------------------------------------------------


DELETE


SELECT FROM WPSUNREALIZEDDATA
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND FORTNIGHTSTARTDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND FORTNIGHTENDDATE <= TO_DATE('25/12/2020','DD/MM/YYYY')
AND COMPONENTCODE='CASHOT_AMT'
AND TRANTYPE= 'UNREALIZED'


UPDATE WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
SET ISTRANSFER='Y'
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND PAYMENTFROMDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTTODATE <= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTLOCK='Y'
AND ISTRANSFER='N'



SELECT COUNT(*)  
FROM WPSCASHOTPAYMENTDETAILS@WPS_2_KIOSK
WHERE COMPANYCODE='0003'
AND DIVISIONCODE='0032'
AND PAYMENTFROMDATE >= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTTODATE <= TO_DATE('25/12/2020','DD/MM/YYYY')
AND PAYMENTLOCK='Y'
AND ISTRANSFER='N'
