      INSERT INTO GTT_PISREIMBURSEMENT 
         
         SELECT A.COMPANYCODE, A.DIVISIONCODE,'2020-2021' YEARCODE,'2020-2021' FORYEARCODE,'202101' YEARMONTH,A.WORKERSERIAL,A.TOKENNO,
         A.EMPLOYEENAME,TO_CHAR(A.DATEOFJOIN,'DD/MM/YYYY') DATEOFJOIN ,     A.CATEGORYCODE, A.GRADECODE, 'LTA' COMPONENTCODE, 
         B.COMPONENTAMOUNT,'LTA'   TRANSACTIONTYPE,    'ADD' ADDLESS, 
         B.COMPONENTAMOUNT  BILLAMOUNT, NVL(D.PAIDAMOUNT,0) PAIDAMOUNT,'DETAILS' TRANTYPE,   
         (NVL(D2.PAIDAMOUNT,0)-NVL(D.PAIDAMOUNT,0)) AMOUNTTAKEN,NVL(C.LASTCOMPONENTAMOUNT,0) PREVCOMPONENTAMOUNT, (NVL(C.LASTCOMPONENTAMOUNT,0)-NVL(D3.PREVIOUSYRTAKEN,0)) PREVIOUSYRBALANCE,
         NVL(D3.PREVIOUSYRTAKEN,0)  PREVIOUSYRTAKEN,(B.COMPONENTAMOUNT + (NVL(C.LASTCOMPONENTAMOUNT,0)-NVL(D3.PREVIOUSYRTAKEN,0)) -NVL(D2.PAIDAMOUNT,0)) TOTALDUE,DECODE('A','A', DECODE('LTA', 'BONUS', B.COMPONENTAMOUNT ,0),NVL(D.PAIDAMOUNT,0))  AMOUNTCLAIMCURRENT,NVL(D4.AMOUNTCLAIMPREVIOUS,0) AMOUNTCLAIMPREVIOUS,
        (B.COMPONENTAMOUNT+(NVL(C.LASTCOMPONENTAMOUNT,0)-NVL(D3.PREVIOUSYRTAKEN,0)))-(NVL(D2.PAIDAMOUNT,0)) BALANCEAMOUNT , NVL(D5.LEAVEBALANCE,0)   LEAVEBALANCE , 0   LEAVEENCASHMENT  
         FROM PISEMPLOYEEMASTER A ,
         (
             SELECT A.WORKERSERIAL, BASIC, DECODE(B.TOKENNO,NULL,A.BASIC,ROUND((A.BASIC/B.YEARDAYS)*B.NOWORKDAYS,2)) COMPONENTAMOUNT FROM 
              (
                  SELECT P.COMPANYCODE, P.DIVISIONCODE,P.UNITCODE, P.GRADECODE, P.CATEGORYCODE, P.DEPARTMENTCODE, P.TOKENNO, P.WORKERSERIAL,  P.YEARMONTH , ASSIGN.BASIC BASIC
                  FROM PISCOMPONENTASSIGNMENT   P, PISASSIGN ASSIGN
                  WHERE 1=1 
                  AND P.TRANSACTIONTYPE='ASSIGNMENT' 
                  AND P.YEARMONTH =  
                  (
                      SELECT MAX(YEARMONTH)  YEARMONTH 
                      FROM PISCOMPONENTASSIGNMENT 
                      WHERE TOKENNO=P.TOKENNO
                      AND TRANSACTIONTYPE='ASSIGNMENT' 
                      AND COMPANYCODE='BT0104'
                      AND DIVISIONCODE='HO'
                      AND YEARMONTH >= DECODE('LTA','BONUS','201904','202004')
                      AND YEARMONTH <= '202101'
                  )-- TOKENNO WITH BASIC, YEARMONTH FOR LAST YEAR
                  AND P.COMPANYCODE=ASSIGN.COMPANYCODE(+)
                  AND P.DIVISIONCODE=ASSIGN.DIVISIONCODE(+)
                  AND P.YEARMONTH=ASSIGN.YEARMONTH  (+)    
                  AND P.WORKERSERIAL=ASSIGN.WORKERSERIAL  (+)    
              ) A,-- LAST YEAR COMPONENT AMOUNT 
              (
                  SELECT TOKENNO, WORKERSERIAL, DATEOFJOIN, (TRUNC(B.ENDDATE-A.DATEOFJOIN)+1) NOWORKDAYS, (TRUNC(B.ENDDATE-B.STARTDATE)+1) YEARDAYS 
                  FROM PISEMPLOYEEMASTER A,
                  (
                      SELECT STARTDATE, ENDDATE FROM FINANCIALYEAR
                      WHERE COMPANYCODE='BT0104'
                      AND DIVISIONCODE='HO'
                      AND YEARCODE='2020-2021'
                  ) B
                  WHERE DATEOFJOIN > B.STARTDATE
                  AND DATEOFJOIN < B.ENDDATE
              ) B
              WHERE A.WORKERSERIAL=B.WORKERSERIAL(+) --CALCULATE YEAR DAYS, NO OF DAYS WORKING FROM DATE OF JOINING FOR LAST YEAR
         ) B,  -- TOKENNO WITH BASIC, YEARMONTH
         (
              SELECT A.WORKERSERIAL, DECODE(B.TOKENNO,NULL,A.BASIC,ROUND((A.BASIC/B.YEARDAYS)*B.NOWORKDAYS,2)) LASTCOMPONENTAMOUNT FROM 
              (
                  SELECT COMPANYCODE, DIVISIONCODE,UNITCODE, GRADECODE, CATEGORYCODE, DEPARTMENTCODE, TOKENNO, WORKERSERIAL,  YEARMONTH , BASIC
                  FROM PISCOMPONENTASSIGNMENT   P
                  WHERE 1=1 
                  AND TRANSACTIONTYPE='ASSIGNMENT' 
                  AND YEARMONTH =  
                  (
                      SELECT MAX(YEARMONTH)  YEARMONTH 
                      FROM PISCOMPONENTASSIGNMENT 
                      WHERE TOKENNO=P.TOKENNO
                      AND TRANSACTIONTYPE='ASSIGNMENT' 
                      AND COMPANYCODE='BT0104'
                      AND DIVISIONCODE='HO'
                      AND YEARMONTH >= '201904'
                      AND YEARMONTH <= '202003'
                  )-- TOKENNO WITH BASIC, YEARMONTH FOR LAST YEAR
              ) A,-- LAST YEAR COMPONENT AMOUNT 
              (
                  SELECT TOKENNO, WORKERSERIAL, DATEOFJOIN, (TRUNC(B.ENDDATE-A.DATEOFJOIN)+1) NOWORKDAYS, (TRUNC(B.ENDDATE-B.STARTDATE)+1) YEARDAYS 
                  FROM PISEMPLOYEEMASTER A,
                  (
                      SELECT STARTDATE, ENDDATE FROM FINANCIALYEAR
                      WHERE COMPANYCODE='BT0104'
                      AND DIVISIONCODE='HO'
                  ) B
                  WHERE DATEOFJOIN > B.STARTDATE
                  AND DATEOFJOIN < B.ENDDATE
              ) B
              WHERE A.WORKERSERIAL=B.WORKERSERIAL(+) --CALCULATE YEAR DAYS, NO OF DAYS WORKING FROM DATE OF JOINING FOR LAST YEAR
         ) C, -- LAST YEAR COMPONENT AMOUNT 
         (
             SELECT WORKERSERIAL, TOKENNO, SUM(PAIDAMOUNT)  PAIDAMOUNT
             FROM PISREIMBURSEMENTDETAILS
             WHERE YEARCODE = '2020-2021'
             AND COMPANYCODE='BT0104'
             AND DIVISIONCODE='HO' 
             AND COMPONENTCODE='LTA' 
             AND YEARMONTH='202101' 
             GROUP BY WORKERSERIAL, TOKENNO 
         ) D, --CALCULATE  PAID AMOUNT THIS YEAR
         (
             SELECT WORKERSERIAL, TOKENNO, SUM(PAIDAMOUNT)  PAIDAMOUNT
             FROM PISREIMBURSEMENTDETAILS
             WHERE YEARCODE = '2020-2021'
             AND YEARMONTH >= '202004'
             AND YEARMONTH <= '202101'
             AND COMPANYCODE='BT0104'
             AND DIVISIONCODE='HO' 
             AND COMPONENTCODE='LTA' 
             GROUP BY WORKERSERIAL, TOKENNO
         ) D2, --CALCULATE  PAID AMOUNT THIS YEAR 
         (
             SELECT WORKERSERIAL, TOKENNO, SUM(PAIDAMOUNT)  PREVIOUSYRTAKEN
             FROM PISREIMBURSEMENTDETAILS
             WHERE 1=1--YEARCODE = '2019-2020'
             AND YEARCODE IN (
                 SELECT (TO_NUMBER(SUBSTR('2020-2021',1,4))-LX)||'-'||(TO_NUMBER(SUBSTR('2020-2021',-4))-LX) XX  FROM 
                 (
                     SELECT Level AS LX 
                     FROM Dual 
                     CONNECT BY Level <= 1
                 )
             )
             AND COMPANYCODE='BT0104'
             AND DIVISIONCODE='HO' 
             AND COMPONENTCODE='LTA' 
             GROUP BY WORKERSERIAL, TOKENNO
         ) D3,--CALCULATE  PAID AMOUNT  FOR LAST YEAR 
         (
             SELECT WORKERSERIAL, TOKENNO, PAIDAMOUNT  AMOUNTCLAIMPREVIOUS
             FROM PISREIMBURSEMENTDETAILS P
             WHERE 1=1 --YEARCODE = '2019-2020'
             AND YEARMONTH = 
             (
                      SELECT MAX(YEARMONTH)  YEARMONTH 
                      FROM PISREIMBURSEMENTDETAILS 
                      WHERE TOKENNO=P.TOKENNO
                     AND COMPANYCODE='BT0104'
                     AND DIVISIONCODE='HO' 
                      AND YEARMONTH < '202101'
             )
             AND COMPANYCODE='BT0104'
             AND DIVISIONCODE='HO' 
             AND COMPONENTCODE='LTA' 
         ) D4,
         (
             SELECT COMPANYCODE,DIVISIONCODE, TOKENNO, WORKERSERIAL, SUM(LV_BAL) LEAVEBALANCE 
             FROM GBL_PISLEAVEBALANCE
             GROUP BY COMPANYCODE,DIVISIONCODE, TOKENNO, WORKERSERIAL
         ) D5
         WHERE 1=1--A.COMPANYCODE=B.COMPANYCODE 
   --      AND A.DIVISIONCODE=B.DIVISIONCODE 
         AND A.WORKERSERIAL=B.WORKERSERIAL 
         AND A.WORKERSERIAL=C.WORKERSERIAL(+)
         AND A.WORKERSERIAL=D.WORKERSERIAL(+)
         AND A.WORKERSERIAL=D2.WORKERSERIAL(+)
         AND A.WORKERSERIAL=D3.WORKERSERIAL(+)
         AND A.WORKERSERIAL=D4.WORKERSERIAL(+)
         AND A.WORKERSERIAL=D5.WORKERSERIAL(+)
         AND B.COMPONENTAMOUNT > 0 
         AND NVL(D.PAIDAMOUNT,0) = 0 
         AND A.COMPANYCODE='BT0104'
         AND A.DIVISIONCODE='HO' 
   AND A.UNITCODE='HO'
   AND A.CATEGORYCODE='SST'
   AND A.GRADECODE='SST'
         ORDER BY A.TOKENNO