DROP TABLE PISREIMBURSEMENTDETAILS CASCADE CONSTRAINTS;


PISREIMBURSEMENTDETAILS

PISREIMBURSEMENTDETAILS

--GBL_PISREIMBURSEMENTDETAILS

GBL_LOANADJFROMREIMBURSE


CREATE TABLE PISREIMBURSEMENTDETAILS
(
  COMPANYCODE      VARCHAR2(10 BYTE),
  DIVISIONCODE     VARCHAR2(10 BYTE),
  YEARCODE         VARCHAR2(10 BYTE),
  FORYEARCODE      VARCHAR2(10 BYTE),
  YEARMONTH        VARCHAR2(10 BYTE),
  WORKERSERIAL     VARCHAR2(10 BYTE),
  TOKENNO          VARCHAR2(10 BYTE),
  CATEGORYCODE     VARCHAR2(10 BYTE),
  GRADECODE        VARCHAR2(10 BYTE),
  COMPONENTCODE    VARCHAR2(10 BYTE),
  COMPONENTAMOUNT  NUMBER(11,2),
  TRANSACTIONTYPE  VARCHAR2(10 BYTE),
  ADDLESS          VARCHAR2(10 BYTE),
  REMARKS          VARCHAR2(250 BYTE),
  BILLAMOUNT       NUMBER(11,2),
  PAIDAMOUNT       NUMBER(11,2),
  LEAVEDATEFROM    DATE,
  LEAVEDATETO      DATE,
  SYSROWID         VARCHAR2(50 BYTE),
  USERNAME         VARCHAR2(100 BYTE),
  LASTMODIFIED     DATE                         DEFAULT SYSDATE,
  TRANTYPE         VARCHAR2(50 BYTE)
)


DROP TABLE LOANADJFROMREIMBURSE CASCADE CONSTRAINTS;

CREATE TABLE LOANADJFROMREIMBURSE
(
  COMPANYCODE      VARCHAR2(10 BYTE),
  DIVISIONCODE     VARCHAR2(10 BYTE),
  YEARCODE         VARCHAR2(10 BYTE),
  YEARMONTH        VARCHAR2(10 BYTE),
  WORKERSERIAL     VARCHAR2(10 BYTE),
  COMPONENTCODE    VARCHAR2(10 BYTE),
  TOKENNO          VARCHAR2(10 BYTE),
  LOANCODE         VARCHAR2(10 BYTE),
  LOANDATE         DATE,
  CAPITALLOANBAL   NUMBER(10,2),
  INTERESTLOANBAL  NUMBER(10,2),
  CAPITALREPAY     NUMBER(10,2),
  INTERESTREPAY    NUMBER(10,2),
  USERNAME         VARCHAR2(100 BYTE),
  LASTMODIFIED     DATE                         DEFAULT SYSDATE,
  SYSROWID         VARCHAR2(50 BYTE)
)