SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'ADDLESS', 0, 
    'VARCHAR2', 10, 0, 'N', 'ADDLESS', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'BILLAMOUNT', 0, 
    'NUMBER', 11, 2, 'N', 'BILLAMOUNT', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'CATEGORYCODE', 0, 
    'VARCHAR2', 10, 0, 'N', 'CATEGORYCODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'COMPANYCODE', 1, 
    'VARCHAR2', 10, 0, 'Y', 'COMPANYCODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'COMPONENTAMOUNT', 0, 
    'NUMBER', 11, 2, 'N', 'COMPONENTAMOUNT', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'COMPONENTCODE', 5, 
    'VARCHAR2', 10, 0, 'Y', 'COMPONENTCODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'DIVISIONCODE', 2, 
    'VARCHAR2', 10, 0, 'Y', 'DIVISIONCODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'FORYEARCODE', 0, 
    'VARCHAR2', 10, 0, 'N', 'FORYEARCODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'GRADECODE', 0, 
    'VARCHAR2', 10, 0, 'N', 'GRADECODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'LEAVEDATEFROM', 0, 
    'DATE', 10, 0, 'N', 'LEAVEDATEFROM', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'LEAVEDATETO', 0, 
    'DATE', 10, 0, 'N', 'LEAVEDATETO', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'NONE', 'GBL_PISREIMBURSEMENTDETAILS', 'OPERATIONMODE', 0, 
    'VARCHAR2', 1, 0, 'N', 'OPERATIONMODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'PAIDAMOUNT', 0, 
    'NUMBER', 11, 2, 'N', 'PAIDAMOUNT', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'REMARKS', 0, 
    'VARCHAR2', 250, 0, 'N', 'REMARKS', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'SYSROWID', 0, 
    'VARCHAR2', 50, 0, 'N', 'SYSROWID', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'TOKENNO', 3, 
    'VARCHAR2', 10, 0, 'Y', 'TOKENNO', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'TRANSACTIONTYPE', 0, 
    'VARCHAR2', 10, 0, 'N', 'TRANSACTIONTYPE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'TRANTYPE', 0, 
    'VARCHAR2', 50, 0, 'N', 'TRANTYPE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'USERNAME', 0, 
    'VARCHAR2', 100, 0, 'N', 'USERNAME', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'WORKERSERIAL', 4, 
    'VARCHAR2', 10, 0, 'Y', 'WORKERSERIAL', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'YEARCODE', 7, 
    'VARCHAR2', 10, 0, 'Y', 'YEARCODE', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (20249, 'PISREIMBURSEMENTDETAILS', 'GBL_PISREIMBURSEMENTDETAILS', 'YEARMONTH', 6, 
    'VARCHAR2', 10, 0, 'Y', 'YEARMONTH', 
    TO_TIMESTAMP('31/01/2020 12:58:35.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;
