select TNAME from tab
where TNAME LIKE '%STL%'
AND INSTR(TNAME,'_') =0
AND INSTR(TNAME,'0') =0


SELECT * FROM WPSSTLENTITLEMENTCALCDETAILS

DELETE FROM WPSSTLENTRY
WHERE DOCUMENTDATE = '07-NOV-2020'

DELETE FROM WPSSTLENTRYDETAILS
WHERE DOCUMENTDATE = '07-NOV-2020'
 

CREATE TABLE WPSSTLENTRY_BK07112020 AS

SELECT * FROM WPSSTLENTRY
WHERE DOCUMENTDATE = '07-NOV-2020'


CREATE TABLE WPSSTLENTRYDETAILS_BK07112020 AS

SELECT * FROM WPSSTLENTRYDETAILS
WHERE DOCUMENTDATE = '07-NOV-2020'
 





WPSSTLENTRY
WPSSTLENTRYDETAILS
WPSSTLRAWDATA
WPSSTLTRANSACTION
WPSSTLWAGESDETAILS
