
1. CREATE OR REPLACE VIEW VW_PISCOMPONENTLEDGERMAPPING 
 AS 
 SELECT COMPANYCODE, DIVISIONCODE, QUALITY_GROUP_CODE as COMPONENTCODE,  ACCODE ACCCODE 
 FROM SYS_PARAM_ACPOST_PAYROLL 
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND  POSTING_PARAM_NAME = 'PIS SALARY POSTING TO ACCOUNTS' 
 AND  MODULENAME = 'PIS' 
 AND ACCODE IS NOT NULL 
UNION ALL
 SELECT DISTINCT COMPANYCODE, DIVISIONCODE, COMPONENTCODE, EXPENSECODE 
 FROM PISCOMPONENTMASTER 
 WHERE COMPANYCODE = '0001' 
 AND DIVISIONCODE = '002' 
 AND EXPENSECODE IS NOT NULL 


INSERT INTO PISSALARY_POSTINGDATA 
( 
  COMPANYCODE, DIVISIONCODE, PERIODFROM, PERIODTO, ACCODE, ACHEAD, DRCR, AMOUNT, ACCOSTCENTRECODE, CATEGORYCODE, UNITCODE, GRADECODE 
) 


SELECT D.COMPANYCODE,D.DIVISIONCODE, 
       TO_DATE('01/10/2020','DD/MM/YYYY') PERIODFROM,TO_DATE('31/10/2020','DD/MM/YYYY') PERIODTO, 
       C.ACCCODE, B.ACHEAD, 
       CASE                                                
            WHEN D.COMPONENTCODE = 'NETSALARY' THEN 'CR' 
            WHEN C.ACCCODE IN (SELECT DISTINCT EXPENSECODE FROM PISCOMPONENTMASTER ) THEN 'CR' 
            WHEN C.ACCCODE IN (SELECT DISTINCT ACCCODE FROM PISCOMPONENTMASTER WHERE COMPONENTCODE IN ('PF_C','FPF')) THEN 'CR' 
            WHEN D.COMPONENTTYPE = 'EARNING' THEN 'DR' 
            WHEN D.COMPONENTTYPE = 'DEDUCTION' THEN 'CR' 
            ELSE 'DR' 
        END AS DRCR, 
       FN_PISSALARY_COMP_AMT_NEW(C.COMPANYCODE,C.DIVISIONCODE,'SALARY PROCESS',C.COMPONENTCODE, '202010' , '' , '002' , '')  AMOUNT, 
       NULL ACCOSTCENTRECODE, '' CATEGORYCODE, '002' UNITCODE, '' GRADECODE 
  FROM PISCOMPONENTMASTER D, 
        ( 
          SELECT DISTINCT COMPANYCODE, DIVISIONCODE, COMPONENTCODE, ACCCODE 
            FROM VW_PISCOMPONENTLEDGERMAPPING 
           WHERE COMPANYCODE = '0001' 
             AND DIVISIONCODE = '002' 
        ) C ,ACACLEDGER B 
 WHERE C.COMPANYCODE = '0001' 
   AND C.DIVISIONCODE = '002' 
   AND C.COMPANYCODE = D.COMPANYCODE 
   AND C.DIVISIONCODE = D.DIVISIONCODE 
   AND C.COMPONENTCODE=D.COMPONENTCODE 
   AND B.COMPANYCODE = C.COMPANYCODE 
   AND B.ACCODE = C.ACCCODE 
   
   
   
SELECT SUM(NVL(MEDICAL,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(LTA,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(FIX_CONV,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(LOCAL_CONV,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(TELEPHONE,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LOAN_HBLDG) from (
SELECT SUM(NVL(LOAN_HBLDG,0)) LOAN_HBLDG
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LOAN_HBLDG,0)) LOAN_HBLDG
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LOAN_EDU) from (
SELECT SUM(NVL(LOAN_EDU,0)) LOAN_EDU
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LOAN_EDU,0)) LOAN_EDU
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LOAN_MRG) from (
SELECT SUM(NVL(LOAN_MRG,0)) LOAN_MRG
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LOAN_MRG,0)) LOAN_MRG
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(ESI_C,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(ESI_E) from (
SELECT SUM(NVL(ESI_E,0)) ESI_E
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(ESI_E,0)) ESI_E
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LINT_MRG) from (
SELECT SUM(NVL(LINT_MRG,0)) LINT_MRG
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LINT_MRG,0)) LINT_MRG
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(BASIC) from (
SELECT SUM(NVL(BASIC,0)) BASIC
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(BASIC,0)) BASIC
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(HRA) from (
SELECT SUM(NVL(HRA,0)) HRA
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(HRA,0)) HRA
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(CANTEEN) from (
SELECT SUM(NVL(CANTEEN,0)) CANTEEN
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(CANTEEN,0)) CANTEEN
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(PF_C,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(PF_C,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(PF_E) from (
SELECT SUM(NVL(PF_E,0)) PF_E
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(PF_E,0)) PF_E
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(PTAX) from (
SELECT SUM(NVL(PTAX,0)) PTAX
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(PTAX,0)) PTAX
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(NETSALARY,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(FPF,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(FPF,0)) 
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(CONV_ALW) from (
SELECT SUM(NVL(CONV_ALW,0)) CONV_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(CONV_ALW,0)) CONV_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(ATN_INCTV) from (
SELECT SUM(NVL(ATN_INCTV,0)) ATN_INCTV
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(ATN_INCTV,0)) ATN_INCTV
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(PUNC_ALW) from (
SELECT SUM(NVL(PUNC_ALW,0)) PUNC_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(PUNC_ALW,0)) PUNC_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(WASH_ALW) from (
SELECT SUM(NVL(WASH_ALW,0)) WASH_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(WASH_ALW,0)) WASH_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(EDU_ALW) from (
SELECT SUM(NVL(EDU_ALW,0)) EDU_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(EDU_ALW,0)) EDU_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(ATN_ALW) from (
SELECT SUM(NVL(ATN_ALW,0)) ATN_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(ATN_ALW,0)) ATN_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(CLEAN_ALW) from (
SELECT SUM(NVL(CLEAN_ALW,0)) CLEAN_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(CLEAN_ALW,0)) CLEAN_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(INSP_ALW) from (
SELECT SUM(NVL(INSP_ALW,0)) INSP_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(INSP_ALW,0)) INSP_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(CHRG_HAND) from (
SELECT SUM(NVL(CHRG_HAND,0)) CHRG_HAND
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(CHRG_HAND,0)) CHRG_HAND
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(PERF_ALW) from (
SELECT SUM(NVL(PERF_ALW,0)) PERF_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(PERF_ALW,0)) PERF_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(SHIFT_ALW) from (
SELECT SUM(NVL(SHIFT_ALW,0)) SHIFT_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(SHIFT_ALW,0)) SHIFT_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LGBK_ALW) from (
SELECT SUM(NVL(LGBK_ALW,0)) LGBK_ALW
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LGBK_ALW,0)) LGBK_ALW
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(MISC_DEDN) from (
SELECT SUM(NVL(MISC_DEDN,0)) MISC_DEDN
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(MISC_DEDN,0)) MISC_DEDN
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LINT_EDU) from (
SELECT SUM(NVL(LINT_EDU,0)) LINT_EDU
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LINT_EDU,0)) LINT_EDU
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)

SELECT SUM(NVL(SARR_ARRD,0))
FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
 AND YEARMONTH = '202010' 
   AND UNITCODE = '002'

select sum(LINT_HBLDG) from (
SELECT SUM(NVL(LINT_HBLDG,0)) LINT_HBLDG
 FROM PISPAYTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' 
   AND UNITCODE = '002'
UNION ALL
SELECT SUM(NVL(LINT_HBLDG,0)) LINT_HBLDG
 FROM PISARREARTRANSACTION A
 WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '002' 
   AND YEARMONTH = '202010' AND TRANSACTIONTYPE='ARREAR'
   AND UNITCODE = '002'
)