select * from menumaster_rnd
where menudesc like 'Wor%Toke%Cha%'

WPS/Pages/Transaction/pgWPSTokenNoChange.aspx

select * from menumaster_rnd
where menucode like  '0110041403'

WPS/Pages/Report/pgReportWPSTemplate.aspx

GRATUITY CALCULATION DETAILS

select * from login

where menucode = '0110041402'

select * from roledetails
where menucode = '0110041402'

GRATUITY PAYMENT ADVICE

select * from reportparametermaster
where reporttag='GRATUITY PAYMENT ADVICE'

GTT_GRATUITYPAYMENTADVICE

WPS/Pages/Report/Transaction/rdl_GRATUITYPAYMENTADVICE.rdlc

exec PROC_GRATUITYCALC_DETAILS('NJ0001','0002','')



~WPS/Pages/Report/Transaction/rdl_GRATUITYPAYMENTADVICE.rdlc~GTT_GRATUITYPAYMENTADVICE

GTT_GRATUITYPAYMENTADVICE

GTT_GRATUITYPAYMENTADVICE

WPS/Pages/Report/pgReportWPSTemplate.aspx

GRATUITY PAYMENT ADVICE


execute immediate lv_sqlstr;


exec PROC_GRATUITYPAYMENTADVICE('NJ0001','0002','','asasas')

PROC_GRATUITYPAYMENTADVICE('NJ0001','0002','')~WPS/Pages/Report/Transaction/rdl_GRATUITYPAYMENTADVICE.rdlc~GTT_GRATUITYPAYMENTADVICE

select 'Hello ''World''' from dual

hello wolrd

Hello 'World'


DROP TABLE NJMCL_WEB.GTT_GRATUITYCALC_DETAILS CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE GTT_GRATUITYCALC_DETAILS
(
  EBNO               VARCHAR2(100 BYTE),
  WORKERNAME         VARCHAR2(100 BYTE),
  PFNO               VARCHAR2(20 BYTE),
  TOKENNO            VARCHAR2(10 BYTE),
  OCCUPATIONNAME     VARCHAR2(100 BYTE),
  DEPARTMENTNAME     VARCHAR2(100 BYTE),
  AGE                VARCHAR2(100 BYTE),
  DATEOFJOINING      DATE,
  DATEOFTERMINATION  DATE,
  LASTWAGESDRAWN     NUMBER(15,2),
  GRATUITYPAYABLE    NUMBER(15,2),
  COMPANYCODE        VARCHAR2(10 BYTE),
  DIVISIONCODE       VARCHAR2(10 BYTE),
  COMPANYNAME        VARCHAR2(100 BYTE),
  DIVISIONNAME       VARCHAR2(100 BYTE),
  REPORTTYPE         VARCHAR2(100 BYTE),
  REPORTNAME         VARCHAR2(200 BYTE),
  INWORDS            VARCHAR2(500 BYTE),
  EX1                NUMBER,
  EX2                NUMBER,
  EX3                NUMBER,
  EX4                NUMBER,
  EX5                NUMBER,
  EX6                VARCHAR2(100 BYTE),
  EX7                VARCHAR2(100 BYTE),
  EX8                VARCHAR2(100 BYTE),
  EX9                VARCHAR2(100 BYTE),
  EX10               VARCHAR2(100 BYTE),
  EX11               VARCHAR2(100 BYTE),
  EX12               VARCHAR2(100 BYTE)
)



ON COMMIT DELETE ROWS
NOCACHE;



INSERT INTO GTT_GRATUITYCALC_DETAILS
(
    EX1, EBNO, WORKERNAME, PFNO, TOKENNO, OCCUPATIONNAME, DEPARTMENTNAME, AGE, DATEOFJOINING, DATEOFTERMINATION, LASTWAGESDRAWN, 
    GRATUITYPAYABLE, INWORDS, COMPANYCODE, DIVISIONCODE, COMPANYNAME, DIVISIONNAME, REPORTTYPE,EX6, REPORTNAME
)
                            
SELECT 1 EX1,'' EBNO,B.WORKERNAME, B.PFNO, A.TOKENNO,B.OCCUPATIONNAME, DEPARTMENTNAME,
EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM DATEOFBIRTH)  AGE,NVL(GRATUITYJOINDATE, PFMEMBERSHIPDATE) DATEOFJOINING,   
DATEOFTERMINATION, A.SAL_15DAYS LASTWAGESDRAWN, NETPAYABLE GRATUITYPAYABLE,  FN_NUM_TO_WORDS(NETPAYABLE,'RS')  INWORDS, 
A.COMPANYCODE,B.DIVISIONCODE, 'THE NAIHATI JUTE MILLS  COMPANY LTD.' COMPANYNAME, 'MILL' DIVISIONNAME, 'Original' REPORTTYPE, 
GRATUITYYEAR LENGTHOFGRATUITY, 'GRATUITY ON '||B.WORKERSTATUS REPORTNAME
FROM GRATUITYSETTLEMENT A, WORKERVIEWGRATUITY B 
WHERE A.WORKERSERIAL=B.WORKERSERIAL 
AND B.COMPANYCODE = 'NJ0001'
AND B.DIVISIONCODE = '0002'  
  ORDER BY A.TOKENNO
  
  

exec PROC_GRATUITYCALC_DETAILS('NJ0001','0002','')

SELECT * FROM GTT_GRATUITYCALC_DETAILS
