DROP TABLE NJMCL_WEB.GRATUITYENTITLEMENTYEAR CASCADE CONSTRAINTS;

CREATE TABLE NJMCL_WEB.GRATUITYENTITLEMENTYEAR
(
  COMPANYCODE          VARCHAR2(10 BYTE),
  DIVISIONCODE         VARCHAR2(10 BYTE),
  MODULE               VARCHAR2(10 BYTE),
  FINANCIALYEAR        VARCHAR2(10 BYTE),
  CALENDARYEAR         VARCHAR2(10 BYTE),
  DEPARTMENTCODE       VARCHAR2(10 BYTE),
  WORKERSERIAL         VARCHAR2(20 BYTE),
  TOKENNO              VARCHAR2(10 BYTE),
  ATTENDANCETYPE       VARCHAR2(10 BYTE),
  ATTENDANCE_ACT       NUMBER(15,2),
  ATTENDANCE           NUMBER(15,2),
  HOLIDAY_ACT          NUMBER(15,2),
  HOLIDAY              NUMBER(15,2),
  STL_ACT              NUMBER(15,2),
  STL                  NUMBER(15,2),
  ESI_ACT              NUMBER(15,2),
  ESI                  NUMBER(15,2),
  AUTHORIZEDLEAVE_ACT  NUMBER(15,2),
  AUTHORIZEDLEAVE      NUMBER(15,2),
  TOTAL                NUMBER(15,2),
  ADJUSTMENT           NUMBER(15,2),
  ADJUSTMENTREMARKS    VARCHAR2(2000 BYTE),
  GRATURITYENTILE      VARCHAR2(5 BYTE),
  SYSROWID             VARCHAR2(50 BYTE),
  USERNAME             VARCHAR2(100 BYTE),
  LASTMODIFIED         DATE                     DEFAULT SYSDATE,
  STATUS               VARCHAR2(50 BYTE)
)
TABLESPACE NJMCL_WEB
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
