 
--       SELECT TOKENNO,EMPLOYEENAME WORKERNAME, WORKERSERIAL, CATEGORYCODE 
--    FROM  PISEMPLOYEEMASTER 
--    WHERE COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
--    AND MODULE=<<MODULE>>
--    AND EMPLOYEESTATUS IN ('DEATH','DISMISSED','RESIGN','RETIRE') 
--    AND STATUSDATE IS NOT NULL        
--    UNION ALL       
--    SELECT TOKENNO,WORKERNAME, WORKERSERIAL, WORKERCATEGORYCODE
--    FROM WPSWORKERMAST
--    WHERE
--    COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
--    AND MODULE=<<MODULE>>
--    AND WORKERSTATUS IN ('DEATH','DISMISSED','RESIGN','RETIRE')
--    and DATEOFTERMINATIONADVICE IS NOT NULL
--    ORDER BY TOKENNO
    
   SELECT TOKENNO,EMPLOYEENAME WORKERNAME, WORKERSERIAL, CATEGORYCODE 
    FROM  PISEMPLOYEEMASTER 
    WHERE COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
    AND MODULE=<<MODULE>>
    AND EMPLOYEESTATUS IN ('DEATH','DISMISSED','RESIGN','RETIRE') 
    AND STATUSDATE IS NOT NULL        
    AND GRATUITYSETTELMENTDATE IS NULL
    UNION ALL       
    SELECT TOKENNO,WORKERNAME, WORKERSERIAL, WORKERCATEGORYCODE
    FROM WPSWORKERMAST
    WHERE
    COMPANYCODE = <<COMPANYCODE>> AND divisioncode = <<DIVISIONCODE>> 
    AND MODULE=<<MODULE>>
    AND WORKERSTATUS IN ('DEATH','DISMISSED','RESIGN','RETIRE')
    and DATEOFTERMINATIONADVICE IS NOT NULL
    AND GRATUITYSETTELMENTDATE IS NULL
    ORDER BY TOKENNO