SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%gratuity%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0110022606'

0110023002

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''


SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG = ''

SELECT * FROM SYSTAF
WHERE SYS_TABLENAME_ACTUAL=''

select * from jswrapper

select * from sys_help_qry
where qry_id='6930'