SELECT * FROM PISPAYTRANSACTION
WHERE 1=1
AND YEARMONTH='202012'

78097
78098


SELECT * FROM PISEMPLOYEEMASTER
WHERE TOKENNO LIKE '%8097'

SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%STAFF %')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

prcPIS_STF_DTULD_b4Save


CREATE TABLE PISPAYTRANSACTION_110121 AS
SELECT * FROM PISPAYTRANSACTION

STAFFPFDATAUPLOAD


SELECT RAW_TABLE_NAME, KEYCOLUMN1 FROM EXPIMPINF_EXCEL

SELECT SOURCE_QUERY FROM EXPIMPINF_EXCEL

PROC_PISSALARY_DATA_IMPORT1