SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, KEY_TABLE, KEY_COLUMN)
 Values
   ('019914', NULL, 'File Upload into Location', 'UTILITIES', NULL, 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'GENERAL', NULL, 
    '''0001'',''0002'',''0003''', '''0001'',''0002'',''0003''', NULL, 'GENERAL/Pages/Common/pgUploadFileIntoLocation.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL, NULL);
COMMIT;


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%ROLE%')


SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='019908'


SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, AUDITRAIL, KEY_COLUMN)
 Values
   ('019908', NULL, 'User Role', 'UTILITIES', 'USER ACCESS', 
    NULL, NULL, 'Y', 'Y', 'N', 
    'N', 'N', 'Y', 'GENERAL', NULL, 
    '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', NULL, 'GENERAL/Pages/Common/pgROLEENTRY.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, AUDITRAIL, KEY_COLUMN)
 Values
   ('019909', NULL, 'User Role', 'UTILITIES', 'USER ACCESS', 
    NULL, NULL, 'Y', 'Y', 'N', 
    'N', 'N', 'Y', 'GENERAL', NULL, 
    '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', NULL, 'GENERAL/Pages/Common/pgROLEENTRY.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL, NULL);
COMMIT;



SELECT * FROM ROLEDETAILS
WHERE MENUCODE='019908'




SET DEFINE OFF;
Insert into MENUMASTER_RND
   (MENUCODE, MENUNAME, MENUDESC, MENUTYPE, MENUTAG, MENUTAG1, MENUTAG2, ENTRYPOSSIBLE, EDITPOSSIBLE, DELETEPOSSIBLE, REPORTSPOSSIBLE, UTILITIESPOSSIBLE, ACTIVE, PROJECTNAME, MENUDETAILS, EFFECTIVEDIVISION, EFFECTIVEINDIVISION, PROCEDURE_SAVE_EDIT, URLSRC, FRM_HEIGHT, FRM_WIDTH, FUNCTIONCALL_BEFORE, FUNCTIONCALL_AFTER, VIEWPOSSIBLE, PRINTPOSSIBLE, DOCDATEVALIDATEFIELD, AUDITRAIL, KEY_COLUMN)
 Values
   ('019909', NULL, 'File Upload into Location', 'UTILITIES', NULL, 
    NULL, NULL, 'Y', 'N', 'N', 
    'N', 'N', 'Y', 'GENERAL', NULL, 
    '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', '''Y01'',''0002'',''0001'',''Y03'',''Y05'',''CHO'',''JHO'',''KHO''', NULL, 'GENERAL/Pages/Common/pgUploadFileIntoLocation.aspx', NULL, 
    NULL, NULL, NULL, 'N', 'N', 
    NULL, NULL, NULL);
COMMIT;


SET DEFINE OFF;
Insert into ROLEDETAILS
   (ROLEID, MENUCODE, ACCESSENTRY, ACCESSEDIT, ACCESSDELETE, ACCESSREPORT, ACCESSUTILITIES, ACCESSVIEW, ACCESSPRINT, PROJECTNAME, SYSROWID)
 Values
   ('1', '019909', 'Y', 'Y', 'X', 
    'X', 'X', 'X', 'X', 'GENERAL', 
    '202009211036100005744466');
COMMIT;


CREATE TABLE UPLOADFILELOCATION
(
    COMPANYCODE VARCHAR2(10),
    DIVISIONCODE VARCHAR2(10),
    UPLOADID    NUMBER(20),
    UPLOADEDBY VARCHAR2(100),
    UPLOADFILEPATH VARCHAR2(1000),
    BACKUPFILEPATH VARCHAR2(1000),
    USERNAME VARCHAR2(100),
    LASTMODIFIED DATE  DEFAULT SYSDATE
)   