CREATE OR REPLACE PROCEDURE PROC_UPLOADFILE_SAVE
(
    P_COMPANYCODE VARCHAR2,
    P_DIVISIONCODE VARCHAR2,
    P_UPLOADEDBY VARCHAR2,
    P_UPLOADFILEPATH VARCHAR2,
    P_BACKUPFILEPATH VARCHAR2,
    P_USERNAME VARCHAR2 
)
AS 
LV_SQLSTR VARCHAR2(1000);
LV_ID NUMBER(20);
BEGIN
-- EXEC PROC_UPLOADFILE_SAVE('BJ0056','0001','CHIRANJIT','A','B','SWT')

    SELECT (COUNT(*) + 1) INTO LV_ID FROM UPLOADFILELOCATION;
--
--CREATE TABLE UPLOADFILELOCATION
--(
--    COMPANYCODE VARCHAR2(10),
--    DIVISIONCODE VARCHAR2(10),
--    UPLOADID    NUMBER(20),
--    UPLOADEDBY VARCHAR2(100),
--    UPLOADFILEPATH VARCHAR2(1000),
--    BACKUPFILEPATH VARCHAR2(1000),
--    USERNAME VARCHAR2(100),
--    LASTMODIFIED DATE  DEFAULT SYSDATE
--)    
    
    
    
    INSERT INTO UPLOADFILELOCATION
    (
        COMPANYCODE, DIVISIONCODE, UPLOADID, UPLOADEDBY, UPLOADFILEPATH, BACKUPFILEPATH, USERNAME, LASTMODIFIED
    )
    VALUES(P_COMPANYCODE, P_DIVISIONCODE, LV_ID, P_UPLOADEDBY, P_UPLOADFILEPATH, P_BACKUPFILEPATH, P_USERNAME, SYSDATE);
END;
/
