INSERT INTO GTT_ESICONTR_EXCEL_NJML
(SRLNO, COMPANYCODE,DIVISIONCODE,COMPANYNAME,EX1,WORKERSERIAL,EMPCODE,EMPNAME,ESINO,TOTALDAYS,TOTALWAGE,ESICONT,AVGDYWAGES,REMARKS,EX2,EX3,EX4,LASTWORKINGDATE,TYPE)


SELECT ROWNUM,COMPANYCODE, DIVISIONCODE, COMPANYNAME, DIVISIONNAME, WORKERSERIAL, EMPCODE, EMPNAME, ESINO, TOTALDAYS, TOTALWAGE, 
ESICONT, AVGDYWAGES, REMARKS, EX2, EX3, EX4,  
CASE WHEN LASTWORKINGDATE<=TO_DATE('30/11/2020','DD/MM/YYYY') THEN LASTWORKINGDATE ELSE NULL END LASTWORKINGDATE, TYPE /*,fnWorkerReasonCode(WORKERSERIAL,TOTALDAYS,ESINO,EX5)*/ FROM (
SELECT 'NJ0001' COMPANYCODE,'0002'DIVISIONCODE,'THE NAIHATI JUTE MILLS  COMPANY LTD.' AS COMPANYNAME,'MILL' AS DIVISIONNAME, 
WORKERSERIAL,EMPCODE,EMPNAME,ESINO, CASE WHEN SUM(NVL(TOTALDAYS,0))<='30' THEN SUM(NVL(TOTALDAYS,0)) ELSE 30 END TOTALDAYS ,SUM(NVL(TOTALWAGE,0)) TOTALWAGE , 
SUM(NVL(ESICONT,0)) ESICONT ,SUM(NVL(AVGDYWAGES,0)) AVGDYWAGES,'' AS REMARKS,  
'ESI CONTRIBUTION PERIOD  ' AS EX2,'FROM  '|| TO_CHAR(TO_DATE('01/11/2020','DD/MM/YYYY'),'MON-YYYY') ||' TO ' || TO_CHAR(LAST_DAY(TO_DATE('01/11/2020','DD/MM/YYYY')),'MON-YYYY') AS EX3,'40-3167-12' AS EX4, 
LASTWORKINGDATE, 1 TYPE --,fnWorkerReasonCode(WORKERSERIAL,SUM(NVL(TOTALDAYS,0)),ESINO,1) REASON 
FROM 
(  
    SELECT A.WORKERSERIAL,A.TOKENNO EMPCODE,B.WORKERNAME EMPNAME,B.ESINO,A.DEPARTMENTCODE DEPT,A.SECTIONCODE SECT, 
    '' SRLNO,SUM(NVL(STLDAYS,0)) AS TOTALDAYS,SUM(NVL(ESI_GROSS,0)) TOTALWAGE,SUM(NVL(A.ESI_E,0)) ESICONT,0 AVGDYWAGES,DATEOFTERMINATION LASTWORKINGDATE 
    FROM WPSSTLWAGESDETAILS A,WPSWORKERMAST B WHERE 1=1 
    AND A.COMPANYCODE ='NJ0001' 
    AND A.DIVISIONCODE = '0002' 
    AND A.PAYMENTDATE>=TO_DATE('01/11/2020','DD/MM/YYYY')            
    AND A.PAYMENTDATE<=LAST_DAY(TO_DATE('01/11/2020','DD/MM/YYYY'))  
    AND A.COMPANYCODE = B.COMPANYCODE   (+)                   
    AND A.DIVISIONCODE = B.DIVISIONCODE (+)                   
    AND A.WORKERSERIAL = B.WORKERSERIAL (+)                   
    AND B.WORKERCATEGORYCODE NOT IN ('O','A')             
    GROUP BY A.WORKERSERIAL,A.TOKENNO,B.WORKERNAME,A.DEPARTMENTCODE,A.SECTIONCODE,B.ESINO,DATEOFTERMINATION  
    UNION ALL   
    SELECT A.WORKERSERIAL,A.TOKENNO EMPCODE,B.WORKERNAME EMPNAME,B.ESINO,A.DEPARTMENTCODE DEPT,A.SECTIONCODE SECT, 
    A.SERIALNO SRLNO,SUM(NVL(A.FEWORKINGDAYS,0)) AS TOTALDAYS,SUM(NVL(A.ESI_GROSS,0)) TOTALWAGE,SUM(NVL(A.ESI_CONT,0)) ESICONT,  
    0 AVGDYWAGES,DATEOFTERMINATION LASTWORKINGDATE  
    FROM WPSWAGESDETAILS_MV A,WPSWORKERMAST B WHERE 1=1  
    AND A.COMPANYCODE ='NJ0001'  
    AND A.DIVISIONCODE = '0002' 
    AND A.FORTNIGHTSTARTDATE>=TO_DATE('01/11/2020','DD/MM/YYYY')          
    AND A.FORTNIGHTENDDATE<=LAST_DAY(TO_DATE('01/11/2020','DD/MM/YYYY'))  
    AND A.COMPANYCODE = B.COMPANYCODE   (+)  
    AND A.DIVISIONCODE = B.DIVISIONCODE (+)  
    AND A.WORKERSERIAL = B.WORKERSERIAL (+)  
    AND B.WORKERCATEGORYCODE NOT IN ('O','A')             
    GROUP BY A.WORKERSERIAL, A.SERIALNO,A.TOKENNO,B.WORKERNAME,A.DEPARTMENTCODE ,A.SECTIONCODE,B.ESINO,DATEOFTERMINATION  
) X  
GROUP BY EMPCODE,EMPNAME,ESINO,LASTWORKINGDATE,WORKERSERIAL                               
UNION ALL  


--*********************
SELECT  'NJ0001','0002','THE NAIHATI JUTE MILLS  COMPANY LTD.' AS COMPANYNAME,'MILL' AS DIVISIONNAME, 
A.WORKERSERIAL,A.TOKENNO EMPCODE,EMPLOYEENAME WORKERNAME,ESINO,
CASE WHEN NVL(ATTN_SALD,0)<='30' THEN NVL(ATTN_SALD,0) ELSE 30 END TOTALDAYS ,ESI_GROSS TOTALWAGE , 
NVL(ESI_E,0) ESICONT ,0 AVGDYWAGES,'' AS REMARKS,
'ESI CONTRIBUTION PERIOD  ' AS EX2,'FROM  '|| TO_CHAR(TO_DATE('01/11/2020','DD/MM/YYYY'),'MON-YYYY') ||' TO ' || TO_CHAR(LAST_DAY(TO_DATE('01/11/2020','DD/MM/YYYY')),'MON-YYYY') AS EX3,'40-3167-12' AS EX4,  
STATUSDATE LASTWORKINGDATE,2 TYPE --,fnWorkerReasonCode(A.WORKERSERIAL,ATTN_SALD,ESINO,2) REASON 
FROM 
(           
    SELECT A.COMPANYCODE,A.DIVISIONCODE,WORKERSERIAL,TOKENNO,A.DEPARTMENTCODE,'' SECTIONCODE, EMPLOYEENAME, ESINO, 
    EXTENDEDRETIREDATE AS EMPLOYEEDATEOFRETIRE, A.CATEGORYCODE,  STATUSDATE
    FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER B 
    WHERE
    A.COMPANYCODE=B.COMPANYCODE
    AND A.DIVISIONCODE=B.DIVISIONCODE
    AND A.CATEGORYCODE=B.CATEGORYCODE
    AND A.COMPANYCODE = 'NJ0001'
    --AND A.DIVISIONCODE= '0001'  
    --AND B.CATEGORYCODE IN (2,3)        
    AND DATEOFJOIN <= TO_DATE('30/11/2020','DD/MM/YYYY')    
    --change 28112020    
    --AND (STATUSDATE IS NULL OR STATUSDATE >TO_DATE('30/11/2020','DD/MM/YYYY'))
    --AND (EMPLOYEESTATUS='ACTIVE' OR STATUSDATE >=TO_DATE('30/11/2020','DD/MM/YYYY')) -- change 28112020
--    and ESIAPPLICABLE='Y'
    --AND ESINO IS NOT NULL                  
) A,            
(     
    SELECT COMPANYCODE,DIVISIONCODE,WORKERSERIAL,TOKENNO, ESI_GROSS,ESI_E,ESI_C,ATTN_LDAY,ATTN_SALD  
    FROM PISPAYTRANSACTION  
    WHERE COMPANYCODE = 'NJ0001'
    --AND DIVISIONCODE= '0001'                             
    AND YEARMONTH = TO_CHAR(TO_DATE('01/11/2020','DD/MM/YYYY'),'YYYYMM')  
) B  
WHERE 1=1
--AND ESI_GROSS>0 
AND A.COMPANYCODE=B.COMPANYCODE--(+)  
--AND A.DIVISIONCODE=B.DIVISIONCODE(+)  
AND A.WORKERSERIAL=B.WORKERSERIAL--(+)   

--*******************************                                   
)Y
ORDER BY ROWNUM


SELECT COMPANYCODE,DIVISIONCODE,WORKERSERIAL,TOKENNO, ESI_GROSS,ESI_E,ESI_C,ATTN_LDAY,ATTN_SALD  
    FROM PISPAYTRANSACTION  
    WHERE COMPANYCODE = 'NJ0001'
    --AND DIVISIONCODE= '0001'                             
    AND YEARMONTH = TO_CHAR(TO_DATE('01/11/2020','DD/MM/YYYY'),'YYYYMM') 
    
    
    
    
    
 SELECT TOKENNO
    FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER B 
    WHERE
    A.COMPANYCODE=B.COMPANYCODE
    AND A.DIVISIONCODE=B.DIVISIONCODE
    AND A.CATEGORYCODE=B.CATEGORYCODE
    AND A.COMPANYCODE = 'NJ0001'
    --AND A.DIVISIONCODE= '0001'  
    --AND B.CATEGORYCODE IN (2,3)        
    AND DATEOFJOIN <= TO_DATE('30/11/2020','DD/MM/YYYY')    
    --change 28112020    
    --AND (STATUSDATE IS NULL OR STATUSDATE >TO_DATE('30/11/2020','DD/MM/YYYY'))
    --AND (EMPLOYEESTATUS='ACTIVE' OR STATUSDATE >=TO_DATE('30/11/2020','DD/MM/YYYY')) -- change 28112020
    and ESIAPPLICABLE='Y'
    
       
SELECT TOKENNO
    FROM PISPAYTRANSACTION  
    WHERE COMPANYCODE = 'NJ0001'
    --AND DIVISIONCODE= '0001'                             
    AND YEARMONTH = TO_CHAR(TO_DATE('01/11/2020','DD/MM/YYYY'),'YYYYMM') 
MINUS
 SELECT TOKENNO
    FROM PISEMPLOYEEMASTER A, PISCATEGORYMASTER B 
    WHERE
    A.COMPANYCODE=B.COMPANYCODE
    AND A.DIVISIONCODE=B.DIVISIONCODE
    AND A.CATEGORYCODE=B.CATEGORYCODE
    AND A.COMPANYCODE = 'NJ0001'
    --AND A.DIVISIONCODE= '0001'  
    --AND B.CATEGORYCODE IN (2,3)        
    AND DATEOFJOIN <= TO_DATE('30/11/2020','DD/MM/YYYY')    
    --change 28112020    
    --AND (STATUSDATE IS NULL OR STATUSDATE >TO_DATE('30/11/2020','DD/MM/YYYY'))
    --AND (EMPLOYEESTATUS='ACTIVE' OR STATUSDATE >=TO_DATE('30/11/2020','DD/MM/YYYY')) -- change 28112020
    and ESIAPPLICABLE='Y'    