SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%gratuity%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE='0110041403'

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

PROC_RPT_GRATUITYWORKSHT_EXL('COMPANYCODE','DIVISIONCODE','YEARCODE','','','','','','btnTOKENNO')

PROC_RPT_GRATUITYWORKSHT_EXL('COMPANYCODE','DIVISIONCODE','YEARCODE','','','','','','btnTOKENNO')


EXEC PROC_GRATUITYCALC_DETAILS('NJ0001','0002','')


exec PROC_GRATUITYCALC_DETAILS('NJ0001','0002','')

SELECT * FROM GTT_GRATUITY_CALC_SHEET



PROC_GRATUITYCALC_DETAILS('COMPANYCODE','DIVISIONCODE','btnTOKENNO','mskFROMDATE','mskTODATE')


EXEC PROC_GRATUITYCALC_DETAILS('NJ0001','0002','','01/04/2020','31/03/2021')


SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%LEAVE%APP%')

SELECT * FROM MENUMASTER_RND
WHERE MENUCODE=''

SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''

SELECT * FROM PISPAYTRANSACTION
WHERE YEARMONTH='202011'
AND TOKENNO='70143'