SELECT * FROM SYS_HELP_QRY
WHERE QRY_ID='2026'



                  AND NVL(CHEQUEBOOKSLNO,'XX') <> 'ONLINE'
                  
                  
SELECT * FROM DIVISIONMASTER

0002    (0022,0023) 

SELECT CHEQUEBOOKSLNO,CHQLEN, STARTINGSLNO, ENDINGSLNO,LASTCHEQUENO_USED,
       CASE WHEN LASTCHEQUENO_USED IS NULL THEN LPAD(STARTINGSLNO,CHQLEN,'0') 
            WHEN LASTCHEQUENO_USED < TO_NUMBER(ENDINGSLNO) THEN LPAD(TO_CHAR(LASTCHEQUENO_USED+1),CHQLEN,'0')
       ELSE 'NOT ALLOWED' END AS NEW_CHEQUENO     
FROM (
        SELECT A.CHEQUEBOOKSLNO,A.CHQLEN, A.STARTINGSLNO ,A.ENDINGSLNO,B.LASTCHEQUENO_USED  
        FROM   (SELECT CHEQUEBOOKSLNO,LENGTH(STARTINGSLNO) AS CHQLEN, TO_NUMBER(STARTINGSLNO) AS STARTINGSLNO ,TO_NUMBER(ENDINGSLNO) AS ENDINGSLNO  
               FROM ACCCHEQUEBOOKMAST 
               WHERE COMPANYCODE = '0002'
                 AND DIVISIONCODE = '0022'
--                 AND ACCODE = <<ACCODE>>
                 AND NVL(ACTIVE,'N')='Y'
               ) A,
               (SELECT CHEQUEBOOKSLNO,MAX(TO_NUMBER(CHEQUENO)) AS LASTCHEQUENO_USED
                FROM ACVOUCHER
                WHERE COMPANYCODE = '0002'
                  AND DIVISIONCODE = '0022'
                  AND NVL(CHEQUEBOOKSLNO,'XX') <> 'ONLINE'
                  --AND VOUCHERTYPE LIKE '%PAYMENTS%'
--                  AND NVL(CASHBANKACCODE,'~NA~') = <<ACCODE>>
                GROUP BY CHEQUEBOOKSLNO
                ) B
        WHERE A.CHEQUEBOOKSLNO = B.CHEQUEBOOKSLNO(+)         
)

  
SELECT CHEQUEBOOKSLNO,
MAX(TO_NUMBER(CHEQUENO)) AS LASTCHEQUENO_USED
FROM ACVOUCHER
GROUP BY CHEQUEBOOKSLNO
  
SELECT CHEQUEBOOKSLNO, CHEQUENO
FROM ACVOUCHER
WHERE CHEQUENO IS NOT NULL


SELECT *
FROM ACVOUCHER


GROUP BY CHEQUEBOOKSLNO



DELETE FROM HOOGHLY_WEB.SYS_HELP_QRY
WHERE QRY_ID='2026'

INSERT INTO HOOGHLY_WEB.SYS_HELP_QRY
SELECT * FROM INFRA_WEB.SYS_HELP_QRY
WHERE QRY_ID='2026'



SELECT * FROM HOOGHLY_WEB.SYS_HELP_QRY
WHERE QRY_ID='2026'


INFRA_WEB        
FORTWILLIAM_WEB  
BOWREAH_WEB      
CALJUTE_WEB      
HOOGHLY_WEB      




UPDATE FORTWILLIAM_WEB.MENUMASTER_RND SET ACTIVE='N'
WHERE MENUCODE='01020221'



UPDATE HOOGHLY_WEB.MENUMASTER_RND SET URLSRC='JUTE/Pages/Transaction/pgRawJuteArrival_without_PO.aspx'
WHERE MENUCODE='01020203'



UPDATE HOOGHLY_WEB.MENUMASTER_RND SET URLSRC='JUTE/Pages/Transaction/pgJUTEPURCHASEORDER_CJIL.aspx'
WHERE MENUCODE='0102020105'




SELECT * FROM MENUMASTER_RND
WHERE UPPER(MENUDESC) LIKE UPPER('%Arrival Details%')

SELECT * FROM INFRA_WEB.MENUMASTER_RND
WHERE MENUCODE='01020221'
UNION ALL
SELECT * FROM FORTWILLIAM_WEB.MENUMASTER_RND
WHERE MENUCODE='01020221'
UNION ALL
SELECT * FROM BOWREAH_WEB.MENUMASTER_RND
WHERE MENUCODE='01020221'
UNION ALL
SELECT * FROM CALJUTE_WEB.MENUMASTER_RND
WHERE MENUCODE='01020221'
UNION ALL
SELECT * FROM HOOGHLY_WEB.MENUMASTER_RND
WHERE MENUCODE='01020221'



INFRA_WEB        
FORTWILLIAM_WEB  
BOWREAH_WEB      
CALJUTE_WEB      
   




SELECT URLSRC FROM INFRA_WEB.MENUMASTER_RND
WHERE MENUCODE='0102020105'

UPDATE MENUMASTER_RND SET URLSRC='JUTE/Pages/Transaction/pgRawJuteArrival_without_PO.aspx'
WHERE MENUCODE='01020203'



SELECT * FROM ROLEDETAILS
WHERE MENUCODE=''

SELECT * FROM REPORTPARAMETERMASTER
WHERE REPORTTAG=''


SELECT CHEQUEBOOKSLNO,CHEQUENO
                FROM ACVOUCHER
                WHERE CHEQUENO IS NOT NULL
                
                
                WHERE COMPANYCODE = <<COMPANYCODE>>
                  AND DIVISIONCODE = <<DIVISIONCODE>>
                  --AND VOUCHERTYPE LIKE '%PAYMENTS%'
                  AND NVL(CASHBANKACCODE,'~NA~') = <<ACCODE>>
                   AND NVL(CHEQUEBOOKSLNO,'XX') <> 'ONLINE'
                GROUP BY CHEQUEBOOKSLNO
                
                
                
SELECT * FROM BOWREAH_WEB.SALESSAUDADETAILS     
WHERE SAUDANO LIKE 'BS/2122/0045'           


SELECT * FROM BOWREAH_WEB.SALESSAUDAVIEW 
WHERE SAUDANO LIKE 'BS/2122/0045'           