


CREATE TABLE NEW_SAL_ARR_HO
(
    NAME	        VARCHAR2(100),
    OLD_SAL	        NUMBER(15,2),
    NEW_SAL	        NUMBER(15,2),	
    ARR_SAL	        NUMBER(15,2),	
    ARR_SAL_TOT	        NUMBER(15,2),	
    OLD_HRA		        NUMBER(15,2),
    NEW_HRA		        NUMBER(15,2),
    ARR_HRA		        NUMBER(15,2),
    ARR_HRA_TOT		        NUMBER(15,2),
    GROSSEARN	        NUMBER(15,2),	
    PF_PERC		        NUMBER(15,2),
    PF_E		        NUMBER(15,2),
    VPF_PERC	        NUMBER(15,2),	
    VPF		        NUMBER(15,2),
    TOTAL_PF		        NUMBER(15,2),
    PTAX		        NUMBER(15,2),
    GROSSDEDN		        NUMBER(15,2),
    NETSALARY	        NUMBER(15,2)
)

SELECT sum(ptax),sum(grossdedn), sum(ptax)-sum(grossdedn) from NEW_SAL_ARR_HO


ALTER TABLE NEW_SAL_ARR_HO ADD EMP_NAME VARCHAR2(100)

ALTER TABLE NEW_SAL_ARR_HO ADD TOKENNO VARCHAR2(10)

UPDATE NEW_SAL_ARR_HO SET NAME=TRIM(NAME)

SELECT * FROM PISEMPLOYEEMASTER A, NEW_SAL_ARR_HO B
WHERE A.EMPLOYEENAME=B.NAME

SELECT NAME FROM  NEW_SAL_ARR_HO
WHERE NAME NOT IN 
(
    SELECT DISTINCT EMPLOYEENAME FROM PISEMPLOYEEMASTER
)


SELECT * FROM PISEMPLOYEEMASTER
WHERE EMPLOYEENAME LIKE '%MOHTA'


SELECT * FROM PISEMPLOYEEMASTER
WHERE EMPLOYEENAME LIKE '%S%BASU'




SELECT * from NEW_SAL_ARR_HO


INSERT INTO PISARREARTRANSACTION
(
    COMPANYCODE, DIVISIONCODE, YEARCODE, YEARMONTH, UNITCODE, DEPARTMENTCODE, CATEGORYCODE, GRADECODE, WORKERSERIAL, TOKENNO, TRANSACTIONTYPE, PAYMODE,
    BASIC,HRA_GROSS,HRA,PF_GROSS,PF_E,PF_C,VPF,PTAX,GROSSEARN,GROSSDEDN,NETSALARY
)
SELECT COMPANYCODE, DIVISIONCODE,'2020-2021' YEARCODE,'202010' YEARMONTH, UNITCODE, DEPARTMENTCODE, CATEGORYCODE, 
GRADECODE, WORKERSERIAL, A.TOKENNO,'ARREAR' TRANSACTIONTYPE,'BANK' PAYMODE,
ARR_SAL_TOT BASIC,ARR_SAL_TOT HRA_GROSS,ARR_HRA_TOT HRA,PF_GROSS,PF_E,PF_C,VPF,PTAX,GROSSEARN, GROSSDEDN,NETSALARY
FROM PISEMPLOYEEMASTER A,
(
    SELECT A.TOKENNO,A.ARR_SAL_TOT,ARR_HRA_TOT, NVL(ARR_SAL_TOT,0) PF_GROSS, NVL(PF_E,0) PF_E,NVL(PF_E,0) PF_C, NVL(VPF,0) VPF , NVL(PTAX,0) PTAX ,
    GROSSEARN ,GROSSDEDN, NETSALARY   
    FROM NEW_SAL_ARR_HO A 
) B
WHERE A.TOKENNO=B.TOKENNO

PISCOMPONENTMASTER

SELECT NAME,A.TOKENNO,A.ARR_SAL_TOT,ARR_HRA_TOT, NVL(ARR_SAL_TOT,0) PF_GROSS, NVL(PF_E,0) PF_E,NVL(PF_E,0) PF_C, NVL(VPF,0) VPF , NVL(PTAX,0) PTAX ,
CASE WHEN NVL(ARR_SAL_TOT,0) > 15000 THEN 0 ELSE ROUND(NVL(ARR_SAL_TOT,0)*8.33/100,0) END PF_1,
    GROSSEARN ,GROSSDEDN, NETSALARY   
    FROM NEW_SAL_ARR_HO A 


DELETE FROM PISARREARTRANSACTION
WHERE YEARMONTH='202010'
AND TOKENNO IN 
(
    SELECT TOKENNO FROM NEW_SAL_ARR_HO
)

UPDATE PISARREARTRANSACTION A SET GROSSDEDN =(
SELECT (PF_E + NEW_PF) FROM 
(
    SELECT TOKENNO, PF_E,VPF, PF_C, GROSSEARN,  GROSSDEDN,  NETSALARY,(GROSSEARN-GROSSDEDN) NET_CHECK,
    DECODE(VPF,0,PF_C,VPF) NEW_PF,(NETSALARY-(GROSSEARN-GROSSDEDN)) DIFF  FROM PISARREARTRANSACTION
    WHERE YEARMONTH='202010'
    AND NETSALARY<>(GROSSEARN-GROSSDEDN)
    )
    WHERE A.TOKENNO=TOKENNO
)
WHERE YEARMONTH='202010'

 SELECT TOKENNO, PF_E,VPF, PF_C, GROSSEARN,  GROSSDEDN,  NETSALARY,(GROSSEARN-GROSSDEDN) NET_CHECK,
    DECODE(VPF,0,PF_C,VPF) NEW_PF,(NETSALARY-(GROSSEARN-GROSSDEDN)) DIFF  FROM PISARREARTRANSACTION
    WHERE YEARMONTH='202010'
    AND NETSALARY<>(GROSSEARN-GROSSDEDN)
     
    
    WHERE A.TOKENNO=TOKENNO
    
    UPDATE PISARREARTRANSACTION SET NETSALARY = (GROSSEARN-GROSSDEDN)
    WHERE  YEARMONTH='202010'
 

UPDATE PISARREARTRANSACTION SET NETSALARY = (GROSSEARN-GROSSDEDN)
WHERE  YEARMONTH='202010'



UPDATE PISARREARTRANSACTION A SET (FPF, PF_C) = (
    SELECT  FPF, PF_C FROM (  
        SELECT 'HO009' TOKENNO, 400 FPF, 176 PF_C FROM DUAL UNION ALL
        SELECT 'HO011' TOKENNO, 400 FPF, 176 PF_C FROM DUAL UNION ALL
        SELECT 'HO020' TOKENNO, 500 FPF, 220 PF_C FROM DUAL 
    )
    WHERE TOKENNO=A.TOKENNO
)

SELECT * FROM PISARREARTRANSACTION
WHERE  YEARMONTH='202010'
AND TOKENNO IN ('HO009','HO011','HO020')


EXEC PROC_RPT_PISPFUPLOAD('JT0069','0001','202010','','','','')

SELECT  FPF, PF_C FROM (  
    SELECT 'HO009' TOKENNO, 400 FPF, 176 PF_C FROM DUAL UNION ALL
    SELECT 'HO011' TOKENNO, 400 FPF, 176 PF_C FROM DUAL UNION ALL
    SELECT 'HO020' TOKENNO, 500 FPF, 220 PF_C FROM DUAL 
)



HO020 500 	 220 

HO011 400 	 176 

   

INSERT INTO GTT_RPT_PISPFUPLOAD 

SELECT C.COMPANYNAME, D.DIVISIONNAME, 'OCTOBER-2020',B.UANNO, B.EMPLOYEENAME || ' ',ROUND(A.GROSSWAGES,0) GROSSWAGES,  ROUND(A.PF_GROSS,0) PF_GROSS, 
( 
    CASE WHEN ROUND(A.PF_GROSS,0) >=15000 THEN 15000 ELSE ROUND(A.PF_GROSS,0) END 
) PF_GROSS1, 
( 
    CASE WHEN ROUND(A.PF_GROSS,0) >=15000 THEN (ROUND(A.PF_GROSS,0)-15000) ELSE 0 END 
) PF_TMP, 
ROUND(A.PF_E,0),PEN_GROSS PF_E1, FPF PF1, PF_C PF2,NULL,NULL,PF_C 
FROM 
( 

    SELECT COMPANYCODE, DIVISIONCODE , WORKERSERIAL, TOKENNO,SUM(GROSSWAGES) GROSSWAGES,SUM (PEN_GROSS) PEN_GROSS,
    SUM(PF_GROSS) PF_GROSS, SUM(PF_E) PF_E , SUM(NVL(PF_C,0)) PF_C , SUM(NVL(FPF,0)) FPF
    FROM 
    (
        SELECT COMPANYCODE, DIVISIONCODE , WORKERSERIAL, TOKENNO,SUM(GROSSEARN) GROSSWAGES,SUM (PEN_GROSS) PEN_GROSS,
        SUM(PF_GROSS) PF_GROSS, (SUM(NVL(PF_E,0)) + SUM(NVL(VPF,0))) PF_E , SUM(NVL(PF_C,0)) PF_C , SUM(NVL(FPF,0)) FPF
        FROM PISPAYTRANSACTION WHERE YEARMONTH >='202010' 
        AND DIVISIONCODE ='0001' 
        AND COMPANYCODE ='JT0069'    AND PF_E > 0                                      
        GROUP BY COMPANYCODE, DIVISIONCODE , WORKERSERIAL, TOKENNO
        UNION ALL
        SELECT COMPANYCODE, DIVISIONCODE , WORKERSERIAL, TOKENNO,SUM(GROSSEARN) GROSSWAGES,SUM (PEN_GROSS) PEN_GROSS,
        SUM(PF_GROSS) PF_GROSS, (SUM(NVL(PF_E,0)) + SUM(NVL(VPF,0))) PF_E , SUM(NVL(PF_C,0)) PF_C , SUM(NVL(FPF,0)) FPF
        FROM PISARREARTRANSACTION WHERE YEARMONTH >='202010' 
        AND DIVISIONCODE ='0001' 
        AND COMPANYCODE ='JT0069'    AND PF_E > 0                                      
        GROUP BY COMPANYCODE, DIVISIONCODE , WORKERSERIAL, TOKENNO
    )
    GROUP BY COMPANYCODE, DIVISIONCODE , WORKERSERIAL, TOKENNO
    
    
    
) A, PISEMPLOYEEMASTER B, COMPANYMAST C, DIVISIONMASTER D 
WHERE A.COMPANYCODE=B.COMPANYCODE 
AND A.DIVISIONCODE=B.DIVISIONCODE 
AND A.WORKERSERIAL=B.WORKERSERIAL 
AND A.COMPANYCODE=C.COMPANYCODE 
AND A.DIVISIONCODE=D.DIVISIONCODE 
AND A.DIVISIONCODE=D.DIVISIONCODE 
ORDER BY B.EMPLOYEENAME


--------------------------------------------------------

--update on 17/11/2020
--------------------------------------------------------
select sum(grossdedn), sum(netsalary) from pisarreartransaction
where tokenno in (
     select tokenno from   NEW_SAL_ARR_HO
)
and yearmonth='202010'

--
--update pisarreartransaction
--set grossdedn = grossdedn-ptax,
-- netsalary = netsalary-ptax
--where tokenno in (
--     select tokenno from   NEW_SAL_ARR_HO
--)
--and yearmonth='202010'
--


select 601692 -  602052 from dual 



update pisarreartransaction
set  
 ptax = 0
where tokenno in (
     select tokenno from   NEW_SAL_ARR_HO
)
and yearmonth='202010'

