SELECT * FROM STORESSUBCOSTCENTRETYPE

SELECT DISTINCT COMPANYCODE, DIVISIONCODE,DIVISIONNAME FROM DIVISIONMASTER

SET DEFINE OFF;
Insert into STORESSUBCOSTCENTRETYPE
   (COMPANYCODE, DIVISIONCODE, SUBCOSTTYPE, SERIALNO)
 Values
   ('GJ0108', '0002', 'JOBCODE', 1);
Insert into STORESSUBCOSTCENTRETYPE
   (COMPANYCODE, DIVISIONCODE, SUBCOSTTYPE, SERIALNO)
 Values
   ('GJ0109', '0002', 'JOBCODE', 1);
Insert into STORESSUBCOSTCENTRETYPE
   (COMPANYCODE, DIVISIONCODE, SUBCOSTTYPE, SERIALNO)
 Values
   ('GJ0110', '0002', 'JOBCODE', 1);
Insert into STORESSUBCOSTCENTRETYPE
   (COMPANYCODE, DIVISIONCODE, SUBCOSTTYPE, SERIALNO)
 Values
   ('GJ0111', '0002', 'JOBCODE', 1);
COMMIT;





SELECT * FROM SYS_TFMAP
WHERE SYS_DATATYPE='DATE'

WHERE SYS_TABLE_SEQUENCIER = ''

SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_ACTUAL = 'STORESSUBCOSTCENTREMAST'


SELECT * FROM SYS_TFMAP
WHERE SYS_TABLENAME_TEMP = 'GBL_STORESSUBCOSTCENTREMAST'

alter TABLE STORESSUBCOSTCENTREMAST
ADD JOBOPENDATE DATE DEFAULT NULL


alter TABLE STORESSUBCOSTCENTREMAST
ADD JOBCOMPLETIONDATE DATE DEFAULT NULL

SET DEFINE OFF;
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (4039, 'STORESSUBCOSTCENTREMAST', 'GBL_STORESSUBCOSTCENTREMAST', 'JOBOPENDATE', 0, 
    'DATE', 10, 0, 'N', 'JOBOPENDATE', 
    TO_TIMESTAMP('21/05/2015 2:30:39.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
Insert into SYS_TFMAP
   (SYS_TABLE_SEQUENCIER, SYS_TABLENAME_ACTUAL, SYS_TABLENAME_TEMP, SYS_COLUMNNAME, SYS_COLUMN_SEQUENCE, SYS_DATATYPE, SYS_COLUMN_LENGTH, SYS_COLUMN_PRECISION, SYS_KEYCOLUMN, SYS_MAPFIELD, SYS_TIMESTAMP, SYS_USEMAP, SYS_DEFAULT, TDSCODE)
 Values
   (4039, 'STORESSUBCOSTCENTREMAST', 'GBL_STORESSUBCOSTCENTREMAST', 'JOBCOMPLETIONDATE', 0, 
    'DATE', 10, 0, 'N', 'JOBCOMPLETIONDATE', 
    TO_TIMESTAMP('21/05/2015 2:30:39.000000 PM','DD/MM/YYYY fmHH12fm:MI:SS.FF AM'), 'Y', NULL, NULL);
COMMIT;


EXEC PROC_CREATE_GBL_TMP_TABLES(4039,0)