PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

2_7 SEEE>0 : UPDATE  PISITAXATTRIBUTEVALUE SET COMPPROJCTEDVALUE =  NVL(COMPACTUALVALUE,0) + (
 SELECT (SUM(CASE WHEN 0 > 0 AND BASIC > 0 THEN 0 ELSE BASIC END)  * 5)  FROM PISASSIGN A ,PISEMPLOYEEMASTER B   
        WHERE A.COMPANYCODE=B.COMPANYCODE  
        AND A.DIVISIONCODE=B.DIVISIONCODE 
        AND A.WORKERSERIAL =B.WORKERSERIAL 
        AND A.COMPANYCODE='0001' 
        AND A.DIVISIONCODE='0002' 
        AND A.WORKERSERIAL ='000199' 
        AND B.EMPLOYEESTATUS='ACTIVE'
 ) WHERE COMPANYCODE='0001' 
 AND DIVISIONCODE='0002' 
 AND YEARCODE='2020-2021' 
 AND COLUMNNO='01_01_01' 
 AND COLUMNATTRIBUTE='BASIC' 
 AND WORKERSERIAL ='000199' 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

2_7 SEEE>0 : UPDATE  PISITAXATTRIBUTEVALUE SET COMPPROJCTEDVALUE =  NVL(COMPACTUALVALUE,0) + (
 SELECT (SUM(CASE WHEN 0 > 0 AND DA > 0 THEN 0 ELSE DA END)  * 5)  FROM PISASSIGN A ,PISEMPLOYEEMASTER B   
        WHERE A.COMPANYCODE=B.COMPANYCODE  
        AND A.DIVISIONCODE=B.DIVISIONCODE 
        AND A.WORKERSERIAL =B.WORKERSERIAL 
        AND A.COMPANYCODE='0001' 
        AND A.DIVISIONCODE='0002' 
        AND A.WORKERSERIAL ='000199' 
        AND B.EMPLOYEESTATUS='ACTIVE'
 ) WHERE COMPANYCODE='0001' 
 AND DIVISIONCODE='0002' 
 AND YEARCODE='2020-2021' 
 AND COLUMNNO='01_01_02' 
 AND COLUMNATTRIBUTE='DA' 
 AND WORKERSERIAL ='000199' 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

2_7 SEEE>0 : UPDATE  PISITAXATTRIBUTEVALUE SET COMPPROJCTEDVALUE =  NVL(COMPACTUALVALUE,0) + (
 SELECT (SUM(CASE WHEN 0 > 0 AND ADHOC > 0 THEN 0 ELSE ADHOC END)  * 5)  FROM PISASSIGN A ,PISEMPLOYEEMASTER B   
        WHERE A.COMPANYCODE=B.COMPANYCODE  
        AND A.DIVISIONCODE=B.DIVISIONCODE 
        AND A.WORKERSERIAL =B.WORKERSERIAL 
        AND A.COMPANYCODE='0001' 
        AND A.DIVISIONCODE='0002' 
        AND A.WORKERSERIAL ='000199' 
        AND B.EMPLOYEESTATUS='ACTIVE'
 ) WHERE COMPANYCODE='0001' 
 AND DIVISIONCODE='0002' 
 AND YEARCODE='2020-2021' 
 AND COLUMNNO='01_01_04' 
 AND COLUMNATTRIBUTE='ADHOC' 
 AND WORKERSERIAL ='000199' 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

2_7 SEEE>0 : UPDATE  PISITAXATTRIBUTEVALUE SET COMPPROJCTEDVALUE =  NVL(COMPACTUALVALUE,0) + (
 SELECT (SUM(CASE WHEN 0 > 0 AND ADHOC_NPF > 0 THEN 0 ELSE ADHOC_NPF END)  * 5)  FROM PISASSIGN A ,PISEMPLOYEEMASTER B   
        WHERE A.COMPANYCODE=B.COMPANYCODE  
        AND A.DIVISIONCODE=B.DIVISIONCODE 
        AND A.WORKERSERIAL =B.WORKERSERIAL 
        AND A.COMPANYCODE='0001' 
        AND A.DIVISIONCODE='0002' 
        AND A.WORKERSERIAL ='000199' 
        AND B.EMPLOYEESTATUS='ACTIVE'
 ) WHERE COMPANYCODE='0001' 
 AND DIVISIONCODE='0002' 
 AND YEARCODE='2020-2021' 
 AND COLUMNNO='01_01_06' 
 AND COLUMNATTRIBUTE='ADHOC_NPF' 
 AND WORKERSERIAL ='000199' 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

2_7 SEEE>0 : UPDATE  PISITAXATTRIBUTEVALUE SET COMPPROJCTEDVALUE =  NVL(COMPACTUALVALUE,0) + (
 SELECT (SUM(CASE WHEN 0 > 0 AND SPL_ALLOW > 0 THEN 0 ELSE SPL_ALLOW END)  * 5)  FROM PISASSIGN A ,PISEMPLOYEEMASTER B   
        WHERE A.COMPANYCODE=B.COMPANYCODE  
        AND A.DIVISIONCODE=B.DIVISIONCODE 
        AND A.WORKERSERIAL =B.WORKERSERIAL 
        AND A.COMPANYCODE='0001' 
        AND A.DIVISIONCODE='0002' 
        AND A.WORKERSERIAL ='000199' 
        AND B.EMPLOYEESTATUS='ACTIVE'
 ) WHERE COMPANYCODE='0001' 
 AND DIVISIONCODE='0002' 
 AND YEARCODE='2020-2021' 
 AND COLUMNNO='01_01_12' 
 AND COLUMNATTRIBUTE='SPL_ALLOW' 
 AND WORKERSERIAL ='000199' 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

PISASSIGN:  CREATE OR REPLACE VIEW PISASSIGN 
 AS 
 SELECT A.COMPANYCODE, A.DIVISIONCODE, A.WORKERSERIAL, A.YEARMONTH 
 , NVL(A.ATN_INCNT,0) AS ATN_INCNT, NVL(A.BASIC,0) AS BASIC, NVL(A.DA,0) AS DA, NVL(A.ADHOC,0) AS ADHOC, NVL(A.SPL_ALLOW,0) AS SPL_ALLOW, NVL(A.SERV_PERC,0) AS SERV_PERC, NVL(A.CONV_PERC,0) AS CONV_PERC, NVL(A.ESI_ADJERN,0) AS ESI_ADJERN, NVL(A.HRA_PERC,0) AS HRA_PERC, NVL(A.VPF_PERC,0) AS VPF_PERC, NVL(A.ITAX,0) AS ITAX, NVL(A.ADHOC_NPF,0) AS ADHOC_NPF, NVL(A.HRA_AMT,0) AS HRA_AMT 
 FROM PISCOMPONENTASSIGNMENT A, 
 ( 
     SELECT WORKERSERIAL, MAX(YEARMONTH) YEARMONTH 
     FROM PISCOMPONENTASSIGNMENT 
     WHERE COMPANYCODE = '0001' AND DIVISIONCODE = '0002' 
       AND YEARMONTH <= '202010' 
       AND TRANSACTIONTYPE = 'ASSIGNMENT' 
     GROUP BY WORKERSERIAL 
 ) B 
 WHERE A.COMPANYCODE = '0001' AND A.DIVISIONCODE = '0002' 
   AND A.TRANSACTIONTYPE = 'ASSIGNMENT' 
   AND A.WORKERSERIAL = B.WORKERSERIAL 
   AND A.YEARMONTH = B.YEARMONTH 
 ORDER BY A.YEARMONTH 

2_7 SEEE>0 : UPDATE  PISITAXATTRIBUTEVALUE SET COMPPROJCTEDVALUE =  NVL(COMPACTUALVALUE,0) + (
COMPACTUALVALUE
 ) WHERE COMPANYCODE='0001' 
 AND DIVISIONCODE='0002' 
 AND YEARCODE='2020-2021' 
 AND COLUMNNO='18_01' 
 AND COLUMNATTRIBUTE='ITAX' 
 AND WORKERSERIAL ='000199' 

