SELECT * FROM JSWRAPPER

SELECT * FROM GTT_GRATUITYWORKSHEET

CREATE TABLE GTT_GRATUITYWORKSHEET AS

DELETE FROM GTT_GRATUITYWORKSHEET

INSERT INTO GTT_GRATUITYWORKSHEET
(
    COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, WORKERNAME, PFMEMBERSHIPDATE, DATEOFTERMINATION, 
    CALENDARYEAR, STRIKE_DAYS, ATTENDANCE, STL, AUTHORIZEDLEAVE, ESI, TOTAL, YESNO, GRATURITYENTILE, 
    SERVICE_PERIOD, SERVICE_YEAR, GRATURITYYEARS, NONGRATURITYYEARS
)
SELECT COMPANYCODE, DIVISIONCODE, A.WORKERSERIAL, A.TOKENNO, WORKERNAME,PFMEMBERSHIPDATE,DATEOFTERMINATION,
CALENDARYEAR,0 STRIKE_DAYS, ATTENDANCE,STL,AUTHORIZEDLEAVE,ESI,TOTAL,YESNO,GRATURITYENTILE,
FN_DATEDIFF(TO_CHAR(PFMEMBERSHIPDATE,'DD/MM/YYYY'), TO_CHAR(DATEOFTERMINATION,'DD/MM/YYYY')) SERVICE_PERIOD,
SERVICE_YEAR,GRATURITYYEARS,(SERVICE_YEAR - GRATURITYYEARS) NONGRATURITYYEARS
 FROM 
(
    SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, WORKERNAME,
    PFMEMBERSHIPDATE,DATEOFTERMINATION,TRUNC(MONTHS_BETWEEN(DATEOFTERMINATION,PFMEMBERSHIPDATE)/12)+1  SERVICE_YEAR 
    FROM WORKERVIEWGRATUITY
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE ='0002'
    --AND UNITCODE=''
--    AND CATEGORYCODE='B'
    --AND GRADECODE=''
--    AND WORKERSERIAL='000001'
--    AND TOKENNO='04053'
) A,
(
    SELECT TOKENNO,WORKERSERIAL, CALENDARYEAR,0 STRIKE_DAYS, ATTENDANCE,STL,AUTHORIZEDLEAVE,ESI,TOTAL,
    CASE WHEN (TOTAL >= 240) THEN 'YES' ELSE 'NO' END YESNO,
    DECODE(GRATURITYENTILE,'Y','YES','NO') GRATURITYENTILE 
    FROM GRATUITYENTITLEMENTYEAR
--    WHERE TOKENNO='04053'
) B,
(
    SELECT WORKERSERIAL, COUNT(GRATURITYENTILE) GRATURITYYEARS
    FROM GRATUITYENTITLEMENTYEAR
    WHERE GRATURITYENTILE='Y'
    GROUP BY WORKERSERIAL
) C
WHERE A.WORKERSERIAL=B.WORKERSERIAL
AND A.WORKERSERIAL=C.WORKERSERIAL
ORDER BY A.TOKENNO, CALENDARYEAR


SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, WORKERNAME,
    PFMEMBERSHIPDATE,DATEOFTERMINATION,TRUNC(MONTHS_BETWEEN(DATEOFTERMINATION,PFMEMBERSHIPDATE)/12)+1  SERVICE_YEAR 
    FROM WORKERVIEWGRATUITY
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE ='0002'
    --AND UNITCODE=''
--    AND CATEGORYCODE='B'
    --AND GRADECODE=''
--    AND WORKERSERIAL='000001'
    AND TOKENNO='04053'


EXEC PROC_RPT_GRATUITYWORKSHT_EXL('NJ0001','0002','2020-2021','01/04/2020','31/12/2020','','','','''001544''')

SELECT * FROM GTT_GRATUITYWORKSHEET


SELECT * FROM GTT_EXCEL_REPORT



(
    P_COMPANYCODE VARCHAR2,
    P_DIVISIONCODE VARCHAR2,
    P_YEARCODE VARCHAR2,
    P_FROMDATE VARCHAR2,
    P_TODATE VARCHAR2,
    P_UNIT VARCHAR2 DEFAULT NULL,
    P_CATEGORY VARCHAR2 DEFAULT NULL,
    P_GRADE VARCHAR2 DEFAULT NULL,
    P_WORKERSERIAL VARCHAR2 DEFAULT NULL
)



INSERT INTO GTT_GRATUITYWORKSHEET
(
    COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, WORKERNAME, PFMEMBERSHIPDATE, DATEOFTERMINATION, 
    CALENDARYEAR, STRIKE_DAYS, ATTENDANCE, STL, AUTHORIZEDLEAVE, ESI, TOTAL, YESNO, GRATURITYENTILE, 
    SERVICE_PERIOD, SERVICE_YEAR, GRATURITYYEARS, NONGRATURITYYEARS
)

SELECT COMPANYCODE, DIVISIONCODE, A.WORKERSERIAL, A.TOKENNO, WORKERNAME,PFMEMBERSHIPDATE,DATEOFTERMINATION,
CALENDARYEAR,0 STRIKE_DAYS, ATTENDANCE,STL,AUTHORIZEDLEAVE,ESI,TOTAL,YESNO,GRATURITYENTILE,
FN_DATEDIFF(TO_CHAR(PFMEMBERSHIPDATE,'DD/MM/YYYY'), TO_CHAR(DATEOFTERMINATION,'DD/MM/YYYY')) SERVICE_PERIOD,
SERVICE_YEAR,GRATURITYYEARS,(SERVICE_YEAR - GRATURITYYEARS) NONGRATURITYYEARS
 FROM 
(
    SELECT COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, WORKERNAME,
    PFMEMBERSHIPDATE,DATEOFTERMINATION,TRUNC(MONTHS_BETWEEN(DATEOFTERMINATION,PFMEMBERSHIPDATE)/12)+1  SERVICE_YEAR 
    FROM WORKERVIEWGRATUITY
    WHERE COMPANYCODE='NJ0001'
    AND DIVISIONCODE ='0002'
    --AND UNITCODE=''
--    AND CATEGORYCODE='B'
    --AND GRADECODE=''
    AND WORKERSERIAL=''001544''
--    AND TOKENNO='04053'
) A,
(
    SELECT TOKENNO,WORKERSERIAL, CALENDARYEAR,0 STRIKE_DAYS, ATTENDANCE,STL,AUTHORIZEDLEAVE,ESI,TOTAL,
    CASE WHEN (TOTAL >= 240) THEN 'YES' ELSE 'NO' END YESNO,
    DECODE(GRATURITYENTILE,'Y','YES','NO') GRATURITYENTILE 
    FROM GRATUITYENTITLEMENTYEAR
--    WHERE TOKENNO='04053'
) B,
(
    SELECT WORKERSERIAL, COUNT(GRATURITYENTILE) GRATURITYYEARS
    FROM GRATUITYENTITLEMENTYEAR
    WHERE GRATURITYENTILE='Y'
    GROUP BY WORKERSERIAL
) C
WHERE A.WORKERSERIAL=B.WORKERSERIAL
AND A.WORKERSERIAL=C.WORKERSERIAL
ORDER BY A.TOKENNO, CALENDARYEAR

