PK_PISPAYTRANSACTION


select * from PISSALARYUPLOADRAWDATA
where yearmonth='202101'

select * from pispaytransaction
where yearmonth='202101'

DROP INDEX NJMCL_WEB.PK_PISPAYTRANSACTION;

CREATE UNIQUE INDEX NJMCL_WEB.PK_PISPAYTRANSACTION ON NJMCL_WEB.PISPAYTRANSACTION
(COMPANYCODE, DIVISIONCODE, YEARMONTH, TRANSACTIONTYPE, WORKERSERIAL) 



select COMPANYCODE, DIVISIONCODE, YEARMONTH,'SALARY' TRANSACTIONTYPE, EMPLOYEECODE 
from PISSALARYUPLOADRAWDATA
where yearmonth='202101'



select EMPLOYEECODE, COUNT(EMPLOYEECODE) 
from PISSALARYUPLOADRAWDATA
where yearmonth='202101'
GROUP BY EMPLOYEECODE
HAVING COUNT(EMPLOYEECODE) > 1

PROC_PISSALARY_DATA_IMPORT1

PROC_PISSALARY_DATA_IMPORT1

(
    P_COMPANYCODE VARCHAR2,
    P_DIVISIONCODE VARCHAR2,
    P_YEARMONTH VARCHAR2
)
