 INSERT INTO WPSSTLTRANSACTION
  (COMPANYCODE, DIVISIONCODE, WORKERSERIAL, TOKENNO, FROMYEAR, YEARCODE, FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
  STLDAYS, STLHOURS, TRANSACTIONTYPE, ADDLESS, USERNAME, PREV_STLHRS, PREV_STLDAYS) 

  SELECT 'NJ0001' COMPANYCODE,'0002' DIVISIONCODE,WORKERSERIAL,TOKENNO,'2021','2020-2021' YEARCODE, 
         FORTNIGHTSTARTDATE, FORTNIGHTENDDATE, 
        /*  STLDAYS, STLDAYS * 8 STLHOURS,*/ 
         CASE WHEN STLDAYS > 0 AND STLDAYS_BF < 0 THEN STLDAYS+STLDAYS_BF ELSE STLDAYS END STLDAYS, 
         CASE WHEN STLDAYS > 0 AND STLDAYS_BF < 0 THEN STLDAYS+STLDAYS_BF ELSE STLDAYS END * 8 STLHOURS, 
        'ENTITLEMENT' TRANSACTIONTYPE,'ADD' ADDLESS, 'SWT', 
        0 STLHRS_BF, 
        0 STLDAYS_BF 
        /*STLDAYS_BF * 8, STLDAYS_BF */ 
    FROM WPSSTLENTITLEMENTCALCDETAILS 
    WHERE COMPANYCODE = 'NJ0001' AND DIVISIONCODE = '0002' 
      AND FORTNIGHTSTARTDATE = '01-JAN-22' AND FORTNIGHTENDDATE = '15-JAN-22' 
      AND ( NVL(STLDAYS,0) > 0 OR NVL(STLDAYS_BF,0) <> 0) 