'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pgStoresChallanOutDtls_GJPL

    '''<summary>
    '''lblLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblForHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCOMPCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOMPCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIVCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIVCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYEARCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYEARCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOPTMODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPTMODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUSRNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUSRNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCHALLANGRIDDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCHALLANGRIDDATA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGridCellHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGridCellHelp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGridCurRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGridCurRow As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChallanOutNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChallanOutNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTRANSACTIONNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRANSACTIONNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChallanDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChallanDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskTRANSACTIONDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskTRANSACTIONDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOutType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOutType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbOUTTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbOUTTYPE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMANDATORY1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPartyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartyCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPARTYCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPARTYNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYNAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtREPRESENTATIVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtREPRESENTATIVE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMANDATORY3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMANDATORY3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehicleNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehicleNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAGAINSTNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAGAINSTNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAGAINSTNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAGAINSTNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAGAINSTDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAGAINSTDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskAGAINSTDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskAGAINSTDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPARTYCHALLANNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPARTYCHALLANNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPARTYCHALLANNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPARTYCHALLANNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPARTYCHALLANDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPARTYCHALLANDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mskPARTYCHALLANDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskPARTYCHALLANDATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCellDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPanel As Global.System.Web.UI.WebControls.Panel
End Class
